/**
 * Azure Resource Manager resource schemas, for the data editor's ARM checks.
 *
 * Every resource type Microsoft publishes a schema for, with the apiVersions
 * that exist for it, is in ./arm-schema-index.ts, which ships with the page.
 * The property schemas — for each type, the fields, required fields and enums
 * of one apiVersion, the newest stable one — are in web/data/editor/arm/, a
 * chunk per namespace, fetched when a template names a type in it. In Node
 * they are read from disk as they are asked for, so tests need not await.
 *
 * Both are generated by tools/fetch-editor-arm.mjs (npm run editor:arm).
 */

import { ARM_SCHEMA_INDEX } from './arm-schema-index.ts';

/**
 * A schema node, in the compact form the fetcher writes:
 * t type ('s' string, 'i' integer, 'n' number, 'b' boolean, 'o' object, 'a' array),
 * e enum, p properties, r required, o open (takes fields not listed),
 * i items, m a map's value, d a shared definition, x more definitions that
 * also apply, u definitions any one of which may apply. `{}` is anything.
 */
export interface ArmNode {
  readonly t?: 's' | 'i' | 'n' | 'b' | 'o' | 'a';
  readonly e?: readonly string[];
  readonly p?: Readonly<Record<string, ArmNode>>;
  readonly r?: readonly string[];
  readonly o?: 1;
  readonly i?: ArmNode;
  readonly m?: ArmNode;
  readonly d?: number;
  readonly x?: readonly number[];
  readonly u?: readonly number[];
}

interface Chunk {
  readonly t: Readonly<Record<string, { readonly v: string; readonly s: ArmNode }>>;
  readonly d: readonly ArmNode[];
}

/** A node with its definitions folded in: what a value at that place may be. */
export interface ArmShape {
  readonly type?: ArmNode['t'];
  readonly enum?: readonly string[];
  /** Undefined when the fields are not known (anything goes). */
  readonly fields?: Readonly<Record<string, ArmNode>>;
  readonly required: readonly string[];
  /** Takes fields beyond `fields`. */
  readonly open: boolean;
  readonly items?: ArmNode;
  readonly map?: ArmNode;
}

export interface ArmTypeSchema {
  /** The type as Microsoft spells it. */
  readonly type: string;
  /** The apiVersion this schema is for. */
  readonly apiVersion: string;
  readonly body: ArmNode;
  readonly defs: readonly ArmNode[];
}

export interface ArmTypeInfo {
  /** The type as Microsoft spells it: types are case-insensitive. */
  readonly type: string;
  /** Every apiVersion, newest first (a stable version ahead of the same date's previews). */
  readonly versions: readonly string[];
  readonly chunk?: string;
}

export const ARM_SCHEMA_SOURCE = ARM_SCHEMA_INDEX.source;
export const ARM_SCHEMA_FETCHED = ARM_SCHEMA_INDEX.fetched;
export const ARM_SCHEMA_COMMIT = ARM_SCHEMA_INDEX.commit;

// ------------------------------------------------------------------ index ---

let byLower: Map<string, ArmTypeInfo> | undefined;
let namespaces: Map<string, string> | undefined;

function build(): Map<string, ArmTypeInfo> {
  if (byLower) return byLower;
  byLower = new Map();
  namespaces = new Map();
  const split = ARM_SCHEMA_INDEX.versions.map((v) => v.split(','));
  for (const [ns, types] of Object.entries(ARM_SCHEMA_INDEX.types)) {
    namespaces.set(ns.toLowerCase(), ns);
    for (const [rest, [list, chunk]] of Object.entries(types)) {
      const type = `${ns}/${rest}`;
      byLower.set(type.toLowerCase(), {
        type,
        versions: split[list as number] ?? [],
        chunk: chunk === undefined ? undefined : ARM_SCHEMA_INDEX.chunks[chunk],
      });
    }
  }
  return byLower;
}

/** A resource type's apiVersions and chunk, whatever its case; undefined for a type no schema names. */
export function armType(type: string): ArmTypeInfo | undefined {
  return build().get(type.toLowerCase());
}

/** The namespace as Microsoft spells it, when there is a schema for any type in it. */
export function armNamespace(ns: string): string | undefined {
  build();
  return namespaces?.get(ns.toLowerCase());
}

/** Every type, or every type in one namespace. */
export function armTypes(ns?: string): string[] {
  const all = [...build().values()].map((t) => t.type);
  if (!ns) return all;
  const prefix = `${ns.toLowerCase()}/`;
  return all.filter((t) => t.toLowerCase().startsWith(prefix));
}

// ----------------------------------------------------------------- chunks ---

const LOADED = new Map<string, Chunk>();
const FETCHING = new Map<string, Promise<void>>();

/** Node's fs, when there is one: tests and tools read chunks straight from disk. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const nodeFs: any = (globalThis as any).process?.getBuiltinModule?.('node:fs');

function chunkUrl(chunk: string): URL {
  // Built, this module is web/lib/editor/ and the data web/data/editor/arm/;
  // run from source (tests, tools), it is src/editor/.
  const base = import.meta.url.includes('/src/editor/') ? '../../web/data/editor/arm/' : '../../data/editor/arm/';
  return new URL(`${base}${chunk}.json`, import.meta.url);
}

/** Fetch the chunk holding a type's schema; resolves at once when it is loaded or there is none. */
export function loadArmType(type: string): Promise<void> {
  const chunk = armType(type)?.chunk;
  if (!chunk || LOADED.has(chunk)) return Promise.resolve();
  let pending = FETCHING.get(chunk);
  if (!pending) {
    pending = fetch(chunkUrl(chunk))
      .then((r) => {
        if (!r.ok) throw new Error(`${chunk}.json: HTTP ${r.status}`);
        return r.json() as Promise<Chunk>;
      })
      .then((c) => {
        LOADED.set(chunk, c);
      })
      .catch((err: unknown) => {
        FETCHING.delete(chunk);
        throw err;
      });
    FETCHING.set(chunk, pending);
  }
  return pending;
}

function chunkFor(name: string): Chunk | undefined {
  const loaded = LOADED.get(name);
  if (loaded || !nodeFs) return loaded;
  // In Node, read it now: tests and tools then need not await anything.
  try {
    const c = JSON.parse(nodeFs.readFileSync(chunkUrl(name), 'utf8')) as Chunk;
    LOADED.set(name, c);
    return c;
  } catch {
    return undefined;
  }
}

/** A type's schema, when its chunk is loaded (always, in Node). */
export function armTypeSchema(type: string): ArmTypeSchema | undefined {
  const info = armType(type);
  if (!info?.chunk) return undefined;
  const chunk = chunkFor(info.chunk);
  const entry = chunk?.t[info.type];
  if (!chunk || !entry) return undefined;
  return { type: info.type, apiVersion: entry.v, body: entry.s, defs: chunk.d };
}

// ----------------------------------------------------------------- shapes ---

/** Fold a node's definitions into one shape. */
export function shapeOf(node: ArmNode, defs: readonly ArmNode[]): ArmShape {
  let type = node.t;
  let en = node.e;
  let fields: Record<string, ArmNode> | undefined = node.p ? { ...node.p } : undefined;
  const required = new Set(node.r ?? []);
  let open = node.o === 1;
  let items = node.i;
  let map = node.m;
  const seen = new Set<number>();
  const fold = (id: number, withRequired: boolean): void => {
    if (seen.has(id)) return;
    seen.add(id);
    const d = defs[id];
    if (!d) {
      open = true;
      return;
    }
    const s = d;
    type ??= s.t;
    if (withRequired) en ??= s.e;
    if (s.p) fields = { ...(fields ?? {}), ...s.p };
    else if (!s.e && !s.i && !s.m && !s.t) open = true;
    if (withRequired) for (const r of s.r ?? []) required.add(r);
    if (s.o) open = true;
    items ??= s.i;
    map ??= s.m;
    if (s.d !== undefined) fold(s.d, withRequired);
    for (const x of s.x ?? []) fold(x, withRequired);
    for (const u of s.u ?? []) fold(u, false);
  };
  if (node.d !== undefined) fold(node.d, true);
  for (const x of node.x ?? []) fold(x, true);
  for (const u of node.u ?? []) fold(u, false);
  if (fields && !Object.keys(fields).length && open) fields = undefined;
  return { type, enum: en, fields, required: [...required], open, items, map };
}
