# Generated by ATK: terraform-aws-workloads.mjs
# Source: reports/manual/enriched.1768319239167.json
#
# This file is SAFE to generate without AWS credentials.
# It defines SGs + optional EC2 stubs. By default, workloads are NOT deployed.
#
# To deploy EC2 stubs:
#   terraform plan -var="deploy_workloads=true" -var="ami_id=ami-xxxxxxxx" -var="key_name=yourkey"
#

variable "deploy_workloads" {
  type    = bool
  default = false
}

variable "ami_id" {
  type        = string
  default     = ""
  description = "AMI to use when deploy_workloads=true"
}

variable "key_name" {
  type        = string
  default     = ""
  description = "EC2 key pair name when deploy_workloads=true"
}

locals {
  # Use all private subnets generated by the network module.
  # Network exporter tags subnets with Role=public|private|isolated.
  private_subnet_ids = [
    for k, s in aws_subnet.subnet : s.id
    if try(s.tags["Role"], "") == "private"
  ]

  # Workload map for stable for_each keys
  workloads = {
    "app01" = {
      name          = "app01"
      instance_type = "t3.medium"
    }
  }
}

# Baseline SG is created in main.tf as aws_security_group.baseline (per VPC)
# We add per-workload SGs with no ingress by default, and allow all egress.

resource "aws_security_group" "workload" {
  for_each = local.workloads

  name        = "${var.naming_prefix}-${each.key}-sg"
  description = "ATK workload SG (no ingress by default)"
  vpc_id      = values(aws_vpc.vpc)[0].id

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.naming_prefix}-${each.key}-sg"
  }
}

# policy.internet_exposed=false => no public ingress resources are generated here.

# Optional EC2 stubs (OFF by default)
resource "aws_instance" "workload" {
  for_each = var.deploy_workloads ? local.workloads : {}

  ami           = var.ami_id
  instance_type = each.value.instance_type
  key_name      = var.key_name

  subnet_id = length(local.private_subnet_ids) > 0
    ? element(local.private_subnet_ids, index(keys(local.workloads), each.key) % length(local.private_subnet_ids))
    : null

  vpc_security_group_ids = [aws_security_group.workload[each.key].id]

  tags = {
    Name = "${var.naming_prefix}-${each.key}"
  }

  lifecycle {
    precondition {
      condition     = var.ami_id != ""
      error_message = "ami_id must be set when deploy_workloads=true"
    }
    precondition {
      condition     = length(local.private_subnet_ids) > 0
      error_message = "No private subnets were generated. Ensure Role=private subnets exist."
    }
  }
}

output "atk_workload_plan" {
  value = {
    deploy_workloads = var.deploy_workloads
    workload_keys    = keys(local.workloads)
    private_subnets   = local.private_subnet_ids
  }
}
