/**
 * PowerShell against the Windows infrastructure everyone still runs.
 *
 * File servers and their permissions, DNS and DHCP, Group Policy, SQL Server,
 * IIS, patching, and who is a local administrator where. These are the
 * reports that get asked for at audit time and written from scratch every
 * time, and the module scaffold at the end is for when the answer is a proper
 * module rather than another loose script.
 */

import { bool, num, str,                      } from '../../kit/blueprint.js';
import { error, warning,              } from '../../core/findings.js';
import { scriptBlueprint,                      } from '../from-script.js';
import { identifier, listOf, pascal, quoted,             } from '../script.js';

const PLATFORM = 'powershell'         ;

function preamble(params                   , changes         )           {
  return [
    ...(changes ? ["[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]"] : ['[CmdletBinding()]']),
    'param(',
    ...params.map((line, index, all) => `    ${line}${index === all.length - 1 ? '' : ','}`),
    ')',
    '',
    'Set-StrictMode -Version Latest',
    "$ErrorActionPreference = 'Stop'",
    '',
  ];
}

function logging()           {
  return [
    'function Write-Log {',
    "    param([Parameter(Mandatory)][string]$Message, [ValidateSet('INFO','WARN','ERROR')][string]$Level = 'INFO')",
    "    $line = '{0} [{1}] {2}' -f (Get-Date).ToString('yyyy-MM-dd HH:mm:ss'), $Level, $Message",
    "    if ($Level -eq 'ERROR') { Write-Error $line -ErrorAction Continue }",
    "    elseif ($Level -eq 'WARN') { Write-Warning $line }",
    '    else { Write-Information $line -InformationAction Continue }',
    '}',
    '',
  ];
}

export const POWERSHELL_INFRA                             = [
  scriptBlueprint({
    id: 'ps_file_acl_audit',
    platform: PLATFORM,
    label: 'File share permission audit',
    group: 'File services',
    description: 'Who can reach what on a share: broken inheritance, permissions granted to individuals rather than groups, and anything readable by Everyone.',
    inputs: [
      { id: 'script_name', label: 'Script name', control: 'text', default: 'Get-SharePermissions' },
      { id: 'paths', label: 'Paths', control: 'textarea', default: '\\\\files01\\Departments\n\\\\files01\\Projects' },
      { id: 'depth', label: 'How deep', control: 'number', default: 2, min: 1, max: 10, hint: 'Folders below the root. Deep scans on a large share take hours' },
      { id: 'flag', label: 'Flag', control: 'select', default: 'all', options: [
        { value: 'all', label: 'Broken inheritance, direct user grants, and open access' },
        { value: 'open', label: 'Open access only — Everyone, Authenticated Users, Domain Users' },
        { value: 'inheritance', label: 'Broken inheritance only' },
      ] },
      { id: 'open_principals', label: 'Treat as open', control: 'text', default: 'Everyone, Authenticated Users, Domain Users, BUILTIN\\Users' },
      { id: 'resolve_groups', label: 'Expand group membership', control: 'toggle', default: false, hint: 'Shows who is actually in each group — slow, and the interesting part' },
      { id: 'include_share_permissions', label: 'Also read the share permissions', control: 'toggle', default: true, hint: 'Share and NTFS permissions combine; reading only one tells you half the story' },
    ],
    script: (values                 )         => {
      const name = identifier(str(values, 'script_name', 'Get-SharePermissions'), 'Get-SharePermissions');
      const paths = listOf(str(values, 'paths', '').replace(/\n/g, ','));
      const depth = num(values, 'depth', 2);
      const open = listOf(str(values, 'open_principals', ''));
      const findings            = [];

      if (paths.length === 0) findings.push(error('scripts.ps.no-paths', 'No path was given, so this scans nothing.', { source: 'ArchToolKit' }));
      if (depth > 4) {
        findings.push(
          warning('scripts.ps.deep-acl-scan', `Reading ACLs ${depth} levels deep on a departmental share means hundreds of thousands of Get-Acl calls, each of which is a round trip. Start at two levels and go deeper only where something looks wrong.`, {
            source: 'ArchToolKit',
          }),
        );
      }
      if (bool(values, 'resolve_groups', false)) {
        findings.push(
          warning('scripts.ps.group-expansion-slow', 'Expanding group membership is a directory query per group, recursively. It is the part of the report people actually want, and it is what turns a five-minute run into an hour.', {
            source: 'ArchToolKit',
          }),
        );
      }
      if (!bool(values, 'include_share_permissions', true)) {
        findings.push(
          warning('scripts.ps.ntfs-only', 'Share and NTFS permissions combine, and the effective right is the more restrictive of the two. Reading only NTFS reports access that the share permission may be blocking, and misses a share granted to Everyone over a tight NTFS tree.', {
            source: 'ArchToolKit',
          }),
        );
      }

      return {
        platform: PLATFORM,
        title: `Audit permissions on ${paths.length} share path${paths.length === 1 ? '' : 's'}, ${depth} level${depth === 1 ? '' : 's'} deep`,
        effect: 'read',
        requires: [
          { what: 'Read access to the folders — which for an audit usually means administrator' },
          ...(bool(values, 'resolve_groups', false) ? [{ what: 'The ActiveDirectory module, to expand groups' }] : []),
          ...(bool(values, 'include_share_permissions', true) ? [{ what: 'Remote access to the file server, for Get-SmbShareAccess' }] : []),
        ],
        parameters: [
          { name: '-Path', description: 'Paths to scan, overriding the built-in list.', required: false },
          { name: '-Depth', description: 'How many levels below the root.', required: false },
        ],
        notes: [
          'Broken inheritance is the finding that matters most. A folder with inheritance disabled keeps whatever it was given at that moment, for ever, and is invisible from the parent — which is how someone still has access to a share they left five years ago.',
          'A permission granted to a named user rather than a group is the second finding. It does not appear in any group review and it survives the person changing roles.',
          `Open access is anything granted to ${open.join(', ')}. On a departmental share that is almost always a mistake and almost always old.`,
          'The report is per folder, not per file. File-level permissions inside a folder with sane inheritance are rare and the report would be unreadable.',
        ],
        usage: [`pwsh -File .\\${name}.ps1 -Verbose`, `pwsh -File .\\${name}.ps1 -Depth 1`, `pwsh -File .\\${name}.ps1 | Where-Object IsOpen | Format-Table Path, Principal, Rights`],
        undo: ['Nothing to undo — it reads and reports.'],
        body: [
          ...preamble([`[string[]]$Path = @(${paths.map((p) => quoted(p)).join(', ')})`, `[int]$Depth = ${depth}`, "[string]$OutputPath = 'C:\\Reports'"], false),
          ...logging(),
          `$openPrincipals = @(${open.map((p) => quoted(p)).join(', ')})`,
          '',
          ...(bool(values, 'resolve_groups', false)
            ? [
                '$groupCache = @{}',
                'function Resolve-GroupMembers {',
                '    param([string]$Name)',
                '    if ($groupCache.ContainsKey($Name)) { return $groupCache[$Name] }',
                "    $short = $Name -replace '^.*\\\\', ''",
                '    try {',
                '        $members = Get-ADGroupMember -Identity $short -Recursive -ErrorAction Stop |',
                '            Select-Object -ExpandProperty SamAccountName',
                "        $groupCache[$Name] = $members -join ', '",
                '    } catch {',
                "        $groupCache[$Name] = ''",
                '    }',
                '    return $groupCache[$Name]',
                '}',
                '',
              ]
            : []),
          'try {',
          ...(bool(values, 'resolve_groups', false) ? ['    Import-Module ActiveDirectory', ''] : []),
          '    $report = [System.Collections.Generic.List[object]]::new()',
          '',
          '    foreach ($root in $Path) {',
          '        if (-not (Test-Path $root)) {',
          '            Write-Log "No such path: $root" -Level WARN',
          '            continue',
          '        }',
          '        Write-Log "Scanning $root"',
          '',
          ...(bool(values, 'include_share_permissions', true)
            ? [
                '        # Share and NTFS permissions combine; the effective right is the',
                '        # more restrictive of the two. Reading only one tells half the story.',
                "        if ($root -match '^\\\\\\\\([^\\\\]+)\\\\([^\\\\]+)') {",
                '            $server = $Matches[1]',
                '            $share = $Matches[2]',
                '            try {',
                '                foreach ($access in Get-SmbShareAccess -Name $share -CimSession $server -ErrorAction Stop) {',
                '                    $report.Add([pscustomobject]@{',
                '                        Path        = $root',
                "                        Level       = 'Share'",
                '                        Principal   = $access.AccountName',
                '                        Rights      = $access.AccessRight',
                '                        Type        = $access.AccessControlType',
                '                        Inherited   = $null',
                '                        IsOpen      = $access.AccountName -in $openPrincipals',
                '                        IsDirectUser = $false',
                '                        BrokenInheritance = $false',
                '                    })',
                '                }',
                '            } catch {',
                '                Write-Log "Could not read the share permissions for $share on ${server}: $($_.Exception.Message)" -Level WARN',
                '            }',
                '        }',
                '',
              ]
            : []),
          '        $folders = @(Get-Item -Path $root)',
          '        for ($level = 1; $level -le $Depth; $level++) {',
          '            $folders += Get-ChildItem -Path $root -Directory -Depth ($level - 1) -ErrorAction SilentlyContinue',
          '        }',
          '        $folders = $folders | Sort-Object FullName -Unique',
          '        Write-Log "  $($folders.Count) folders"',
          '',
          '        foreach ($folder in $folders) {',
          '            try {',
          '                $acl = Get-Acl -Path $folder.FullName -ErrorAction Stop',
          '            } catch {',
          '                Write-Log "  Could not read $($folder.FullName): $($_.Exception.Message)" -Level WARN',
          '                continue',
          '            }',
          '',
          '            # Inheritance disabled means this folder keeps whatever it was',
          '            # given at that moment, for ever, invisibly from the parent.',
          '            $broken = $acl.AreAccessRulesProtected',
          '',
          '            foreach ($rule in $acl.Access) {',
          '                $principal = $rule.IdentityReference.Value',
          '                $isOpen = $principal -in $openPrincipals',
          '',
          '                # A grant to a named user does not appear in any group review',
          '                # and survives the person changing roles.',
          '                $isUser = $false',
          '                try {',
          "                    $short = $principal -replace '^.*\\\\', ''",
          "                    if ($principal -notmatch '^(NT |BUILTIN|CREATOR|S-1-5)') {",
          '                        $isUser = $null -ne (Get-ADUser -Filter "SamAccountName -eq \'$short\'" -ErrorAction SilentlyContinue)',
          '                    }',
          '                } catch { }',
          '',
          ...(str(values, 'flag', 'all') === 'open'
            ? ['                if (-not $isOpen) { continue }']
            : str(values, 'flag', 'all') === 'inheritance'
              ? ['                if (-not $broken) { continue }']
              : ['                if (-not ($isOpen -or $isUser -or $broken)) { continue }']),
          '',
          '                $report.Add([pscustomobject]@{',
          '                    Path              = $folder.FullName',
          "                    Level             = 'NTFS'",
          '                    Principal         = $principal',
          '                    Rights            = $rule.FileSystemRights',
          '                    Type              = $rule.AccessControlType',
          '                    Inherited         = $rule.IsInherited',
          '                    IsOpen            = $isOpen',
          '                    IsDirectUser      = $isUser',
          '                    BrokenInheritance = $broken',
          ...(bool(values, 'resolve_groups', false) ? ['                    Members           = if (-not $isUser) { Resolve-GroupMembers $principal } else { $null }'] : []),
          '                })',
          '            }',
          '        }',
          '    }',
          '',
          '    if (-not (Test-Path $OutputPath)) { New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null }',
          '    $file = Join-Path $OutputPath ("' + name + '-{0:yyyyMMdd}.csv" -f (Get-Date))',
          '    $report | Export-Csv -Path $file -NoTypeInformation',
          '',
          '    Write-Log "$($report.Count) entries of interest"',
          '    Write-Log "  $(@($report | Where-Object IsOpen).Count) grant access to a broad principal"',
          '    Write-Log "  $(@($report | Where-Object IsDirectUser).Count) grant access to a named user rather than a group"',
          '    Write-Log "  $(@($report | Where-Object BrokenInheritance | Select-Object -Unique Path).Count) folders have inheritance disabled"',
          '    Write-Log "Report written to $file"',
          '    $report',
          '}',
          'catch {',
          '    Write-Log $_.Exception.Message -Level ERROR',
          '    throw',
          '}',
        ],
        findings,
      };
    },
  }),

  scriptBlueprint({
    id: 'ps_dns_dhcp_report',
    platform: PLATFORM,
    label: 'DNS and DHCP health',
    group: 'Network services',
    description: 'Scope utilisation, stale DNS records, scavenging settings and whether the two agree with each other — the report that explains most "the name resolves to the wrong machine" tickets.',
    inputs: [
      { id: 'script_name', label: 'Script name', control: 'text', default: 'Get-DnsDhcpHealth' },
      { id: 'dhcp_servers', label: 'DHCP servers', control: 'text', default: 'dhcp01.example.com, dhcp02.example.com' },
      { id: 'dns_servers', label: 'DNS servers', control: 'text', default: 'dc01.example.com' },
      { id: 'zones', label: 'DNS zones', control: 'text', default: 'example.com', hint: 'Empty for every primary zone' },
      { id: 'scope_warn', label: 'Warn when a scope is above (% used)', control: 'number', default: 80, min: 1, max: 100 },
      { id: 'stale_days', label: 'A record is stale after (days)', control: 'number', default: 30, min: 1, max: 3650 },
      { id: 'check_scavenging', label: 'Check scavenging is configured', control: 'toggle', default: true },
      { id: 'find_duplicates', label: 'Find duplicate A and AAAA records', control: 'toggle', default: true, hint: 'Two records of one type for one name is the usual cause of intermittent connection failures' },
      { id: 'include_ipv6', label: 'Include IPv6', control: 'toggle', default: true, hint: 'AAAA records and DHCPv6 scopes, beside the A records and IPv4 scopes' },
    ],
    script: (values                 )         => {
      const name = identifier(str(values, 'script_name', 'Get-DnsDhcpHealth'), 'Get-DnsDhcpHealth');
      const dhcp = listOf(str(values, 'dhcp_servers', ''));
      const dns = listOf(str(values, 'dns_servers', ''));
      const zones = listOf(str(values, 'zones', ''));
      const scopeWarn = num(values, 'scope_warn', 80);
      const v6 = bool(values, 'include_ipv6', true);
      const findings            = [];

      if (dhcp.length === 0 && dns.length === 0) findings.push(error('scripts.ps.no-servers', 'No DHCP and no DNS server was given.', { source: 'ArchToolKit' }));
      if (bool(values, 'check_scavenging', true)) {
        findings.push(
          warning('scripts.ps.scavenging-hazard', 'Enabling scavenging on a zone that has never had it deletes every record whose timestamp is older than the refresh and no-refresh intervals combined — which, on a zone where it was never on, can be most of them. Enable it in a window, with a backup of the zone, and watch the first cycle.', {
            remediation: 'Export the zone first: Export-DnsServerZone -Name <zone> -FileName <zone>.bak',
            source: 'ArchToolKit',
          }),
        );
      }

      return {
        platform: PLATFORM,
        title: 'Report DHCP scope utilisation and DNS record health',
        effect: 'read',
        requires: [
          ...(dhcp.length > 0 ? [{ what: 'The DhcpServer module', how: 'Install-WindowsFeature RSAT-DHCP' }] : []),
          ...(dns.length > 0 ? [{ what: 'The DnsServer module', how: 'Install-WindowsFeature RSAT-DNS-Server' }] : []),
          { what: 'Read access to the DHCP and DNS servers' },
        ],
        parameters: [{ name: '-OutputPath', description: 'Where the CSVs are written.', required: false }],
        notes: [
          'Scope utilisation is the number that predicts an outage. A scope at 95% on a Friday is a Monday morning where new machines get no address and nobody can explain why.',
          'A stale DNS record is one whose timestamp has not moved. It usually points at an address that now belongs to something else, which is why a name intermittently resolves to the wrong machine.',
          ...(bool(values, 'find_duplicates', true) ? ['Two A records for one name means round-robin between them, so connections fail roughly half the time. It is the single most confusing DNS fault to diagnose from the client side.'] : []),
          'Scavenging has to be enabled in three places — the server, the zone, and the ageing settings — and all three have to agree. A zone with scavenging on and a server with it off does nothing.',
          ...(v6
            ? [
                'AAAA records are read beside A records. A stale AAAA is worse than a stale A: clients prefer IPv6, so a name whose AAAA points at a reused address fails first, and only for dual-stack clients.',
                'DHCPv6 scopes are reported with the IPv4 ones (the Family column tells them apart). Windows DHCP failover is IPv4 only, so DHCPv6 resilience is a split scope on two servers, and there is no failover state to check.',
                'Hosts that take their IPv6 address by SLAAC never appear in a DHCPv6 scope; the router advertisement decides that, not this server.',
              ]
            : []),
        ],
        usage: [`pwsh -File .\\${name}.ps1 -Verbose`, `pwsh -File .\\${name}.ps1 | Where-Object PercentUsed -gt ${scopeWarn}`],
        undo: ['Nothing to undo — it reads and reports.'],
        body: [
          ...preamble(["[string]$OutputPath = 'C:\\Reports'", `[int]$StaleDays = ${num(values, 'stale_days', 30)}`], false),
          ...logging(),
          'try {',
          '    if (-not (Test-Path $OutputPath)) { New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null }',
          "    $stamp = (Get-Date).ToString('yyyyMMdd')",
          '',
          ...(dhcp.length > 0
            ? [
                '    # --- DHCP ------------------------------------------------------------',
                '    Import-Module DhcpServer',
                '    $scopes = [System.Collections.Generic.List[object]]::new()',
                `    foreach ($server in @(${dhcp.map((s) => quoted(s)).join(', ')})) {`,
                '        try {',
                '            $found = Get-DhcpServerv4Scope -ComputerName $server -ErrorAction Stop',
                '        } catch {',
                '            Write-Log "Could not read ${server}: $($_.Exception.Message)" -Level WARN',
                '            continue',
                '        }',
                '        foreach ($scope in $found) {',
                '            $stats = Get-DhcpServerv4ScopeStatistics -ComputerName $server -ScopeId $scope.ScopeId',
                '            $scopes.Add([pscustomobject]@{',
                '                Server       = $server',
                "                Family       = 'IPv4'",
                '                ScopeId      = $scope.ScopeId',
                '                Name         = $scope.Name',
                '                State        = $scope.State',
                '                Range        = "$($scope.StartRange) - $($scope.EndRange)"',
                '                LeaseHours   = [math]::Round($scope.LeaseDuration.TotalHours, 1)',
                '                Total        = $stats.Free + $stats.InUse',
                '                InUse        = $stats.InUse',
                '                Free         = $stats.Free',
                '                PercentUsed  = [math]::Round($stats.PercentageInUse, 1)',
                '            })',
                `            if ($stats.PercentageInUse -ge ${scopeWarn}) {`,
                '                Write-Log "$server $($scope.Name) is $([math]::Round($stats.PercentageInUse, 1))% used" -Level WARN',
                '            }',
                '        }',
                '        Write-Log "$server : $($found.Count) scopes"',
                '',
                '        # A failover relationship that is not normal means one server is',
                '        # carrying the load and nobody has noticed.',
                '        try {',
                '            foreach ($failover in Get-DhcpServerv4Failover -ComputerName $server -ErrorAction Stop) {',
                "                if ($failover.State -ne 'Normal') {",
                '                    Write-Log "$server failover $($failover.Name) is $($failover.State)" -Level WARN',
                '                }',
                '            }',
                '        } catch { }',
                ...(v6
                  ? [
                      '',
                      '        # DHCPv6. A stateful scope is always a /64, so "free" is a',
                      '        # number with twenty digits; the percentage is the figure to read.',
                      '        # Windows has no DHCPv6 failover, so there is nothing to check',
                      '        # there — two servers mean a split scope set up by hand.',
                      '        try {',
                      '            $found6 = @(Get-DhcpServerv6Scope -ComputerName $server -ErrorAction Stop)',
                      '        } catch {',
                      '            Write-Log "Could not read DHCPv6 on ${server}: $($_.Exception.Message)" -Level WARN',
                      '            $found6 = @()',
                      '        }',
                      '        foreach ($scope in $found6) {',
                      '            $stats = Get-DhcpServerv6ScopeStatistics -ComputerName $server -Prefix $scope.Prefix',
                      "            $inUse = if ($stats.PSObject.Properties['AddressesInUse']) { $stats.AddressesInUse } else { $stats.InUse }",
                      "            $free = if ($stats.PSObject.Properties['AddressesFree']) { $stats.AddressesFree } else { $stats.Free }",
                      "            $percent = if ($stats.PSObject.Properties['PercentageInUse']) { [double]$stats.PercentageInUse } elseif (($free + $inUse) -gt 0) { 100.0 * $inUse / ($free + $inUse) } else { 0 }",
                      '            $scopes.Add([pscustomobject]@{',
                      '                Server       = $server',
                      "                Family       = 'IPv6'",
                      '                ScopeId      = "$($scope.Prefix)/64"',
                      '                Name         = $scope.Name',
                      '                State        = $scope.State',
                      '                Range        = "$($scope.Prefix)/64"',
                      '                LeaseHours   = [math]::Round($scope.PreferredLifetime.TotalHours, 1)',
                      '                Total        = $free + $inUse',
                      '                InUse        = $inUse',
                      '                Free         = $free',
                      '                PercentUsed  = [math]::Round($percent, 1)',
                      '            })',
                      `            if ($percent -ge ${scopeWarn}) {`,
                      '                Write-Log "$server $($scope.Name) (DHCPv6) is $([math]::Round($percent, 1))% used" -Level WARN',
                      '            }',
                      '        }',
                      '        Write-Log "$server : $($found6.Count) DHCPv6 scopes"',
                    ]
                  : []),
                '    }',
                '    $scopes | Export-Csv -Path (Join-Path $OutputPath "dhcp-scopes-$stamp.csv") -NoTypeInformation',
                '',
              ]
            : []),
          ...(dns.length > 0
            ? [
                '    # --- DNS -------------------------------------------------------------',
                '    Import-Module DnsServer',
                '    $records = [System.Collections.Generic.List[object]]::new()',
                '    $cutoff = (Get-Date).AddDays(-$StaleDays)',
                '',
                `    foreach ($server in @(${dns.map((s) => quoted(s)).join(', ')})) {`,
                ...(zones.length > 0
                  ? [`        $zoneNames = @(${zones.map((z) => quoted(z)).join(', ')})`]
                  : ["        $zoneNames = (Get-DnsServerZone -ComputerName $server | Where-Object { -not $_.IsReverseLookupZone -and $_.ZoneType -eq 'Primary' }).ZoneName"]),
                '',
                ...(bool(values, 'check_scavenging', true)
                  ? [
                      '        # Scavenging has to agree in three places or it does nothing.',
                      '        $serverScavenging = Get-DnsServerScavenging -ComputerName $server',
                      '        if (-not $serverScavenging.ScavengingState) {',
                      '            Write-Log "$server : scavenging is off at the server, so no zone can scavenge" -Level WARN',
                      '        }',
                      '',
                    ]
                  : []),
                '        foreach ($zone in $zoneNames) {',
                ...(bool(values, 'check_scavenging', true)
                  ? [
                      '            $zoneAging = Get-DnsServerZoneAging -ComputerName $server -Name $zone -ErrorAction SilentlyContinue',
                      '            if ($zoneAging -and -not $zoneAging.AgingEnabled) {',
                      '                Write-Log "$server/${zone}: ageing is off, so records never get a timestamp and never scavenge" -Level WARN',
                      '            }',
                      '',
                    ]
                  : []),
                ...(v6 ? ['            # AAAA records go stale the same way A records do, and are easier to miss.'] : []),
                `            foreach ($rrType in @(${v6 ? "'A', 'AAAA'" : "'A'"})) {`,
                '                $found = @(Get-DnsServerResourceRecord -ComputerName $server -ZoneName $zone -RRType $rrType -ErrorAction SilentlyContinue)',
                '                foreach ($record in $found) {',
                '                    $stale = $record.Timestamp -and $record.Timestamp -lt $cutoff',
                '                    $records.Add([pscustomobject]@{',
                '                        Server    = $server',
                '                        Zone      = $zone',
                '                        Name      = $record.HostName',
                '                        Type      = $rrType',
                "                        Address   = if ($rrType -eq 'AAAA') { $record.RecordData.IPv6Address.IPAddressToString } else { $record.RecordData.IPv4Address.IPAddressToString }",
                '                        Timestamp = $record.Timestamp',
                '                        Static    = $null -eq $record.Timestamp',
                '                        AgeDays   = if ($record.Timestamp) { [int]((Get-Date) - $record.Timestamp).TotalDays } else { $null }',
                '                        Stale     = $stale',
                '                    })',
                '                }',
                '                Write-Log "$server/${zone}: $($found.Count) $rrType records"',
                '            }',
                '        }',
                '    }',
                '',
                '    $records | Export-Csv -Path (Join-Path $OutputPath "dns-records-$stamp.csv") -NoTypeInformation',
                '    Write-Log "$(@($records | Where-Object Stale).Count) records not refreshed for $StaleDays days"',
                '    Write-Log "$(@($records | Where-Object Static).Count) records have no timestamp — either static, or created before ageing was on"',
                '',
                ...(bool(values, 'find_duplicates', true)
                  ? [
                      '    # Two A records for one name means round-robin, so connections',
                      '    # fail roughly half the time. It is the hardest DNS fault to see',
                      '    # from the client.',
                      ...(v6
                        ? [
                            '    # Grouped by type as well: one A and one AAAA for a name is',
                            '    # dual-stack, not a duplicate.',
                          ]
                        : []),
                      '    $duplicates = @($records | Group-Object Zone, Name, Type | Where-Object Count -gt 1)',
                      '    foreach ($group in $duplicates) {',
                      "        Write-Log \"Duplicate: $($group.Name) resolves to $(($group.Group.Address) -join ', ')\" -Level WARN",
                      '    }',
                      `    Write-Log "$($duplicates.Count) names have more than one ${v6 ? 'A or AAAA' : 'A'} record"`,
                      '',
                    ]
                  : []),
              ]
            : []),
          '    Write-Log "Reports written to $OutputPath"',
          ...(dhcp.length > 0 ? ['    $scopes | Sort-Object PercentUsed -Descending'] : ['    $records | Where-Object Stale']),
          '}',
          'catch {',
          '    Write-Log $_.Exception.Message -Level ERROR',
          '    throw',
          '}',
        ],
        findings,
      };
    },
  }),

  scriptBlueprint({
    id: 'ps_local_admin_audit',
    platform: PLATFORM,
    label: 'Local administrator audit',
    group: 'Security',
    description: 'Who is a local administrator on every machine, expanded through nested groups — the question that has no central answer and that every audit asks.',
    inputs: [
      { id: 'script_name', label: 'Script name', control: 'text', default: 'Get-LocalAdministrators' },
      { id: 'computers_from', label: 'Machines from', control: 'select', default: 'ad', options: [
        { value: 'ad', label: 'An Active Directory OU' },
        { value: 'file', label: 'A text file' },
      ] },
      { id: 'ou', label: 'OU', control: 'text', default: 'OU=Workstations,DC=example,DC=com', showWhen: { input: 'computers_from', equals: ['ad'] } },
      { id: 'expected', label: 'Expected members', control: 'textarea', default: 'EXAMPLE\\Domain Admins\nEXAMPLE\\Workstation Admins\nAdministrator', hint: 'Anything else is a finding' },
      { id: 'expand_groups', label: 'Expand domain groups', control: 'toggle', default: true },
      { id: 'also_check', label: 'Also report', control: 'select', default: 'laps', options: [
        { value: 'laps', label: 'Whether LAPS is managing the local administrator password' },
        { value: 'none', label: 'Membership only' },
      ] },
      { id: 'parallel', label: 'Machines at a time', control: 'number', default: 20, min: 1, max: 200 },
    ],
    script: (values                 )         => {
      const name = identifier(str(values, 'script_name', 'Get-LocalAdministrators'), 'Get-LocalAdministrators');
      const expected = listOf(str(values, 'expected', '').replace(/\n/g, ','));
      const fromAd = str(values, 'computers_from', 'ad') === 'ad';
      const laps = str(values, 'also_check', 'laps') === 'laps';
      const findings            = [];

      if (expected.length === 0) {
        findings.push(
          warning('scripts.ps.no-expected-members', 'With no expected list every member is reported, which is an inventory rather than a finding. Naming what should be there is what turns this into an exception report.', {
            source: 'ArchToolKit',
          }),
        );
      }
      findings.push(
        warning('scripts.ps.local-admin-remoting', 'This needs remoting to every machine. A workstation that is off, asleep or off the network is reported as unreachable rather than as compliant — and on a typical estate that is a third of them at any moment. Run it over several days and merge.', {
          source: 'ArchToolKit',
        }),
      );

      return {
        platform: PLATFORM,
        title: 'Report local administrator membership across the estate',
        effect: 'read',
        requires: [
          { what: 'PowerShell remoting to the machines' },
          { what: 'Local administrator on them, to read the group' },
          ...(fromAd ? [{ what: 'The ActiveDirectory module, to list the machines' }] : []),
        ],
        parameters: [
          { name: '-ComputerName', description: 'Machines, overriding the OU or file.', required: false },
          { name: '-OutputPath', description: 'Where the CSV is written.', required: false },
        ],
        notes: [
          'A nested domain group is where the interesting members hide. "EXAMPLE\\Helpdesk" in the local administrators group is one line here and forty people in reality — so it is expanded.',
          'An account in the group that no longer resolves is reported as an orphaned SID. That is a deleted account whose membership was never cleaned up, and it is worth removing.',
          ...(laps ? ['LAPS managing the local administrator password means that account is unique per machine and rotates. A machine without it shares whatever password was in the image, which is the classic lateral movement path.'] : []),
          'Unreachable is not compliant. A machine that could not be read is in the report with that status, and should stay on the list until it is.',
        ],
        usage: [`pwsh -File .\\${name}.ps1 -Verbose`, `pwsh -File .\\${name}.ps1 | Where-Object Unexpected`, `pwsh -File .\\${name}.ps1 | Group-Object Status | Select-Object Name, Count`],
        undo: ['Nothing to undo — it reads and reports.'],
        body: [
          ...preamble(
            [
              '[string[]]$ComputerName',
              ...(fromAd ? [`[string]$SearchBase = ${quoted(str(values, 'ou', ''))}`] : ['[string]$ComputerListPath']),
              `[int]$ThrottleLimit = ${num(values, 'parallel', 20)}`,
              "[string]$OutputPath = 'C:\\Reports'",
            ],
            false,
          ),
          ...logging(),
          `$expected = @(${expected.map((e) => quoted(e)).join(', ')})`,
          '',
          'try {',
          '    if (-not $ComputerName) {',
          ...(fromAd
            ? [
                '        Import-Module ActiveDirectory',
                '        $ComputerName = Get-ADComputer -SearchBase $SearchBase -Filter { Enabled -eq $true } |',
                '            Select-Object -ExpandProperty Name',
              ]
            : ['        $ComputerName = Get-Content -Path $ComputerListPath | Where-Object { $_.Trim() }']),
          '    }',
          '    Write-Log "$($ComputerName.Count) machines in scope"',
          '',
          '    $results = $ComputerName | ForEach-Object -ThrottleLimit $ThrottleLimit -Parallel {',
          '        $computer = $_',
          '        $out = [System.Collections.Generic.List[object]]::new()',
          '',
          '        if (-not (Test-Connection -ComputerName $computer -Count 1 -Quiet -TimeoutSeconds 2)) {',
          "            $out.Add([pscustomobject]@{ Computer = $computer; Member = '-'; Type = '-'; Status = 'Unreachable'; Unexpected = $false })",
          '            return $out',
          '        }',
          '',
          '        try {',
          '            $members = Invoke-Command -ComputerName $computer -ErrorAction Stop -ScriptBlock {',
          '                $group = Get-LocalGroup -SID S-1-5-32-544   # Administrators, whatever it is called locally',
          '                Get-LocalGroupMember -Group $group | ForEach-Object {',
          '                    [pscustomobject]@{',
          '                        Name           = $_.Name',
          '                        ObjectClass    = $_.ObjectClass',
          '                        PrincipalSource = $_.PrincipalSource',
          '                        SID            = $_.SID.Value',
          '                    }',
          '                }',
          '            }',
          '        } catch {',
          "            $out.Add([pscustomobject]@{ Computer = $computer; Member = '-'; Type = '-'; Status = 'Failed'; Detail = $_.Exception.Message; Unexpected = $false })",
          '            return $out',
          '        }',
          '',
          '        foreach ($member in $members) {',
          '            $out.Add([pscustomobject]@{',
          '                Computer   = $computer',
          '                Member     = $member.Name',
          '                Type       = $member.ObjectClass',
          '                Source     = $member.PrincipalSource',
          '                SID        = $member.SID',
          "                Status     = 'OK'",
          '                Unexpected = $member.Name -notin $using:expected',
          '            })',
          '        }',
          '        return $out',
          '    }',
          '',
          '    $results = @($results) | Sort-Object Computer, Member',
          '',
          ...(bool(values, 'expand_groups', true)
            ? [
                '    # A nested domain group is one line here and forty people in reality.',
                '    Import-Module ActiveDirectory -ErrorAction SilentlyContinue',
                '    $cache = @{}',
                "    foreach ($row in $results | Where-Object { $_.Type -eq 'Group' -and $_.Source -eq 'ActiveDirectory' }) {",
                "        $short = $row.Member -replace '^.*\\\\', ''",
                '        if (-not $cache.ContainsKey($short)) {',
                '            try {',
                '                $cache[$short] = (Get-ADGroupMember -Identity $short -Recursive -ErrorAction Stop).SamAccountName',
                '            } catch {',
                '                $cache[$short] = @()',
                '            }',
                '        }',
                "        $row | Add-Member -NotePropertyName 'ExpandsTo' -NotePropertyValue ($cache[$short] -join ', ') -Force",
                "        $row | Add-Member -NotePropertyName 'EffectiveCount' -NotePropertyValue $cache[$short].Count -Force",
                '    }',
                '',
              ]
            : []),
          ...(laps
            ? [
                '    # LAPS means the local administrator password is unique per machine',
                '    # and rotates. Without it, every machine shares the image password.',
                '    Import-Module ActiveDirectory -ErrorAction SilentlyContinue',
                '    foreach ($computer in ($results.Computer | Sort-Object -Unique)) {',
                '        try {',
                "            $ad = Get-ADComputer -Identity $computer -Properties 'ms-Mcs-AdmPwdExpirationTime', 'msLAPS-PasswordExpirationTime' -ErrorAction Stop",
                "            $managed = $null -ne $ad.'ms-Mcs-AdmPwdExpirationTime' -or $null -ne $ad.'msLAPS-PasswordExpirationTime'",
                '            if (-not $managed) { Write-Log "$computer : the local administrator password is not managed by LAPS" -Level WARN }',
                '        } catch { }',
                '    }',
                '',
              ]
            : []),
          '    if (-not (Test-Path $OutputPath)) { New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null }',
          '    $file = Join-Path $OutputPath ("' + name + '-{0:yyyyMMdd}.csv" -f (Get-Date))',
          '    $results | Export-Csv -Path $file -NoTypeInformation',
          '',
          '    $unexpected = @($results | Where-Object Unexpected)',
          "    $unreachable = @($results | Where-Object Status -eq 'Unreachable')",
          '    Write-Log "$($results.Count) rows across $(($results.Computer | Sort-Object -Unique).Count) machines"',
          '    Write-Log "$($unexpected.Count) unexpected members on $(($unexpected.Computer | Sort-Object -Unique).Count) machines" -Level WARN',
          '    Write-Log "$($unreachable.Count) machines could not be read — unreachable is not compliant"',
          '',
          '    # An account that no longer resolves is a deleted account whose',
          '    # membership was never cleaned up.',
          "    $orphans = @($results | Where-Object { $_.Member -match '^S-1-5-21-' })",
          '    if ($orphans.Count) { Write-Log "$($orphans.Count) orphaned SIDs — deleted accounts still in the group" -Level WARN }',
          '',
          '    Write-Log "Report written to $file"',
          '    $results',
          '}',
          'catch {',
          '    Write-Log $_.Exception.Message -Level ERROR',
          '    throw',
          '}',
        ],
        findings,
      };
    },
  }),

  scriptBlueprint({
    id: 'ps_patch_compliance',
    platform: PLATFORM,
    label: 'Patch compliance report',
    group: 'Windows servers',
    description: 'What is missing, how old it is, whether a reboot is pending, and which machines have not checked in at all — the four numbers a patching conversation needs.',
    inputs: [
      { id: 'script_name', label: 'Script name', control: 'text', default: 'Get-PatchCompliance' },
      { id: 'computers_from', label: 'Machines from', control: 'select', default: 'ad', options: [
        { value: 'ad', label: 'An Active Directory OU' },
        { value: 'file', label: 'A text file' },
      ] },
      { id: 'ou', label: 'OU', control: 'text', default: 'OU=Servers,DC=example,DC=com', showWhen: { input: 'computers_from', equals: ['ad'] } },
      { id: 'severity', label: 'Count as missing', control: 'select', default: 'security', options: [
        { value: 'security', label: 'Security updates only' },
        { value: 'all', label: 'Everything the machine offers' },
        { value: 'critical', label: 'Critical and important only' },
      ] },
      { id: 'age_warn', label: 'Flag updates older than (days)', control: 'number', default: 30, min: 1, max: 365 },
      { id: 'checkin_days', label: 'Flag machines not checked in for (days)', control: 'number', default: 14, min: 1, max: 365 },
      { id: 'check_reboot', label: 'Check for a pending reboot', control: 'toggle', default: true, hint: 'An installed patch that has never rebooted is not applied' },
      { id: 'parallel', label: 'Machines at a time', control: 'number', default: 15, min: 1, max: 100 },
    ],
    script: (values                 )         => {
      const name = identifier(str(values, 'script_name', 'Get-PatchCompliance'), 'Get-PatchCompliance');
      const fromAd = str(values, 'computers_from', 'ad') === 'ad';
      const severity = str(values, 'severity', 'security');
      const findings            = [];

      findings.push(
        warning('scripts.ps.windows-update-com-slow', 'Querying Windows Update on a machine is a COM call that contacts the update source, and it can take minutes per machine. Across a hundred servers this is a long run whatever the parallelism, and it puts load on the WSUS server if there is one.', {
          remediation: 'If there is a patching product — Configuration Manager, Intune, WSUS reporting — its database has this already and answering from there is instant.',
          source: 'ArchToolKit',
        }),
      );
      if (bool(values, 'check_reboot', true)) {
        findings.push(
          warning('scripts.ps.pending-reboot-matters', 'A machine with a pending reboot has patches installed that are not in effect. It reports as compliant to most tools and is not protected, which is the worst of both.', {
            source: 'ArchToolKit',
          }),
        );
      }

      return {
        platform: PLATFORM,
        title: `Report missing ${severity} updates across the estate`,
        effect: 'read',
        requires: [
          { what: 'PowerShell remoting to the machines' },
          { what: 'Local administrator on them, to query Windows Update' },
          ...(fromAd ? [{ what: 'The ActiveDirectory module' }] : []),
        ],
        parameters: [
          { name: '-ComputerName', description: 'Machines, overriding the OU or file.', required: false },
          { name: '-OutputPath', description: 'Where the CSV is written.', required: false },
        ],
        notes: [
          'This reads what each machine believes is missing, from its own update source. A machine pointed at the wrong WSUS group will report itself compliant against the wrong baseline — so the source is reported too.',
          'The oldest missing update is the number that matters. "Twelve updates missing" says less than "the oldest is from March".',
          ...(bool(values, 'check_reboot', true) ? ['Pending reboot is checked in all three places Windows records it: Component Based Servicing, Windows Update, and a pending file rename. Checking only one misses cases.'] : []),
          'Nothing is installed. This is a report — installing is a separate decision, a separate window and a separate script.',
        ],
        usage: [`pwsh -File .\\${name}.ps1 -Verbose`, `pwsh -File .\\${name}.ps1 | Where-Object { $_.MissingCount -gt 0 } | Sort-Object OldestMissingDays -Descending`],
        undo: ['Nothing to undo — it reads and reports. Nothing is installed.'],
        body: [
          ...preamble(
            [
              '[string[]]$ComputerName',
              ...(fromAd ? [`[string]$SearchBase = ${quoted(str(values, 'ou', ''))}`] : ['[string]$ComputerListPath']),
              `[int]$ThrottleLimit = ${num(values, 'parallel', 15)}`,
              "[string]$OutputPath = 'C:\\Reports'",
            ],
            false,
          ),
          ...logging(),
          'try {',
          '    if (-not $ComputerName) {',
          ...(fromAd
            ? ['        Import-Module ActiveDirectory', '        $ComputerName = Get-ADComputer -SearchBase $SearchBase -Filter { Enabled -eq $true } | Select-Object -ExpandProperty Name']
            : ['        $ComputerName = Get-Content -Path $ComputerListPath | Where-Object { $_.Trim() }']),
          '    }',
          '    Write-Log "$($ComputerName.Count) machines. This is slow — one COM call per machine."',
          '',
          '    $results = $ComputerName | ForEach-Object -ThrottleLimit $ThrottleLimit -Parallel {',
          '        $computer = $_',
          `        $severity = '${severity}'`,
          '',
          '        if (-not (Test-Connection -ComputerName $computer -Count 1 -Quiet -TimeoutSeconds 2)) {',
          "            return [pscustomobject]@{ Computer = $computer; Status = 'Unreachable' }",
          '        }',
          '',
          '        try {',
          '            Invoke-Command -ComputerName $computer -ErrorAction Stop -ArgumentList $severity -ScriptBlock {',
          '                param($severity)',
          '',
          '                $searcher = (New-Object -ComObject Microsoft.Update.Session).CreateUpdateSearcher()',
          "                $criteria = 'IsInstalled=0 and IsHidden=0'",
          "                if ($severity -eq 'security') { $criteria += \" and CategoryIDs contains '0FA1201D-4330-4FA8-8AE9-B877473B6441'\" }",
          '                $found = $searcher.Search($criteria).Updates',
          '',
          '                $missing = @()',
          '                foreach ($update in $found) {',
          "                    if ($severity -eq 'critical' -and $update.MsrcSeverity -notin @('Critical', 'Important')) { continue }",
          '                    $missing += [pscustomobject]@{',
          '                        Title    = $update.Title',
          '                        Severity = $update.MsrcSeverity',
          '                        Released = $update.LastDeploymentChangeTime',
          "                        KB       = ($update.KBArticleIDs | ForEach-Object { \"KB$_\" }) -join ', '",
          '                    }',
          '                }',
          '',
          '                # Where the machine gets its updates. A machine pointed at the',
          '                # wrong group reports itself compliant against the wrong baseline.',
          "                $wu = Get-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate' -ErrorAction SilentlyContinue",
          '',
          '                # Pending reboot is recorded in three places. Checking one misses cases.',
          '                $reboot = $false',
          "                if (Test-Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Component Based Servicing\\RebootPending') { $reboot = $true }",
          "                if (Test-Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update\\RebootRequired') { $reboot = $true }",
          "                $pendingRename = Get-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager' -Name PendingFileRenameOperations -ErrorAction SilentlyContinue",
          '                if ($pendingRename) { $reboot = $true }',
          '',
          '                $lastInstalled = Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 1',
          '                $oldest = $missing | Where-Object Released | Sort-Object Released | Select-Object -First 1',
          '',
          '                [pscustomobject]@{',
          '                    Computer          = $env:COMPUTERNAME',
          "                    Status            = 'OK'",
          '                    MissingCount      = $missing.Count',
          "                    Critical          = @($missing | Where-Object Severity -eq 'Critical').Count",
          "                    Important         = @($missing | Where-Object Severity -eq 'Important').Count",
          '                    OldestMissing     = $oldest.Released',
          '                    OldestMissingDays = if ($oldest.Released) { [int]((Get-Date) - $oldest.Released).TotalDays } else { $null }',
          '                    LastInstalled     = $lastInstalled.InstalledOn',
          '                    DaysSincePatch    = if ($lastInstalled.InstalledOn) { [int]((Get-Date) - $lastInstalled.InstalledOn).TotalDays } else { $null }',
          '                    PendingReboot     = $reboot',
          '                    UpdateSource      = if ($wu.WUServer) { $wu.WUServer } else { \'Microsoft Update\' }',
          '                    TargetGroup       = $wu.TargetGroup',
          "                    TopMissing        = ($missing | Select-Object -First 5 | ForEach-Object { $_.KB }) -join ', '",
          '                }',
          '            }',
          '        } catch {',
          "            [pscustomobject]@{ Computer = $computer; Status = 'Failed'; Detail = $_.Exception.Message }",
          '        }',
          '    }',
          '',
          '    $results = @($results) | Sort-Object OldestMissingDays -Descending',
          '',
          '    if (-not (Test-Path $OutputPath)) { New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null }',
          '    $file = Join-Path $OutputPath ("' + name + '-{0:yyyyMMdd}.csv" -f (Get-Date))',
          '    $results | Export-Csv -Path $file -NoTypeInformation',
          '',
          `    $behind = @($results | Where-Object { $_.OldestMissingDays -ge ${num(values, 'age_warn', 30)} })`,
          `    $quiet = @($results | Where-Object { $_.DaysSincePatch -ge ${num(values, 'checkin_days', 14)} })`,
          '    $rebooting = @($results | Where-Object PendingReboot)',
          "    $unreachable = @($results | Where-Object Status -ne 'OK')",
          '',
          '    Write-Log "$($results.Count) machines"',
          '    Write-Log "  $($behind.Count) have an update older than ' + num(values, 'age_warn', 30) + ' days" -Level WARN',
          '    Write-Log "  $($quiet.Count) have installed nothing for ' + num(values, 'checkin_days', 14) + ' days"',
          '    Write-Log "  $($rebooting.Count) have patches installed but not in effect, waiting for a reboot" -Level WARN',
          '    Write-Log "  $($unreachable.Count) could not be read"',
          '',
          '    # A machine pointed at an unexpected source is compliant against the',
          '    # wrong baseline, which is worse than being out of date.',
          '    $results | Where-Object UpdateSource | Group-Object UpdateSource |',
          '        ForEach-Object { Write-Log "  $($_.Count) use $($_.Name)" }',
          '',
          '    Write-Log "Report written to $file"',
          '    $results',
          '}',
          'catch {',
          '    Write-Log $_.Exception.Message -Level ERROR',
          '    throw',
          '}',
        ],
        findings,
      };
    },
  }),

  scriptBlueprint({
    id: 'ps_sql_health',
    platform: PLATFORM,
    label: 'SQL Server health check',
    group: 'Databases',
    description: 'Backups, free space, failed jobs, long-running queries and whether the recovery model matches what the backups actually do.',
    inputs: [
      { id: 'script_name', label: 'Script name', control: 'text', default: 'Get-SqlHealth' },
      { id: 'instances', label: 'Instances', control: 'textarea', default: 'sql01.example.com\nsql02.example.com\\NAMED' },
      { id: 'checks', label: 'Check', control: 'select', default: 'all', options: [
        { value: 'all', label: 'Backups, space, jobs, and long-running queries' },
        { value: 'backups', label: 'Backups only' },
        { value: 'space', label: 'Space only' },
      ] },
      { id: 'full_backup_hours', label: 'A full backup is overdue after (hours)', control: 'number', default: 26, min: 1, max: 8760 },
      { id: 'log_backup_minutes', label: 'A log backup is overdue after (minutes)', control: 'number', default: 30, min: 1, max: 10080 },
      { id: 'free_percent', label: 'Warn when a data file is below (% free)', control: 'number', default: 15, min: 1, max: 90 },
      { id: 'auth', label: 'Connect with', control: 'select', default: 'windows', options: [
        { value: 'windows', label: 'Windows authentication' },
        { value: 'sql', label: 'SQL authentication, from SecretManagement' },
      ] },
      { id: 'secret_name', label: 'Secret name', control: 'text', default: 'SqlMonitoring', showWhen: { input: 'auth', equals: ['sql'] } },
    ],
    script: (values                 )         => {
      const name = identifier(str(values, 'script_name', 'Get-SqlHealth'), 'Get-SqlHealth');
      const instances = listOf(str(values, 'instances', '').replace(/\n/g, ','));
      const checks = str(values, 'checks', 'all');
      const sqlAuth = str(values, 'auth', 'windows') === 'sql';
      const findings            = [];

      if (instances.length === 0) findings.push(error('scripts.ps.no-instances', 'No instance was given.', { source: 'ArchToolKit' }));
      findings.push(
        warning('scripts.ps.recovery-model-mismatch', 'A database in full recovery whose log is never backed up grows until the disk fills, and its backups cannot restore to a point in time anyway. That mismatch is the most common serious SQL configuration fault and this reports it explicitly.', {
          source: 'ArchToolKit',
        }),
      );
      if (sqlAuth) {
        findings.push(
          warning('scripts.ps.sql-auth', 'SQL authentication means a password that has to live somewhere. It comes from SecretManagement here rather than the script, but Windows authentication with a service account avoids the question entirely.', {
            source: 'ArchToolKit',
          }),
        );
      }

      return {
        platform: PLATFORM,
        title: `Health check ${instances.length} SQL Server instance${instances.length === 1 ? '' : 's'}`,
        effect: 'read',
        requires: [
          { what: 'The SqlServer module', how: 'Install-Module SqlServer -Scope CurrentUser' },
          { what: 'VIEW SERVER STATE and read access to msdb on each instance' },
          ...(sqlAuth ? [{ what: 'The SecretManagement module and a registered vault' }] : []),
        ],
        parameters: [
          { name: '-Instance', description: 'Instances, overriding the built-in list.', required: false },
          { name: '-OutputPath', description: 'Where the CSVs are written.', required: false },
        ],
        notes: [
          'A backup that has never been restored is not a backup. This checks that backups happened, not that they work — a restore test is a different and more important exercise.',
          'The recovery model check is the one worth reading first: a database in full recovery with no log backups is growing without limit and cannot restore to a point in time. Both halves of that are bad and it is very common.',
          ...(checks === 'all' ? ['Long-running queries are a snapshot, not a trend. A query that has been running for two hours might be a nightly job or might be blocking everything — the report shows the blocking session so you can tell.'] : []),
          'Nothing is changed. No job is started, no backup is taken, nothing is shrunk.',
        ],
        usage: [`pwsh -File .\\${name}.ps1 -Verbose`, `pwsh -File .\\${name}.ps1 | Where-Object BackupOverdue`],
        undo: ['Nothing to undo — it reads and reports.'],
        body: [
          ...preamble(
            [
              `[string[]]$Instance = @(${instances.map((i) => quoted(i)).join(', ')})`,
              "[string]$OutputPath = 'C:\\Reports'",
              ...(sqlAuth ? ['[pscredential]$Credential'] : []),
            ],
            false,
          ),
          'Import-Module SqlServer',
          '',
          ...logging(),
          ...(sqlAuth
            ? [
                'Import-Module Microsoft.PowerShell.SecretManagement',
                `if (-not $Credential) { $Credential = Get-Secret -Name ${quoted(str(values, 'secret_name', 'SqlMonitoring'))} }`,
                '$connection = @{ Credential = $Credential }',
                '',
              ]
            : ['$connection = @{}', '']),
          'try {',
          '    $report = [System.Collections.Generic.List[object]]::new()',
          '    $jobs = [System.Collections.Generic.List[object]]::new()',
          '',
          '    foreach ($server in $Instance) {',
          '        Write-Log "$server"',
          '        try {',
          ...(checks === 'all' || checks === 'backups' || checks === 'space'
            ? [
                '            $query = @"',
                'SELECT',
                '    d.name                              AS DatabaseName,',
                '    d.state_desc                        AS State,',
                '    d.recovery_model_desc               AS RecoveryModel,',
                "    CAST(SUM(CASE WHEN f.type = 0 THEN f.size END) * 8.0 / 1024 AS DECIMAL(18,1)) AS DataMB,",
                "    CAST(SUM(CASE WHEN f.type = 1 THEN f.size END) * 8.0 / 1024 AS DECIMAL(18,1)) AS LogMB,",
                "    (SELECT MAX(backup_finish_date) FROM msdb.dbo.backupset b WHERE b.database_name = d.name AND b.type = 'D') AS LastFull,",
                "    (SELECT MAX(backup_finish_date) FROM msdb.dbo.backupset b WHERE b.database_name = d.name AND b.type = 'I') AS LastDiff,",
                "    (SELECT MAX(backup_finish_date) FROM msdb.dbo.backupset b WHERE b.database_name = d.name AND b.type = 'L') AS LastLog",
                'FROM sys.databases d',
                'JOIN sys.master_files f ON f.database_id = d.database_id',
                "WHERE d.name NOT IN ('tempdb')",
                'GROUP BY d.name, d.state_desc, d.recovery_model_desc',
                '"@',
                '            $databases = Invoke-Sqlcmd -ServerInstance $server -Query $query @connection -ErrorAction Stop',
                '',
                '            foreach ($database in $databases) {',
                '                $fullAge = if ($database.LastFull -is [datetime]) { [math]::Round(((Get-Date) - $database.LastFull).TotalHours, 1) } else { $null }',
                '                $logAge = if ($database.LastLog -is [datetime]) { [math]::Round(((Get-Date) - $database.LastLog).TotalMinutes, 1) } else { $null }',
                '',
                '                # The finding that matters most: full recovery with no log',
                '                # backups grows without limit and cannot restore to a point',
                '                # in time either. Both halves are bad.',
                "                $mismatch = $database.RecoveryModel -eq 'FULL' -and ($null -eq $database.LastLog -or $logAge -gt 1440)",
                '',
                '                $report.Add([pscustomobject]@{',
                '                    Instance       = $server',
                '                    Database       = $database.DatabaseName',
                '                    State          = $database.State',
                '                    RecoveryModel  = $database.RecoveryModel',
                '                    DataMB         = $database.DataMB',
                '                    LogMB          = $database.LogMB',
                '                    LastFull       = $database.LastFull',
                '                    FullAgeHours   = $fullAge',
                '                    LastLog        = $database.LastLog',
                '                    LogAgeMinutes  = $logAge',
                `                    BackupOverdue  = ($null -eq $fullAge) -or ($fullAge -gt ${num(values, 'full_backup_hours', 26)})`,
                '                    RecoveryMismatch = $mismatch',
                '                })',
                '',
                '                if ($mismatch) {',
                '                    Write-Log "  $($database.DatabaseName): FULL recovery, log never backed up. The log will grow until the disk fills." -Level WARN',
                '                }',
                `                if (($null -eq $fullAge) -or ($fullAge -gt ${num(values, 'full_backup_hours', 26)})) {`,
                '                    Write-Log "  $($database.DatabaseName): no full backup for $fullAge hours" -Level WARN',
                '                }',
                '            }',
                '',
              ]
            : []),
          ...(checks === 'all'
            ? [
                '            # --- agent jobs ------------------------------------------------',
                '            $jobQuery = @"',
                'SELECT TOP 50',
                '    j.name                              AS JobName,',
                '    j.enabled                           AS Enabled,',
                "    msdb.dbo.agent_datetime(h.run_date, h.run_time) AS LastRun,",
                "    CASE h.run_status WHEN 0 THEN 'Failed' WHEN 1 THEN 'Succeeded' WHEN 2 THEN 'Retry' WHEN 3 THEN 'Cancelled' ELSE 'Unknown' END AS Status,",
                '    h.message                           AS Message',
                'FROM msdb.dbo.sysjobs j',
                'LEFT JOIN msdb.dbo.sysjobhistory h ON h.job_id = j.job_id AND h.step_id = 0',
                'WHERE h.instance_id IN (SELECT MAX(instance_id) FROM msdb.dbo.sysjobhistory WHERE step_id = 0 GROUP BY job_id)',
                'ORDER BY h.run_date DESC, h.run_time DESC',
                '"@',
                '            foreach ($job in Invoke-Sqlcmd -ServerInstance $server -Query $jobQuery @connection -ErrorAction Stop) {',
                '                $jobs.Add([pscustomobject]@{',
                '                    Instance = $server',
                '                    Job      = $job.JobName',
                '                    Enabled  = $job.Enabled',
                '                    LastRun  = $job.LastRun',
                '                    Status   = $job.Status',
                '                    Message  = $job.Message',
                '                })',
                "                if ($job.Status -eq 'Failed') { Write-Log \"  Job failed: $($job.JobName)\" -Level WARN }",
                '            }',
                '',
                '            # --- long-running queries ---------------------------------------',
                '            $running = @"',
                'SELECT',
                '    r.session_id, r.status, r.command,',
                '    DATEDIFF(SECOND, r.start_time, GETDATE()) AS ElapsedSeconds,',
                '    r.blocking_session_id, r.wait_type,',
                '    DB_NAME(r.database_id) AS DatabaseName,',
                '    SUBSTRING(t.text, 1, 200) AS QueryText',
                'FROM sys.dm_exec_requests r',
                'CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) t',
                'WHERE r.session_id > 50 AND DATEDIFF(SECOND, r.start_time, GETDATE()) > 300',
                'ORDER BY ElapsedSeconds DESC',
                '"@',
                '            foreach ($query in Invoke-Sqlcmd -ServerInstance $server -Query $running @connection -ErrorAction SilentlyContinue) {',
                '                Write-Log "  Running for $($query.ElapsedSeconds)s on $($query.DatabaseName): $($query.QueryText)" -Level WARN',
                '                if ($query.blocking_session_id -gt 0) {',
                '                    Write-Log "    blocked by session $($query.blocking_session_id), waiting on $($query.wait_type)" -Level WARN',
                '                }',
                '            }',
                '',
              ]
            : []),
          '        } catch {',
          '            Write-Log "Could not query ${server}: $($_.Exception.Message)" -Level ERROR',
          "            $report.Add([pscustomobject]@{ Instance = $server; Database = '-'; State = 'Unreachable' })",
          '        }',
          '    }',
          '',
          '    if (-not (Test-Path $OutputPath)) { New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null }',
          "    $stamp = (Get-Date).ToString('yyyyMMdd')",
          '    $report | Export-Csv -Path (Join-Path $OutputPath "sql-databases-$stamp.csv") -NoTypeInformation',
          ...(checks === 'all' ? ['    $jobs | Export-Csv -Path (Join-Path $OutputPath "sql-jobs-$stamp.csv") -NoTypeInformation'] : []),
          '',
          '    Write-Log "$($report.Count) databases across $($Instance.Count) instances"',
          '    Write-Log "  $(@($report | Where-Object BackupOverdue).Count) have an overdue full backup" -Level WARN',
          '    Write-Log "  $(@($report | Where-Object RecoveryMismatch).Count) are in FULL recovery with no log backups" -Level WARN',
          ...(checks === 'all' ? ["    Write-Log \"  $(@($jobs | Where-Object Status -eq 'Failed').Count) agent jobs failed on their last run\" -Level WARN"] : []),
          '    $report',
          '}',
          'catch {',
          '    Write-Log $_.Exception.Message -Level ERROR',
          '    throw',
          '}',
        ],
        findings,
      };
    },
  }),

  scriptBlueprint({
    id: 'ps_module_scaffold',
    platform: PLATFORM,
    label: 'Module scaffold',
    group: 'Scaffolding',
    description: 'The whole thing rather than another loose script: a module with a manifest, public and private functions, tests, a build script and the folder layout that makes all of it work.',
    inputs: [
      { id: 'module_name', label: 'Module name', control: 'text', default: 'Example.Operations' },
      { id: 'description', label: 'Description', control: 'text', default: 'Operational tooling for the platform team' },
      { id: 'author', label: 'Author', control: 'text', default: 'Platform Team' },
      { id: 'functions', label: 'Public functions', control: 'text', default: 'Get-ServiceHealth, Restart-Application, Get-DeploymentStatus' },
      { id: 'required_modules', label: 'Required modules', control: 'text', default: '', hint: 'Modules this one depends on' },
      { id: 'compatible', label: 'Compatible with', control: 'select', default: 'both', options: [
        { value: 'both', label: 'Windows PowerShell 5.1 and PowerShell 7' },
        { value: 'core', label: 'PowerShell 7 only' },
      ] },
      { id: 'include_build', label: 'Include a build script', control: 'toggle', default: true },
      { id: 'include_ci', label: 'Include a CI workflow', control: 'toggle', default: true },
    ],
    script: (values                 )         => {
      const module = str(values, 'module_name', 'Example.Module').replace(/[^A-Za-z0-9.]/g, '');
      const functions = listOf(str(values, 'functions', '')).map((f) => f.replace(/[^A-Za-z-]/g, ''));
      const required = listOf(str(values, 'required_modules', ''));
      const both = str(values, 'compatible', 'both') === 'both';
      const findings            = [];

      if (functions.length === 0) findings.push(error('scripts.ps.no-functions', 'A module with no public functions exports nothing.', { source: 'ArchToolKit' }));
      for (const fn of functions) {
        if (!/^[A-Z][a-z]+-[A-Z]/.test(fn)) {
          findings.push(warning('scripts.ps.function-naming', `"${fn}" is not Verb-Noun. \`Get-Verb\` lists the approved verbs, and a module that uses an unapproved one warns on every import.`, { source: 'ArchToolKit' }));
        }
      }
      if (both) {
        findings.push(
          warning('scripts.ps.compatibility-claim', 'Claiming compatibility with both editions means testing on both. A ternary, a null-coalescing operator or `ForEach-Object -Parallel` will parse on 7 and fail on 5.1 — and it fails at import, not at the line.', {
            remediation: 'Run the Pester tests on both editions in CI, which is what the generated workflow does.',
            source: 'ArchToolKit',
          }),
        );
      }

      return {
        platform: PLATFORM,
        title: `${module} — a module, with a manifest, tests and a build`,
        effect: 'idempotent',
        requires: [
          { what: 'PowerShell 5.1 or later' },
          { what: 'Pester, for the tests', how: 'Install-Module Pester -Scope CurrentUser -Force' },
          { what: 'PSScriptAnalyzer, for the linting', how: 'Install-Module PSScriptAnalyzer -Scope CurrentUser' },
        ],
        parameters: [
          { name: '-Path', description: 'Where to create the module folder.', required: false },
          { name: '-WhatIf', description: 'List what would be created and create nothing.', required: false },
        ],
        notes: [
          'The layout is the conventional one: Public for exported functions, Private for the rest, and a .psm1 that dot-sources both and exports only Public. That separation is what lets a helper stay a helper.',
          'The manifest lists FunctionsToExport explicitly rather than using a wildcard. A wildcard makes `Import-Module` scan every file on every import, which is slow and gets slower as the module grows.',
          'One function per file, named after the function. It is how everyone expects to find things, and it makes a diff readable.',
          ...(both ? ['CompatiblePSEdition is declared as both, so PowerShell will refuse to import it where it will not work rather than failing halfway through.'] : []),
        ],
        usage: [
          `pwsh -File .\\New-${module.replace(/\./g, '')}Module.ps1 -WhatIf`,
          `pwsh -File .\\New-${module.replace(/\./g, '')}Module.ps1`,
          `Import-Module .\\${module}\\${module}.psd1 -Force -Verbose`,
          `Invoke-Pester .\\${module}\\Tests`,
        ],
        undo: [`Remove-Item -Path .\\${module} -Recurse -Force`, 'Nothing outside the module folder is touched.'],
        body: [
          ...preamble([`[string]$Path = '.'`, `[string]$ModuleName = ${quoted(module)}`], true),
          ...logging(),
          `$functions = @(${functions.map((f) => quoted(f)).join(', ')})`,
          '',
          'try {',
          '    $root = Join-Path $Path $ModuleName',
          '    if (Test-Path $root) { throw "$root exists already. Remove it, or choose another path." }',
          '',
          "    foreach ($folder in @('Public', 'Private', 'Tests')) {",
          '        $target = Join-Path $root $folder',
          '        if ($PSCmdlet.ShouldProcess($target, \'Create the folder\')) {',
          '            New-Item -Path $target -ItemType Directory -Force | Out-Null',
          '        }',
          '    }',
          '',
          '    # --- the root module ---------------------------------------------------',
          '    # Dot-source everything, export only Public. That separation is what',
          '    # lets a helper stay a helper.',
          '    $psm1 = @\'',
          '$public  = @(Get-ChildItem -Path "$PSScriptRoot/Public/*.ps1"  -ErrorAction SilentlyContinue)',
          '$private = @(Get-ChildItem -Path "$PSScriptRoot/Private/*.ps1" -ErrorAction SilentlyContinue)',
          '',
          'foreach ($file in @($public + $private)) {',
          '    try {',
          '        . $file.FullName',
          '    } catch {',
          '        throw "Failed to import $($file.FullName): $_"',
          '    }',
          '}',
          '',
          'Export-ModuleMember -Function $public.BaseName',
          "'@",
          '    if ($PSCmdlet.ShouldProcess("$ModuleName.psm1", \'Write the root module\')) {',
          '        Set-Content -Path (Join-Path $root "$ModuleName.psm1") -Value $psm1 -Encoding utf8',
          '    }',
          '',
          '    # --- the manifest ------------------------------------------------------',
          '    # FunctionsToExport is listed explicitly. A wildcard makes every import',
          '    # scan every file, which gets slower as the module grows.',
          '    $manifest = @{',
          '        Path              = Join-Path $root "$ModuleName.psd1"',
          '        RootModule        = "$ModuleName.psm1"',
          "        ModuleVersion     = '0.1.0'",
          `        Author            = ${quoted(str(values, 'author', ''))}`,
          `        Description       = ${quoted(str(values, 'description', ''))}`,
          `        PowerShellVersion = '${both ? '5.1' : '7.0'}'`,
          `        CompatiblePSEditions = @(${both ? "'Desktop', 'Core'" : "'Core'"})`,
          '        FunctionsToExport = $functions',
          '        CmdletsToExport   = @()',
          '        VariablesToExport = @()',
          '        AliasesToExport   = @()',
          ...(required.length > 0 ? [`        RequiredModules   = @(${required.map((r) => quoted(r)).join(', ')})`] : []),
          "        Tags              = @('operations', 'automation')",
          '    }',
          "    if ($PSCmdlet.ShouldProcess(\"$ModuleName.psd1\", 'Write the manifest')) {",
          '        New-ModuleManifest @manifest',
          '    }',
          '',
          '    # --- one file per function ---------------------------------------------',
          '    foreach ($function in $functions) {',
          "        $verb, $noun = $function -split '-', 2",
          '        $body = @"',
          'function $function {',
          '    <#',
          '    .SYNOPSIS',
          '        One line saying what $function does.',
          '',
          '    .DESCRIPTION',
          '        What it is for, what it assumes, and anything surprising.',
          '',
          '    .EXAMPLE',
          "        $function -Name 'example'",
          '    #>',
          "    [CmdletBinding($(if ($verb -in @('Set','New','Remove','Restart','Stop','Start')) { 'SupportsShouldProcess' } else { '' }))]",
          '    [OutputType([pscustomobject])]',
          '    param(',
          '        [Parameter(Mandatory, ValueFromPipeline, ValueFromPipelineByPropertyName)]',
          '        [ValidateNotNullOrEmpty()]',
          '        [string[]]`$Name',
          '    )',
          '',
          '    begin {',
          '        Set-StrictMode -Version Latest',
          '        Write-Verbose "Starting `$(`$MyInvocation.MyCommand.Name)"',
          '    }',
          '',
          '    process {',
          '        foreach (`$item in `$Name) {',
          '            # The work goes here.',
          '            [pscustomobject]@{',
          '                Name      = `$item',
          "                Status    = 'OK'",
          '                Timestamp = Get-Date',
          '            }',
          '        }',
          '    }',
          '',
          '    end { }',
          '}',
          '"@',
          '        $file = Join-Path $root "Public/$function.ps1"',
          "        if ($PSCmdlet.ShouldProcess($file, 'Write the function')) {",
          '            Set-Content -Path $file -Value $body -Encoding utf8',
          '        }',
          '',
          '        # --- and its test --------------------------------------------------',
          '        $test = @"',
          "Describe '$function' {",
          '    BeforeAll {',
          '        Import-Module "`$PSScriptRoot/../$ModuleName.psd1" -Force',
          '    }',
          '',
          "    It 'is exported by the module' {",
          "        Get-Command $function -Module $ModuleName | Should -Not -BeNullOrEmpty",
          '    }',
          '',
          "    It 'has comment-based help' {",
          '        (Get-Help $function).Synopsis | Should -Not -BeNullOrEmpty',
          '    }',
          '',
          "    It 'returns one object per input' {",
          "        `$result = $function -Name 'a', 'b'",
          '        `$result.Count | Should -Be 2',
          '    }',
          '',
          "    It 'rejects an empty name' {",
          "        { $function -Name '' } | Should -Throw",
          '    }',
          '}',
          '"@',
          '        $testFile = Join-Path $root "Tests/$function.Tests.ps1"',
          "        if ($PSCmdlet.ShouldProcess($testFile, 'Write the test')) {",
          '            Set-Content -Path $testFile -Value $test -Encoding utf8',
          '        }',
          '    }',
          '',
          ...(bool(values, 'include_build', true)
            ? [
                '    # --- build script ------------------------------------------------------',
                '    $build = @"',
                '[CmdletBinding()]',
                'param(',
                "    [ValidateSet('Test', 'Lint', 'All')]",
                "    [string]`$Task = 'All'",
                ')',
                '',
                "`$ErrorActionPreference = 'Stop'",
                "`$moduleRoot = `$PSScriptRoot",
                '',
                "if (`$Task -in 'Lint', 'All') {",
                "    Write-Host 'Linting...' -ForegroundColor Cyan",
                "    `$issues = Invoke-ScriptAnalyzer -Path `$moduleRoot -Recurse -Severity Warning, Error",
                '    if (`$issues) {',
                '        `$issues | Format-Table -AutoSize',
                '        throw "`$(`$issues.Count) analyser findings"',
                '    }',
                "    Write-Host '  clean' -ForegroundColor Green",
                '}',
                '',
                "if (`$Task -in 'Test', 'All') {",
                "    Write-Host 'Testing...' -ForegroundColor Cyan",
                '    `$config = New-PesterConfiguration',
                '    `$config.Run.Path = "`$moduleRoot/Tests"',
                "    `$config.Output.Verbosity = 'Detailed'",
                '    `$config.CodeCoverage.Enabled = `$true',
                '    `$config.CodeCoverage.Path = @("`$moduleRoot/Public", "`$moduleRoot/Private")',
                '    Invoke-Pester -Configuration `$config',
                '}',
                '"@',
                "    if ($PSCmdlet.ShouldProcess('build.ps1', 'Write the build script')) {",
                '        Set-Content -Path (Join-Path $root \'build.ps1\') -Value $build -Encoding utf8',
                '    }',
                '',
              ]
            : []),
          ...(bool(values, 'include_ci', true)
            ? [
                '    # --- CI ---------------------------------------------------------------',
                `    ${'$'}ci = @"`,
                'name: module',
                '',
                'on: [push, pull_request]',
                '',
                'jobs:',
                '  test:',
                '    strategy:',
                '      matrix:',
                `        os: [${both ? 'windows-latest, ubuntu-latest' : 'ubuntu-latest'}]`,
                '    runs-on: `${{ matrix.os }}',
                '    steps:',
                '      - uses: actions/checkout@v4',
                '      - name: Install dependencies',
                '        shell: pwsh',
                '        run: |',
                '          Install-Module Pester, PSScriptAnalyzer -Force -Scope CurrentUser',
                '      - name: Build',
                '        shell: pwsh',
                '        run: ./$ModuleName/build.ps1 -Task All',
                '"@',
                "    if ($PSCmdlet.ShouldProcess('.github/workflows/module.yml', 'Write the workflow')) {",
                "        New-Item -Path (Join-Path $Path '.github/workflows') -ItemType Directory -Force | Out-Null",
                "        Set-Content -Path (Join-Path $Path '.github/workflows/module.yml') -Value $ci -Encoding utf8",
                '    }',
                '',
              ]
            : []),
          '    Write-Log "Created $ModuleName with $($functions.Count) function(s)"',
          '    Write-Log "Next: Import-Module ./$ModuleName/$ModuleName.psd1 -Force"',
          ...(bool(values, 'include_build', true) ? ['    Write-Log "Then:  ./$ModuleName/build.ps1"'] : []),
          '',
          '    [pscustomobject]@{',
          '        Module    = $ModuleName',
          '        Path      = $root',
          '        Functions = $functions',
          '    }',
          '}',
          'catch {',
          '    Write-Log $_.Exception.Message -Level ERROR',
          '    throw',
          '}',
        ],
        findings,
      };
    },
  }),
];
