/**
 * Python: the rest of it.
 *
 * Talking to network devices, producing a spreadsheet somebody will actually
 * open, reading from a database without loading it all into memory, a job that
 * has to run on a schedule and not run twice, validating configuration before
 * it is deployed, comparing two exports, and checking a few hundred endpoints
 * at once.
 *
 * Standard library wherever it is possible. Where it is not — openpyxl for a
 * formatted workbook, a database driver — the requirement is stated with the
 * command that installs it, and nothing else is assumed.
 */

import { bool, num, str,                      } from '../../kit/blueprint.js';
import { error, warning,              } from '../../core/findings.js';
import { scriptBlueprint,                      } from '../from-script.js';
import { identifier, listOf, pyString, snake,             } from '../script.js';

const PLATFORM = 'python'         ;

function preamble(imports                   , docstring                   )           {
  return [
    '"""',
    ...docstring,
    '"""',
    '',
    'from __future__ import annotations',
    '',
    'import argparse',
    'import logging',
    'import sys',
    ...imports,
    '',
    'LOG = logging.getLogger("vcf-automation")',
    '',
    '',
    'def configure_logging(verbose: bool) -> None:',
    '    logging.basicConfig(',
    '        level=logging.DEBUG if verbose else logging.INFO,',
    '        format="%(asctime)s %(levelname)-7s %(message)s",',
    '        datefmt="%Y-%m-%d %H:%M:%S",',
    '        stream=sys.stderr,',
    '    )',
    '',
  ];
}

const ENTRY = [
  '',
  'if __name__ == "__main__":',
  '    try:',
  '        sys.exit(main())',
  '    except KeyboardInterrupt:',
  '        LOG.warning("Interrupted")',
  '        sys.exit(130)',
];

export const PYTHON_EXTRA                             = [
  scriptBlueprint({
    id: 'py_device_backup',
    platform: PLATFORM,
    label: 'Network device configuration backup',
    group: 'Network',
    description: 'Pull the running configuration from every device, diff it against yesterday, and keep the history — which is the cheapest change detection any network has.',
    inputs: [
      { id: 'script_name', label: 'Script name', control: 'text', default: 'backup-configs' },
      { id: 'inventory', label: 'Inventory', control: 'select', default: 'csv', options: [
        { value: 'csv', label: 'A CSV of host, platform, group' },
        { value: 'yaml', label: 'An Ansible-style inventory' },
      ] },
      { id: 'library', label: 'Connect with', control: 'select', default: 'netmiko', options: [
        { value: 'netmiko', label: 'netmiko — handles the per-vendor differences' },
        { value: 'paramiko', label: 'paramiko — raw SSH, no vendor knowledge' },
      ] },
      { id: 'platforms', label: 'Platforms', control: 'text', default: 'cisco_ios, cisco_nxos, arista_eos, paloalto_panos', hint: 'netmiko device types' },
      { id: 'store', label: 'Keep the history in', control: 'select', default: 'git', options: [
        { value: 'git', label: 'A git repository — diffs and blame for free' },
        { value: 'dated', label: 'Dated folders' },
      ] },
      { id: 'parallel', label: 'Devices at a time', control: 'number', default: 10, min: 1, max: 100 },
      { id: 'scrub', label: 'Remove before storing', control: 'text', default: 'ntp clock-period, ! Last configuration change', hint: 'Lines that change on their own and make every diff noisy' },
      { id: 'alert_on_change', label: 'Report what changed', control: 'toggle', default: true },
    ],
    script: (values                 )         => {
      const name = identifier(str(values, 'script_name', 'backup-configs'), 'backup-configs');
      const module = snake(name, 'backup_configs');
      const netmiko = str(values, 'library', 'netmiko') === 'netmiko';
      const git = str(values, 'store', 'git') === 'git';
      const scrub = listOf(str(values, 'scrub', ''));
      const findings            = [];

      findings.push(
        warning('scripts.py.device-credentials', 'Device credentials come from the environment, never from the inventory file and never from an argument. An inventory with passwords in it ends up in version control, which is exactly where the configuration backups are going.', {
          source: 'ArchToolKit',
        }),
      );
      if (scrub.length === 0) {
        findings.push(
          warning('scripts.py.no-scrubbing', 'Without scrubbing, every backup differs from the last because of a timestamp or an NTP drift line. The diff becomes noise and people stop reading it, which defeats the whole point.', {
            remediation: 'Strip the lines that change on their own before storing.',
            source: 'ArchToolKit',
          }),
        );
      }
      findings.push(
        warning('scripts.py.secrets-in-configs', 'A device configuration contains hashed passwords, SNMP strings and pre-shared keys. The repository holding these backups is as sensitive as the devices, and should be private, access-controlled and probably not on a shared platform.', {
          source: 'ArchToolKit',
        }),
      );

      return {
        platform: PLATFORM,
        title: 'Back up device configurations and report what changed',
        effect: 'idempotent',
        requires: [
          { what: 'Python 3.9 or later' },
          ...(netmiko ? [{ what: 'netmiko', how: 'pip install netmiko' }] : [{ what: 'paramiko', how: 'pip install paramiko' }]),
          ...(git ? [{ what: 'git, and a private repository for the output' }] : []),
          { what: 'NET_USER and NET_PASSWORD in the environment', how: 'export NET_USER=...; read -s NET_PASSWORD; export NET_PASSWORD' },
        ],
        parameters: [
          { name: 'inventory', description: 'The device list.', required: true, example: './devices.csv' },
          { name: '-o, --output', description: 'Where the configurations are kept.', required: false },
          { name: '--dry-run', description: 'Connect and read, but write nothing.', required: false },
        ],
        notes: [
          'Devices are read in parallel with a thread pool. This is I/O waiting on a slow device, not computation, so threads are the right tool and the GIL is irrelevant.',
          'A device that cannot be reached is reported and the run continues. On any real network some device is always unreachable, and stopping for it means never completing a backup.',
          ...(git ? ['Git gives diffs, blame and history for nothing. `git log -p device.cfg` answers "when did this change and to what" in one command, which is the whole reason for doing this.'] : []),
          ...(scrub.length > 0 ? [`Scrubbed before storing: ${scrub.join(', ')}. Without that, every backup differs from the last for no reason and nobody reads the diffs.`] : []),
          'The output holds hashed passwords and SNMP strings. Treat the repository as sensitive as the devices themselves.',
        ],
        usage: [
          'export NET_USER=svc-backup',
          'read -s NET_PASSWORD && export NET_PASSWORD',
          `python3 ${module}.py devices.csv --dry-run`,
          `python3 ${module}.py devices.csv -o /srv/network-configs`,
        ],
        undo: [
          ...(git ? ['Every version is in git: `git checkout <commit> -- <device>.cfg` restores one.'] : ['The dated folders are the history.']),
          'Nothing on a device is changed. This only reads.',
        ],
        body: [
          ...preamble(
            [
              'import csv',
              'import difflib',
              'import os',
              'import subprocess',
              'from concurrent.futures import ThreadPoolExecutor, as_completed',
              'from datetime import datetime',
              'from pathlib import Path',
              'from typing import Any',
              '',
              ...(netmiko ? ['from netmiko import ConnectHandler', 'from netmiko.exceptions import NetmikoAuthenticationException, NetmikoTimeoutException'] : ['import paramiko']),
            ],
            ['Back up device configurations and report what changed.', '', 'Credentials come from the environment. Nothing is written to a device.', '', ''],
          ),
          '',
          `SCRUB = [${scrub.map((sc) => pyString(sc)).join(', ')}]`,
          'COMMANDS = {',
          '    "cisco_ios": "show running-config",',
          '    "cisco_nxos": "show running-config",',
          '    "cisco_xr": "show running-config",',
          '    "arista_eos": "show running-config",',
          '    "juniper_junos": "show configuration | display set",',
          '    "paloalto_panos": "show config running",',
          '    "fortinet": "show full-configuration",',
          '}',
          'DEFAULT_COMMAND = "show running-config"',
          '',
          '',
          'def credentials() -> tuple[str, str]:',
          '    """From the environment, never from the inventory or an argument."""',
          '    user = os.environ.get("NET_USER")',
          '    password = os.environ.get("NET_PASSWORD")',
          '    if not user or not password:',
          '        raise RuntimeError("Set NET_USER and NET_PASSWORD before running this")',
          '    return user, password',
          '',
          '',
          'def read_inventory(path: Path) -> list[dict[str, str]]:',
          '    devices: list[dict[str, str]] = []',
          ...(str(values, 'inventory', 'csv') === 'csv'
            ? [
                '    with path.open(newline="", encoding="utf-8-sig") as handle:',
                '        for row in csv.DictReader(handle):',
                '            host = (row.get("host") or "").strip()',
                '            if not host:',
                '                continue',
                '            devices.append(',
                '                {',
                '                    "host": host,',
                '                    "platform": (row.get("platform") or "cisco_ios").strip(),',
                '                    "group": (row.get("group") or "default").strip(),',
                '                }',
                '            )',
              ]
            : [
                '    # A minimal INI-style inventory reader: [group] then one host per line.',
                '    group = "default"',
                '    for line in path.read_text(encoding="utf-8").splitlines():',
                '        line = line.strip()',
                '        if not line or line.startswith("#"):',
                '            continue',
                '        if line.startswith("[") and line.endswith("]"):',
                '            group = line[1:-1].split(":")[0]',
                '            continue',
                '        parts = line.split()',
                '        variables = dict(p.split("=", 1) for p in parts[1:] if "=" in p)',
                '        devices.append(',
                '            {',
                '                "host": parts[0],',
                '                "platform": variables.get("ansible_network_os", "cisco_ios"),',
                '                "group": group,',
                '            }',
                '        )',
              ]),
          '    LOG.info("%d devices in %s", len(devices), path)',
          '    return devices',
          '',
          '',
          'def scrub(config: str) -> str:',
          '    """Strip the lines that change on their own.',
          '',
          '    Without this every backup differs from the last because of a timestamp',
          '    or an NTP drift value, the diff becomes noise, and people stop reading',
          '    it — which defeats the point of taking backups at all.',
          '    """',
          '    if not SCRUB:',
          '        return config',
          '    kept = [line for line in config.splitlines() if not any(pattern in line for pattern in SCRUB)]',
          '    return "\\n".join(kept) + "\\n"',
          '',
          '',
          'def fetch(device: dict[str, str], user: str, password: str) -> dict[str, Any]:',
          '    """One device. Never raises — a failure is a result, not an exception."""',
          '    host = device["host"]',
          '    platform = device["platform"]',
          '    command = COMMANDS.get(platform, DEFAULT_COMMAND)',
          '',
          ...(netmiko
            ? [
                '    try:',
                '        with ConnectHandler(',
                '            device_type=platform,',
                '            host=host,',
                '            username=user,',
                '            password=password,',
                '            conn_timeout=20,',
                '            fast_cli=False,',
                '        ) as connection:',
                '            connection.enable()',
                '            output = connection.send_command(command, read_timeout=120)',
                '        return {"host": host, "group": device["group"], "status": "ok", "config": scrub(output)}',
                '    except NetmikoAuthenticationException:',
                '        return {"host": host, "group": device["group"], "status": "auth-failed", "config": ""}',
                '    except NetmikoTimeoutException:',
                '        return {"host": host, "group": device["group"], "status": "unreachable", "config": ""}',
                '    except Exception as exc:  # noqa: BLE001 — one device must not stop the run',
                '        return {"host": host, "group": device["group"], "status": f"failed: {exc}", "config": ""}',
              ]
            : [
                '    client = paramiko.SSHClient()',
                '    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())',
                '    try:',
                '        client.connect(host, username=user, password=password, timeout=20, look_for_keys=False)',
                '        _stdin, stdout, _stderr = client.exec_command(command, timeout=120)',
                '        output = stdout.read().decode("utf-8", "replace")',
                '        return {"host": host, "group": device["group"], "status": "ok", "config": scrub(output)}',
                '    except paramiko.AuthenticationException:',
                '        return {"host": host, "group": device["group"], "status": "auth-failed", "config": ""}',
                '    except Exception as exc:  # noqa: BLE001',
                '        return {"host": host, "group": device["group"], "status": f"failed: {exc}", "config": ""}',
                '    finally:',
                '        client.close()',
              ]),
          '',
          '',
          'def store(result: dict[str, Any], root: Path, dry_run: bool) -> str | None:',
          '    """Write it, and return a diff against the previous version."""',
          ...(git
            ? ['    target = root / result["group"] / f"{result[\'host\']}.cfg"']
            : ['    target = root / datetime.now().strftime("%Y-%m-%d") / result["group"] / f"{result[\'host\']}.cfg"']),
          '',
          '    previous = target.read_text(encoding="utf-8") if target.exists() else ""',
          '    current = result["config"]',
          '',
          '    if previous == current:',
          '        LOG.debug("%s unchanged", result["host"])',
          '        return None',
          '',
          '    diff = "\\n".join(',
          '        difflib.unified_diff(',
          '            previous.splitlines(),',
          '            current.splitlines(),',
          '            fromfile=f"{result[\'host\']} (previous)",',
          '            tofile=f"{result[\'host\']} (now)",',
          '            lineterm="",',
          '            n=2,',
          '        )',
          '    )',
          '',
          '    if dry_run:',
          '        LOG.info("Dry run: would write %s", target)',
          '        return diff',
          '',
          '    target.parent.mkdir(parents=True, exist_ok=True)',
          '    target.write_text(current, encoding="utf-8")',
          '    return diff',
          '',
          '',
          'def main(argv: list[str] | None = None) -> int:',
          '    parser = argparse.ArgumentParser(',
          '        description="Back up device configurations and report what changed",',
          '        formatter_class=argparse.ArgumentDefaultsHelpFormatter,',
          '    )',
          '    parser.add_argument("inventory", type=Path, help="the device list")',
          '    parser.add_argument("-o", "--output", type=Path, default=Path("./configs"))',
          `    parser.add_argument("--workers", type=int, default=${num(values, 'parallel', 10)})`,
          '    parser.add_argument("--dry-run", action="store_true", help="connect and read, write nothing")',
          '    parser.add_argument("--verbose", action="store_true")',
          '    args = parser.parse_args(argv)',
          '    configure_logging(args.verbose)',
          '',
          '    try:',
          '        user, password = credentials()',
          '        devices = read_inventory(args.inventory)',
          '    except (OSError, RuntimeError, ValueError) as exc:',
          '        LOG.error("%s", exc)',
          '        return 2',
          '',
          '    if not devices:',
          '        LOG.error("No devices to back up")',
          '        return 1',
          '',
          '    results: list[dict[str, Any]] = []',
          '    changes: dict[str, str] = {}',
          '',
          '    # Threads, not processes: this is waiting on slow devices, so the GIL',
          '    # is irrelevant and a thread is far cheaper.',
          '    with ThreadPoolExecutor(max_workers=args.workers) as pool:',
          '        futures = {pool.submit(fetch, device, user, password): device for device in devices}',
          '        for future in as_completed(futures):',
          '            result = future.result()',
          '            results.append(result)',
          '            if result["status"] != "ok":',
          '                LOG.warning("%s: %s", result["host"], result["status"])',
          '                continue',
          '            LOG.info("%s: %d lines", result["host"], len(result["config"].splitlines()))',
          '            diff = store(result, args.output, args.dry_run)',
          '            if diff:',
          '                changes[result["host"]] = diff',
          '',
          '    ok = sum(1 for r in results if r["status"] == "ok")',
          '    LOG.info("%d of %d devices backed up", ok, len(results))',
          '    for result in results:',
          '        if result["status"] != "ok":',
          '            LOG.warning("  %s: %s", result["host"], result["status"])',
          '',
          ...(bool(values, 'alert_on_change', true)
            ? [
                '    if changes:',
                '        LOG.warning("%d device(s) changed since the last backup", len(changes))',
                '        for host, diff in changes.items():',
                '            print(f"\\n=== {host} ===")',
                '            print(diff)',
                '    else:',
                '        LOG.info("Nothing changed")',
                '',
              ]
            : []),
          ...(git
            ? [
                '    if changes and not args.dry_run:',
                '        # Git gives diffs, blame and history for nothing.',
                '        try:',
                '            subprocess.run(["git", "-C", str(args.output), "add", "-A"], check=True, capture_output=True)',
                '            message = f"Configuration backup {datetime.now():%Y-%m-%d %H:%M} — {len(changes)} changed"',
                '            subprocess.run(',
                '                ["git", "-C", str(args.output), "commit", "-m", message],',
                '                check=True,',
                '                capture_output=True,',
                '            )',
                '            LOG.info("Committed: %s", message)',
                '        except subprocess.CalledProcessError as exc:',
                '            LOG.warning("git failed: %s", exc.stderr.decode("utf-8", "replace")[:200])',
                '        except FileNotFoundError:',
                '            LOG.warning("git is not installed — the configurations were written but not committed")',
                '',
              ]
            : []),
          '    failed = [r for r in results if r["status"] != "ok"]',
          '    return 1 if failed else 0',
          ...ENTRY,
        ],
        findings,
      };
    },
  }),

  scriptBlueprint({
    id: 'py_excel_report',
    platform: PLATFORM,
    label: 'Formatted Excel report',
    group: 'Reporting',
    description: 'A workbook somebody will actually open: frozen headers, autofilters, conditional formatting on the numbers that matter, column widths that fit, and a summary sheet.',
    inputs: [
      { id: 'script_name', label: 'Script name', control: 'text', default: 'build-report' },
      { id: 'source', label: 'Data from', control: 'select', default: 'csv', options: [
        { value: 'csv', label: 'A CSV' },
        { value: 'json', label: 'JSON' },
        { value: 'multiple', label: 'Several CSVs, one sheet each' },
      ] },
      { id: 'sheet_name', label: 'Sheet name', control: 'text', default: 'Data' },
      { id: 'highlight_column', label: 'Colour scale on', control: 'text', default: 'PercentUsed', hint: 'A numeric column — empty for none' },
      { id: 'threshold_rules', label: 'Highlight rows where', control: 'textarea', default: 'PercentUsed > 90 | red\nPercentUsed > 75 | amber', hint: 'column operator value | colour' },
      { id: 'summary_sheet', label: 'Add a summary sheet', control: 'toggle', default: true },
      { id: 'summary_by', label: 'Summarise by', control: 'text', default: 'Environment', showWhen: { input: 'summary_sheet', equals: ['true'] } },
      { id: 'chart', label: 'Add a chart', control: 'toggle', default: true, showWhen: { input: 'summary_sheet', equals: ['true'] } },
      { id: 'freeze_header', label: 'Freeze the header row', control: 'toggle', default: true },
    ],
    script: (values                 )         => {
      const name = identifier(str(values, 'script_name', 'build-report'), 'build-report');
      const module = snake(name, 'build_report');
      const rules = str(values, 'threshold_rules', '')
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .map((line) => {
          const [condition, colour] = line.split('|').map((p) => p.trim());
          const parts = (condition ?? '').split(/\s+/);
          return { column: parts[0] ?? '', operator: parts[1] ?? '>', value: parts[2] ?? '0', colour: (colour ?? 'red').toLowerCase() };
        })
        .filter((r) => r.column);
      const summary = bool(values, 'summary_sheet', true);
      const findings            = [];

      findings.push(
        warning('scripts.py.excel-not-a-database', 'A spreadsheet is a report, not a data store. Anything the next script has to read should be written as CSV or JSON as well — a formatted workbook is for people, and parsing one back is painful.', {
          source: 'ArchToolKit',
        }),
      );
      if (rules.length === 0 && !str(values, 'highlight_column', '')) {
        findings.push(
          warning('scripts.py.no-highlighting', 'Without conditional formatting this is a CSV with a nicer font. The highlighting is the part that makes a thousand-row report readable at a glance.', {
            source: 'ArchToolKit',
          }),
        );
      }

      return {
        platform: PLATFORM,
        title: 'Build a formatted Excel workbook from data',
        effect: 'idempotent',
        requires: [
          { what: 'Python 3.9 or later' },
          { what: 'openpyxl', how: 'pip install openpyxl' },
        ],
        parameters: [
          { name: 'input', description: 'The data to read.', required: true, example: './data.csv' },
          { name: '-o, --output', description: 'The workbook to write.', required: false, example: 'report.xlsx' },
          { name: '--dry-run', description: 'Report what the workbook would contain and write nothing.', required: false },
        ],
        notes: [
          'Column widths are calculated from the content rather than guessed. A report where half the columns show ##### is one nobody reads.',
          'Numbers are written as numbers, not strings. A column of numbers stored as text will not sort, will not sum, and produces the green triangle everybody ignores.',
          ...(bool(values, 'freeze_header', true) ? ['The header row is frozen and an autofilter is applied, which is what makes a long report usable.'] : []),
          ...(summary ? ['The summary sheet is first, so the workbook opens on the answer rather than on the data.'] : []),
          'The workbook is written to a temporary name and moved into place, so an interrupted run does not leave a corrupt file that Excel will refuse to open.',
          '--dry-run reads the data and reports the sheets, the row counts and the columns without writing anything, which is how you check the input is the shape you expected.',
        ],
        usage: [`python3 ${module}.py data.csv --dry-run`, `python3 ${module}.py data.csv`, `python3 ${module}.py data.csv -o monthly-report.xlsx`],
        undo: ['The input is untouched. Delete the workbook and run it again.'],
        body: [
          ...preamble(
            [
              'import csv',
              ...(str(values, 'source', 'csv') === 'json' ? ['import json'] : []),
              'from collections import Counter, defaultdict',
              'from datetime import datetime',
              'from pathlib import Path',
              'from typing import Any',
              '',
              'from openpyxl import Workbook',
              'from openpyxl.chart import BarChart, Reference',
              'from openpyxl.formatting.rule import CellIsRule, ColorScaleRule',
              'from openpyxl.styles import Alignment, Font, PatternFill',
              'from openpyxl.utils import get_column_letter',
            ],
            ['Build a formatted Excel workbook from data.', '', 'A spreadsheet is a report, not a data store.', '', ''],
          ),
          '',
          'HEADER_FILL = PatternFill("solid", fgColor="1F4E78")',
          'HEADER_FONT = Font(color="FFFFFF", bold=True)',
          'FILLS = {',
          '    "red": PatternFill("solid", fgColor="FFC7CE"),',
          '    "amber": PatternFill("solid", fgColor="FFEB9C"),',
          '    "green": PatternFill("solid", fgColor="C6EFCE"),',
          '}',
          '',
          '',
          'def read_rows(path: Path) -> list[dict[str, Any]]:',
          ...(str(values, 'source', 'json') === 'json'
            ? [
                '    data = json.loads(path.read_text(encoding="utf-8"))',
                '    rows = data if isinstance(data, list) else data.get("data", data.get("items", []))',
              ]
            : [
                '    with path.open(newline="", encoding="utf-8-sig") as handle:',
                '        rows = [dict(row) for row in csv.DictReader(handle)]',
              ]),
          '    LOG.info("Read %d rows from %s", len(rows), path)',
          '    return rows',
          '',
          '',
          'def as_number(value: Any) -> Any:',
          '    """Write numbers as numbers.',
          '',
          '    A column of numbers stored as text will not sort, will not sum, and',
          '    produces the green triangle everybody ignores.',
          '    """',
          '    if value is None or value == "":',
          '        return None',
          '    text = str(value).strip().replace(",", "")',
          '    try:',
          '        return int(text)',
          '    except ValueError:',
          '        pass',
          '    try:',
          '        return float(text)',
          '    except ValueError:',
          '        return value',
          '',
          '',
          'def write_sheet(book: Workbook, title: str, rows: list[dict[str, Any]]) -> Any:',
          '    sheet = book.create_sheet(title=title[:31])  # Excel caps a sheet name at 31',
          '    if not rows:',
          '        sheet["A1"] = "(no data)"',
          '        return sheet',
          '',
          '    headers = list(rows[0])',
          '    for column, header in enumerate(headers, start=1):',
          '        cell = sheet.cell(row=1, column=column, value=header)',
          '        cell.fill = HEADER_FILL',
          '        cell.font = HEADER_FONT',
          '        cell.alignment = Alignment(horizontal="center", vertical="center")',
          '',
          '    for line, row in enumerate(rows, start=2):',
          '        for column, header in enumerate(headers, start=1):',
          '            sheet.cell(row=line, column=column, value=as_number(row.get(header)))',
          '',
          '    # Widths from the content. A report where half the columns show #####',
          '    # is one nobody reads.',
          '    for column, header in enumerate(headers, start=1):',
          '        longest = max(',
          '            [len(str(header))] + [len(str(row.get(header, ""))) for row in rows[:500]]',
          '        )',
          '        sheet.column_dimensions[get_column_letter(column)].width = min(max(longest + 2, 10), 60)',
          '',
          ...(bool(values, 'freeze_header', true) ? ['    sheet.freeze_panes = "A2"'] : []),
          '    sheet.auto_filter.ref = f"A1:{get_column_letter(len(headers))}{len(rows) + 1}"',
          '',
          ...(rules.length > 0 || str(values, 'highlight_column', '')
            ? [
                '    # The highlighting is what makes a thousand-row report readable.',
                '    def column_for(header_name: str) -> str | None:',
                '        if header_name not in headers:',
                '            return None',
                '        return get_column_letter(headers.index(header_name) + 1)',
                '',
                '    last = len(rows) + 1',
                ...rules.flatMap((rule) => [
                  `    letter = column_for(${pyString(rule.column)})`,
                  '    if letter:',
                  '        sheet.conditional_formatting.add(',
                  '            f"{letter}2:{letter}{last}",',
                  '            CellIsRule(',
                  `                operator=${pyString(rule.operator === '>' ? 'greaterThan' : rule.operator === '<' ? 'lessThan' : 'equal')},`,
                  `                formula=[${pyString(rule.value)}],`,
                  `                fill=FILLS[${pyString(rule.colour)}],`,
                  '            ),',
                  '        )',
                ]),
                ...(str(values, 'highlight_column', '')
                  ? [
                      `    letter = column_for(${pyString(str(values, 'highlight_column', ''))})`,
                      '    if letter:',
                      '        sheet.conditional_formatting.add(',
                      '            f"{letter}2:{letter}{last}",',
                      '            ColorScaleRule(',
                      '                start_type="min", start_color="C6EFCE",',
                      '                mid_type="percentile", mid_value=50, mid_color="FFEB9C",',
                      '                end_type="max", end_color="FFC7CE",',
                      '            ),',
                      '        )',
                    ]
                  : []),
                '',
              ]
            : []),
          '    return sheet',
          '',
          '',
          ...(summary
            ? [
                'def write_summary(book: Workbook, rows: list[dict[str, Any]]) -> None:',
                `    column = ${pyString(str(values, 'summary_by', 'Environment'))}`,
                '    sheet = book.create_sheet(title="Summary", index=0)  # first, so it opens on the answer',
                '',
                '    sheet["A1"] = "Summary"',
                '    sheet["A1"].font = Font(size=14, bold=True)',
                '    sheet["A2"] = f"Generated {datetime.now():%Y-%m-%d %H:%M}"',
                '    sheet["A3"] = f"{len(rows):,} rows"',
                '',
                '    counts = Counter(str(row.get(column, "(unset)")) for row in rows)',
                '    sheet["A5"] = column',
                '    sheet["B5"] = "Count"',
                '    for cell in ("A5", "B5"):',
                '        sheet[cell].fill = HEADER_FILL',
                '        sheet[cell].font = HEADER_FONT',
                '',
                '    for index, (value, count) in enumerate(counts.most_common(), start=6):',
                '        sheet.cell(row=index, column=1, value=value)',
                '        sheet.cell(row=index, column=2, value=count)',
                '',
                '    sheet.column_dimensions["A"].width = 30',
                '    sheet.column_dimensions["B"].width = 12',
                '',
                ...(bool(values, 'chart', true)
                  ? [
                      '    if counts:',
                      '        chart = BarChart()',
                      '        chart.title = f"By {column}"',
                      '        chart.y_axis.title = "Count"',
                      '        data = Reference(sheet, min_col=2, min_row=5, max_row=5 + len(counts))',
                      '        categories = Reference(sheet, min_col=1, min_row=6, max_row=5 + len(counts))',
                      '        chart.add_data(data, titles_from_data=True)',
                      '        chart.set_categories(categories)',
                      '        chart.height = 8',
                      '        chart.width = 16',
                      '        sheet.add_chart(chart, "D5")',
                      '',
                    ]
                  : []),
                '',
              ]
            : []),
          'def main(argv: list[str] | None = None) -> int:',
          '    parser = argparse.ArgumentParser(',
          '        description="Build a formatted Excel workbook",',
          '        formatter_class=argparse.ArgumentDefaultsHelpFormatter,',
          '    )',
          '    parser.add_argument("input", type=Path, nargs="+", help="the data to read")',
          '    parser.add_argument("-o", "--output", type=Path, default=Path("report.xlsx"))',
          '    parser.add_argument("--dry-run", action="store_true", help="report the sheets and write nothing")',
          '    parser.add_argument("--verbose", action="store_true")',
          '    args = parser.parse_args(argv)',
          '    configure_logging(args.verbose)',
          '',
          '    try:',
          '        if args.dry_run:',
          '            # Read the data and say what the workbook would hold, so the',
          '            # input can be checked without producing a file.',
          '            for path in args.input:',
          '                rows = read_rows(path)',
          '                columns = list(rows[0]) if rows else []',
          '                LOG.info("Would write sheet %s: %d rows, columns %s", path.stem, len(rows), ", ".join(columns))',
          '            LOG.info("Dry run: nothing written")',
          '            return 0',
          '',
          '        book = Workbook()',
          '        book.remove(book.active)  # the default sheet, which is never wanted',
          '',
          '        first: list[dict[str, Any]] = []',
          '        for path in args.input:',
          '            rows = read_rows(path)',
          '            if not first:',
          '                first = rows',
          `            title = path.stem if len(args.input) > 1 else ${pyString(str(values, 'sheet_name', 'Data'))}`,
          '            write_sheet(book, title, rows)',
          '',
          ...(summary ? ['        write_summary(book, first)', ''] : []),
          '        # Write to a temporary name and move it into place, so an',
          '        # interrupted run does not leave a file Excel refuses to open.',
          '        temporary = args.output.with_suffix(".tmp.xlsx")',
          '        book.save(temporary)',
          '        temporary.replace(args.output)',
          '        LOG.info("Wrote %s", args.output)',
          '    except (OSError, ValueError, KeyError) as exc:',
          '        LOG.error("%s", exc)',
          '        return 1',
          '',
          '    return 0',
          ...ENTRY,
        ],
        findings,
      };
    },
  }),

  scriptBlueprint({
    id: 'py_scheduled_job',
    platform: PLATFORM,
    label: 'Scheduled job with locking and state',
    group: 'Scaffolding',
    description: 'A job that runs on a timer: a lock so two copies cannot overlap, a state file so it knows where it got to, metrics so somebody can tell it is working, and an exit code.',
    inputs: [
      { id: 'script_name', label: 'Script name', control: 'text', default: 'sync-job' },
      { id: 'summary', label: 'What it does', control: 'text', default: 'Synchronises the inventory from the source of truth' },
      { id: 'lock', label: 'Lock', control: 'select', default: 'file', options: [
        { value: 'file', label: 'A lock file with the pid, checked for staleness' },
        { value: 'socket', label: 'An abstract socket — released by the kernel, Linux only' },
      ] },
      { id: 'state', label: 'Remember between runs', control: 'select', default: 'watermark', options: [
        { value: 'watermark', label: 'A high-water mark, so each run picks up where the last stopped' },
        { value: 'checksum', label: 'A checksum of the last input, to skip unchanged data' },
        { value: 'none', label: 'Nothing — every run is independent' },
      ] },
      { id: 'metrics', label: 'Emit metrics', control: 'select', default: 'file', options: [
        { value: 'file', label: 'A Prometheus textfile, for the node exporter' },
        { value: 'log', label: 'A summary line in the log' },
        { value: 'none', label: 'None' },
      ] },
      { id: 'max_runtime', label: 'Give up after (minutes)', control: 'number', default: 30, min: 1, max: 1440 },
      { id: 'retry', label: 'Retry a failed item', control: 'number', default: 2, min: 0, max: 10 },
    ],
    script: (values                 )         => {
      const name = identifier(str(values, 'script_name', 'sync-job'), 'sync-job');
      const module = snake(name, 'sync_job');
      const socketLock = str(values, 'lock', 'file') === 'socket';
      const state = str(values, 'state', 'watermark');
      const metrics = str(values, 'metrics', 'file');
      const findings            = [];

      if (!socketLock) {
        findings.push(
          warning('scripts.py.stale-lock-file', 'A lock file survives a kill -9, so the next run finds it and refuses to start — for ever, silently. The generated script checks whether the pid in the file is still alive, which handles that; do not remove the check.', {
            source: 'ArchToolKit',
          }),
        );
      }
      if (metrics === 'none') {
        findings.push(
          warning('scripts.py.no-metrics', 'A scheduled job with no metrics fails silently. The most common failure is not an error — it is the job quietly not running at all, and nothing notices for weeks.', {
            remediation: 'Emit at least a last-success timestamp, and alert when it goes stale.',
            source: 'ArchToolKit',
          }),
        );
      }

      return {
        platform: PLATFORM,
        title: `${name} — ${str(values, 'summary', 'a scheduled job')}`,
        effect: 'idempotent',
        requires: [{ what: 'Python 3.9 or later' }, { what: 'Nothing else — standard library only' }],
        parameters: [
          { name: '--dry-run', description: 'Report what would happen and change nothing.', required: false },
          { name: '--force', description: 'Ignore the state and process everything.', required: false },
          { name: '--verbose', description: 'Debug logging.', required: false },
        ],
        notes: [
          socketLock
            ? 'The lock is an abstract socket, which the kernel releases when the process ends however it ends — including kill -9. It is Linux-only and it is the one lock that cannot go stale.'
            : 'The lock file holds the pid. A stale lock from a killed process is detected by checking whether that pid is still alive, which is what stops a crash blocking every future run.',
          ...(state !== 'none'
            ? ['The state file is written only after a successful run. A failed run leaves the previous watermark, so the next attempt covers the same ground rather than skipping it.']
            : []),
          ...(metrics === 'file'
            ? ['Metrics are written to a Prometheus textfile. The number that matters is the last success timestamp: alert when it gets old, and you catch the job not running at all — which is the failure nobody notices.']
            : []),
          `The job kills itself after ${num(values, 'max_runtime', 30)} minutes. A scheduled job with no timeout that hangs simply never runs again, and nothing says so.`,
          'Exit codes: 0 success, 1 a handled failure, 2 bad arguments, 3 already running. Whatever schedules this can act on them.',
        ],
        usage: [
          `python3 ${module}.py --dry-run --verbose`,
          `python3 ${module}.py`,
          `# in cron, with the output going somewhere it will be seen:`,
          `*/15 * * * * /usr/bin/python3 /opt/jobs/${module}.py >> /var/log/${module}.log 2>&1`,
        ],
        undo: ['What there is to undo depends on what goes in process(). Write it here as that is filled in.', '--dry-run changes nothing, so it is always safe.'],
        body: [
          ...preamble(
            [
              'import json',
              'import os',
              ...(socketLock ? ['import socket'] : ['import errno']),
              'import signal',
              'import time',
              'from datetime import datetime, timezone',
              'from pathlib import Path',
              'from typing import Any',
            ],
            [`${name} — ${str(values, 'summary', '')}`, '', 'A lock so two copies cannot overlap, state so it knows where it got to,', 'metrics so somebody can tell it is working.', '', ''],
          ),
          '',
          `JOB_NAME = ${pyString(module)}`,
          'STATE_DIR = Path(os.environ.get("JOB_STATE_DIR", "/var/lib/vcf-automation"))',
          'METRICS_DIR = Path(os.environ.get("JOB_METRICS_DIR", "/var/lib/node_exporter/textfile_collector"))',
          `MAX_RUNTIME = ${num(values, 'max_runtime', 30) * 60}`,
          `RETRIES = ${num(values, 'retry', 2)}`,
          '',
          '',
          ...(socketLock
            ? [
                'def acquire_lock() -> socket.socket | None:',
                '    """An abstract socket. The kernel releases it however the process ends.',
                '',
                '    This is the one lock that cannot go stale: there is no file left',
                '    behind by a kill -9 to confuse the next run.',
                '    """',
                '    lock = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)',
                '    try:',
                '        lock.bind("\\0" + JOB_NAME)  # the leading NUL makes it abstract',
                '        return lock',
                '    except OSError:',
                '        return None',
                '',
                '',
              ]
            : [
                'def acquire_lock() -> Path | None:',
                '    """A lock file with the pid in it.',
                '',
                '    A lock file survives a kill -9, so the next run would find it and',
                '    refuse to start for ever. Checking whether the pid is still alive',
                '    is what makes that recoverable.',
                '    """',
                '    lock_path = STATE_DIR / f"{JOB_NAME}.lock"',
                '    STATE_DIR.mkdir(parents=True, exist_ok=True)',
                '',
                '    if lock_path.exists():',
                '        try:',
                '            pid = int(lock_path.read_text(encoding="utf-8").strip())',
                '        except (ValueError, OSError):',
                '            pid = 0',
                '',
                '        if pid:',
                '            try:',
                '                os.kill(pid, 0)  # signal 0 tests for existence',
                '                LOG.error("Already running as pid %d", pid)',
                '                return None',
                '            except OSError as exc:',
                '                if exc.errno == errno.EPERM:',
                '                    LOG.error("Already running as pid %d (owned by another user)", pid)',
                '                    return None',
                '        LOG.warning("Removing a stale lock from pid %s", pid)',
                '        lock_path.unlink(missing_ok=True)',
                '',
                '    lock_path.write_text(str(os.getpid()), encoding="utf-8")',
                '    return lock_path',
                '',
                '',
              ]),
          ...(state !== 'none'
            ? [
                'def read_state() -> dict[str, Any]:',
                '    path = STATE_DIR / f"{JOB_NAME}.state.json"',
                '    if not path.exists():',
                '        LOG.info("No previous state — this is the first run")',
                '        return {}',
                '    try:',
                '        state = json.loads(path.read_text(encoding="utf-8"))',
                '        LOG.info("Last successful run: %s", state.get("last_success"))',
                '        return state',
                '    except (OSError, json.JSONDecodeError) as exc:',
                '        LOG.warning("Could not read the state file (%s) — treating this as a first run", exc)',
                '        return {}',
                '',
                '',
                'def write_state(state: dict[str, Any]) -> None:',
                '    """Only after a success.',
                '',
                '    A failed run leaves the previous watermark, so the next attempt',
                '    covers the same ground rather than skipping it.',
                '    """',
                '    path = STATE_DIR / f"{JOB_NAME}.state.json"',
                '    STATE_DIR.mkdir(parents=True, exist_ok=True)',
                '    temporary = path.with_suffix(".tmp")',
                '    temporary.write_text(json.dumps(state, indent=2, default=str), encoding="utf-8")',
                '    temporary.replace(path)',
                '',
                '',
              ]
            : []),
          ...(metrics === 'file'
            ? [
                'def write_metrics(success: bool, processed: int, failed: int, seconds: float) -> None:',
                '    """A Prometheus textfile.',
                '',
                '    The number that matters is the last success timestamp. Alerting when',
                '    it gets old catches the job not running at all, which is the failure',
                '    nobody notices.',
                '    """',
                '    if not METRICS_DIR.exists():',
                '        LOG.debug("No metrics directory at %s", METRICS_DIR)',
                '        return',
                '    lines = [',
                '        f"# HELP {JOB_NAME}_last_run_timestamp_seconds When this job last ran.",',
                '        f"# TYPE {JOB_NAME}_last_run_timestamp_seconds gauge",',
                '        f"{JOB_NAME}_last_run_timestamp_seconds {time.time():.0f}",',
                '        f"# HELP {JOB_NAME}_last_success_timestamp_seconds When this job last succeeded.",',
                '        f"# TYPE {JOB_NAME}_last_success_timestamp_seconds gauge",',
                '    ]',
                '    if success:',
                '        lines.append(f"{JOB_NAME}_last_success_timestamp_seconds {time.time():.0f}")',
                '    lines += [',
                '        f"# TYPE {JOB_NAME}_duration_seconds gauge",',
                '        f"{JOB_NAME}_duration_seconds {seconds:.1f}",',
                '        f"# TYPE {JOB_NAME}_processed_total gauge",',
                '        f"{JOB_NAME}_processed_total {processed}",',
                '        f"# TYPE {JOB_NAME}_failed_total gauge",',
                '        f"{JOB_NAME}_failed_total {failed}",',
                '    ]',
                '    target = METRICS_DIR / f"{JOB_NAME}.prom"',
                '    temporary = target.with_suffix(".tmp")',
                '    temporary.write_text("\\n".join(lines) + "\\n", encoding="utf-8")',
                '    temporary.replace(target)  # atomic, so the exporter never reads half a file',
                '',
                '',
              ]
            : []),
          'def process(item: Any, dry_run: bool) -> bool:',
          '    """One item. Return True when it worked."""',
          '    if dry_run:',
          '        LOG.info("Dry run: would process %s", item)',
          '        return True',
          '    # The work goes here.',
          '    return True',
          '',
          '',
          'def collect(state: dict[str, Any], force: bool) -> list[Any]:',
          '    """What to work on this run."""',
          ...(state === 'watermark'
            ? [
                '    since = None if force else state.get("watermark")',
                '    if since:',
                '        LOG.info("Picking up from %s", since)',
                '    else:',
                '        LOG.info("Processing everything")',
              ]
            : state === 'checksum'
              ? [
                  '    previous = None if force else state.get("checksum")',
                  '    # Compute the checksum of the input here and compare.',
                  '    LOG.debug("Previous checksum: %s", previous)',
                ]
              : []),
          '    # Fetch the items here.',
          '    return []',
          '',
          '',
          'def main(argv: list[str] | None = None) -> int:',
          '    parser = argparse.ArgumentParser(',
          `        description=${pyString(str(values, 'summary', ''))},`,
          '        formatter_class=argparse.ArgumentDefaultsHelpFormatter,',
          '    )',
          '    parser.add_argument("--dry-run", action="store_true", help="report and change nothing")',
          '    parser.add_argument("--force", action="store_true", help="ignore the state and process everything")',
          '    parser.add_argument("--verbose", action="store_true")',
          '    args = parser.parse_args(argv)',
          '    configure_logging(args.verbose)',
          '',
          '    # A scheduled job with no timeout that hangs simply never runs again,',
          '    # and nothing says so.',
          '    def timed_out(_signum: int, _frame: Any) -> None:',
          '        LOG.error("Ran for longer than %d seconds — giving up", MAX_RUNTIME)',
          '        raise TimeoutError(f"exceeded {MAX_RUNTIME}s")',
          '',
          '    signal.signal(signal.SIGALRM, timed_out)',
          '    signal.alarm(MAX_RUNTIME)',
          '',
          '    lock = acquire_lock()',
          '    if lock is None:',
          '        return 3',
          '',
          '    started = time.monotonic()',
          '    processed = 0',
          '    failed = 0',
          '    success = False',
          '',
          '    try:',
          ...(state !== 'none' ? ['        state = read_state()', '        items = collect(state, args.force)'] : ['        state = {}', '        items = collect(state, args.force)']),
          '        LOG.info("%d item(s) to process", len(items))',
          '',
          '        for item in items:',
          '            for attempt in range(1, RETRIES + 2):',
          '                try:',
          '                    if process(item, args.dry_run):',
          '                        processed += 1',
          '                        break',
          '                except Exception as exc:  # noqa: BLE001 — one item must not stop the run',
          '                    if attempt > RETRIES:',
          '                        LOG.error("Gave up on %s: %s", item, exc)',
          '                        failed += 1',
          '                    else:',
          '                        LOG.warning("%s failed (%s) — retrying", item, exc)',
          '                        time.sleep(2 ** attempt)',
          '',
          '        success = failed == 0',
          ...(state !== 'none'
            ? [
                '        if success and not args.dry_run:',
                '            state["last_success"] = datetime.now(timezone.utc).isoformat()',
                ...(state === 'watermark' ? ['            state["watermark"] = datetime.now(timezone.utc).isoformat()'] : []),
                '            write_state(state)',
              ]
            : []),
          '    except TimeoutError:',
          '        return 1',
          '    except Exception as exc:  # noqa: BLE001',
          '        LOG.error("%s", exc)',
          '        LOG.debug("Traceback", exc_info=True)',
          '        return 1',
          '    finally:',
          '        signal.alarm(0)',
          '        elapsed = time.monotonic() - started',
          ...(metrics === 'file'
            ? ['        write_metrics(success, processed, failed, elapsed)']
            : metrics === 'log'
              ? ['        LOG.info("%s: processed=%d failed=%d seconds=%.1f success=%s", JOB_NAME, processed, failed, elapsed, success)']
              : []),
          ...(socketLock ? ['        if lock is not None:', '            lock.close()'] : ['        if isinstance(lock, Path):', '            lock.unlink(missing_ok=True)']),
          '',
          '    LOG.info("Done: %d processed, %d failed", processed, failed)',
          '    return 0 if success else 1',
          ...ENTRY,
        ],
        findings,
      };
    },
  }),

  scriptBlueprint({
    id: 'py_bulk_check',
    platform: PLATFORM,
    label: 'Bulk endpoint and certificate check',
    group: 'Network',
    description: 'Check a few hundred URLs at once: status, response time, redirect chain, certificate expiry and whether the security headers are there.',
    inputs: [
      { id: 'script_name', label: 'Script name', control: 'text', default: 'check-endpoints' },
      { id: 'source', label: 'URLs from', control: 'select', default: 'file', options: [
        { value: 'file', label: 'A text file, one per line' },
        { value: 'csv', label: 'A CSV with a url column' },
      ] },
      { id: 'checks', label: 'Check', control: 'select', default: 'all', options: [
        { value: 'all', label: 'Status, timing, redirects, certificate and headers' },
        { value: 'status', label: 'Status and timing only' },
        { value: 'certificate', label: 'Certificates only' },
      ] },
      { id: 'workers', label: 'At a time', control: 'number', default: 20, min: 1, max: 200 },
      { id: 'timeout', label: 'Timeout (seconds)', control: 'number', default: 10, min: 1, max: 120 },
      { id: 'cert_warn_days', label: 'Warn when a certificate has fewer days', control: 'number', default: 30, min: 1, max: 365 },
      { id: 'expect_status', label: 'Expected status', control: 'text', default: '200, 301, 302' },
      { id: 'follow_redirects', label: 'Follow redirects', control: 'toggle', default: false, hint: 'Off shows where each one actually points, which is usually the question' },
    ],
    script: (values                 )         => {
      const name = identifier(str(values, 'script_name', 'check-endpoints'), 'check-endpoints');
      const module = snake(name, 'check_endpoints');
      const checks = str(values, 'checks', 'all');
      const expected = listOf(str(values, 'expect_status', '')).filter((s) => /^\d+$/.test(s));
      const findings            = [];

      if (expected.length === 0) findings.push(error('scripts.py.no-expected-status', 'No expected status was given, so every result is a failure.', { source: 'ArchToolKit' }));
      if (num(values, 'workers', 20) > 50) {
        findings.push(
          warning('scripts.py.too-many-workers', 'Fifty simultaneous requests at one site looks like a load test to anything watching, and a rate limiter or a WAF will start refusing. Keep it low when the URLs share a host.', {
            source: 'ArchToolKit',
          }),
        );
      }

      return {
        platform: PLATFORM,
        title: 'Check endpoints for status, timing and certificate expiry',
        effect: 'read',
        requires: [{ what: 'Python 3.9 or later' }, { what: 'Nothing else — urllib and ssl are standard library' }],
        parameters: [
          { name: 'input', description: 'The URLs to check.', required: true, example: './urls.txt' },
          { name: '-o, --output', description: 'Where the CSV is written.', required: false },
          { name: '--workers', description: 'How many at once.', required: false },
        ],
        notes: [
          'Every request has a timeout. A check that hangs is worse than one that fails, because whatever is watching waits instead of alerting.',
          ...(bool(values, 'follow_redirects', false)
            ? ['Redirects are followed, so the status is the final one. The chain is still reported, because a five-hop redirect is a finding of its own.']
            : ['Redirects are not followed, so the status shows where each URL actually points. That is usually the question — a 301 to the wrong place looks fine if you follow it.']),
          ...(checks !== 'status' ? ['The certificate is read without validating the chain, so an endpoint whose chain is already broken is reported on rather than failing the check.'] : []),
          'Threads, not async. This is waiting on the network, the standard library has no async HTTP client, and a thread pool is both simpler and fast enough.',
          'Exit code is non-zero when anything failed, so this works as a monitoring check and in a pipeline.',
        ],
        usage: [`python3 ${module}.py urls.txt`, `python3 ${module}.py urls.txt --workers 5 --verbose`, `python3 ${module}.py urls.txt -o results.csv; echo $?`],
        undo: ['Nothing to undo — it reads.'],
        body: [
          ...preamble(
            [
              'import csv',
              'import socket',
              'import ssl',
              'import time',
              'import urllib.error',
              'import urllib.request',
              'from concurrent.futures import ThreadPoolExecutor, as_completed',
              'from datetime import datetime',
              'from pathlib import Path',
              'from typing import Any',
            ],
            ['Check endpoints for status, timing and certificate expiry.', '', 'Everything has a timeout. A check that hangs is worse than one that fails.', '', ''],
          ),
          '',
          `EXPECTED = {${expected.join(', ')}}`,
          `CERT_WARN_DAYS = ${num(values, 'cert_warn_days', 30)}`,
          'SECURITY_HEADERS = [',
          '    "strict-transport-security",',
          '    "x-content-type-options",',
          '    "x-frame-options",',
          '    "content-security-policy",',
          ']',
          '',
          '',
          'class NoRedirect(urllib.request.HTTPRedirectHandler):',
          '    """Report where a URL points rather than where it ends up.',
          '',
          '    A 301 to the wrong place looks perfectly healthy if you follow it.',
          '    """',
          '',
          '    def redirect_request(self, *_args: Any, **_kwargs: Any) -> None:',
          '        return None',
          '',
          '',
          ...(checks !== 'status'
            ? [
                'def certificate(url: str, timeout: int) -> dict[str, Any]:',
                '    """Read what the server presents, without validating the chain.',
                '',
                '    An endpoint whose chain is already broken should be reported on,',
                '    not skipped.',
                '    """',
                '    if not url.startswith("https://"):',
                '        return {}',
                '    hostport = url[len("https://") :].split("/")[0]',
                '    host, _, port = hostport.partition(":")',
                '    port_number = int(port) if port else 443',
                '',
                '    context = ssl.create_default_context()',
                '    context.check_hostname = False',
                '    context.verify_mode = ssl.CERT_NONE',
                '',
                '    try:',
                '        with socket.create_connection((host, port_number), timeout=timeout) as raw:',
                '            with context.wrap_socket(raw, server_hostname=host) as tls:',
                '                der = tls.getpeercert(binary_form=True)',
                '                info = ssl._ssl._test_decode_cert  # noqa: SLF001 — no public API for this',
                '                cert = tls.getpeercert()',
                '                protocol = tls.version()',
                '    except (OSError, ssl.SSLError) as exc:',
                '        return {"cert_error": str(exc)[:120]}',
                '',
                '    not_after = cert.get("notAfter") if cert else None',
                '    if not not_after:',
                '        # CERT_NONE gives an empty dict; re-read with validation to get',
                '        # the dates, and fall back to reporting only the protocol.',
                '        try:',
                '            strict = ssl.create_default_context()',
                '            with socket.create_connection((host, port_number), timeout=timeout) as raw:',
                '                with strict.wrap_socket(raw, server_hostname=host) as tls:',
                '                    cert = tls.getpeercert()',
                '            not_after = cert.get("notAfter")',
                '        except (OSError, ssl.SSLError) as exc:',
                '            return {"tls_version": protocol, "cert_error": f"chain: {str(exc)[:80]}"}',
                '',
                '    try:',
                '        expiry = datetime.strptime(not_after, "%b %d %H:%M:%S %Y %Z")',
                '    except (TypeError, ValueError):',
                '        return {"tls_version": protocol}',
                '',
                '    days = (expiry - datetime.now()).days',
                '    issuer = dict(x[0] for x in cert.get("issuer", ())) if cert else {}',
                '    return {',
                '        "tls_version": protocol,',
                '        "cert_expires": expiry.strftime("%Y-%m-%d"),',
                '        "cert_days_left": days,',
                '        "cert_issuer": issuer.get("organizationName", ""),',
                '    }',
                '',
                '',
              ]
            : []),
          'def check(url: str, timeout: int) -> dict[str, Any]:',
          '    """One URL. Never raises — a failure is a row, not an exception."""',
          '    row: dict[str, Any] = {"url": url}',
          '',
          ...(checks !== 'certificate'
            ? [
                `    opener = urllib.request.build_opener(${bool(values, 'follow_redirects', false) ? '' : 'NoRedirect'})`,
                '    request = urllib.request.Request(url, headers={"User-Agent": "automation/1.0"}, method="GET")',
                '    started = time.monotonic()',
                '    try:',
                '        with opener.open(request, timeout=timeout) as response:',
                '            row["status"] = response.status',
                '            row["final_url"] = response.url',
                '            headers = {k.lower(): v for k, v in response.headers.items()}',
                '    except urllib.error.HTTPError as exc:',
                '        # A redirect counts as an HTTPError once redirects are off,',
                '        # which is exactly what we want to report.',
                '        row["status"] = exc.code',
                '        row["final_url"] = exc.headers.get("Location", url)',
                '        headers = {k.lower(): v for k, v in exc.headers.items()}',
                '    except urllib.error.URLError as exc:',
                '        row["status"] = 0',
                '        row["error"] = str(exc.reason)[:120]',
                '        headers = {}',
                '    except (OSError, ValueError) as exc:',
                '        row["status"] = 0',
                '        row["error"] = str(exc)[:120]',
                '        headers = {}',
                '',
                '    row["ms"] = round((time.monotonic() - started) * 1000)',
                '    row["expected"] = row["status"] in EXPECTED',
                '',
                ...(checks === 'all'
                  ? [
                      '    row["server"] = headers.get("server", "")',
                      '    missing = [h for h in SECURITY_HEADERS if h not in headers]',
                      '    row["missing_headers"] = ", ".join(missing)',
                      '',
                    ]
                  : []),
              ]
            : []),
          ...(checks !== 'status' ? ['    row.update(certificate(url, timeout))', ''] : []),
          '    return row',
          '',
          '',
          'def read_urls(path: Path) -> list[str]:',
          ...(str(values, 'source', 'file') === 'csv'
            ? [
                '    with path.open(newline="", encoding="utf-8-sig") as handle:',
                '        urls = [(row.get("url") or "").strip() for row in csv.DictReader(handle)]',
              ]
            : ['    urls = [line.strip() for line in path.read_text(encoding="utf-8").splitlines()]']),
          '    urls = [u for u in urls if u and not u.startswith("#")]',
          '    # A bare hostname is almost always meant as https.',
          '    return [u if "://" in u else f"https://{u}" for u in urls]',
          '',
          '',
          'def main(argv: list[str] | None = None) -> int:',
          '    parser = argparse.ArgumentParser(',
          '        description="Check endpoints for status, timing and certificate expiry",',
          '        formatter_class=argparse.ArgumentDefaultsHelpFormatter,',
          '    )',
          '    parser.add_argument("input", type=Path, help="the URLs to check")',
          '    parser.add_argument("-o", "--output", type=Path)',
          `    parser.add_argument("--workers", type=int, default=${num(values, 'workers', 20)})`,
          `    parser.add_argument("--timeout", type=int, default=${num(values, 'timeout', 10)})`,
          '    parser.add_argument("--verbose", action="store_true")',
          '    args = parser.parse_args(argv)',
          '    configure_logging(args.verbose)',
          '',
          '    try:',
          '        urls = read_urls(args.input)',
          '    except OSError as exc:',
          '        LOG.error("%s", exc)',
          '        return 2',
          '',
          '    if not urls:',
          '        LOG.error("No URLs to check")',
          '        return 2',
          '    LOG.info("Checking %d URLs with %d workers", len(urls), args.workers)',
          '',
          '    rows: list[dict[str, Any]] = []',
          '    with ThreadPoolExecutor(max_workers=args.workers) as pool:',
          '        futures = {pool.submit(check, url, args.timeout): url for url in urls}',
          '        for future in as_completed(futures):',
          '            row = future.result()',
          '            rows.append(row)',
          '            if row.get("error"):',
          '                LOG.warning("%s: %s", row["url"], row["error"])',
          '            elif not row.get("expected", True):',
          '                LOG.warning("%s: %s", row["url"], row.get("status"))',
          '            else:',
          '                LOG.debug("%s: %s in %sms", row["url"], row.get("status"), row.get("ms"))',
          '',
          '    rows.sort(key=lambda r: r["url"])',
          '',
          '    if args.output:',
          '        columns: list[str] = []',
          '        for row in rows:',
          '            for key in row:',
          '                if key not in columns:',
          '                    columns.append(key)',
          '        with args.output.open("w", newline="", encoding="utf-8") as handle:',
          '            writer = csv.DictWriter(handle, fieldnames=columns)',
          '            writer.writeheader()',
          '            writer.writerows(rows)',
          '        LOG.info("Wrote %d rows to %s", len(rows), args.output)',
          '',
          '    bad = [r for r in rows if r.get("error") or not r.get("expected", True)]',
          ...(checks !== 'status'
            ? [
                '    expiring = [r for r in rows if isinstance(r.get("cert_days_left"), int) and r["cert_days_left"] < CERT_WARN_DAYS]',
                '    for row in expiring:',
                '        LOG.warning("%s: certificate expires in %d days", row["url"], row["cert_days_left"])',
              ]
            : ['    expiring = []']),
          '',
          '    print(f"{len(rows)} checked, {len(bad)} unhealthy, {len(expiring)} certificates expiring soon")',
          '    for row in bad[:20]:',
          '        print(f"  {row[\'url\']}: {row.get(\'error\') or row.get(\'status\')}")',
          '',
          '    return 1 if (bad or expiring) else 0',
          ...ENTRY,
        ],
        findings,
      };
    },
  }),

  scriptBlueprint({
    id: 'py_compare_exports',
    platform: PLATFORM,
    label: 'Compare two exports',
    group: 'Data',
    description: 'What was added, what was removed and what changed between two versions of the same export — the question behind most "why is this different" tickets.',
    inputs: [
      { id: 'script_name', label: 'Script name', control: 'text', default: 'compare-inventory' },
      { id: 'format', label: 'Format', control: 'select', default: 'csv', options: [
        { value: 'csv', label: 'CSV' },
        { value: 'json', label: 'JSON' },
      ] },
      { id: 'key_column', label: 'Key', control: 'text', default: 'Hostname', hint: 'What identifies a row in both files' },
      { id: 'compare_columns', label: 'Compare', control: 'text', default: '', hint: 'Columns to compare — empty for all of them' },
      { id: 'ignore_columns', label: 'Ignore', control: 'text', default: 'LastSeen, ExportedAt, Timestamp', hint: 'Columns that always differ and never matter' },
      { id: 'output', label: 'Output', control: 'select', default: 'both', options: [
        { value: 'both', label: 'A summary on screen and a CSV of the differences' },
        { value: 'summary', label: 'Summary only' },
        { value: 'csv', label: 'CSV only' },
      ] },
      { id: 'case_sensitive', label: 'Case sensitive', control: 'toggle', default: false },
      { id: 'fail_on_change', label: 'Exit non-zero when anything differs', control: 'toggle', default: false, hint: 'For a pipeline that should stop on drift' },
    ],
    script: (values                 )         => {
      const name = identifier(str(values, 'script_name', 'compare-exports'), 'compare-exports');
      const module = snake(name, 'compare_exports');
      const key = str(values, 'key_column', 'Hostname');
      const ignore = listOf(str(values, 'ignore_columns', ''));
      const findings            = [];

      if (!key) findings.push(error('scripts.py.no-key', 'Without a key column there is no way to say which row in one file corresponds to which in the other.', { source: 'ArchToolKit' }));
      if (ignore.length === 0) {
        findings.push(
          warning('scripts.py.no-ignored-columns', 'Most exports carry a timestamp or a "last seen" column that differs on every run. Without ignoring those, every row looks changed and the report is useless.', {
            source: 'ArchToolKit',
          }),
        );
      }

      return {
        platform: PLATFORM,
        title: `Compare two exports on ${key}: added, removed and changed`,
        effect: 'read',
        requires: [{ what: 'Python 3.9 or later' }, { what: 'Nothing else — standard library only' }],
        parameters: [
          { name: 'before', description: 'The earlier export.', required: true },
          { name: 'after', description: 'The later export.', required: true },
          { name: '-o, --output', description: 'Where the differences CSV is written.', required: false },
        ],
        notes: [
          `Rows are matched on ${key}. A row whose key changed reads as one removal and one addition, which is correct but worth knowing when the numbers look wrong.`,
          ...(ignore.length > 0 ? [`Ignored on both sides: ${ignore.join(', ')}. These are the columns that differ on every export and mean nothing.`] : []),
          'A changed row is reported field by field, with the old and new value. "Row changed" on its own is not actionable.',
          'Both files are read fully into memory, keyed by the key column. For anything over about a million rows this needs a database rather than a script.',
        ],
        usage: [`python3 ${module}.py monday.csv friday.csv`, `python3 ${module}.py monday.csv friday.csv -o differences.csv`, `python3 ${module}.py monday.csv friday.csv --verbose`],
        undo: ['Nothing to undo — it reads.'],
        body: [
          ...preamble(
            ['import csv', ...(str(values, 'format', 'csv') === 'json' ? ['import json'] : []), 'from pathlib import Path', 'from typing import Any'],
            [`Compare two exports on ${key}.`, '', 'Added, removed and changed — field by field.', '', ''],
          ),
          '',
          `KEY = ${pyString(key)}`,
          `IGNORE = {${ignore.map((c) => pyString(c)).join(', ')}}`,
          ...(str(values, 'compare_columns', '')
            ? [`COMPARE: set[str] | None = {${listOf(str(values, 'compare_columns', '')).map((c) => pyString(c)).join(', ')}}`]
            : ['COMPARE: set[str] | None = None  # None means every column']),
          `CASE_SENSITIVE = ${bool(values, 'case_sensitive', false) ? 'True' : 'False'}`,
          '',
          '',
          'def read(path: Path) -> dict[str, dict[str, Any]]:',
          '    """Keyed by the key column, so the comparison is a dictionary lookup."""',
          ...(str(values, 'format', 'csv') === 'json'
            ? [
                '    data = json.loads(path.read_text(encoding="utf-8"))',
                '    rows = data if isinstance(data, list) else data.get("data", data.get("items", []))',
              ]
            : [
                '    with path.open(newline="", encoding="utf-8-sig") as handle:',
                '        reader = csv.DictReader(handle)',
                '        if reader.fieldnames is None:',
                '            raise ValueError(f"{path} is empty")',
                '        rows = [dict(row) for row in reader]',
              ]),
          '',
          '    keyed: dict[str, dict[str, Any]] = {}',
          '    duplicates = 0',
          '    for row in rows:',
          '        if KEY not in row:',
          '            raise ValueError(f"{path} has no {KEY} column")',
          '        value = str(row[KEY]).strip()',
          '        if not value:',
          '            continue',
          '        if not CASE_SENSITIVE:',
          '            value = value.lower()',
          '        if value in keyed:',
          '            duplicates += 1',
          '        keyed[value] = row',
          '',
          '    if duplicates:',
          '        LOG.warning("%s has %d duplicate keys — the last of each wins", path, duplicates)',
          '    LOG.info("Read %d rows from %s", len(keyed), path)',
          '    return keyed',
          '',
          '',
          'def differences(before: dict[str, Any], after: dict[str, Any]) -> list[dict[str, Any]]:',
          '    """Field by field. "Row changed" on its own is not actionable."""',
          '    columns = COMPARE if COMPARE is not None else set(before) | set(after)',
          '    out: list[dict[str, Any]] = []',
          '    for column in sorted(columns - IGNORE - {KEY}):',
          '        was = str(before.get(column, "")).strip()',
          '        now = str(after.get(column, "")).strip()',
          '        if not CASE_SENSITIVE:',
          '            was, now = was.lower(), now.lower()',
          '        if was != now:',
          '            out.append(',
          '                {',
          '                    "field": column,',
          '                    "before": before.get(column, ""),',
          '                    "after": after.get(column, ""),',
          '                }',
          '            )',
          '    return out',
          '',
          '',
          'def main(argv: list[str] | None = None) -> int:',
          '    parser = argparse.ArgumentParser(',
          '        description="Compare two exports",',
          '        formatter_class=argparse.ArgumentDefaultsHelpFormatter,',
          '    )',
          '    parser.add_argument("before", type=Path, help="the earlier export")',
          '    parser.add_argument("after", type=Path, help="the later export")',
          '    parser.add_argument("-o", "--output", type=Path)',
          '    parser.add_argument("--verbose", action="store_true")',
          '    args = parser.parse_args(argv)',
          '    configure_logging(args.verbose)',
          '',
          '    try:',
          '        before = read(args.before)',
          '        after = read(args.after)',
          '    except (OSError, ValueError) as exc:',
          '        LOG.error("%s", exc)',
          '        return 2',
          '',
          '    added = sorted(set(after) - set(before))',
          '    removed = sorted(set(before) - set(after))',
          '    common = sorted(set(before) & set(after))',
          '',
          '    rows: list[dict[str, Any]] = []',
          '    for item in added:',
          '        rows.append({"key": item, "change": "added", "field": "", "before": "", "after": ""})',
          '    for item in removed:',
          '        rows.append({"key": item, "change": "removed", "field": "", "before": "", "after": ""})',
          '',
          '    changed = 0',
          '    for item in common:',
          '        found = differences(before[item], after[item])',
          '        if found:',
          '            changed += 1',
          '        for difference in found:',
          '            rows.append({"key": item, "change": "changed", **difference})',
          '',
          ...(str(values, 'output', 'both') !== 'csv'
            ? [
                '    print(f"{len(before):,} rows before, {len(after):,} after")',
                '    print(f"  added:   {len(added):,}")',
                '    print(f"  removed: {len(removed):,}")',
                '    print(f"  changed: {changed:,}")',
                '',
                '    for item in added[:10]:',
                '        print(f"  + {item}")',
                '    if len(added) > 10:',
                '        print(f"  + ... and {len(added) - 10} more")',
                '    for item in removed[:10]:',
                '        print(f"  - {item}")',
                '    if len(removed) > 10:',
                '        print(f"  - ... and {len(removed) - 10} more")',
                '',
                '    shown = 0',
                '    for row in rows:',
                '        if row["change"] != "changed" or shown >= 20:',
                '            continue',
                '        print(f"  ~ {row[\'key\']}.{row[\'field\']}: {row[\'before\']!r} -> {row[\'after\']!r}")',
                '        shown += 1',
                '',
              ]
            : []),
          ...(str(values, 'output', 'both') !== 'summary'
            ? [
                '    output = args.output or Path("differences.csv")',
                '    if rows:',
                '        with output.open("w", newline="", encoding="utf-8") as handle:',
                '            writer = csv.DictWriter(handle, fieldnames=["key", "change", "field", "before", "after"])',
                '            writer.writeheader()',
                '            writer.writerows(rows)',
                '        LOG.info("Wrote %d differences to %s", len(rows), output)',
                '    else:',
                '        LOG.info("No differences")',
                '',
              ]
            : []),
          ...(bool(values, 'fail_on_change', false) ? ['    return 1 if rows else 0'] : ['    return 0']),
          ...ENTRY,
        ],
        findings,
      };
    },
  }),
];
