/**
 * VCF Operations for Networks: the build-out.
 *
 * Every Networks blueprint, built with its defaults and with every select
 * option and toggle flipped: the scripts parse as bash, the JSON parses, no
 * credential is written, no retired or pre-9.x name reaches the output, and the
 * calls are the ones the 9.1 API reference documents. Then the traps each one
 * is meant to catch.
 */

import { describe, it } from 'node:test';
import { spawnSync } from 'node:child_process';
import { expect } from '../testing/expect.ts';
import { defaultValues, type BlueprintValues } from '../kit/blueprint.ts';
import { hasErrors } from '../core/findings.ts';
// Looked up in these two files only, so this runs while other blueprint files are being edited.
import { NETWORKS_MORE } from './blueprints/vcf-logs-networks-more.ts';
import { NETWORKS_AUTOMATIONS } from './blueprints/vcf-networks-logs.ts';
import { DS_KINDS } from './blueprints/vcf-networks-sources.ts';

const MINE = [...NETWORKS_MORE, ...NETWORKS_AUTOMATIONS];
const automationFor = (id: string) => MINE.find((blueprint) => blueprint.id === id);

function build(id: string, overrides: BlueprintValues = {}) {
  const blueprint = automationFor(id);
  if (!blueprint) throw new Error(`missing ${id}`);
  return blueprint.build({ ...defaultValues(blueprint), ...overrides }, id);
}
const codes = (out: ReturnType<typeof build>) => (out.findings ?? []).map((finding) => finding.code);
const all = (out: ReturnType<typeof build>) => Object.values(out.files).join('\n');
const script = (out: ReturnType<typeof build>) => Object.entries(out.files).find(([path]) => path.endsWith('.sh'))?.[1] ?? '';

function variants(): { id: string; label: string; files: Record<string, string> }[] {
  const out: { id: string; label: string; files: Record<string, string> }[] = [];
  for (const blueprint of MINE) {
    const base = defaultValues(blueprint);
    const list: [string, BlueprintValues][] = [['defaults', base]];
    for (const input of blueprint.inputs) {
      if (input.control === 'select') for (const option of input.options ?? []) list.push([`${input.id}=${option.value}`, { ...base, [input.id]: option.value }]);
      if (input.control === 'toggle') list.push([`${input.id}=${String(!base[input.id])}`, { ...base, [input.id]: !base[input.id] }]);
    }
    for (const [label, values] of list) out.push({ id: blueprint.id, label, files: { ...blueprint.build(values, blueprint.id).files } });
  }
  return out;
}
const BUILDS = variants();
const HAS_BASH = spawnSync('bash', ['-c', 'exit 0']).status === 0;

describe('networks build-out: every blueprint and every option', () => {
  it('has the whole set', () => {
    for (const id of ['vcfnet_data_sources', 'vcfnet_ip_definitions', 'vcfnet_ip_tags_dns', 'vcfnet_applications', 'vcfnet_app_discovery', 'vcfnet_microseg_policy', 'vcfnet_intent_check', 'vcfnet_intents', 'vcfnet_search_alert', 'vcfnet_access', 'vcfnet_backup', 'vcfnet_flow_check', 'vcfnet_change_watch']) {
      expect(automationFor(id)?.platform).toBe('vcf-operations-networks');
    }
  });

  it('builds clean from the defaults', () => {
    for (const blueprint of MINE) {
      const out = blueprint.build(defaultValues(blueprint), blueprint.id);
      if (hasErrors(out.findings ?? [])) throw new Error(`${blueprint.id}: ${codes(out).join(', ')}`);
      expect(typeof out.files['IMPORT.md']).toBe('string');
    }
  });

  it('every .json parses and every script is valid bash', () => {
    for (const b of BUILDS) {
      for (const [path, text] of Object.entries(b.files)) {
        if (path.endsWith('.json')) {
          try {
            JSON.parse(text);
          } catch (err) {
            throw new Error(`${b.id} (${b.label}) ${path}: ${(err as Error).message}`);
          }
        }
        if (HAS_BASH && path.endsWith('.sh')) {
          const result = spawnSync('bash', ['-n'], { input: text, encoding: 'utf8' });
          if (result.status !== 0) throw new Error(`${b.id} (${b.label}) ${path}: ${result.stderr}`);
        }
      }
    }
  });

  it('writes no credential, no pre-9.x product name, no tool footprint', () => {
    const credential = /\b(password|passwd|secret|api[_-]?key|token|credential|community)\w*\s*[:=]+\s*["'][^"'$%{<@]/i;
    for (const b of BUILDS) {
      for (const [path, text] of Object.entries(b.files)) {
        if (credential.test(text)) throw new Error(`${b.id} (${b.label}) ${path} looks like it holds a credential`);
        // README.md carries the platform's "formerly" line on purpose; nothing else may.
        if (path === 'README.md') continue;
        if (/\bAria\b|vRealize|PowervRNI|vRNI|\bESXi\b|6\.14|archtoolkit|Generated by/i.test(text)) throw new Error(`${b.id} (${b.label}) ${path} has a retired name or footprint`);
      }
    }
  });

  it('applies: every script that changes something has an opt-in --dry-run and no preview default', () => {
    for (const blueprint of MINE) {
      const automation = blueprint.automation(defaultValues(blueprint), blueprint.id);
      if (automation.effect === 'read') continue;
      const sh = Object.entries(automation.files).find(([path]) => path.endsWith('.sh'))?.[1] ?? '';
      expect(sh.includes('DRY_RUN=0; [[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1')).toBe(true);
    }
  });
});

describe('vcfnet_data_sources: every kind the API has', () => {
  it('offers every kind in the audit and none that is deprecated', () => {
    const kinds = Object.keys(DS_KINDS);
    for (const id of ['vcenter', 'nsxt', 'hcx', 'cisco', 'cisco-asrxr', 'arista', 'juniper', 'dell', 'dell-os10', 'hpe', 'brocade', 'mellanox', 'huawei', 'cisco-aci', 'ucs', 'hpov', 'hpvc', 'f5', 'checkpoint', 'panorama', 'fortinet', 'kubernetes', 'openshift', 'velocloud', 'infoblox', 'servicenow', 'generic', 'common-device']) {
      expect(kinds.includes(id)).toBe(true);
    }
    expect(Object.values(DS_KINDS).some((kind) => /aws|azure/i.test(kind.path))).toBe(false);
  });

  it('validates a vCenter first and turns IPFIX on in the add body', () => {
    const out = build('vcfnet_data_sources');
    expect(script(out)).toContain('/data-sources/vcenters/validate');
    const sources = JSON.parse(out.files['sources.json']!) as { body: Record<string, unknown> }[];
    expect(sources[0]!.body['ipfix_request']).toEqual({ enable_all: true });
    expect(sources[0]!.body['enabled']).toBe(true);
    const onlySome = JSON.parse(build('vcfnet_data_sources', { ipfix_dvs: 'vds-a, vds-b' }).files['sources.json']!) as { body: Record<string, unknown> }[];
    expect(onlySome[0]!.body['ipfix_request']).toEqual({ enable_for_dvs: 'vds-a,vds-b' });
  });

  it('sends NSX IPFIX and latency', () => {
    const body = (JSON.parse(build('vcfnet_data_sources', { source_type: 'nsxt', sources: 'nsx-mgmt.example.com | nsx-mgmt | -' }).files['sources.json']!) as { body: Record<string, unknown> }[])[0]!.body;
    expect(body['ipfix_enabled']).toBe(true);
    expect(body['latency_enabled']).toBe(true);
  });

  it('sets per-switch SNMP v3 through snmp-config, secrets from the environment', () => {
    const out = build('vcfnet_data_sources', { source_type: 'cisco', sources: 'leaf-01.example.com | leaf-01 | NEXUS_9K\n2001:db8::11 | leaf-02 | NEXUS_9K' });
    expect(codes(out).includes('vcfnet.ds.model')).toBe(false);
    expect(script(out)).toContain('/data-sources/cisco-switches/$ID/snmp-config');
    expect(script(out)).toContain('$ENV.VCFNET_SNMP_AUTH_PASSWORD');
    expect(JSON.parse(out.files['snmp.json']!).snmp.snmp_version).toBe('v3');
    const sources = JSON.parse(out.files['sources.json']!) as { body: Record<string, unknown> }[];
    expect(sources[1]!.body['ip']).toBe('2001:db8::11');
    expect(sources[0]!.body['switch_type']).toBe('NEXUS_9K');
  });

  it('flags a missing switch model and SNMP v2c', () => {
    expect(codes(build('vcfnet_data_sources', { source_type: 'dell', sources: 'sw1.example.com | sw1 | -' })).includes('vcfnet.ds.model')).toBe(true);
    expect(codes(build('vcfnet_data_sources', { source_type: 'arista', sources: 'sw1.example.com | sw1 | -', snmp: 'v2c' })).includes('vcfnet.ds.snmp-v2c')).toBe(true);
  });

  it('bulk-adds from the CSV through /data-sources/bulk/add', () => {
    const out = build('vcfnet_data_sources', { source_type: 'juniper', mode: 'bulk', sources: 'ex-01.example.com | ex-01 | -' });
    expect(script(out)).toContain('/data-sources/bulk/add');
    expect(out.files['import/bulk-add-devices.csv']!.split('\n')[0]).toBe('datasource_type,ip,fqdn,username,password,nickname,polling_interval_in_mins,collector_ip,notes');
    expect(codes(build('vcfnet_data_sources', { mode: 'bulk' })).includes('vcfnet.ds.bulk-kind')).toBe(true);
  });

  it('enables and disables by address, with the path the reference gives', () => {
    expect(script(build('vcfnet_data_sources', { mode: 'disable' }))).toContain('/data-sources/vcenters/$ID/disable');
    expect(script(build('vcfnet_data_sources', { source_type: 'cisco-asrxr', mode: 'enable', sources: 'asr1.example.com | asr1 | -' }))).toContain('/data-sources/cisco-asr-xr-switches/$ID/enable');
  });

  it('adds a Kubernetes cluster with its kubeconfig and NSX manager', () => {
    const out = build('vcfnet_data_sources', { source_type: 'kubernetes', sources: 'vks-prod | vks-prod | -' });
    expect(script(out)).toContain('.credentials.kubeconfig = $k');
    expect(script(out)).toContain('manager_id');
  });
});

describe('vcfnet_applications and discovery', () => {
  it('creates the application with its tiers in one call, with IP and tag criteria', () => {
    const out = build('vcfnet_applications', { tiers: 'web | vcenter-tag | Tier:web\nweb | ip | 10.1.1.0/24 2001:db8:1::/64\ndb | security-group | orders-db' });
    expect(codes(out).filter((code) => code !== 'vcfnet.app.overlap')).toEqual([]);
    expect(script(out)).toContain('/groups/applications/full');
    const full = JSON.parse(out.files['application-full.json']!) as { tiers: { name: string; group_membership_criteria: { membership_type: string; ip_address_membership_criteria?: { ip_addresses: string[] } }[] }[] };
    expect(full.tiers.length).toBe(2);
    expect(full.tiers[0]!.group_membership_criteria[1]!.ip_address_membership_criteria!.ip_addresses).toEqual(['10.1.1.0/24', '2001:db8:1::/64']);
  });

  it('warns on overlapping tiers and refuses an unknown criterion', () => {
    expect(codes(build('vcfnet_applications', { tiers: 'web | name-like | web\nweb-db | name-like | web-db' })).includes('vcfnet.app.overlap')).toBe(true);
    expect(codes(build('vcfnet_applications', { tiers: 'web | colour | red' })).includes('vcfnet.app.criterion')).toBe(true);
  });

  it('configures FBAD over clusters and saves what matches', () => {
    const out = build('vcfnet_app_discovery');
    const config = JSON.parse(out.files['fbad-config.json']!);
    expect(config.scope_object_type).toBe(66);
    expect(script(out)).toContain('/groups/discovered-applications/save');
    expect(script(out)).toContain('custom-config/fbad/file/upload');
    expect(codes(build('vcfnet_app_discovery', { app_regex: '([' })).includes('vcfnet.fbad.regex')).toBe(true);
  });
});

describe('vcfnet_microseg_policy', () => {
  it('fetches recommended rules and applies an NSX policy', () => {
    const out = build('vcfnet_microseg_policy');
    expect(script(out)).toContain('/micro-seg/recommended-rules');
    expect(script(out)).toContain('/policy/api/v1/infra/domains/default/security-policies/');
    expect(script(out)).toContain('IPAddressExpression');
  });

  it('writes files only for CSV, and warns on a default deny or a short window', () => {
    expect(script(build('vcfnet_microseg_policy', { output: 'csv' })).includes('nsx PATCH')).toBe(false);
    expect(codes(build('vcfnet_microseg_policy', { default_rule: 'DROP' })).includes('vcfnet.microseg.default-deny')).toBe(true);
    expect(codes(build('vcfnet_microseg_policy', { window_days: '1' })).includes('vcfnet.microseg.short-window')).toBe(true);
  });
});

describe('Networks settings', () => {
  it('sets East-West and Internet tags and subnet VLANs, IPv6 included', () => {
    const out = build('vcfnet_ip_definitions');
    expect(script(out)).toContain('tag_id EAST_WEST');
    expect(script(out)).toContain('/settings/subnet-mappings');
    expect(JSON.parse(out.files['east-west.json']!).some((entry: { parent: { subnet?: string } }) => entry.parent.subnet === 'fd00::/8')).toBe(true);
    expect(JSON.parse(out.files['subnet-mappings.json']!)[2]).toEqual({ cidr: '2001:db8:10::/64', vlan_id: 110 });
    expect(codes(build('vcfnet_ip_definitions', { subnet_vlans: '10.0.0.0/24 | 5000' })).includes('vcfnet.ip.bad-vlan')).toBe(true);
    expect(codes(build('vcfnet_ip_definitions', { east_west: '10.0.0.0/8 | -' })).includes('vcfnet.ip.no-ipv6')).toBe(true);
  });

  it('turns a search into an enabled alert with its destinations', () => {
    const out = build('vcfnet_search_alert', { notify_snmp: 'traps.example.com', notify_webhook: 'https://hooks.example.com/net', notify_syslog: 'syslog.example.com' });
    const body = JSON.parse(out.files['alert.json']!);
    expect(body.generate_alert_criteria).toBe('SEARCH_RESULT_CHANGE');
    const sh = script(out);
    for (const call of ['/settings/alerts/search-based-alerts', '/enable', '/settings/snmp/profiles', '/settings/syslog', '/settings/databus/subscribers', '/search/ql']) expect(sh).toContain(call);
    expect(codes(build('vcfnet_search_alert', { notify_snmp: 'traps.example.com', snmp_version: 'v2c' })).includes('vcfnet.notify.weak-snmp')).toBe(true);
    expect(codes(build('vcfnet_search_alert', { notify_email: '' })).includes('vcfnet.alert.nobody-told')).toBe(true);
  });

  it('makes NSX change watch a change alert, one per part for "all"', () => {
    const out = build('vcfnet_change_watch', { watch_what: 'all' });
    const alerts = Object.entries(out.files).filter(([path]) => path.startsWith('alerts/')).map(([, text]) => JSON.parse(text));
    expect(alerts.length).toBe(4);
    for (const alert of alerts) {
      expect(alert.alert_type).toBe('CHANGE');
      expect(alert.generate_alert_criteria).toBe('SEARCH_RESULT_CHANGE');
    }
  });

  it('creates intents with their parameters, and says when they are unverified', () => {
    const duplex = JSON.parse(build('vcfnet_intents', { intent_type: 'DuplexMismatch' }).files['intent.json']!);
    expect(duplex.intentTypeId).toBe('DuplexMismatch');
    expect(duplex.paramValues.map((p: { id: string }) => p.id)).toEqual(['CheckMgmtInterface', 'SkipWhenNoInfo', 'SkipAutoDuplex']);
    expect(duplex.enabled).toBe(true);
    expect(script(build('vcfnet_intents'))).toContain('/alert-configs/intents/');
    expect(codes(build('vcfnet_intents', { intent_type: 'Segmentation' })).includes('vcfnet.intent.params-verify')).toBe(true);
  });

  it('adds IP tags through the API and writes the DNS file for the manual import', () => {
    const out = build('vcfnet_ip_tags_dns');
    expect(script(out)).toContain('/settings/ip-tags/v2/');
    expect(out.files['import/dns-mapping.csv']!.split('\n')[0]).toBe('IP Address,FQDN');
    expect(out.files['IMPORT.md']!).toContain('no call for it');
  });

  it('grants the three roles through the API, and refuses any other', () => {
    const out = build('vcfnet_access');
    expect(script(out)).toContain('/settings/user-groups/vidm');
    expect(codes(build('vcfnet_access', { principals: 'group | ops | example.com | OPERATOR' })).includes('vcfnet.access.role')).toBe(true);
    expect(build('vcfnet_access', { ldap: true }).files['IMPORT.md']!).toContain('LDAP (by hand');
  });

  it('configures an enabled backup with the password from the environment', () => {
    const out = build('vcfnet_backup');
    const body = JSON.parse(out.files['backup.json']!);
    expect(body.backup_schedule.enable).toBe(true);
    expect('password' in body.ssh_file_server).toBe(false);
    expect(script(out)).toContain('$ENV.VCFNET_BACKUP_PASSWORD');
    expect(codes(build('vcfnet_backup', { server_type: 'FTP' })).includes('vcfnet.backup.ftp')).toBe(true);
  });
});
