/**
 * The VCF Operations content build-out: alerts with every symptom kind and
 * symptom sets on related objects, standalone symptoms, alert groups, super
 * metrics from the builder, workload policies and alert actions that apply
 * through policy-apply.sh, Security Posture Management in place of Compliance,
 * and payload templates for every outbound method.
 *
 * Built from the blueprint list in vcf-operations-content.ts directly, so these
 * run whatever state the other blueprint files are in.
 */

import { describe, it } from 'node:test';
import { expect } from '../testing/expect.ts';
import { defaultValues, type BlueprintValues } from '../kit/blueprint.ts';
import { hasErrors } from '../core/findings.ts';
import { VCF_OPERATIONS_CONTENT } from './blueprints/vcf-operations-content.ts';
import { SYMPTOM_KINDS, kindInfo, symptomJson, alertJson, alertModelXml, policyApplyScript, type SymptomSpec } from './blueprints/vcf-ops-symptoms.ts';

function blueprint(id: string) {
  const found = VCF_OPERATIONS_CONTENT.find((candidate) => candidate.id === id);
  if (!found) throw new Error(`missing ${id}`);
  return found;
}

function build(id: string, overrides: BlueprintValues = {}) {
  const bp = blueprint(id);
  return bp.build({ ...defaultValues(bp), ...overrides }, 'x');
}

function codes(id: string, overrides: BlueprintValues = {}): string[] {
  return (build(id, overrides).findings ?? []).map((finding) => finding.code);
}

function automation(id: string, overrides: BlueprintValues = {}) {
  const bp = blueprint(id);
  return bp.automation({ ...defaultValues(bp), ...overrides }, 'x');
}

const CHANGED = ['vcfops_alert_definition', 'vcfops_alert_action', 'vcfops_symptom_definition', 'vcfops_alert_group', 'vcfops_super_metric', 'vcfops_workload_policy', 'vcfops_compliance', 'vcfops_webhook_payload'];

/** Every select option and every toggle flipped, as the page lets people pick them. */
function variants(id: string): BlueprintValues[] {
  const bp = blueprint(id);
  const base = defaultValues(bp);
  const out: BlueprintValues[] = [{ ...base }];
  for (const input of bp.inputs) {
    if (input.control === 'select') for (const option of input.options ?? []) out.push({ ...base, [input.id]: option.value });
    if (input.control === 'toggle') out.push({ ...base, [input.id]: !base[input.id] });
  }
  return out;
}

describe('ops content build-out: every blueprint, every option', () => {
  it('has the new blueprints', () => {
    for (const id of CHANGED) expect(Boolean(VCF_OPERATIONS_CONTENT.find((b) => b.id === id))).toBe(true);
  });

  it('builds clean from its defaults, and builds with each option without throwing', () => {
    const problems: string[] = [];
    for (const id of CHANGED) {
      const out = build(id);
      if (hasErrors(out.findings ?? [])) problems.push(`${id}: ${(out.findings ?? []).filter((f) => f.severity === 'error').map((f) => f.code).join(', ')}`);
      for (const values of variants(id)) {
        try {
          const made = blueprint(id).build(values, id);
          if (!made.files['README.md'] || !made.files['IMPORT.md']) problems.push(`${id}: no README or IMPORT.md for ${JSON.stringify(values)}`);
        } catch (failure) {
          problems.push(`${id} threw for ${JSON.stringify(values)}: ${String(failure)}`);
        }
      }
    }
    expect(problems).toEqual([]);
  });

  it('keeps the house rules in every file it writes', () => {
    const banned = /\bESXi\b|\bAria\b|vRealize|vROps|Service Broker|Generated by|archtoolkit/i;
    const problems: string[] = [];
    for (const id of CHANGED) {
      for (const values of variants(id)) {
        for (const [file, body] of Object.entries(blueprint(id).build(values, id).files)) {
          if (file === 'README.md') continue; // the platform's "formerly" line names the 8.x products on purpose
          body.split('\n').forEach((line, index) => {
            // An 8.x name is allowed where it says it is 8.x (the shared IMPORT.md intro and sources).
            if (banned.test(line) && !/8\.x/.test(line)) problems.push(`${id} ${file}:${index + 1}: ${line.trim().slice(0, 80)}`);
          });
        }
      }
    }
    expect([...new Set(problems)]).toEqual([]);
  });

  it('writes JSON that parses', () => {
    const problems: string[] = [];
    for (const id of CHANGED) {
      for (const values of variants(id)) {
        for (const [file, body] of Object.entries(blueprint(id).build(values, id).files)) {
          if (!file.endsWith('.json')) continue;
          try {
            JSON.parse(body);
          } catch (failure) {
            problems.push(`${id} ${file}: ${String(failure)}`);
          }
        }
      }
    }
    expect(problems).toEqual([]);
  });

  it('labels the object type ESX host, not ESXi', () => {
    const metric = blueprint('vcfops_alert_definition').inputs.find((input) => input.id === 'metric');
    expect((metric?.options ?? []).some((option) => option.group === 'ESX host')).toBe(true);
  });
});

describe('ops content build-out: alert definitions', () => {
  it('still writes the warning / critical pair by default, applied and enabled in the default policy', () => {
    const files = build('vcfops_alert_definition').files;
    expect(Object.keys(files).filter((file) => /-symptom-\d+-/.test(file)).length).toBe(2);
    const changes = JSON.parse(files['policy-changes.json']!);
    expect(changes.policies).toEqual(['Default Policy']);
    expect(changes.changes[0].set.enabled).toBe('true');
    expect(files['apply.sh']!.includes('policy-apply.sh')).toBe(true);
    expect(files['apply.sh']!.includes('already exists')).toBe(true);
    expect(files['policy-apply.sh']!.includes('/suite-api/api/policies/import?forceImport=true')).toBe(true);
    expect(files['policy-apply.sh']!.includes('verify.py')).toBe(true);
  });

  it('keeps its known traps', () => {
    expect(codes('vcfops_alert_definition', { warning_at: 90, critical_at: 80 }).includes('vcfops.alert.inverted')).toBe(true);
    expect(codes('vcfops_alert_definition', { warning_at: 101, critical_at: 120 }).includes('vcfops.alert.over-100')).toBe(true);
    expect(codes('vcfops_alert_definition', { threshold_pair: false }).includes('vcfops.alert.no-symptoms')).toBe(true);
    expect(codes('vcfops_alert_definition', { base_kind: 'VMWARE:ClusterComputeResource' }).includes('vcfops.alert.kind-mismatch')).toBe(true);
    expect(codes('vcfops_alert_definition', { policies: '' }).includes('vcfops.alert.no-policy')).toBe(true);
  });

  it('writes every symptom kind with its own condition type', () => {
    const symptoms = [
      '1 | property | warning | summary|runtime|isIdle | EQ | true',
      '1 | property-numeric | warning | config|hardware|num_Cpu | GT | 16',
      '1 | dynamic | immediate | cpu|usage_average | DT_ABOVE',
      '1 | message | warning | MESSAGE_EVENT | CONTAINS | HA agent',
      '1 | fault | critical | fault|hardware|memory',
      '1 | metric-event | warning | cpu|usage_average | GT | 90',
      '1 | log | critical | ESX lost access to volume | GT | 0',
    ].join('\n');
    const made = automation('vcfops_alert_definition', { symptoms, threshold_pair: false, base_kind: 'VMWARE:HostSystem' });
    const types = Object.entries(made.files)
      .filter(([file]) => /-symptom-\d+-/.test(file))
      .map(([, body]) => JSON.parse(body).state.condition.type as string);
    expect(types).toEqual(['CONDITION_PROPERTY_STRING', 'CONDITION_PROPERTY_NUMERIC', 'CONDITION_DT', 'CONDITION_MESSAGE_EVENT', 'CONDITION_FAULT', 'CONDITION_MESSAGE_EVENT', 'CONDITION_MESSAGE_EVENT']);
    const found = (made.findings ?? []).map((finding) => finding.code);
    expect(found.includes('vcfops.alert.log-symptom')).toBe(true);
    expect(found.includes('vcfops.alert.no-symptoms')).toBe(false);
  });

  it('writes several symptom sets on related objects, with a population, as one composite', () => {
    const made = automation('vcfops_alert_definition', {
      base_kind: 'VMWARE:ClusterComputeResource',
      symptom_sets: '1 | descendant | VMWARE:HostSystem | count | 2 | or\n2 | self | - | all | 0 | and',
      symptoms: '2 | metric | critical | cpu|demandPct | GT | 90',
      sets_operator: 'AND',
      impact: 'RISK',
    });
    const alert = JSON.parse(made.files['x-alert.json']!);
    const set = alert.states[0]['base-symptom-set'];
    expect(set.type).toBe('SYMPTOM_SET_COMPOSITE');
    expect(set.operator).toBe('AND');
    expect(set['symptom-sets'][0].relation).toBe('DESCENDANT');
    expect(set['symptom-sets'][0].aggregation).toBe('COUNT');
    expect(set['symptom-sets'][0].value).toBe(2);
    expect(set['symptom-sets'][0].resourceKindKey).toBe('HostSystem');
    expect(alert.states[0].impact.detail).toBe('RISK');
    const xml = made.files['import/alert-definitions.xml']!;
    expect(xml.includes('applyOn="descendant"')).toBe(true);
    expect(xml.includes('aggregation="count" value="2"')).toBe(true);
    expect((made.findings ?? []).some((f) => f.code === 'vcfops.alert.kind-mismatch')).toBe(false);
  });

  it('catches a population that can never hold', () => {
    expect(codes('vcfops_alert_definition', { symptom_sets: '1 | child | VMWARE:VirtualMachine | percent | 150 | or' }).includes('vcfops.alert.population-pct')).toBe(true);
    expect(codes('vcfops_alert_definition', { symptom_sets: '1 | child | VMWARE:VirtualMachine | count | 0 | or' }).includes('vcfops.alert.population-n')).toBe(true);
    expect(codes('vcfops_alert_definition', { symptoms: '9 | metric | warning | cpu|x | GT | 1' }).includes('vcfops.alert.undefined-set')).toBe(true);
    expect(codes('vcfops_alert_definition', { symptoms: '1 | nonsense | warning | cpu|x | GT | 1' }).includes('vcfops.alert.bad-kind')).toBe(true);
  });

  it('attaches an action to the recommendation, found by name at apply time', () => {
    const made = automation('vcfops_alert_definition', { rec_action: 'MoveVM' });
    const rec = JSON.parse(made.files['x-recommendation.json']!);
    expect(rec.action.actionId).toBe('__ACTION_ID__');
    expect(made.files['apply.sh']!.includes("action_id 'Move VM'")).toBe(true);
    expect((made.findings ?? []).some((f) => f.code === 'vcfops.alert.action-target')).toBe(true);
  });

  it('fixes the criticality when asked, and says the symptoms’ own are ignored', () => {
    const made = automation('vcfops_alert_definition', { criticality: 'CRITICAL' });
    expect(JSON.parse(made.files['x-alert.json']!).states[0].severity).toBe('CRITICAL');
    expect((made.findings ?? []).some((f) => f.code === 'vcfops.alert.fixed-criticality')).toBe(true);
  });
});

describe('ops content build-out: the symptom model', () => {
  it('has an operator for every kind, and XML for every kind', () => {
    for (const kind of SYMPTOM_KINDS) {
      expect(kind.operators.length).toBeGreaterThan(0);
      const spec: SymptomSpec = { id: `S-${kind.value}`, placeholder: '__S__', kind: kind.value, name: 'n & m', adapterKind: 'VMWARE', resourceKind: 'HostSystem', severity: 'WARNING', key: 'cpu|x', operator: kind.operators[0]!.value, value: '5', wait: 3, cancel: 3 };
      expect(typeof (symptomJson(spec).state as { condition: { type: string } }).condition.type).toBe('string');
      const xml = alertModelXml([], [spec]);
      expect(xml.includes('<SymptomDefinition adapterKind="VMWARE" cancelCycle="3"')).toBe(true);
      expect(xml.includes('name="n &amp; m"')).toBe(true);
    }
    expect(kindInfo('nonsense').value).toBe('metric');
  });

  it('writes one symptom set as a plain set and several as a composite', () => {
    const s: SymptomSpec = { id: 'S', placeholder: '__S__', kind: 'metric', name: 'n', adapterKind: 'VMWARE', resourceKind: 'HostSystem', severity: 'WARNING', key: 'k', operator: 'GT', value: '1', wait: 1, cancel: 1 };
    const one = alertJson({ id: 'A', name: 'a', description: '', adapterKind: 'VMWARE', resourceKind: 'HostSystem', type: 16, subType: 19, criticality: 'AUTO', impact: 'HEALTH', setsOperator: 'OR', sets: [{ relation: 'SELF', adapterKind: 'VMWARE', resourceKind: 'HostSystem', population: 'ALL', n: 0, combine: 'OR', symptoms: [s] }], recommendations: [] });
    expect(((one.states as Record<string, Record<string, unknown>>[])[0]!['base-symptom-set'] as { type: string }).type).toBe('SYMPTOM_SET');
  });

  it('policy-apply.sh exports first, reads back, and exits 4 when something did not take', () => {
    const script = policyApplyScript();
    expect(script.startsWith('#!/usr/bin/env bash')).toBe(true);
    expect(script.indexOf('export_policy "$ID" "$BEFORE"')).toBeLessThan(script.indexOf('/suite-api/api/policies/import?forceImport=true" -H'));
    expect(script.indexOf('/suite-api/api/policies/import?forceImport=true" -H')).toBeLessThan(script.indexOf('verify.py" "$WORK/after.zip"'));
    expect(script.includes('RC=4')).toBe(true);
    expect(script.includes('--dry-run')).toBe(true);
    // GROUPS is a bash builtin array; assigning to it silently does nothing.
    expect(/\bGROUPS\b/.test(script)).toBe(false);
  });
});

describe('ops content build-out: the standalone symptom', () => {
  it('builds every kind', () => {
    for (const kind of SYMPTOM_KINDS) {
      const made = automation('vcfops_symptom_definition', { kind: kind.value, key: 'cpu|readyPct', value: '10' });
      expect(Boolean(made.files['import/symptom-definitions.xml'])).toBe(true);
      expect(JSON.parse(made.files['x.json']!).state.condition.type.startsWith('CONDITION_')).toBe(true);
    }
  });

  it('catches what cannot work', () => {
    expect(codes('vcfops_symptom_definition', { key: '' }).includes('vcfops.symptom.no-key')).toBe(true);
    expect(codes('vcfops_symptom_definition', { kind: 'property', op_text: 'REGEX', value: '([' }).includes('vcfops.symptom.bad-regex')).toBe(true);
    expect(codes('vcfops_symptom_definition', { value: '150' }).includes('vcfops.symptom.over-100')).toBe(true);
    expect(codes('vcfops_symptom_definition', { value: 'high' }).includes('vcfops.symptom.not-a-number')).toBe(true);
    expect(codes('vcfops_symptom_definition', { kind: 'log' }).includes('vcfops.symptom.log')).toBe(true);
  });
});

describe('ops content build-out: alert groups', () => {
  it('resolves, enables and routes the group', () => {
    const files = build('vcfops_alert_group').files;
    expect(files['apply.sh']!.includes('/suite-api/api/notifications/rules')).toBe(true);
    expect(files['apply.sh']!.includes('policy-apply.sh')).toBe(true);
    expect(files['apply.sh']!.includes('Not found')).toBe(true);
  });

  it('only routes when told to leave the policies alone, and only changes policies when not routing', () => {
    expect(Boolean(build('vcfops_alert_group', { direction: 'leave' }).files['policy-apply.sh'])).toBe(false);
    expect(build('vcfops_alert_group', { route: false }).files['apply.sh']!.includes('/notifications/rules')).toBe(false);
    expect(codes('vcfops_alert_group', { direction: 'disable' }).includes('vcfops.alertgroup.route-disabled')).toBe(true);
    expect(codes('vcfops_alert_group', { alerts: '' }).includes('vcfops.alertgroup.empty')).toBe(true);
  });
});

describe('ops content build-out: super metrics', () => {
  it('is assigned to its object type and enabled in its policies, applied', () => {
    const files = build('vcfops_super_metric').files;
    expect(JSON.parse(files['x.json']!).resourceKinds).toEqual([{ adapterKindKey: 'VMWARE', resourceKindKey: 'ClusterComputeResource' }]);
    const changes = JSON.parse(files['policy-changes.json']!);
    expect(changes.changes[0].block).toBe('SuperMetrics');
    expect(changes.changes[0].id).toBe('__SM_ID__');
    expect(files['apply.sh']!.includes('policy-apply.sh')).toBe(true);
  });

  it('builds a formula from the builder, with where and isFresh', () => {
    const payload = JSON.parse(build('vcfops_super_metric', { preset: 'builder', fn: 'count', src_kind: 'VMWARE:VirtualMachine', src_metric: 'sys|poweredOn', depth: 1, where: '$value == 0', fresh: true, object_types: 'VMWARE:HostSystem,VMWARE:ClusterComputeResource', unit: 'none' }).files['x.json']!);
    expect(payload.formula).toBe('count(${adaptertype=VMWARE, objecttype=VirtualMachine, metric=sys|poweredOn, depth=1, where=($value == 0), isFresh=true})');
    expect(payload.resourceKinds.length).toBe(2);
    expect(payload.unitId).toBe('none');
  });

  it('catches what computes nothing', () => {
    expect(codes('vcfops_super_metric', { preset: 'custom', formula: '' }).includes('vcfops.supermetric.empty')).toBe(true);
    expect(codes('vcfops_super_metric', { preset: 'custom', formula: 'avg(${this, metric=cpu|x})' }).includes('vcfops.supermetric.no-type')).toBe(true);
    expect(codes('vcfops_super_metric', { preset: 'builder', depth: 0 }).includes('vcfops.supermetric.depth-zero')).toBe(true);
    expect(codes('vcfops_super_metric', { policies: '' }).includes('vcfops.supermetric.no-policy')).toBe(true);
  });
});

describe('ops content build-out: workload policy and alert action apply', () => {
  it('creates the policy under its parent, sets capacity, assigns groups and priority', () => {
    const files = build('vcfops_workload_policy').files;
    const changes = JSON.parse(files['policy-changes.json']!);
    expect(changes.create.parent).toBe('Default Policy');
    expect(changes.groups).toEqual(['Tier 1 VMs', 'Tier 1 hosts']);
    expect(changes.priority).toBe(1);
    expect(changes.changes.length).toBe(3);
    expect(files['apply.sh']!.includes('exec "$HERE/policy-apply.sh"')).toBe(true);
    expect(Object.keys(files).some((file) => /design\.md$/.test(file))).toBe(false);
    expect(JSON.parse(build('vcfops_workload_policy', { capacity_model: 'demand' }).files['policy-changes.json']!).changes[0].set).toEqual({ enabled: 'false' });
  });

  it('automates the action in a dedicated policy, with a change ticket', () => {
    const files = build('vcfops_alert_action').files;
    const changes = JSON.parse(files['policy-changes.json']!);
    expect(changes.changes[0].set).toEqual({ enabled: 'true', automate: 'true' });
    expect(changes.groups).toEqual(['Automation — safe to act on']);
    expect(files['apply.sh']!.includes('CHANGE_TICKET')).toBe(true);
    expect(files['apply.sh']!.includes('PUT /suite-api/api/alertdefinitions')).toBe(true);
    expect(build('vcfops_alert_action', { change_ticket: false }).files['apply.sh']!.includes('CHANGE_TICKET:?')).toBe(false);
    expect(codes('vcfops_alert_action', { policy_name: 'Default Policy' }).includes('vcfops.action.default-policy')).toBe(true);
    expect(codes('vcfops_alert_action', { attach: false }).includes('vcfops.action.not-attached')).toBe(true);
    expect(codes('vcfops_alert_action', { action: 'DeletePoweredOffVM' }).includes('vcfops.action.delete-vm')).toBe(true);
    expect(automation('vcfops_alert_action', { action: 'DeletePoweredOffVM' }).effect).toBe('irreversible');
  });
});

describe('ops content build-out: compliance is Security Posture Management', () => {
  it('offers only the 9.1 Security Posture Management benchmarks', () => {
    const benchmark = blueprint('vcfops_compliance').inputs.find((input) => input.id === 'benchmark');
    expect((benchmark?.options ?? []).map((option) => option.value)).toEqual(['VCF 9.x Security Configuration Guide v1.0', 'PCI DSS v4.0.1 for VCF 9 v1.0', 'VCF 9 General Controls v1.0']);
  });

  it('keeps an old saved choice working, and says it is retired', () => {
    const made = automation('vcfops_compliance', { benchmark: 'CIS' });
    expect((made.findings ?? []).some((f) => f.code === 'vcfops.compliance.retired')).toBe(true);
    expect(made.title.includes('VCF 9.x Security Configuration Guide')).toBe(true);
  });

  it('enables the benchmark through the policy and still reports', () => {
    const files = build('vcfops_compliance').files;
    expect(files['enable-benchmark.sh']!.includes('policy-apply.sh')).toBe(true);
    expect(Boolean(files['report.sh'])).toBe(true);
    expect(files['crontab.txt']!.includes('<')).toBe(false);
  });
});

describe('ops content build-out: payload templates', () => {
  it('writes a template for every outbound method and binds it to the rule', () => {
    for (const destination of ['runbook', 'servicenow', 'email', 'slack', 'snmp', 'teams']) {
      const files = build('vcfops_webhook_payload', { destination }).files;
      expect(files['apply-template.sh']!.includes('/suite-api/api/notifications/payloadtemplates')).toBe(true);
      expect(files['apply-template.sh']!.includes('templateId')).toBe(true);
    }
    expect(Boolean(build('vcfops_webhook_payload', { destination: 'email' }).files['x-template.html'])).toBe(true);
    expect(build('vcfops_webhook_payload', { destination: 'email' }).files['x-template.html']!.includes('${ALERT_DEFINITION}')).toBe(true);
    expect(Boolean(build('vcfops_webhook_payload', { destination: 'snmp' }).files['send-sample.sh'])).toBe(false);
  });

  it('maps ServiceNow fields from the rows, with correlation_id always set', () => {
    const template = JSON.parse(build('vcfops_webhook_payload', { destination: 'servicenow', sn_fields: 'short_description | ${ALERT_DEFINITION}\ncategory | Storage' }).files['x-template.json']!);
    expect(template.category).toBe('Storage');
    expect(template.correlation_id).toBe('${ALERT_ID}');
    expect(template.assignment_group).toBe('Platform Operations');
  });

  it('keeps its known traps', () => {
    expect(codes('vcfops_webhook_payload', { destination: 'teams', endpoint: 'https://example.webhook.office.com/webhookb2/abc' }).includes('vcfops.payload.teams-connector')).toBe(true);
    expect(codes('vcfops_webhook_payload', { endpoint: 'https://hooks.example.com/x?token=abc' }).includes('vcfops.payload.secret-in-url')).toBe(true);
    expect(codes('vcfops_webhook_payload', { destination: 'snmp', snmp_fields: 'x' }).includes('vcfops.payload.snmp-empty')).toBe(false);
    expect(codes('vcfops_webhook_payload', { destination: 'email', email_subject: 'Alert' }).includes('vcfops.payload.subject')).toBe(true);
  });
});
