/**
 * The Linux shell command catalogue.
 *
 * Bash is where the gap between the help and the knowledge is widest. `man tar`
 * is forty screens and still does not tell you that `tar` strips the leading
 * slash and that is why your restore went into the wrong directory. `man find`
 * documents `-delete` without mentioning that its position on the line decides
 * whether it deletes what you filtered or everything.
 *
 * So the note is the point of each entry. The syntax line is a real invocation,
 * not a summary with angle brackets round every word.
 */

import { group,                   } from './catalog.js';

export const BASH_CATALOG                          = [
  group('bash', 'Files and directories', [
    {
      name: 'ls',
      task: 'list files, with size, owner and time',
      syntax: 'ls -lhAt --time-style=long-iso /var/log',
      parameters: [
        { name: '-h', what: 'Sizes as K/M/G rather than bytes.' },
        { name: '-A', what: 'Hidden files but not . and .. — almost always what -a was meant to be.' },
        { name: '-t', what: 'Newest first. With -r, oldest first.' },
      ],
      effect: 'read',
      note: 'Never parse ls in a script. Filenames can contain spaces and newlines, and ls will happily print them; use find -print0 or a glob instead.',
      related: ['sh.find', 'sh.stat'],
    },
    {
      name: 'find',
      task: 'find files by name, age, size or owner, and act on them',
      syntax: "find /var/log -type f -name '*.log' -mtime +30 -size +10M -printf '%s\\t%p\\n'",
      parameters: [
        { name: '-mtime +30', what: 'Modified more than 30 days ago. -mmin takes minutes.' },
        { name: '-print0', what: 'Null-separated, so xargs -0 survives spaces in names.' },
        { name: '-exec ... +', what: 'Batches the arguments. With \\; it runs once per file, which is far slower.' },
        { name: '-maxdepth 1', what: 'Must come before the other tests or find warns and ignores it.' },
      ],
      effect: 'read',
      note: 'Order matters and is not intuitive: -delete and -exec run against everything that reaches them, so a -name put after -delete deletes the lot. Always run the line with -print first, then swap in the action.',
      related: ['sh.xargs', 'sh.ls'],
    },
    {
      name: 'stat',
      task: 'see a file\u2019s real size, inode, permissions and timestamps',
      syntax: "stat -c '%n %s %U:%G %a %y' /etc/hosts",
      effect: 'read',
      note: 'The %a format gives the octal permission, which is what chmod wants. It is also the only easy way to see that a file has a different ctime from its mtime, which is how you spot a permission change someone denies making.',
    },
    {
      name: 'du',
      task: 'find what is using the disk',
      syntax: 'du -xh --max-depth=1 / | sort -h | tail -20',
      parameters: [
        { name: '-x', what: 'Stay on one filesystem. Without it you walk into /proc and network mounts.' },
        { name: '--max-depth=1', what: 'One level, so the output is readable.' },
      ],
      effect: 'read',
      note: 'du counts allocated blocks, df counts the filesystem. When they disagree by a lot, a deleted file is still held open — find it with lsof +L1, not with du.',
      related: ['sh.df', 'sh.lsof', 'sh.ncdu'],
    },
    {
      name: 'df',
      task: 'see free space and free inodes',
      syntax: 'df -hT -x tmpfs -x devtmpfs && df -i -x tmpfs',
      effect: 'read',
      note: 'A "disk full" with plenty of space free is inodes, which only df -i shows. It is usually a directory with a few million tiny session or mail files in it.',
      related: ['sh.du'],
    },
    {
      name: 'ncdu',
      task: 'browse disk usage interactively',
      syntax: 'ncdu -x /var',
      effect: 'read',
      note: 'It is du with arrow keys, and it is the fastest way to answer "what filled the disk at 3am" when you are on the box. -x keeps it off other filesystems.',
      availability: 'Not installed by default; apt/dnf install ncdu.',
    },
    {
      name: 'rsync',
      task: 'copy or mirror files, locally or over ssh',
      syntax: 'rsync -avh --dry-run --exclude .git/ /srv/app/ backup:/srv/app/',
      parameters: [
        { name: '-a', what: 'Archive: recursive, keeps permissions, times, symlinks and owners.' },
        { name: '--dry-run', what: 'Report only. Run it first, every time.' },
        { name: '--delete', what: 'Remove things at the destination that are gone from the source.' },
      ],
      effect: 'changes',
      note: 'A trailing slash on the source means "the contents of", no trailing slash means "the directory itself". src/ and src copy to different places, and this is the single most common rsync mistake.',
      related: ['sh.scp', 'sh.tar'],
    },
    {
      name: 'tar',
      task: 'make or extract an archive',
      syntax: 'tar -czf /backup/etc-$(date +%F).tar.gz -C / etc',
      parameters: [
        { name: '-C /', what: 'Change directory first, so the paths stored are relative and predictable.' },
        { name: '-t', what: 'List the contents without extracting. Do this before every restore.' },
        { name: '--one-file-system', what: 'Do not descend into mounts.' },
      ],
      effect: 'changes',
      note: 'tar strips the leading slash when creating and does not put it back when extracting, so an archive made from /etc extracts into ./etc wherever you happen to be standing. cd to / first, or pass -C on extract.',
      related: ['sh.rsync'],
    },
    {
      name: 'ln',
      task: 'make a symbolic or hard link',
      syntax: 'ln -sfn /opt/app/releases/2026-09-01 /opt/app/current',
      effect: 'changes',
      note: '-sfn is the atomic-ish release switch: without -n, ln follows an existing symlink to a directory and creates the link inside it rather than replacing it. That is how you end up with /opt/app/current/current.',
    },
    {
      name: 'chmod',
      task: 'change permissions',
      syntax: 'chmod -R u=rwX,g=rX,o= /srv/app',
      effect: 'changes',
      note: 'The capital X sets the execute bit on directories and on files that already have one, which is what you want recursively. A lowercase x makes every text file executable.',
      related: ['sh.chown', 'sh.setfacl'],
    },
    {
      name: 'chown',
      task: 'change owner and group',
      syntax: 'chown -R --from=root:root app:app /srv/app',
      effect: 'changes',
      note: '--from only changes files that currently have that owner, which turns a risky recursive chown into a reversible one.',
    },
    {
      name: 'setfacl',
      task: 'give a second user or group access without changing the owner',
      syntax: 'setfacl -R -m g:deploy:rx -m d:g:deploy:rx /srv/app',
      effect: 'changes',
      note: 'The d: entries are the default ACL, which applies to files created later. Without them the permission works today and quietly stops applying to anything new.',
      related: ['sh.getfacl'],
    },
    {
      name: 'getfacl',
      task: 'see the ACLs on a file',
      syntax: 'getfacl -p /srv/app',
      effect: 'read',
      note: 'A + on the end of the permission string in ls -l means there are ACLs. If permissions "look right" but access is denied, this is the next place to look, then SELinux.',
    },
    {
      name: 'lsof',
      task: 'see which process has a file, a port or a deleted file open',
      syntax: 'lsof +L1 /var && lsof -nP -iTCP:8080 -sTCP:LISTEN',
      parameters: [
        { name: '+L1', what: 'Files with fewer than one link: deleted but still held open.' },
        { name: '-nP', what: 'No DNS and no port-name lookup, so it returns immediately.' },
      ],
      effect: 'read',
      note: 'This is the answer to "df says full, du says empty": a log file was deleted while a process still had it open, and the space comes back only when that process is restarted or the descriptor truncated.',
      related: ['sh.fuser', 'sh.ss'],
    },
    {
      name: 'fuser',
      task: 'find or kill whatever is using a mount point',
      syntax: 'fuser -vm /mnt/data',
      effect: 'read',
      note: 'The answer to "device is busy" on umount. -k kills them, which is occasionally right and usually the start of a second incident.',
    },
    {
      name: 'shred',
      task: 'overwrite a file before removing it',
      syntax: 'shred -vzun 3 /tmp/keyfile',
      effect: 'destructive',
      note: 'It does nothing useful on a journalling filesystem, on SSDs with wear levelling, or on anything copy-on-write like ZFS or btrfs — the old blocks are still there under a different name. Full-disk encryption is the real answer.',
    },
  ]),

  group('bash', 'Text, search and data', [
    {
      name: 'grep',
      task: 'search file contents',
      syntax: "grep -rniI --exclude-dir=.git -e 'timeout' -e 'retry' /etc",
      parameters: [
        { name: '-I', what: 'Skip binary files, which otherwise fill the terminal.' },
        { name: '-o', what: 'Print only the match, which makes it a crude extractor.' },
        { name: '-P', what: 'Perl regex: lookahead, \\d, non-greedy. GNU grep only.' },
        { name: '-c / -l', what: 'Count per file / just the filenames.' },
      ],
      effect: 'read',
      note: 'grep returns 1 when it finds nothing, which under set -e kills the script. Write `grep -q foo file || true` when a miss is a normal outcome.',
      related: ['sh.rg', 'sh.awk', 'sh.sed'],
    },
    {
      name: 'rg',
      task: 'search a tree fast, honouring .gitignore',
      syntax: "rg -n --hidden --glob '!.git' 'password' .",
      module: 'ripgrep',
      effect: 'read',
      note: 'It skips anything in .gitignore by default, which is a feature until you are looking for a file that is ignored — then you need --no-ignore and wonder why nothing matched.',
      availability: 'Not installed by default.',
    },
    {
      name: 'sed',
      task: 'edit a stream or a file in place',
      syntax: "sed -i.bak -E 's/^#?(PermitRootLogin).*/\\1 no/' /etc/ssh/sshd_config",
      parameters: [
        { name: '-i.bak', what: 'Edit in place and keep the original. Do this rather than bare -i.' },
        { name: '-E', what: 'Extended regex, so + ? ( ) do not need backslashes.' },
        { name: '-n ... p', what: 'Print nothing except what you select.' },
      ],
      effect: 'changes',
      note: 'BSD sed on macOS requires an argument to -i, GNU sed does not — the form with an empty suffix works on one and breaks on the other. Always pass a real suffix like .bak, and it works on both.',
      related: ['sh.awk', 'sh.tr'],
    },
    {
      name: 'awk',
      task: 'pick columns, sum them, or reformat a line',
      syntax: "awk -F: '$3 >= 1000 { printf \"%s\\t%s\\n\", $1, $6 }' /etc/passwd",
      parameters: [
        { name: '-F', what: 'Field separator. -F\'\\t\' for tabs, -F\'[,:]\' for either.' },
        { name: '-v n=5', what: 'Pass a shell value in. Never interpolate the shell variable into the program text.' },
        { name: 'END { }', what: 'Runs once at the end — where totals get printed.' },
      ],
      effect: 'read',
      note: 'Whitespace splitting collapses runs of spaces, so `awk \'{print $2}\'` on df output works but on a file with empty fields silently shifts columns. Use -F when the separator is real.',
      related: ['sh.cut', 'sh.grep'],
    },
    {
      name: 'cut',
      task: 'take fixed fields from a delimited line',
      syntax: "cut -d: -f1,6 /etc/passwd",
      effect: 'read',
      note: 'cut cannot treat runs of spaces as one separator, which is why it fails on aligned output and awk does not. For anything with alignment, use awk.',
    },
    {
      name: 'sort',
      task: 'sort lines, numerically, by field, or by size suffix',
      syntax: "sort -t, -k3,3 -k1,1r --numeric-sort data.csv",
      parameters: [
        { name: '-h', what: 'Human sizes: 9K before 1M. This is what makes du | sort useful.' },
        { name: '-u', what: 'Sort and deduplicate in one pass.' },
        { name: '-k3,3', what: 'Field 3 only. -k3 means "from field 3 to end of line", which is rarely meant.' },
      ],
      effect: 'read',
      note: 'The locale changes the sort order — en_US ignores punctuation and case in ways that break diffs and set comparisons. Put LC_ALL=C in front of sort in any script whose output is compared.',
      related: ['sh.uniq'],
    },
    {
      name: 'uniq',
      task: 'collapse or count repeated lines',
      syntax: "awk '{print $1}' access.log | sort | uniq -c | sort -rn | head -20",
      effect: 'read',
      note: 'uniq only sees adjacent duplicates, so it is wrong unless the input is sorted. That is why the idiom is always sort | uniq -c and never uniq -c alone.',
    },
    {
      name: 'tr',
      task: 'replace or delete characters',
      syntax: "tr -d '\\r' < windows.txt > unix.txt",
      effect: 'read',
      note: 'The fix for "the script works when I type it and fails from the file": a CRLF line ending makes the shell look for a command with an invisible carriage return on the end. The error names a command that looks correct.',
    },
    {
      name: 'jq',
      task: 'query, filter and reshape JSON',
      syntax: "jq -r '.items[] | select(.status==\"active\") | [.name, .id] | @tsv' data.json",
      parameters: [
        { name: '-r', what: 'Raw output: strings without quotes, which is what a shell variable wants.' },
        { name: '-e', what: 'Exit non-zero when the result is null or false — how a script tests for a value.' },
        { name: '--arg k v', what: 'Pass a shell value in safely rather than splicing it into the filter.' },
      ],
      effect: 'read',
      note: '.foo on a missing key returns null rather than failing, so a typo produces an empty result and no error. Use .foo? for "maybe absent" and -e when absence should be a failure.',
      related: ['sh.yq', 'sh.curl'],
    },
    {
      name: 'yq',
      task: 'query or edit YAML the way jq does JSON',
      syntax: "yq -i '.spec.replicas = 3' deployment.yaml",
      effect: 'changes',
      note: 'There are two different programs called yq — the Go one (mikefarah) whose syntax is jq-like, and the Python wrapper (kislyuk) which needs a jq filter in quotes. Check `yq --version` before trusting any example you find.',
      availability: 'Not installed by default.',
    },
    {
      name: 'diff',
      task: 'compare two files or trees',
      syntax: 'diff -ruN --color=auto /etc/nginx.old /etc/nginx',
      effect: 'read',
      note: 'diff exits 1 when the files differ, which is normal and not an error — under set -e it stops the script. Guard it with `|| true` or test the exit code deliberately.',
    },
    {
      name: 'column',
      task: 'line up delimited output into readable columns',
      syntax: "mount | column -t | head",
      effect: 'read',
      note: 'The last thing in a pipeline, never the middle: once it is aligned, the separator is gone and nothing downstream can parse it.',
    },
    {
      name: 'xargs',
      task: 'turn a list of lines into arguments for a command',
      syntax: "find . -name '*.log' -mtime +14 -print0 | xargs -0 -r -P4 -n50 gzip",
      parameters: [
        { name: '-0', what: 'Null separated, matching find -print0. Survives spaces.' },
        { name: '-r', what: 'Do not run at all when the input is empty.' },
        { name: '-P4', what: 'Four at once.' },
      ],
      effect: 'changes',
      note: 'Without -r, an empty input still runs the command once with no arguments — which for something like `xargs rm` is harmless and for `xargs tar -cf out.tar` produces an empty archive that overwrites a good one.',
      related: ['sh.find', 'sh.parallel'],
    },
    {
      name: 'parallel',
      task: 'run a command over many inputs at once',
      syntax: "parallel -j8 --halt now,fail=1 'gzip {}' ::: *.log",
      effect: 'changes',
      note: 'By default it keeps going after a failure and you find out at the end. --halt now,fail=1 stops on the first one, which is what a deployment script wants.',
      availability: 'Not installed by default.',
    },
    {
      name: 'tee',
      task: 'write output to a file and pass it on',
      syntax: 'make 2>&1 | tee -a build.log',
      effect: 'changes',
      note: 'The usual way to write to a root-owned file as a normal user: `echo x | sudo tee -a /etc/file` works, while `sudo echo x >> /etc/file` does not, because the redirect happens in your shell, not under sudo.',
    },
  ]),

  group('bash', 'Processes and services', [
    {
      name: 'ps',
      task: 'list processes with the fields you choose',
      syntax: "ps -eo pid,ppid,user,pcpu,pmem,etimes,args --sort=-pcpu | head -20",
      parameters: [
        { name: 'etimes', what: 'Age in seconds, which sorts and compares. etime is a human string that does not.' },
        { name: '--sort=-rss', what: 'Biggest memory first.' },
      ],
      effect: 'read',
      note: 'ps aux truncates the command line at the terminal width unless you pipe it; ps -eo args gives the whole thing. That truncation is how people miss the argument that explains the problem.',
      related: ['sh.top', 'sh.pgrep'],
    },
    {
      name: 'pgrep',
      task: 'find process ids by name or user',
      syntax: "pgrep -af -u app 'java.*catalina'",
      effect: 'read',
      note: 'The pattern matches the process name only unless you pass -f, and matching on the full line will also match the pgrep you just typed if you are not careful. -a shows what matched, so you can see that before acting on it.',
      related: ['sh.pkill'],
    },
    {
      name: 'pkill',
      task: 'signal processes by name',
      syntax: "pkill --signal TERM -u app -f 'worker.py --queue=slow'",
      effect: 'destructive',
      note: 'Always run the identical pattern through pgrep -a first. pkill -f with a loose pattern has killed sshd on more than one occasion, and there is no undo and no confirmation.',
      related: ['sh.pgrep', 'sh.kill'],
    },
    {
      name: 'kill',
      task: 'signal a process',
      syntax: 'kill -TERM 4821 && sleep 10 && kill -KILL 4821 2>/dev/null',
      effect: 'destructive',
      note: '-9 skips the process\u2019s own cleanup, so temp files, locks and half-written data stay. Send TERM, wait, and only then KILL. A process that ignores TERM is usually stuck in uninterruptible I/O, where KILL will not work either.',
    },
    {
      name: 'nohup',
      task: 'run something that survives the terminal closing',
      syntax: 'nohup ./long-job.sh > job.log 2>&1 &',
      effect: 'changes',
      note: 'It survives the hangup but not a reboot, and the output goes to nohup.out if you forget the redirect. For anything that matters, a systemd unit or a tmux session is the better answer.',
      related: ['sh.systemd-run', 'sh.tmux'],
    },
    {
      name: 'timeout',
      task: 'stop a command that hangs',
      syntax: 'timeout --kill-after=30s 5m ./sync.sh',
      effect: 'changes',
      note: 'It exits 124 on timeout, which is how a script tells "it failed" from "it never finished". --kill-after sends KILL when TERM is ignored, which is the difference between a timeout that works and one that hangs with it.',
    },
    {
      name: 'top',
      task: 'watch CPU and memory live',
      syntax: 'top -b -n1 -o %CPU | head -20',
      effect: 'read',
      note: '-b -n1 makes it scriptable: one batch snapshot to stdout. The interactive version reports the first sample against boot time, so the first screen of CPU figures is an average since boot rather than now.',
      related: ['sh.htop', 'sh.ps'],
    },
    {
      name: 'htop',
      task: 'watch processes interactively',
      syntax: 'htop -u app',
      effect: 'read',
      note: 'Press H to hide threads — otherwise a Java process shows as three hundred entries and the list is unreadable.',
      availability: 'Not installed by default.',
    },
    {
      name: 'systemctl status',
      task: 'see whether a service is running and why it stopped',
      syntax: 'systemctl status nginx --no-pager -l',
      effect: 'read',
      note: 'The last ten log lines it prints are usually enough, and --no-pager is what makes it work inside a script or over ssh -t. For anything older, journalctl -u.',
      related: ['sh.journalctl'],
    },
    {
      name: 'systemctl restart',
      task: 'restart a service',
      syntax: 'systemctl restart nginx && systemctl is-active nginx',
      effect: 'changes',
      note: 'restart succeeds if the unit started, not if the application works. Always follow with is-active and a real check of the port or endpoint. For nginx and haproxy, prefer `reload` — it keeps connections.',
    },
    {
      name: 'systemctl enable',
      task: 'make a service start at boot',
      syntax: 'systemctl enable --now nginx',
      effect: 'changes',
      note: 'enable alone does nothing until the next boot; start alone is forgotten at the next boot. --now does both, and is why services "mysteriously" do not come back after a reboot when it was omitted.',
    },
    {
      name: 'systemctl list-units',
      task: 'list what is loaded, running or failed',
      syntax: 'systemctl list-units --type=service --state=failed --no-pager',
      effect: 'read',
      note: 'The first command to run on a machine that "feels wrong". --state=failed is the whole check, and it usually names the problem in one line.',
    },
    {
      name: 'systemctl daemon-reload',
      task: 'pick up an edited unit file',
      syntax: 'systemctl daemon-reload && systemctl restart myapp',
      effect: 'changes',
      note: 'Without it, systemd keeps running the old unit and your edit appears to have no effect. If you edited the file and nothing changed, this is why.',
    },
    {
      name: 'systemd-run',
      task: 'run a one-off command as a supervised transient unit',
      syntax: "systemd-run --unit=reindex --property=MemoryMax=2G --collect /usr/local/bin/reindex.sh",
      effect: 'changes',
      note: 'Better than nohup for anything long: it is logged in the journal, it has resource limits, and it survives your session cleanly. --collect removes the unit when it finishes so it does not sit in the failed list.',
    },
    {
      name: 'journalctl',
      task: 'read logs by unit, time or priority',
      syntax: "journalctl -u nginx --since '30 min ago' -p warning --no-pager",
      parameters: [
        { name: '-f', what: 'Follow, like tail -f.' },
        { name: '-b -1', what: 'The previous boot — how you read the logs of a crash.' },
        { name: '-o json-pretty', what: 'Full structured fields, including the ones the default format hides.' },
      ],
      effect: 'read',
      note: 'If the journal is not persistent (no /var/log/journal), everything is lost at reboot, which is exactly when you want it. `mkdir -p /var/log/journal && systemctl restart systemd-journald` fixes it.',
    },
    {
      name: 'crontab',
      task: 'list or edit scheduled jobs',
      syntax: 'crontab -l -u app',
      effect: 'read',
      note: 'cron runs with a nearly empty environment and PATH=/usr/bin:/bin, so a job that works in your shell fails there. Set the full path to every binary, and redirect output — otherwise it goes to local mail nobody reads.',
      related: ['sh.systemctl-list-timers'],
    },
    {
      name: 'systemctl list-timers',
      task: 'see scheduled systemd timers and when they next run',
      syntax: 'systemctl list-timers --all --no-pager',
      effect: 'read',
      note: 'Where modern distributions moved cron jobs. A timer with a Persistent=true runs a missed job after a reboot; cron silently skips it, which is the real difference between the two.',
    },
  ]),

  group('bash', 'Networking', [
    {
      name: 'ip a',
      task: 'see addresses and interfaces',
      syntax: 'ip -br -c a',
      effect: 'read',
      note: '-br gives one line per interface, which is what you want on a box with bridges and VLANs. ifconfig is not installed on modern distributions and shows nothing about secondary addresses even when it is.',
      related: ['sh.ip-r', 'sh.nmcli'],
    },
    {
      name: 'ip r',
      task: 'see or test routing',
      syntax: 'ip r get 10.20.30.40',
      effect: 'read',
      note: '`ip r get` answers the question people actually have — which interface and source address this specific destination will use — rather than making you read the table and work it out.',
    },
    {
      name: 'ip link set',
      task: 'bring an interface up or down, or set MTU',
      syntax: 'ip link set dev ens192 mtu 9000 up',
      effect: 'changes',
      note: 'Nothing set with `ip` survives a reboot. It is for testing; the permanent version goes in netplan, NetworkManager or ifcfg. Setting MTU 9000 on one end only is a working ping and a broken transfer.',
    },
    {
      name: 'ss',
      task: 'list listening ports and established connections',
      syntax: 'ss -tulpnH | sort -k5',
      parameters: [
        { name: '-t -u', what: 'TCP, UDP.' },
        { name: '-l', what: 'Listening only.' },
        { name: '-p', what: 'The owning process — needs root to show other users\u2019.' },
        { name: '-n', what: 'No name resolution, so it returns at once.' },
      ],
      effect: 'read',
      note: 'ss -s gives a one-line summary that shows TIME-WAIT counts; a machine with tens of thousands of them is running out of ephemeral ports, which presents as random connection failures rather than as a network problem.',
      related: ['sh.lsof', 'sh.netstat'],
    },
    {
      name: 'netstat',
      task: 'the old way to list ports',
      syntax: 'netstat -tulpn',
      effect: 'read',
      deprecated: 'ss, which is faster and in the base install',
      note: 'It is in net-tools, which is not installed on most current distributions. Worth knowing only because every runbook written before 2018 uses it.',
    },
    {
      name: 'dig',
      task: 'query DNS properly',
      syntax: 'dig +short @10.0.0.53 app.example.com A && dig +trace app.example.com',
      parameters: [
        { name: '+short', what: 'Just the answer.' },
        { name: '+trace', what: 'Walk from the root — shows which server in the chain is wrong.' },
        { name: '@server', what: 'Ask a specific resolver, bypassing the system one.' },
      ],
      effect: 'read',
      note: 'dig ignores /etc/hosts and nsswitch, so it can return the "right" answer while the application resolves something else. To see what the application sees, use getent hosts.',
      related: ['sh.getent'],
    },
    {
      name: 'getent',
      task: 'resolve a name the way an application will',
      syntax: 'getent hosts app.example.com && getent passwd jdoe',
      effect: 'read',
      note: 'This goes through nsswitch.conf — hosts file, then DNS, then whatever else is configured — which is why it is the right check when dig and the application disagree. It also answers whether LDAP or SSSD is returning a user.',
    },
    {
      name: 'curl',
      task: 'call an HTTP endpoint and see what came back',
      syntax: "curl -fsS --connect-timeout 5 --max-time 30 -o /dev/null -w '%{http_code} %{time_total}s\\n' https://api.example.com/health",
      parameters: [
        { name: '-f', what: 'Non-zero exit on 4xx/5xx. Without it, curl succeeds on a 500.' },
        { name: '-sS', what: 'Quiet, but still show errors.' },
        { name: '--resolve host:443:IP', what: 'Test one backend by name without touching DNS or hosts.' },
        { name: '-w', what: 'Print timings and status, for a health check.' },
      ],
      effect: 'read',
      note: 'Bare curl exits 0 on an HTTP 500 — the request succeeded, the response was an error. Any script that checks an endpoint needs -f, or it will report healthy through an outage.',
      related: ['sh.wget', 'sh.jq', 'sh.openssl-s-client'],
    },
    {
      name: 'wget',
      task: 'download a file or mirror a path',
      syntax: 'wget --tries=3 --timeout=30 -O /tmp/pkg.tgz https://example.com/pkg.tgz',
      effect: 'changes',
      note: 'Unlike curl it writes a file by default and names it from the URL, which on a redirect can be something unexpected. -O names it yourself; -O - sends it to stdout.',
    },
    {
      name: 'nc',
      task: 'test whether a TCP port is open',
      syntax: 'nc -vz -w3 db.example.com 5432',
      effect: 'read',
      note: 'The quickest port test there is, but there are three incompatible netcats (BSD, GNU, nmap-ncat) and the flags differ. In bash, `timeout 3 bash -c "</dev/tcp/host/5432"` needs nothing installed at all.',
    },
    {
      name: 'mtr',
      task: 'see where along a path the loss is',
      syntax: 'mtr -rwzbc 100 8.8.8.8',
      effect: 'read',
      note: 'Loss at a middle hop and not at the last one is almost always ICMP rate limiting on that router, not a problem. Only loss that continues to the final hop is real.',
      related: ['sh.traceroute'],
    },
    {
      name: 'traceroute',
      task: 'see the path to a host',
      syntax: 'traceroute -T -p 443 app.example.com',
      effect: 'read',
      note: '-T uses TCP to the real port, which gets through firewalls that drop the default UDP probes — the usual reason a traceroute "stops" halfway.',
    },
    {
      name: 'tcpdump',
      task: 'capture packets to look at',
      syntax: "tcpdump -nni any -s0 -c 2000 -w /tmp/cap.pcap 'host 10.0.0.5 and port 443'",
      parameters: [
        { name: '-nn', what: 'No name or port resolution — otherwise the capture itself generates DNS traffic.' },
        { name: '-w file', what: 'Write a pcap for Wireshark instead of printing.' },
        { name: '-c', what: 'Stop after N packets, so you cannot fill the disk.' },
      ],
      effect: 'read',
      note: 'Always bound it with -c or a timeout. A tcpdump left running on a busy interface has filled the root filesystem of plenty of production machines, turning a diagnosis into an outage.',
    },
    {
      name: 'nmcli',
      task: 'configure networking persistently on RHEL-family hosts',
      syntax: "nmcli con mod ens192 ipv4.addresses 10.0.0.9/24 ipv4.gateway 10.0.0.1 ipv4.method manual && nmcli con up ens192",
      effect: 'changes',
      note: 'The change is saved on `con mod` but does not take effect until `con up`, and `con up` on the interface you are connected through will drop your session. Do it from the console, or wrap it in a scheduled revert.',
    },
    {
      name: 'ethtool',
      task: 'see link speed, duplex and driver errors',
      syntax: 'ethtool ens192 && ethtool -S ens192 | grep -iE "err|drop|discard"',
      effect: 'read',
      note: 'The -S counters are cumulative since boot, so a non-zero value is not news; take two readings a minute apart and compare. Rising rx_missed_errors is the NIC dropping because the host cannot keep up.',
    },
    {
      name: 'ping',
      task: 'check reachability',
      syntax: 'ping -c4 -W2 -M do -s 1472 10.0.0.1',
      effect: 'read',
      note: '-M do -s 1472 is the MTU test: 1472 plus 28 bytes of headers is exactly 1500, so if that fails and a smaller size works, something in the path is fragmenting. That is the usual cause of "ssh connects then freezes".',
    },
  ]),

  group('bash', 'Users, access and security', [
    {
      name: 'useradd',
      task: 'create a service or human account',
      syntax: 'useradd -r -s /usr/sbin/nologin -d /srv/app -M app',
      parameters: [
        { name: '-r', what: 'System account: low UID, no ageing.' },
        { name: '-M', what: 'Do not create the home directory.' },
      ],
      effect: 'changes',
      note: 'useradd does not create a home directory or set a shell sensibly by default on every distribution, and adduser on Debian is a different, interactive program. In a script, always name -s and -d explicitly.',
    },
    {
      name: 'usermod',
      task: 'add a user to groups',
      syntax: 'usermod -aG docker,wheel jdoe',
      effect: 'changes',
      note: 'Without -a, -G replaces every secondary group the user had, which is how people lose their own sudo access. The change also does not apply to sessions already open — they need a fresh login.',
    },
    {
      name: 'passwd',
      task: 'lock or expire an account',
      syntax: 'passwd -l jdoe && chage -E 0 jdoe',
      effect: 'changes',
      note: 'passwd -l only stops password login; SSH keys still work. Locking an account properly means the key file and the shell too, which is why offboarding scripts that only run passwd -l do not actually offboard anyone.',
      related: ['sh.chage'],
    },
    {
      name: 'chage',
      task: 'see or set password and account expiry',
      syntax: 'chage -l svc_backup',
      effect: 'read',
      note: 'Run it over service accounts before an audit: a service account with password ageing enabled will expire at some point and take an integration down at an hour nobody chose.',
    },
    {
      name: 'sudo -l',
      task: 'see what a user is allowed to run',
      syntax: 'sudo -l -U jdoe',
      effect: 'read',
      note: 'This is the real answer to "what can they do", rather than reading sudoers and its includes by eye. NOPASSWD on anything that can spawn a shell — vi, less, find, tar — is full root, and this is where you see it.',
    },
    {
      name: 'visudo',
      task: 'edit sudo rules safely',
      syntax: 'visudo -f /etc/sudoers.d/90-deploy && visudo -c',
      effect: 'changes',
      note: 'Never edit /etc/sudoers with a normal editor: one syntax error and nobody can become root on that machine again. visudo checks before saving, and a drop-in file under sudoers.d limits the damage.',
    },
    {
      name: 'ssh-keygen',
      task: 'make a key, or fix a changed host key',
      syntax: "ssh-keygen -t ed25519 -C 'deploy@ci' -f ~/.ssh/deploy_ed25519",
      effect: 'changes',
      note: 'ed25519 rather than RSA unless something old refuses it. `ssh-keygen -R host` removes a stale entry from known_hosts — but a host key that changed without a rebuild deserves an explanation before you remove it.',
    },
    {
      name: 'ssh-copy-id',
      task: 'install a public key on a remote host',
      syntax: 'ssh-copy-id -i ~/.ssh/deploy_ed25519.pub app@server',
      effect: 'changes',
      note: 'It gets the permissions right, which is the whole reason to use it: sshd silently refuses a key if ~/.ssh is group-writable, and the error on the client is just "permission denied".',
    },
    {
      name: 'openssl s_client',
      task: 'inspect a TLS certificate as served',
      syntax: 'openssl s_client -connect app.example.com:443 -servername app.example.com </dev/null 2>/dev/null | openssl x509 -noout -dates -subject -issuer',
      effect: 'read',
      note: 'Without -servername you get the default virtual host\u2019s certificate, not the one you asked about, and then spend an hour wondering why the CN is wrong. The </dev/null is what stops it hanging.',
      related: ['sh.openssl-x509'],
    },
    {
      name: 'openssl x509',
      task: 'read a certificate file',
      syntax: 'openssl x509 -in cert.pem -noout -text -fingerprint -sha256',
      effect: 'read',
      note: 'To prove a key and certificate belong together, compare `openssl x509 -noout -modulus -in cert.pem | openssl md5` with the same over the key. Mismatched pairs are the commonest cause of a service that will not start after a renewal.',
    },
    {
      name: 'getenforce',
      task: 'check SELinux mode',
      syntax: 'getenforce && ausearch -m avc -ts recent',
      effect: 'read',
      note: 'When permissions look correct and access is still denied on a RHEL-family host, this is the answer. Check the denial with ausearch before reaching for setenforce 0 — the fix is usually one semanage or restorecon, not turning it off.',
    },
    {
      name: 'firewall-cmd',
      task: 'open a port on a RHEL-family host',
      syntax: 'firewall-cmd --permanent --add-port=8443/tcp && firewall-cmd --reload',
      effect: 'changes',
      note: '--permanent writes the rule but does not apply it, and without --permanent it applies and is lost at reboot. You need both, and the --reload — this is the single most common firewalld mistake.',
      related: ['sh.ufw', 'sh.nft'],
    },
    {
      name: 'ufw',
      task: 'open a port on a Debian-family host',
      syntax: 'ufw allow from 10.0.0.0/8 to any port 22 proto tcp',
      effect: 'changes',
      note: '`ufw enable` over SSH will lock you out unless the SSH rule is already there. Add the rule, verify with `ufw show added`, then enable.',
    },
    {
      name: 'nft',
      task: 'read the real firewall ruleset',
      syntax: 'nft list ruleset',
      effect: 'read',
      note: 'On current kernels iptables is a compatibility front end over nftables, so `iptables -L` can show something different from what is actually loaded. This is the truth.',
    },
  ]),

  group('bash', 'Packages, storage and the system', [
    {
      name: 'apt',
      task: 'install or upgrade packages on Debian and Ubuntu',
      syntax: 'apt-get update && apt-get install -y --no-install-recommends nginx',
      effect: 'changes',
      note: 'Use apt-get in scripts, not apt: apt prints a warning that its interface is not stable, and its output format changes between releases. DEBIAN_FRONTEND=noninteractive stops a config prompt hanging the run forever.',
      related: ['sh.dnf'],
    },
    {
      name: 'apt-mark',
      task: 'hold a package at its current version',
      syntax: 'apt-mark hold kubelet kubeadm kubectl && apt-mark showhold',
      effect: 'changes',
      note: 'The way to stop an unattended upgrade moving a cluster component. It is also the first thing to check when an upgrade "did not apply" — a hold set a year ago and forgotten.',
    },
    {
      name: 'dnf',
      task: 'install or upgrade packages on RHEL-family hosts',
      syntax: 'dnf install -y nginx && dnf history list --reverse | tail',
      effect: 'changes',
      note: '`dnf history undo <id>` rolls back a transaction, which apt cannot do. That makes a risky upgrade on RHEL genuinely reversible if you note the transaction id before you start.',
    },
    {
      name: 'rpm -q',
      task: 'find out what owns a file, or what a package installed',
      syntax: 'rpm -qf /usr/sbin/nginx && rpm -ql nginx | head',
      effect: 'read',
      note: '`rpm -Va` verifies every installed file against the package and lists what has been modified — the fastest way to find the config someone edited by hand and did not mention.',
    },
    {
      name: 'lsblk',
      task: 'see disks, partitions and mount points',
      syntax: 'lsblk -o NAME,SIZE,FSTYPE,UUID,MOUNTPOINT,MODEL',
      effect: 'read',
      note: 'Name the columns — the default output leaves out FSTYPE and UUID, which are the two you need to write an fstab line correctly.',
      related: ['sh.blkid'],
    },
    {
      name: 'blkid',
      task: 'get the UUID of a filesystem',
      syntax: 'blkid /dev/sdb1',
      effect: 'read',
      note: 'Mount by UUID in fstab, never by /dev/sdX: device names are assigned in discovery order and change when a disk is added, which makes a machine that booted fine yesterday drop to an emergency shell today.',
    },
    {
      name: 'mount',
      task: 'mount a filesystem, or check what is mounted and how',
      syntax: 'mount -o remount,rw / && findmnt -t nfs4',
      effect: 'changes',
      note: 'After editing fstab, run `mount -a` while you are still logged in. A bad fstab line is only discovered at the next boot otherwise, and it boots to an emergency prompt that needs console access.',
      related: ['sh.findmnt'],
    },
    {
      name: 'findmnt',
      task: 'see mounts as a tree, with options',
      syntax: 'findmnt --real -o TARGET,SOURCE,FSTYPE,OPTIONS',
      effect: 'read',
      note: 'Far more readable than mount and it shows the effective options rather than what fstab asked for — which is how you discover a filesystem came up read-only after an error.',
    },
    {
      name: 'pvs',
      task: 'see LVM physical volumes, groups and logical volumes',
      syntax: 'pvs && vgs && lvs -o +lv_size,lv_path',
      effect: 'read',
      note: 'The three together answer "can I grow this": free extents in vgs is the ceiling. An LV that is already the size of the VG needs a new PV first, not a resize.',
      related: ['sh.lvextend'],
    },
    {
      name: 'lvextend',
      task: 'grow a logical volume and its filesystem',
      syntax: 'lvextend -r -L +20G /dev/mapper/vg0-lv_var',
      effect: 'changes',
      note: '-r resizes the filesystem in the same step. Without it the LV grows and df shows no change, and people then run resize2fs on an XFS filesystem, which needs xfs_growfs instead. XFS cannot be shrunk at all, ever.',
    },
    {
      name: 'smartctl',
      task: 'check a disk\u2019s health',
      syntax: 'smartctl -a /dev/sda | grep -iE "reallocated|pending|health|wear"',
      effect: 'read',
      note: 'Current_Pending_Sector above zero means sectors it cannot read and has not yet remapped — data loss that has already happened. Treat that as a replacement, not as something to watch.',
    },
    {
      name: 'dmesg',
      task: 'read kernel messages',
      syntax: 'dmesg -T --level=err,warn | tail -40',
      effect: 'read',
      note: '-T turns the seconds-since-boot into real timestamps, which is the difference between a log you can correlate and one you cannot. Look here for OOM kills, disk errors and NIC resets when an application "just died".',
    },
    {
      name: 'free',
      task: 'see memory pressure honestly',
      syntax: 'free -h --wide',
      effect: 'read',
      note: 'The column that matters is "available", not "free": Linux uses spare memory for cache and gives it back on demand. A machine with 200M free and 12G available is fine; one with 12G free and no cache has just lost something.',
    },
    {
      name: 'vmstat',
      task: 'tell CPU, memory and I/O pressure apart',
      syntax: 'vmstat 2 5',
      effect: 'read',
      note: 'Ignore the first line, which is an average since boot. High `wa` is I/O wait, non-zero `si`/`so` is swapping, and a large `b` column is processes blocked on disk — three different problems that all present as "the server is slow".',
      related: ['sh.iostat'],
    },
    {
      name: 'iostat',
      task: 'see per-device disk latency and utilisation',
      syntax: 'iostat -xz 2 5',
      effect: 'read',
      note: 'The column to read is await (milliseconds per request), not %util — on SSDs and virtualised storage %util saturates at 100 while the device is still keeping up, so it is not a useful signal.',
      availability: 'In the sysstat package.',
    },
    {
      name: 'uptime',
      task: 'see load average and how long the machine has been up',
      syntax: 'uptime && nproc',
      effect: 'read',
      note: 'Load average is only meaningful against core count, which is why nproc belongs next to it — and on Linux it counts processes blocked on disk as well as on CPU, so a high load with idle CPUs is a storage problem.',
    },
  ]),

  group('bash', 'Writing the script itself', [
    {
      name: 'set -euo pipefail',
      task: 'make the shell stop on errors instead of carrying on',
      syntax: "set -euo pipefail\nIFS=$'\\n\\t'",
      effect: 'read',
      note: 'The first line of every script worth trusting. Without pipefail, `false | tee log` succeeds; without -u, a typo in a variable name expands to an empty string and `rm -rf \"$prefix/\"` becomes `rm -rf /`.',
      related: ['sh.trap', 'sh.shellcheck'],
    },
    {
      name: 'trap',
      task: 'clean up on exit, interrupt or error',
      syntax: "tmp=$(mktemp -d)\ntrap 'rm -rf \"$tmp\"' EXIT INT TERM",
      effect: 'read',
      note: 'Trap EXIT rather than each signal separately — it runs on a normal exit too, which is the case people forget. Set the trap immediately after creating the thing it cleans up, not at the end of the script.',
    },
    {
      name: 'mktemp',
      task: 'make a temporary file or directory safely',
      syntax: 'tmp=$(mktemp -d -t myjob.XXXXXX)',
      effect: 'changes',
      note: 'A fixed name in /tmp is a symlink attack and a collision between two runs. mktemp with a trap is two lines and removes both problems.',
    },
    {
      name: 'shellcheck',
      task: 'find the bugs before running the script',
      syntax: 'shellcheck -S warning -x deploy.sh',
      effect: 'read',
      note: 'It catches the class of bug that only shows up with a filename containing a space — unquoted expansions, [ vs [[, word splitting on command substitution. Run it in CI; every one of its findings is real.',
      availability: 'Not installed by default.',
    },
    {
      name: 'getopts',
      task: 'parse script options',
      syntax: 'while getopts ":n:vh" opt; do case $opt in n) name=$OPTARG ;; v) verbose=1 ;; h) usage; exit 0 ;; *) usage; exit 2 ;; esac; done\nshift $((OPTIND - 1))',
      effect: 'read',
      note: 'It handles short options only — no --dry-run. The leading colon turns on silent error handling so you can write your own message. For long options, parse with a while/case over "$1".',
    },
    {
      name: 'read',
      task: 'read lines safely in a loop',
      syntax: 'while IFS= read -r line; do printf \'%s\\n\' "$line"; done < input.txt',
      effect: 'read',
      note: '`IFS= read -r` is one idiom, not two options: without IFS= it strips leading whitespace, and without -r it eats backslashes. A loop over `for line in $(cat file)` splits on spaces and is always wrong.',
    },
    {
      name: 'printf',
      task: 'output predictably',
      syntax: "printf '%-20s %s\\n' \"$name\" \"$value\"",
      effect: 'read',
      note: 'Use it instead of echo in anything portable: echo -e and echo -n behave differently between shells and between /bin/echo and the builtin. printf is specified and does the same thing everywhere.',
    },
    {
      name: 'declare -A',
      task: 'use an associative array',
      syntax: "declare -A env_url=( [dev]=https://dev.example.com [prod]=https://example.com )\necho \"${env_url[prod]}\"",
      effect: 'read',
      note: 'Bash 4 and later, which means not the /bin/bash shipped with macOS. A script that uses these and starts with #!/bin/sh will fail on dash with a confusing syntax error.',
    },
    {
      name: 'mapfile',
      task: 'read a file into an array',
      syntax: 'mapfile -t servers < servers.txt\nprintf \'%s\\n\' "${servers[@]}"',
      effect: 'read',
      note: '-t strips the trailing newline from each element, which you always want. "${arr[@]}" in quotes preserves elements with spaces; "${arr[*]}" joins them into one string.',
    },
    {
      name: 'flock',
      task: 'stop two copies of a script running at once',
      syntax: 'flock -n /var/lock/myjob.lock -c "/usr/local/bin/myjob.sh" || exit 0',
      effect: 'changes',
      note: 'The right fix for a cron job that occasionally takes longer than its interval and then two of them fight. -n makes the second one exit rather than queue, which is usually what is wanted.',
    },
    {
      name: 'logger',
      task: 'write to the system log from a script',
      syntax: 'logger -t myjob -p local0.info "completed in ${secs}s"',
      effect: 'changes',
      note: 'Better than a private log file: it is timestamped, rotated, and forwarded to wherever the rest of the logs go. -t tags it so journalctl -t myjob finds it.',
    },
    {
      name: 'envsubst',
      task: 'fill variables into a template file',
      syntax: "envsubst '\\$HOST \\$PORT' < config.template > /etc/app/config",
      effect: 'changes',
      note: 'Name the variables to substitute. Without that list it replaces every $-something in the file, which destroys nginx configs, regexes and anything with a shell snippet in it.',
    },
    {
      name: 'date',
      task: 'produce a timestamp that sorts',
      syntax: 'date -u +%Y-%m-%dT%H:%M:%SZ && date -d @1735689600 +%F',
      effect: 'read',
      note: 'Use %F (or the full ISO form) in filenames so they sort chronologically, and UTC on anything that crosses machines. `date -d @epoch` converts a Unix timestamp, which is what half of log correlation is.',
    },
  ]),

  group('bash', 'Containers and remote work', [
    {
      name: 'docker ps',
      task: 'see running containers with the fields you want',
      syntax: "docker ps -a --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'",
      effect: 'read',
      note: '-a is the important half: a container that exited two minutes ago is invisible without it, and that is exactly the one you are looking for.',
      related: ['sh.docker-logs'],
    },
    {
      name: 'docker logs',
      task: 'read a container\u2019s output',
      syntax: 'docker logs --since 15m --timestamps -f app',
      effect: 'read',
      note: 'Only stdout and stderr of PID 1 are here. An application that writes to a file inside the container shows nothing, which is why "no logs" usually means the logging config, not the container.',
    },
    {
      name: 'docker exec',
      task: 'get a shell inside a running container',
      syntax: 'docker exec -it app sh -c "ps -ef; ls -l /app"',
      effect: 'changes',
      note: 'Many images have no bash — use sh. Nothing you change this way survives a restart, so it is for looking, and a fix applied here will vanish at the next deploy and take the explanation with it.',
    },
    {
      name: 'docker stats',
      task: 'see container CPU and memory against their limits',
      syntax: 'docker stats --no-stream',
      effect: 'read',
      note: '--no-stream makes it scriptable. A container sitting at exactly its memory limit is about to be OOM-killed, and that shows as an unexplained restart with exit code 137.',
    },
    {
      name: 'docker system prune',
      task: 'reclaim disk from images, containers and volumes',
      syntax: 'docker system df && docker system prune -a --filter "until=168h"',
      effect: 'destructive',
      note: 'Without --filter, -a removes every image not currently in use, including ones you cannot pull again. Add --volumes only when you are certain: that is where the databases are.',
    },
    {
      name: 'kubectl get',
      task: 'list Kubernetes objects with detail',
      syntax: 'kubectl get pods -A -o wide --sort-by=.status.startTime | tail -20',
      effect: 'read',
      note: '-o wide adds node and IP, which is what most questions need. Without --sort-by the order is arbitrary, and the pod that just restarted is not where you expect it.',
      related: ['sh.kubectl-describe', 'sh.kubectl-logs'],
    },
    {
      name: 'kubectl describe',
      task: 'find out why a pod is not running',
      syntax: 'kubectl describe pod app-7d9f -n prod',
      effect: 'read',
      note: 'The Events at the bottom are the answer, not the spec at the top — ImagePullBackOff, FailedScheduling with the reason, or a failing probe. Events are dropped after an hour, so a pod stuck since yesterday may show none.',
    },
    {
      name: 'kubectl logs',
      task: 'read a pod\u2019s logs, including the previous crash',
      syntax: 'kubectl logs -n prod deploy/app -c app --previous --tail=200',
      effect: 'read',
      note: '--previous is the whole point in a crash loop: the current container has just started and has nothing to say. Name the container with -c when the pod has a sidecar, or it picks one for you.',
    },
    {
      name: 'ssh',
      task: 'run a command on a remote host',
      syntax: "ssh -o BatchMode=yes -o ConnectTimeout=5 app@server 'systemctl is-active nginx'",
      effect: 'changes',
      note: 'BatchMode=yes makes it fail instead of prompting for a password, which is what you want in a script — otherwise a key problem presents as a job that hangs forever with no output.',
    },
    {
      name: 'scp',
      task: 'copy a file to or from a remote host',
      syntax: 'scp -p -o ConnectTimeout=5 ./config.yaml app@server:/srv/app/',
      effect: 'changes',
      note: 'Fine for one file; for anything repeated use rsync, which only sends changes and can resume. Recent OpenSSH switched scp to the SFTP protocol underneath, which changed how some wildcards behave.',
    },
    {
      name: 'tmux',
      task: 'keep a long job alive across a dropped connection',
      syntax: 'tmux new -As maint',
      effect: 'changes',
      note: 'new -As attaches if the session exists and creates it if not, so it is safe to run the same command every time. Start anything longer than a coffee inside one — a dropped VPN during a migration is otherwise a corrupted run.',
    },
  ]),
];
