/**
 * The Windows command line catalogue.
 *
 * cmd is not a language anyone chooses any more, and it is still what runs in a
 * task sequence, a logon script, a golden-image build step, a WinPE prompt and
 * the recovery console — the places where PowerShell is not there yet or not
 * there at all. That is what this covers: the commands you reach for when the
 * machine is half built or half broken.
 *
 * Batch has its own set of traps that nothing warns you about — delayed
 * expansion inside a for loop, the difference between %%i in a file and %i at
 * the prompt, an errorlevel that only some commands set. Those are the notes.
 */

import { group,                   } from './catalog.js';

export const CMD_CATALOG                          = [
  group('cmd', 'Batch language and flow', [
    {
      name: 'setlocal enabledelayedexpansion',
      task: 'make variables set inside a loop readable inside the same loop',
      syntax: 'setlocal enabledelayedexpansion\nfor %%f in (*.log) do (\n  set "name=%%~nf"\n  echo !name!\n)',
      effect: 'read',
      note: 'The single biggest batch trap. %var% is substituted when the whole block is parsed, so inside a for or if block it holds the value from before the loop started. !var! reads it at the moment the line runs, and needs this on.',
      related: ['cmd.for-f', 'cmd.endlocal'],
    },
    {
      name: 'endlocal',
      task: 'discard variables set by the script, or pass one back out',
      syntax: 'endlocal & set "RESULT=%RESULT%"',
      effect: 'read',
      note: 'setlocal without endlocal is fine — it ends at the end of the script — but nothing set inside survives. That `endlocal & set` idiom is the only way to return a value to the caller.',
    },
    {
      name: 'for /f',
      task: 'loop over the lines of a file or the output of a command',
      syntax: 'for /f "usebackq skip=1 tokens=1,3 delims=," %%a in ("data.csv") do @echo %%a %%b',
      parameters: [
        { name: 'usebackq', what: 'Lets you quote a path with spaces and run a command in backticks.' },
        { name: 'tokens=1,3', what: 'Which fields. The first goes in %%a, the next in %%b, not %%c.' },
        { name: 'skip=1', what: 'Drop the header line.' },
      ],
      effect: 'read',
      note: 'The variable is %%a in a file and %a at the prompt — a line copied from a working script fails interactively and vice versa, with an unhelpful error. Tokens land in consecutive letters regardless of their numbers.',
      related: ['cmd.setlocal-enabledelayedexpansion'],
    },
    {
      name: 'for /r',
      task: 'walk a directory tree',
      syntax: 'for /r "C:\\Logs" %%f in (*.log) do @if %%~zf gtr 10000000 echo %%~ff %%~zf',
      effect: 'read',
      note: 'The ~ modifiers are where the power is: %%~nf is the name, %%~xf the extension, %%~zf the size, %%~tf the timestamp, %%~ff the full path, %%~dpf the drive and folder. There is no other way to get these in batch.',
    },
    {
      name: 'if errorlevel',
      task: 'branch on whether the previous command failed',
      syntax: 'robocopy A B /E\nif %errorlevel% geq 8 (echo FAILED & exit /b 1)',
      effect: 'read',
      note: '`if errorlevel 1` means "1 or greater", not "equal to 1" — and internal commands like copy and set often do not set it at all. Prefer `if %errorlevel% neq 0`, and remember robocopy treats anything under 8 as success.',
      related: ['cmd.robocopy', 'cmd.exit-b'],
    },
    {
      name: 'exit /b',
      task: 'return a code from a script or a subroutine',
      syntax: 'exit /b 0',
      effect: 'read',
      note: 'Without /b it closes the whole console window, which in a task sequence or a wrapped installer looks like a crash. /b returns from the script; the code is what the caller reads.',
    },
    {
      name: 'call',
      task: 'run another batch file or a subroutine and come back',
      syntax: 'call :deploy "%target%"\ngoto :eof\n\n:deploy\necho deploying %~1\ngoto :eof',
      effect: 'changes',
      note: 'Without call, running another .bat hands control over and never returns — the rest of your script simply does not run, with no error. %~1 strips the quotes from an argument, which is nearly always what you want.',
    },
    {
      name: 'set /a',
      task: 'do arithmetic',
      syntax: 'set /a "gb=%bytes% / 1024 / 1024 / 1024"',
      effect: 'read',
      note: 'Integers only, and a number with a leading zero is read as octal — so 08 and 09 are errors, which bites anything parsing a date or a time.',
    },
    {
      name: 'set "var=value"',
      task: 'set a variable without picking up stray spaces',
      syntax: 'set "path_to_log=C:\\Program Files\\App\\app.log"',
      effect: 'read',
      note: 'Quote the whole assignment, not the value. `set var= value` stores a leading space and `set var=value ` a trailing one, and both cause comparisons and paths to fail in ways that are invisible on screen.',
    },
    {
      name: 'pushd',
      task: 'change directory, including onto a UNC path',
      syntax: 'pushd "\\\\server\\share\\folder" && dir && popd',
      effect: 'changes',
      note: 'cd cannot go to a UNC path at all; pushd maps a temporary drive letter and popd releases it. That is the standard way to work against a share from a batch file.',
    },
    {
      name: 'timeout',
      task: 'wait, without blocking on a keypress',
      syntax: 'timeout /t 30 /nobreak > nul',
      effect: 'read',
      note: 'Without /nobreak any key ends the wait, and in a service or task-sequence context with no console timeout fails outright — `ping -n 31 127.0.0.1 > nul` is the ugly fallback that always works.',
    },
    {
      name: 'start',
      task: 'launch a program, waiting or not',
      syntax: 'start "" /wait /b "setup.exe" /quiet /norestart',
      effect: 'changes',
      note: 'The empty "" is the window title, and leaving it out makes start treat your quoted program path as the title and fail. /wait is what makes an installer finish before the next line runs.',
    },
  ]),

  group('cmd', 'Files and copying', [
    {
      name: 'robocopy',
      task: 'copy or mirror folders reliably',
      syntax: 'robocopy "D:\\Data" "\\\\nas\\data" /E /COPY:DAT /R:2 /W:5 /MT:16 /LOG+:C:\\Logs\\copy.log /TEE',
      parameters: [
        { name: '/E', what: 'Subdirectories including empty ones.' },
        { name: '/MIR', what: 'Mirror — deletes at the destination. Dangerous; see the note.' },
        { name: '/R:2 /W:5', what: 'Two retries, five seconds apart. The default is a million retries at 30s.' },
        { name: '/L', what: 'List only. The dry run.' },
      ],
      effect: 'changes',
      note: '/MIR deletes anything at the destination that is not at the source, so a mistyped source path empties the destination. Always run it once with /L first. Exit codes under 8 are success, which breaks naive error checks.',
      related: ['cmd.if-errorlevel', 'cmd.xcopy'],
    },
    {
      name: 'xcopy',
      task: 'the older copy, still used in build steps',
      syntax: 'xcopy "src\\*" "dst\\" /E /I /Y /H',
      effect: 'changes',
      deprecated: 'robocopy, which retries, logs and resumes',
      note: '/I is what stops it stopping to ask whether the destination is a file or a directory — the usual reason an unattended build hangs with no output.',
    },
    {
      name: 'icacls',
      task: 'read or set NTFS permissions',
      syntax: 'icacls "C:\\App" /grant "DOMAIN\\AppSvc:(OI)(CI)(M)" /T /C',
      parameters: [
        { name: '(OI)(CI)', what: 'Inherit to files and to subfolders. Without them the grant applies to that folder only.' },
        { name: '/T', what: 'Recurse.' },
        { name: '/C', what: 'Continue past errors.' },
      ],
      effect: 'changes',
      note: 'Save the current state with `icacls C:\\App /save acl.txt /T` before changing anything — /restore puts it back, and it is the only practical undo for a recursive permission change.',
      related: ['cmd.takeown'],
    },
    {
      name: 'takeown',
      task: 'take ownership of files you cannot otherwise touch',
      syntax: 'takeown /F "C:\\Windows\\System32\\drivers\\etc\\hosts" /A',
      effect: 'changes',
      note: 'Ownership is not permission: after takeown you still need icacls to grant access. /A gives it to Administrators rather than to you personally, which is what you want on a shared server.',
    },
    {
      name: 'attrib',
      task: 'see or clear hidden, system and read-only flags',
      syntax: 'attrib -h -s -r "D:\\folder\\*" /S /D',
      effect: 'changes',
      note: 'A folder that "will not delete" and files that are "missing" from a share are usually hidden+system. /D is needed for directories; without it only files are touched.',
    },
    {
      name: 'fsutil',
      task: 'query volumes, reservations and file details',
      syntax: 'fsutil volume diskfree C: && fsutil fsinfo ntfsinfo C:',
      effect: 'read',
      note: '`fsutil dirty query C:` tells you whether the volume is flagged for a chkdsk at next boot — worth knowing before a reboot window rather than during one.',
    },
    {
      name: 'compact',
      task: 'compress files in place on NTFS',
      syntax: 'compact /C /S /I /EXE:LZX "D:\\Archive"',
      effect: 'changes',
      note: 'The quickest way to buy space on a full volume without deleting anything. LZX compresses hardest and costs CPU on read; do not use it on an active database or a VHD.',
    },
    {
      name: 'where',
      task: 'find which executable will actually run',
      syntax: 'where python && where /R C:\\ nginx.exe',
      effect: 'read',
      note: 'The Windows `which`. When a command behaves like the wrong version, this is the answer — usually a shim or an older copy earlier in PATH.',
    },
    {
      name: 'mklink',
      task: 'make a symbolic or directory junction link',
      syntax: 'mklink /J "C:\\App\\current" "C:\\App\\releases\\2026-09-01"',
      effect: 'changes',
      note: '/J makes a junction, which needs no special privilege and works for local directories; /D makes a real symlink and requires administrator or developer mode. Use /J unless the target is a network path.',
    },
  ]),

  group('cmd', 'System, services and processes', [
    {
      name: 'sc query',
      task: 'see a service\u2019s state and start type',
      syntax: 'sc query "Spooler" && sc qc "Spooler"',
      effect: 'read',
      note: 'The space after the equals in `sc config Name start= auto` is mandatory and there must be none before it — `start=auto` fails with a usage message that does not explain why.',
      related: ['cmd.sc-config'],
    },
    {
      name: 'sc config',
      task: 'change a service\u2019s start type or account',
      syntax: 'sc config "MyApp" start= delayed-auto obj= "NT SERVICE\\MyApp"',
      effect: 'changes',
      note: 'delayed-auto keeps a heavy service from competing with everything else at boot, which often fixes a service that fails on startup and starts fine by hand. Changing obj= does not grant "log on as a service" — that is a separate right.',
    },
    {
      name: 'net start',
      task: 'start or stop a service, or list running ones',
      syntax: 'net stop "MyApp" && net start "MyApp"',
      effect: 'changes',
      note: 'net stop fails if other services depend on it and gives up rather than asking; `sc stop` plus a wait loop, or net stop /y, is what a script needs. It also blocks forever if the service prompts.',
    },
    {
      name: 'tasklist',
      task: 'list processes, including on another machine',
      syntax: 'tasklist /svc /fi "MEMUSAGE gt 500000" /fo table',
      effect: 'read',
      note: '/svc maps services to the svchost process hosting them, which is the only way to tell which of eight identical svchost entries is the one using the CPU.',
      related: ['cmd.taskkill'],
    },
    {
      name: 'taskkill',
      task: 'end a process',
      syntax: 'taskkill /IM "app.exe" /T',
      effect: 'destructive',
      note: '/F is a hard kill with no cleanup — try without it first, and add /T so child processes go too rather than being orphaned. Without /T you kill the launcher and the real work carries on.',
    },
    {
      name: 'schtasks',
      task: 'create, query or run a scheduled task',
      syntax: 'schtasks /Create /TN "Nightly Report" /TR "\\"C:\\Scripts\\report.cmd\\"" /SC DAILY /ST 02:30 /RU "SYSTEM" /RL HIGHEST',
      effect: 'changes',
      note: 'The quoting is the whole difficulty: the command inside /TR needs its own escaped quotes when the path has spaces. Build it once, then export with /XML and create from that file everywhere else.',
    },
    {
      name: 'shutdown',
      task: 'restart or shut down, now or later, with a reason',
      syntax: 'shutdown /r /t 300 /c "Patching window" /d p:2:4',
      effect: 'destructive',
      note: '`shutdown /a` cancels a pending one, but only during the countdown — which is why /t with a few minutes on it is worth having even when you mean now. /d records a reason in the event log for the audit afterwards.',
    },
    {
      name: 'systeminfo',
      task: 'get OS build, uptime, patches and memory in one call',
      syntax: 'systeminfo | findstr /C:"OS Version" /C:"System Boot Time" /C:"Total Physical Memory"',
      effect: 'read',
      note: 'It is slow — ten seconds or more — because it queries hotfixes and the domain. For just the build number, `ver` or the registry is instant.',
    },
    {
      name: 'wmic',
      task: 'query almost any system object from a batch file',
      syntax: 'wmic logicaldisk where "DriveType=3" get DeviceID,FreeSpace,Size /format:csv',
      effect: 'read',
      deprecated: 'PowerShell Get-CimInstance; wmic is removed from current Windows builds',
      note: 'Deprecated and being removed, so anything new should use PowerShell — but it is still the only one-liner that works in WinPE and in old task sequences, which is why it is here.',
    },
    {
      name: 'reg query',
      task: 'read the registry',
      syntax: 'reg query "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion" /v DisplayVersion',
      effect: 'read',
      note: 'A 32-bit process reads the WOW6432Node view without saying so. Add /reg:64 when a script run by an old tool cannot find a key that is plainly there.',
      related: ['cmd.reg-add'],
    },
    {
      name: 'reg add',
      task: 'write a registry value',
      syntax: 'reg add "HKLM\\SOFTWARE\\Contoso" /v Mode /t REG_DWORD /d 1 /f',
      effect: 'changes',
      note: 'Export the key first with `reg export` — that file is your undo. /f suppresses the prompt, which unattended runs need and which also removes the last chance to notice a wrong path.',
    },
    {
      name: 'powercfg',
      task: 'see and fix power settings, or find what is waking the machine',
      syntax: 'powercfg /lastwake && powercfg /requests && powercfg /change standby-timeout-ac 0',
      effect: 'changes',
      note: '/requests names the process holding the machine awake, and /lastwake explains a server that reboots or resumes at odd hours. On servers, USB selective suspend is a surprisingly common cause of a dropped NIC.',
    },
    {
      name: 'bcdedit',
      task: 'read or change boot configuration',
      syntax: 'bcdedit /enum && bcdedit /set {current} safeboot minimal',
      effect: 'destructive',
      note: 'Export first with `bcdedit /export C:\\bcd.bak`. A wrong value here produces a machine that does not boot and needs console or recovery media — there is no remote fix.',
    },
  ]),

  group('cmd', 'Networking and domain', [
    {
      name: 'ipconfig',
      task: 'see addresses, or clear the DNS cache',
      syntax: 'ipconfig /all && ipconfig /flushdns && ipconfig /registerdns',
      effect: 'changes',
      note: '/registerdns forces the host to re-register its A record, which fixes a stale entry after a rename or an address change without waiting for the refresh interval.',
    },
    {
      name: 'nslookup',
      task: 'query DNS from Windows',
      syntax: 'nslookup -type=SRV _ldap._tcp.dc._msdcs.example.com 10.0.0.10',
      effect: 'read',
      note: 'That SRV query is the domain-join diagnostic: if it returns nothing, the client cannot find a domain controller, and no amount of retrying the join will help until DNS does.',
    },
    {
      name: 'netsh interface ip',
      task: 'set a static address from the command line',
      syntax: 'netsh interface ip set address name="Ethernet" static 10.0.0.9 255.255.255.0 10.0.0.1',
      effect: 'changes',
      note: 'It takes effect immediately, so running it over RDP on the interface you are connected through ends the session mid-command. Do it from the console or wrap it in a scheduled revert.',
      related: ['cmd.netsh-advfirewall'],
    },
    {
      name: 'netsh advfirewall',
      task: 'add a firewall rule',
      syntax: 'netsh advfirewall firewall add rule name="App 8443" dir=in action=allow protocol=TCP localport=8443 profile=domain',
      effect: 'changes',
      note: 'Without profile= the rule applies to all three profiles including Public, which is more exposure than intended. Check what is actually blocking with `netsh advfirewall monitor show firewall`.',
    },
    {
      name: 'netstat',
      task: 'see listening ports and which process owns them',
      syntax: 'netstat -ano | findstr LISTENING',
      effect: 'read',
      note: '-b names the executable but needs administrator and is slow; -ano gives the PID instantly and `tasklist /fi "PID eq 1234"` turns it into a name. That pair is the standard "what is on port 443" answer.',
    },
    {
      name: 'nltest',
      task: 'test the secure channel and find domain controllers',
      syntax: 'nltest /sc_query:example.com && nltest /dsgetdc:example.com',
      effect: 'read',
      note: 'A broken secure channel is the cause of "the trust relationship between this workstation and the primary domain failed". `nltest /sc_reset` often fixes it without a rejoin, which saves rebuilding the machine account.',
    },
    {
      name: 'gpresult',
      task: 'see which Group Policies actually applied',
      syntax: 'gpresult /h C:\\Temp\\gpo.html /f && gpresult /r /scope:computer',
      effect: 'read',
      note: 'The HTML report shows denied policies and the reason, which /r does not. Run it as the affected user for user policy — as an administrator you get your own, and then conclude the policy is not applying when it is.',
    },
    {
      name: 'gpupdate',
      task: 'reapply policy now',
      syntax: 'gpupdate /force /wait:180',
      effect: 'changes',
      note: '/force reapplies everything rather than only what changed, which is the point but is also heavy on a slow link. Some settings — drive maps, software installation — still only apply at logon or boot, so a reboot may still be needed.',
    },
    {
      name: 'klist',
      task: 'see or clear Kerberos tickets',
      syntax: 'klist && klist purge',
      effect: 'changes',
      note: 'After adding a user to a group, their token keeps the old membership until the ticket is renewed. `klist purge` and a new logon is how you test the change now rather than tomorrow.',
    },
    {
      name: 'whoami',
      task: 'see the current account, its groups and its privileges',
      syntax: 'whoami /all',
      effect: 'read',
      note: '/priv shows whether a privilege is Enabled or merely present, which is how you tell an elevated prompt from an administrator account that is not elevated — they look identical otherwise.',
    },
    {
      name: 'net use',
      task: 'map or list network drives',
      syntax: 'net use Z: "\\\\server\\share" /persistent:no',
      effect: 'changes',
      note: 'A drive mapped in an elevated prompt is invisible to non-elevated programs and vice versa — the usual reason a script "cannot find" a drive the user can see. Never put a password on this line; it goes into the command history.',
    },
    {
      name: 'net localgroup',
      task: 'add a domain account to a local group',
      syntax: 'net localgroup "Administrators" "DOMAIN\\ServerAdmins" /add',
      effect: 'changes',
      note: 'Works offline against the local SAM, which is why it is still in build scripts. It cannot see group nesting, so `net localgroup Administrators` lists the group, not the people in it.',
    },
  ]),

  group('cmd', 'Images, repair and recovery', [
    {
      name: 'dism',
      task: 'repair the component store or service an image',
      syntax: 'dism /Online /Cleanup-Image /RestoreHealth /Source:WIM:D:\\sources\\install.wim:1 /LimitAccess',
      effect: 'changes',
      note: 'RestoreHealth reaches out to Windows Update by default and fails on an isolated machine; /Source with /LimitAccess points it at media instead. Run this before sfc, not after — sfc repairs from the store dism just fixed.',
      related: ['cmd.sfc'],
    },
    {
      name: 'sfc',
      task: 'check and repair protected system files',
      syntax: 'sfc /scannow',
      effect: 'changes',
      note: 'It repairs from the component store, so if that is corrupt it reports failures it cannot fix — which is why dism comes first. The detail is in CBS.log, not on screen.',
    },
    {
      name: 'chkdsk',
      task: 'check a volume for filesystem errors',
      syntax: 'chkdsk D: /scan /perf',
      effect: 'changes',
      note: '/scan runs online on NTFS and does not need a reboot; /f locks the volume and schedules a boot-time run that can take hours on a large disk with no progress anyone can see. Use /scan first.',
    },
    {
      name: 'diskpart',
      task: 'partition and format from a command line',
      syntax: 'echo list disk | diskpart',
      effect: 'destructive',
      note: 'There is no confirmation and no undo: `select disk 1` followed by `clean` destroys a disk in under a second, and the disk numbers change between boots. Always `list disk` and check the size before selecting anything.',
    },
    {
      name: 'bootrec',
      task: 'rebuild boot records from recovery media',
      syntax: 'bootrec /fixmbr && bootrec /fixboot && bootrec /rebuildbcd',
      effect: 'destructive',
      note: 'On a UEFI machine /fixmbr does nothing useful and /fixboot often returns access denied — the UEFI repair is bcdboot against the EFI partition instead. Knowing which firmware mode the machine is in comes first.',
    },
    {
      name: 'wbadmin',
      task: 'back up or restore a volume or system state',
      syntax: 'wbadmin start backup -backupTarget:E: -include:C: -allCritical -quiet',
      effect: 'changes',
      note: '-allCritical is what makes the backup bootable; without it you have the files but cannot restore the system. Check with `wbadmin get versions` afterwards — a backup nobody has listed is not a backup.',
    },
    {
      name: 'vssadmin',
      task: 'see shadow copies and how much space they use',
      syntax: 'vssadmin list shadowstorage && vssadmin list writers',
      effect: 'read',
      note: '`list writers` showing a writer in a failed state explains a backup that fails with no other clue; restarting that writer\u2019s service usually clears it. Never delete shadows on a server that is running a backup.',
    },
    {
      name: 'manage-bde',
      task: 'check or unlock BitLocker from the command line',
      syntax: 'manage-bde -status C: && manage-bde -protectors -get C:',
      effect: 'read',
      note: '-protectors -get prints the recovery key id, which is what you match against the copy in AD or Entra. Suspend rather than decrypt before a firmware update: `manage-bde -protectors -disable C: -rebootcount 1`.',
    },
    {
      name: 'slmgr',
      task: 'check or set Windows licensing',
      syntax: 'cscript //nologo C:\\Windows\\System32\\slmgr.vbs /dlv',
      effect: 'read',
      note: 'Call it through cscript //nologo in a script — run bare, it pops a dialog box and waits for someone to click OK, which in an unattended build means the job simply never finishes.',
    },
    {
      name: 'findstr',
      task: 'search text from a batch file',
      syntax: 'findstr /I /S /C:"connection refused" "C:\\Logs\\*.log"',
      effect: 'read',
      note: '/C: makes the search a literal string; without it, spaces separate several search terms and it matches any of them. Its regex support is not the one you know — use PowerShell for anything beyond a literal.',
    },
  ]),
];
