/**
 * The Python catalogue.
 *
 * Python's own documentation is good, which changes what is worth writing here.
 * The entries that earn their place are the ones where the obvious call is
 * subtly wrong: `requests.get` with no timeout hangs forever, `os.path.join`
 * throws away everything before an absolute component, `datetime.utcnow()`
 * returns a naive datetime that claims to be local, `yaml.load` executes what
 * it reads.
 *
 * So this leans towards the standard library and the four or five packages that
 * are on every infrastructure box, and every note is the failure mode rather
 * than the signature.
 */

import { group,                   } from './catalog.js';

export const PYTHON_CATALOG                          = [
  group('python', 'Files and paths', [
    {
      name: 'pathlib.Path',
      task: 'build, join and test paths',
      syntax: "from pathlib import Path\np = Path('/srv/app') / 'config' / 'app.yaml'\nif p.is_file():\n    text = p.read_text(encoding='utf-8')",
      effect: 'read',
      note: 'The / operator discards everything to its left if the right side is absolute, exactly as os.path.join does — so joining a path with user input can silently escape the directory you meant. Check with p.resolve().is_relative_to(base).',
      related: ['py.path-glob', 'py.shutil'],
    },
    {
      name: 'Path.glob',
      task: 'find files by pattern, recursively',
      syntax: "for log in sorted(Path('/var/log').rglob('*.log')):\n    print(log, log.stat().st_size)",
      effect: 'read',
      note: 'glob returns a generator, so `if not p.glob("*")` is always False — it is testing the generator object, not its contents. Wrap it in list() or any() before testing.',
    },
    {
      name: 'shutil',
      task: 'copy, move or delete trees, and check free space',
      syntax: "import shutil\nshutil.copy2(src, dst)\ntotal, used, free = shutil.disk_usage('/var')",
      effect: 'changes',
      note: 'copy2 keeps the timestamps and copy does not, which matters for anything incremental. shutil.rmtree has no confirmation and no undo — guard it with a resolved-path check against a base directory.',
    },
    {
      name: 'tempfile',
      task: 'make a temporary file or directory that cleans itself up',
      syntax: "import tempfile\nwith tempfile.TemporaryDirectory() as tmp:\n    work = Path(tmp) / 'out.csv'",
      effect: 'changes',
      note: 'NamedTemporaryFile on Windows cannot be reopened by name while it is still open, which is why code that works on Linux fails there with a permission error. Use delete=False and remove it yourself, or use a directory.',
    },
    {
      name: 'open',
      task: 'read or write a text file without encoding surprises',
      syntax: "with open(path, 'w', encoding='utf-8', newline='') as fh:\n    fh.write(text)",
      effect: 'changes',
      note: 'Without encoding= Python uses the platform default, which on Windows is still cp1252 — so a script that reads UTF-8 fine on Linux raises UnicodeDecodeError there. Always name the encoding.',
    },
    {
      name: 'os.replace',
      task: 'replace a file atomically',
      syntax: "tmp = path.with_suffix('.tmp')\ntmp.write_text(new_text, encoding='utf-8')\nos.replace(tmp, path)",
      effect: 'changes',
      note: 'Write to a temporary file in the same directory and then replace. Writing in place means a crash halfway leaves a truncated config — and os.rename fails across devices where os.replace on the same filesystem does not.',
    },
    {
      name: 'fnmatch',
      task: 'match a filename against a shell-style pattern',
      syntax: "from fnmatch import fnmatch\nif fnmatch(name, '*.bak'):\n    ...",
      effect: 'read',
      note: 'It is case-insensitive on Windows and case-sensitive on Linux, because it follows the platform. fnmatchcase is the one that behaves the same everywhere, which is what a test or a rules file wants.',
    },
    {
      name: 'zipfile',
      task: 'read or write a zip archive',
      syntax: "import zipfile\nwith zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED) as z:\n    for f in files:\n        z.write(f, arcname=f.name)",
      effect: 'changes',
      note: 'Without arcname the full absolute path goes into the archive. Never extractall() an archive you did not create: a crafted entry with ../ in its name writes outside the target directory.',
    },
  ]),

  group('python', 'Data, text and structure', [
    {
      name: 'csv.DictReader',
      task: 'read a CSV by column name',
      syntax: "import csv\nwith open(path, newline='', encoding='utf-8-sig') as fh:\n    for row in csv.DictReader(fh):\n        print(row['Name'])",
      effect: 'read',
      note: "newline='' is required — without it, quoted fields containing line breaks are split into extra rows. utf-8-sig quietly strips the byte-order mark Excel writes, which otherwise makes the first column name unmatchable.",
      related: ['py.csv-dictwriter', 'py.pandas-read-csv'],
    },
    {
      name: 'csv.DictWriter',
      task: 'write a CSV with a header',
      syntax: "with open(out, 'w', newline='', encoding='utf-8') as fh:\n    w = csv.DictWriter(fh, fieldnames=cols, extrasaction='ignore')\n    w.writeheader()\n    w.writerows(rows)",
      effect: 'changes',
      note: 'A key in a row that is not in fieldnames raises unless you pass extrasaction="ignore"; a field missing from a row is written as empty, silently. Those two defaults are opposites, which catches people out.',
    },
    {
      name: 'json.dumps',
      task: 'write JSON that a human or a diff can read',
      syntax: "json.dumps(data, indent=2, sort_keys=True, default=str)",
      effect: 'read',
      note: 'default=str is what stops it dying on a datetime, Decimal or Path. sort_keys makes two dumps of the same data comparable, which is the difference between a useful diff and noise.',
      related: ['py.json-load'],
    },
    {
      name: 'json.load',
      task: 'read JSON from a file or a response',
      syntax: "with open(path, encoding='utf-8') as fh:\n    data = json.load(fh)",
      effect: 'read',
      note: 'It raises JSONDecodeError on empty input, which is what an HTTP 204 or a truncated download gives you. Catch it separately from the network error — they need different responses.',
    },
    {
      name: 'yaml.safe_load',
      task: 'read a YAML file safely',
      syntax: "import yaml\ndata = yaml.safe_load(Path('config.yaml').read_text(encoding='utf-8'))",
      module: 'PyYAML',
      effect: 'read',
      note: 'Never yaml.load without a loader: it can construct arbitrary Python objects from the file, which is remote code execution when the file is not yours. Also, unquoted `no`, `off` and `yes` become booleans, which is how a country code NO becomes False.',
    },
    {
      name: 'configparser',
      task: 'read an INI file',
      syntax: "import configparser\ncfg = configparser.ConfigParser(interpolation=None)\ncfg.read(path, encoding='utf-8')\nport = cfg.getint('server', 'port', fallback=8080)",
      effect: 'read',
      note: 'Interpolation is on by default, so a literal % in a password or a path raises an error that reads like a syntax problem in the file. Pass interpolation=None unless you are using it.',
    },
    {
      name: 'collections.defaultdict',
      task: 'group or count without checking for the key first',
      syntax: "from collections import defaultdict\nby_owner = defaultdict(list)\nfor vm in vms:\n    by_owner[vm['owner']].append(vm['name'])",
      effect: 'read',
      note: 'Reading a missing key creates it, so a typo in a lookup silently adds an empty entry rather than raising. Convert to a plain dict before returning it, or a later `in` test will lie.',
      related: ['py.collections-counter'],
    },
    {
      name: 'collections.Counter',
      task: 'count occurrences and get the top N',
      syntax: "from collections import Counter\nCounter(e['source'] for e in events).most_common(10)",
      effect: 'read',
      note: 'The whole "sort | uniq -c | sort -rn | head" pipeline in one line, and it takes a generator so it does not build the list first.',
    },
    {
      name: 're.compile',
      task: 'match or extract with a regular expression',
      syntax: "import re\npat = re.compile(r'^(?P<ts>\\S+)\\s+(?P<level>WARN|ERROR)\\s+(?P<msg>.*)$')\nm = pat.match(line)\nif m:\n    print(m['level'], m['msg'])",
      effect: 'read',
      note: 'match anchors at the start, search does not, fullmatch requires the whole string — picking the wrong one is most regex "bugs". Always use a raw string, or \\d becomes an escape Python warns about and then changes.',
    },
    {
      name: 'datetime.now(timezone.utc)',
      task: 'get the current time correctly',
      syntax: "from datetime import datetime, timezone\nnow = datetime.now(timezone.utc)\nstamp = now.strftime('%Y-%m-%dT%H:%M:%SZ')",
      effect: 'read',
      note: 'datetime.utcnow() is deprecated and returns a naive datetime holding UTC, which compares wrongly against anything aware and silently shifts when formatted. Always attach the timezone.',
      related: ['py.zoneinfo-zoneinfo'],
    },
    {
      name: 'zoneinfo.ZoneInfo',
      task: 'convert between time zones',
      syntax: "from zoneinfo import ZoneInfo\nlocal = utc_dt.astimezone(ZoneInfo('Europe/London'))",
      effect: 'read',
      note: 'Standard library from 3.9, but on Windows there is no system tz database — install tzdata or every lookup raises ZoneInfoNotFoundError. Name a region, never a fixed offset, or daylight saving is wrong half the year.',
    },
    {
      name: 'pandas.read_csv',
      task: 'load tabular data for analysis',
      syntax: "import pandas as pd\ndf = pd.read_csv(path, dtype=str, keep_default_na=False)",
      module: 'pandas',
      effect: 'read',
      note: 'By default it infers types, which turns an account code 0012345 into 12345 and a version 1.10 into 1.1. For anything that is an identifier rather than a number, read as str and convert deliberately.',
      related: ['py.pandas-to-excel'],
    },
    {
      name: 'pandas.to_excel',
      task: 'write a spreadsheet with more than one sheet',
      syntax: "with pd.ExcelWriter(out, engine='openpyxl') as xl:\n    summary.to_excel(xl, sheet_name='Summary', index=False)\n    detail.to_excel(xl, sheet_name='Detail', index=False)",
      module: 'pandas, openpyxl',
      effect: 'changes',
      note: 'index=False on every call, or the row numbers become a mystery first column in the delivered file. Sheet names are capped at 31 characters and cannot contain : \\ / ? * [ ], and pandas raises rather than truncating.',
    },
    {
      name: 'openpyxl.load_workbook',
      task: 'read or edit an existing spreadsheet',
      syntax: "from openpyxl import load_workbook\nwb = load_workbook(path, data_only=True, read_only=True)\nws = wb['Inventory']",
      module: 'openpyxl',
      effect: 'read',
      note: 'data_only=True returns the last value Excel calculated and cached — None if the file was written by a program rather than by Excel, because there is no cached value to return. That surprise accounts for most "my formulas are empty" reports.',
    },
  ]),

  group('python', 'Running things and processes', [
    {
      name: 'subprocess.run',
      task: 'run a command and capture its output',
      syntax: "import subprocess\nr = subprocess.run(['systemctl', 'is-active', name], capture_output=True, text=True, timeout=30)\nif r.returncode != 0:\n    raise RuntimeError(r.stderr.strip())",
      parameters: [
        { name: 'check=True', what: 'Raise CalledProcessError on a non-zero exit instead of carrying on.' },
        { name: 'text=True', what: 'Return str rather than bytes.' },
        { name: 'timeout', what: 'Seconds. Without it a hung child hangs the script forever.' },
      ],
      effect: 'changes',
      note: 'Pass a list, never a string with shell=True — that is command injection the moment any part of it comes from data. Without check=True a failed command looks exactly like a successful one.',
      related: ['py.subprocess-popen', 'py.shlex-quote'],
    },
    {
      name: 'subprocess.Popen',
      task: 'stream a long-running command\u2019s output as it happens',
      syntax: "with subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1) as p:\n    for line in p.stdout:\n        log.info(line.rstrip())",
      effect: 'changes',
      note: 'If you use PIPE and do not read it, the child blocks forever once the 64K pipe buffer fills — the classic "it works for small output and hangs on big output" bug. communicate() or a read loop, always.',
    },
    {
      name: 'shlex.quote',
      task: 'safely put a value into a shell command line',
      syntax: "import shlex\ncmd = f\"tar -czf backup.tgz {shlex.quote(path)}\"",
      effect: 'read',
      note: 'Only needed when a shell is genuinely involved; the real fix is to avoid the shell and pass a list. shlex.split is its inverse and is the right way to parse a command someone typed into a config file.',
    },
    {
      name: 'os.environ.get',
      task: 'read configuration and secrets from the environment',
      syntax: "token = os.environ.get('API_TOKEN')\nif not token:\n    raise SystemExit('API_TOKEN is not set')",
      effect: 'read',
      note: 'os.environ["X"] raises KeyError with a message that names the variable; .get returns None and the failure surfaces later as a confusing 401. Fail loudly at the top instead, and never default a secret to a literal.',
    },
    {
      name: 'argparse',
      task: 'give a script proper options, including a dry run',
      syntax: "import argparse\np = argparse.ArgumentParser(description='Sync inventory')\np.add_argument('--dry-run', action='store_true', help='report without changing anything')\np.add_argument('--limit', type=int, default=100)\nargs = p.parse_args()",
      effect: 'read',
      note: 'type=int validates and converts in one step, and a bad value exits with a usage message rather than a traceback. A --dry-run that is checked in one place and ignored in another is worse than none, so branch once, high up.',
    },
    {
      name: 'logging.basicConfig',
      task: 'get timestamped log output instead of print',
      syntax: "import logging\nlogging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')\nlog = logging.getLogger(__name__)",
      effect: 'read',
      note: 'basicConfig does nothing if any handler already exists, which is why it silently has no effect when a library configured logging first. Call it once, in the entry point, before importing anything that logs.',
      related: ['py.logging-exception'],
    },
    {
      name: 'logging.exception',
      task: 'log an error with its traceback',
      syntax: "try:\n    do_work()\nexcept Exception:\n    log.exception('sync failed')\n    raise",
      effect: 'read',
      note: 'Only valid inside an except block — it is log.error plus the current traceback. `except Exception as e: log.error(e)` throws away the line number, which is the only part you needed.',
    },
    {
      name: 'signal.signal',
      task: 'handle Ctrl-C or a TERM cleanly',
      syntax: "import signal\nstopping = False\ndef _stop(sig, frame):\n    global stopping\n    stopping = True\nsignal.signal(signal.SIGTERM, _stop)",
      effect: 'read',
      note: 'Set a flag and return; doing real work inside a handler can re-enter code that is not reentrant. SIGTERM is what systemd and Docker send before they kill you, and handling it is the difference between a clean stop and a half-written file.',
    },
    {
      name: 'atexit.register',
      task: 'clean up when the script ends any normal way',
      syntax: "import atexit\natexit.register(cleanup)",
      effect: 'read',
      note: 'It does not run on SIGKILL, on os._exit, or on a segfault — so it is for tidiness, not for correctness. Anything that must happen belongs in a try/finally or a context manager.',
    },
    {
      name: 'concurrent.futures.ThreadPoolExecutor',
      task: 'do many slow I/O calls at once',
      syntax: "from concurrent.futures import ThreadPoolExecutor, as_completed\nwith ThreadPoolExecutor(max_workers=16) as pool:\n    futures = {pool.submit(check, h): h for h in hosts}\n    for f in as_completed(futures):\n        print(futures[f], f.result())",
      effect: 'changes',
      note: 'Threads help with network and disk waits, not with CPU work — the GIL means sixteen threads of computation are slower than one. An exception inside a worker is only raised when you call .result(), so a pool whose results are ignored swallows every error.',
    },
  ]),

  group('python', 'Network and APIs', [
    {
      name: 'requests.get',
      task: 'call an HTTP API',
      syntax: "import requests\nr = requests.get(url, headers=headers, timeout=(5, 30))\nr.raise_for_status()\ndata = r.json()",
      parameters: [
        { name: 'timeout=(connect, read)', what: 'Two numbers. Without it there is no timeout at all.' },
        { name: 'params=', what: 'Builds the query string with correct encoding.' },
        { name: 'verify=', what: 'A CA bundle path for an internal certificate authority. Do not set it to False.' },
      ],
      effect: 'read',
      note: 'With no timeout, requests waits forever — that is the single most common cause of a scheduled job that never finishes and holds a lock. And a 404 is not an exception: without raise_for_status() the script carries on with an error page.',
      related: ['py.requests-session', 'py.requests-post'],
    },
    {
      name: 'requests.Session',
      task: 'reuse a connection and retry transient failures',
      syntax: "from requests.adapters import HTTPAdapter, Retry\ns = requests.Session()\ns.mount('https://', HTTPAdapter(max_retries=Retry(total=5, backoff_factor=1, status_forcelist=[429, 502, 503, 504])))",
      effect: 'read',
      note: 'A Session keeps the TCP connection, which on a few hundred calls is several times faster. Retry only replays idempotent methods by default — allowed_methods has to name POST explicitly, and usually should not.',
    },
    {
      name: 'requests.post',
      task: 'send JSON or a form',
      syntax: "r = requests.post(url, json=payload, timeout=30)",
      effect: 'changes',
      note: 'json= sets the content type and encodes for you; data= with a dict sends a form, and data=json.dumps(...) sends the right body with the wrong header. That mismatch is behind most 400s that "should work".',
    },
    {
      name: 'urllib.request',
      task: 'make an HTTP call with nothing installed',
      syntax: "from urllib.request import urlopen, Request\nreq = Request(url, headers={'Accept': 'application/json'})\nwith urlopen(req, timeout=30) as r:\n    data = json.load(r)",
      effect: 'read',
      note: 'Worth knowing for a locked-down box where pip is not available. It raises HTTPError for 4xx and 5xx rather than returning them, which is the opposite of requests and catches people moving between the two.',
    },
    {
      name: 'socket.create_connection',
      task: 'test whether a TCP port is reachable',
      syntax: "import socket\ntry:\n    with socket.create_connection((host, port), timeout=3):\n        ok = True\nexcept OSError:\n    ok = False",
      effect: 'read',
      note: 'The dependency-free port check. Distinguish the exceptions if you care why: timeout means a firewall dropping it, ConnectionRefused means nothing is listening but the host is up — two different problems.',
    },
    {
      name: 'ssl.create_default_context',
      task: 'talk TLS with an internal certificate authority',
      syntax: "import ssl\nctx = ssl.create_default_context(cafile='/etc/pki/tls/certs/internal-ca.pem')",
      effect: 'read',
      note: 'Point it at the CA bundle rather than turning verification off. verify=False or CERT_NONE makes the warning go away and makes the connection interceptable, and it always outlives the afternoon it was added for.',
    },
    {
      name: 'paramiko.SSHClient',
      task: 'run a command on a remote host over SSH',
      syntax: "import paramiko\nc = paramiko.SSHClient()\nc.load_system_host_keys()\nc.connect(host, username=user, key_filename=key, timeout=10)\n_, out, err = c.exec_command('uptime', timeout=30)",
      module: 'paramiko',
      effect: 'changes',
      note: 'set_missing_host_key_policy(AutoAddPolicy()) is in every example and disables the only protection against a man in the middle. Load the known_hosts file instead. exec_command returns immediately — read the streams or you get nothing.',
    },
    {
      name: 'ldap3',
      task: 'query Active Directory or another LDAP directory',
      syntax: "from ldap3 import Server, Connection, SUBTREE\nconn = Connection(Server(host, use_ssl=True), user=dn, password=pw, auto_bind=True)\nconn.extend.standard.paged_search(base, '(objectClass=user)', SUBTREE, attributes=['sAMAccountName'], paged_size=500, generator=False)",
      module: 'ldap3',
      effect: 'read',
      note: 'A plain search returns 1000 entries and stops, with no error — Active Directory\u2019s default page size. Any directory query that could return more must be paged, or you silently report on a fraction of the estate.',
    },
    {
      name: 'pyvmomi SmartConnect',
      task: 'connect to vCenter from Python',
      syntax: "from pyVim.connect import SmartConnect, Disconnect\nsi = SmartConnect(host=vc, user=user, pwd=pw, sslContext=ctx)\natexit.register(Disconnect, si)",
      module: 'pyvmomi',
      effect: 'read',
      note: 'Fetch properties with a PropertyCollector rather than walking objects: iterating vm.summary over a few thousand VMs is one round trip per property and takes minutes, where a collector does it in one call.',
    },
  ]),

  group('python', 'Cloud and infrastructure SDKs', [
    {
      name: 'boto3.client',
      task: 'call an AWS API',
      syntax: "import boto3\nec2 = boto3.client('ec2', region_name='eu-west-2')\nfor page in ec2.get_paginator('describe_instances').paginate():\n    ...",
      module: 'boto3',
      effect: 'read',
      note: 'Almost every list call is paginated and returns the first page with a NextToken you will forget to follow — use get_paginator and the problem disappears. A client is not thread-safe to create concurrently; make one per thread from a Session.',
      related: ['py.boto3-resource'],
    },
    {
      name: 'boto3.resource',
      task: 'work with AWS objects rather than raw API calls',
      syntax: "s3 = boto3.resource('s3')\ns3.Bucket('my-bucket').upload_file('report.xlsx', 'reports/report.xlsx')",
      module: 'boto3',
      effect: 'changes',
      note: 'The resource interface is in maintenance mode and covers fewer services than the client — new work should use client plus paginators, and the examples you find online are often the older style.',
    },
    {
      name: 'botocore.Config',
      task: 'set retries and timeouts for AWS calls',
      syntax: "from botocore.config import Config\ncfg = Config(retries={'max_attempts': 10, 'mode': 'adaptive'}, connect_timeout=5, read_timeout=60)",
      module: 'boto3',
      effect: 'read',
      note: 'The default is legacy mode with a handful of retries, which is not enough when a script hits throttling across a large account. adaptive mode backs off on its own, and is the difference between a run that finishes and one that dies at 80%.',
    },
    {
      name: 'azure.identity.DefaultAzureCredential',
      task: 'authenticate to Azure without a secret in the file',
      syntax: "from azure.identity import DefaultAzureCredential\nfrom azure.mgmt.compute import ComputeManagementClient\ncred = DefaultAzureCredential()\nclient = ComputeManagementClient(cred, subscription_id)",
      module: 'azure-identity',
      effect: 'read',
      note: 'It tries environment, managed identity, Azure CLI and others in order, so it works on your laptop and in a pipeline with no code change — and when it fails it fails slowly, after trying each one. Pass exclude_*_credential to cut the wait.',
    },
    {
      name: 'google.cloud client',
      task: 'call a Google Cloud API',
      syntax: "from google.cloud import storage\nclient = storage.Client()\nfor blob in client.list_blobs('my-bucket', prefix='reports/'):\n    print(blob.name, blob.size)",
      module: 'google-cloud-storage',
      effect: 'read',
      note: 'Authentication comes from GOOGLE_APPLICATION_CREDENTIALS or the metadata server, never from a parameter. List calls return a lazy iterator that pages behind your back, so len() on it does not work and iterating twice re-fetches.',
    },
    {
      name: 'kubernetes.client',
      task: 'talk to a Kubernetes cluster',
      syntax: "from kubernetes import client, config\nconfig.load_kube_config()\nv1 = client.CoreV1Api()\nfor pod in v1.list_namespaced_pod('prod', watch=False).items:\n    print(pod.metadata.name, pod.status.phase)",
      module: 'kubernetes',
      effect: 'read',
      note: 'load_incluster_config() inside a pod, load_kube_config() outside — calling the wrong one is the usual cause of a job that works locally and cannot authenticate in the cluster. Large lists need limit and _continue.',
    },
    {
      name: 'hvac',
      task: 'read a secret from HashiCorp Vault',
      syntax: "import hvac\nc = hvac.Client(url=os.environ['VAULT_ADDR'])\nc.auth.approle.login(role_id=rid, secret_id=sid)\npw = c.secrets.kv.v2.read_secret_version(path='app/db')['data']['data']['password']",
      module: 'hvac',
      effect: 'read',
      note: 'KV v1 and v2 have different paths and different response shapes — the doubled ["data"]["data"] is v2, and mixing them up gives a KeyError that looks like a missing secret. Tokens expire; renew or re-login in a long run.',
    },
    {
      name: 'netmiko.ConnectHandler',
      task: 'run commands on network devices',
      syntax: "from netmiko import ConnectHandler\nwith ConnectHandler(device_type='cisco_ios', host=ip, username=u, password=p) as c:\n    print(c.send_command('show version', use_textfsm=True))",
      module: 'netmiko',
      effect: 'changes',
      note: 'use_textfsm=True turns screen output into a list of dictionaries, which is the difference between parsing and regex misery. send_config_set does not save — follow it with c.save_config() or the change is lost at the next reload.',
    },
    {
      name: 'jinja2.Environment',
      task: 'render a configuration file from a template',
      syntax: "from jinja2 import Environment, FileSystemLoader, StrictUndefined\nenv = Environment(loader=FileSystemLoader('templates'), undefined=StrictUndefined, trim_blocks=True, lstrip_blocks=True)\ntext = env.get_template('nginx.conf.j2').render(**values)",
      module: 'jinja2',
      effect: 'read',
      note: 'StrictUndefined is the important one: by default a misspelled variable renders as an empty string, so you ship a config with a blank where the hostname should be and find out in production.',
    },
    {
      name: 'rich.console',
      task: 'print readable tables and progress in a terminal script',
      syntax: "from rich.console import Console\nfrom rich.table import Table\nt = Table(title='Findings')\nt.add_column('Host'); t.add_column('Status')\nConsole().print(t)",
      module: 'rich',
      effect: 'read',
      note: 'It detects a non-terminal and drops the colour codes, so piping to a file stays clean — unlike hand-rolled ANSI. Keep it out of anything whose output another program parses.',
    },
    {
      name: 'tenacity.retry',
      task: 'retry a flaky call properly',
      syntax: "from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type\n@retry(stop=stop_after_attempt(5), wait=wait_exponential(multiplier=1, max=30), retry=retry_if_exception_type(TimeoutError))\ndef fetch():\n    ...",
      module: 'tenacity',
      effect: 'read',
      note: 'Name the exception types. A bare @retry also retries a permission error and a bad request five times, which turns a clear failure into a slow, confusing one — and can duplicate a non-idempotent write.',
    },
  ]),

  group('python', 'Debugging and correctness', [
    {
      name: 'breakpoint()',
      task: 'stop and look around at a point in the code',
      syntax: 'breakpoint()  # PYTHONBREAKPOINT=0 disables every one of them',
      effect: 'read',
      note: 'Built in since 3.7 and honours PYTHONBREAKPOINT, so a forgotten one can be disabled by an environment variable rather than hanging a scheduled job at 2am waiting for input on a terminal that is not there.',
    },
    {
      name: 'traceback.format_exc',
      task: 'capture a traceback as text for a log or a report',
      syntax: "import traceback\ntry:\n    work()\nexcept Exception:\n    report.append(traceback.format_exc())",
      effect: 'read',
      note: 'Only meaningful inside the except block — called later it returns "NoneType: None", which is how a carefully written error report ends up saying nothing at all.',
    },
    {
      name: 'timeit',
      task: 'measure how long a small thing takes',
      syntax: "python3 -m timeit -s 'import json; d={\"a\":1}' 'json.dumps(d)'",
      effect: 'read',
      note: 'It disables the garbage collector and runs the statement many times, which is why its figures differ from a stopwatch around the same code. Use it to compare two approaches, not to predict real elapsed time.',
    },
    {
      name: 'cProfile',
      task: 'find where a slow script spends its time',
      syntax: "python3 -m cProfile -s cumtime script.py | head -30",
      effect: 'read',
      note: 'Sort by cumtime to find the slow call tree and by tottime to find the slow function itself — they usually point at different lines, and reading the wrong one sends you optimising something that is not the problem.',
    },
    {
      name: 'tracemalloc',
      task: 'find what is holding memory',
      syntax: "import tracemalloc\ntracemalloc.start()\n...\nfor stat in tracemalloc.take_snapshot().statistics('lineno')[:10]:\n    print(stat)",
      effect: 'read',
      note: 'It reports allocations made after start(), so call it before the suspect code rather than at the top of a long-running process where everything looks equally guilty.',
    },
    {
      name: 'warnings.simplefilter',
      task: 'see the deprecation warnings Python hides by default',
      syntax: "python3 -W error::DeprecationWarning script.py",
      effect: 'read',
      note: 'DeprecationWarning is silent unless the code is __main__, so a library quietly telling you it will break in the next release is invisible. Turn it into an error in CI and you find out before the upgrade does.',
    },
    {
      name: 'dataclasses.dataclass',
      task: 'define a record type without boilerplate',
      syntax: "from dataclasses import dataclass, field\n@dataclass(frozen=True, slots=True)\nclass Host:\n    name: str\n    tags: list[str] = field(default_factory=list)",
      effect: 'read',
      note: 'A mutable default must use field(default_factory=list) — a bare [] is shared by every instance, which is the classic Python bug and here it raises rather than silently sharing. frozen=True makes it hashable and safe to use as a key.',
    },
    {
      name: 'enum.Enum',
      task: 'replace magic strings with checked values',
      syntax: "from enum import StrEnum\nclass State(StrEnum):\n    RUNNING = 'running'\n    STOPPED = 'stopped'",
      effect: 'read',
      note: 'StrEnum (3.11+) compares equal to its string value, so it drops into existing code that compares against literals. A plain Enum does not, and that mismatch silently makes every comparison False.',
    },
    {
      name: 'functools.lru_cache',
      task: 'cache the result of an expensive lookup',
      syntax: "from functools import lru_cache\n@lru_cache(maxsize=1024)\ndef resolve(name: str) -> str:\n    ...",
      effect: 'read',
      note: 'The arguments must be hashable, so it cannot wrap a function taking a dict or a list. It also never expires — caching a DNS or directory lookup in a long-running process means serving a stale answer forever.',
    },
    {
      name: 'itertools.batched',
      task: 'process a large list in chunks',
      syntax: "from itertools import batched\nfor chunk in batched(ids, 500):\n    api.delete(list(chunk))",
      effect: 'read',
      note: 'New in 3.12; before that it is the islice loop everyone writes by hand. Most APIs cap a bulk call at a few hundred items and reject the whole request rather than truncating, so batching is not an optimisation.',
    },
    {
      name: 'contextlib.suppress',
      task: 'ignore one specific expected error',
      syntax: "from contextlib import suppress\nwith suppress(FileNotFoundError):\n    path.unlink()",
      effect: 'changes',
      note: 'Better than try/except/pass because it names exactly what is being ignored and cannot accidentally swallow anything else. A bare except: pass hides a KeyboardInterrupt and a typo equally well.',
    },
    {
      name: 'typing.TYPE_CHECKING',
      task: 'import something only for type checking',
      syntax: "from typing import TYPE_CHECKING\nif TYPE_CHECKING:\n    from heavy.module import Thing",
      effect: 'read',
      note: 'Keeps a slow or circular import out of runtime while mypy still sees it. The annotations that use it must be strings, or add `from __future__ import annotations` at the top of the file.',
    },
  ]),

  group('python', 'Packaging, environments and quality', [
    {
      name: 'python -m venv',
      task: 'make an isolated environment',
      syntax: 'python3 -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt',
      effect: 'changes',
      note: 'Always `python -m pip`, not bare pip: on a machine with several interpreters, bare pip installs into whichever one is first in PATH, and then the import fails in the one you are actually running.',
      related: ['py.pip-install'],
    },
    {
      name: 'pip install',
      task: 'install dependencies reproducibly',
      syntax: 'python3 -m pip install --require-hashes -r requirements.lock',
      effect: 'changes',
      note: 'Never pip install as root into the system Python on a Linux server — it overwrites packages the distribution owns and breaks system tools. Use a venv, or --user, or pipx for applications.',
    },
    {
      name: 'pip download',
      task: 'get packages for an air-gapped machine',
      syntax: 'python3 -m pip download -r requirements.txt -d wheels --platform manylinux2014_x86_64 --only-binary=:all:',
      effect: 'changes',
      note: 'Without the platform flags it downloads wheels for the machine you are on, which is the wrong architecture for the one you are building. Then install with --no-index --find-links=wheels.',
    },
    {
      name: 'pip list --outdated',
      task: 'see what is behind, and what has a known vulnerability',
      syntax: 'python3 -m pip list --outdated --format=json',
      effect: 'read',
      note: 'For vulnerabilities rather than age, `pip-audit` reads the same environment and checks it against the advisory database — that is the one an auditor is asking about.',
    },
    {
      name: 'ruff',
      task: 'lint and format fast',
      syntax: 'ruff check --fix . && ruff format .',
      module: 'ruff',
      effect: 'changes',
      note: 'It replaces flake8, isort and most of pylint, and it is quick enough to run on save. --fix rewrites files in place, so run it on a clean tree or you cannot tell its changes from yours.',
    },
    {
      name: 'mypy',
      task: 'check type annotations',
      syntax: 'mypy --strict --ignore-missing-imports src/',
      module: 'mypy',
      effect: 'read',
      note: 'Start without --strict on existing code or you get thousands of findings and turn it off again. The highest-value setting on its own is --disallow-untyped-defs, applied one module at a time.',
    },
    {
      name: 'pytest',
      task: 'run the test suite, or just the last failures',
      syntax: 'pytest -q -x --lf --tb=short',
      module: 'pytest',
      effect: 'read',
      note: '--lf reruns just the last failures, which turns a ten-minute suite into a two-second loop while you fix them. -x stops at the first failure, so you read one traceback instead of forty.',
    },
    {
      name: 'python -m json.tool',
      task: 'check and pretty-print JSON from the shell',
      syntax: 'python3 -m json.tool --sort-keys config.json',
      effect: 'read',
      note: 'Always there, unlike jq. It is also the quickest way to find out which line of a config file is malformed, because the error names the position.',
    },
    {
      name: 'python -m http.server',
      task: 'serve a directory over HTTP for a moment',
      syntax: 'python3 -m http.server 8000 --bind 127.0.0.1 --directory ./dist',
      effect: 'changes',
      note: '--bind 127.0.0.1 matters: without it you have published the directory to the whole network, with directory listing on and no authentication. It is single-threaded and for testing only.',
    },
  ]),
];
