# Generated by ATK: Azure workload intent (NSG intent only)
# Does not create compute by default. Safe to validate offline.

variable "deploy_workloads" { type = bool default = false }

locals {
  atk_internet_exposed = false
  atk_strict           = false
}

# Standalone workload NSG you can attach to NICs later
resource "azurerm_network_security_group" "workload_default" {
  name                = "${var.naming_prefix}-workload-default-nsg"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

# Optional: public front-door NSG intent (HTTPS only)
resource "azurerm_network_security_group" "frontdoor_public" {
  count               = local.atk_internet_exposed ? 1 : 0
  name                = "${var.naming_prefix}-frontdoor-public-nsg"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_network_security_rule" "frontdoor_https" {
  count                       = local.atk_internet_exposed ? 1 : 0
  name                        = "Allow-HTTPS-In"
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "443"
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.rg.name
  network_security_group_name = azurerm_network_security_group.frontdoor_public[0].name
}
