/**
 * Relocate: the VMware service on each cloud that HCX moves VMs into unchanged.
 *
 *   azure_mig_avs    Azure VMware Solution private cloud, and an ExpressRoute
 *                    authorisation to connect it to the hub
 *   google_mig_gcve  Google Cloud VMware Engine network, private cloud and the
 *                    peering to the landing zone's VPC
 *   oci_mig_ocvs     Oracle Cloud VMware Solution SDDC, with the VLANs and
 *                    provisioning subnet it needs in the landing zone's VCN
 *
 * AWS has none: Amazon EVS has no resource in the aws provider this kit is
 * pinned to (6.66), so the AWS relocate path is a runbook, not Terraform.
 *
 * The node count comes from the plan's estimate; the real sizing is the VCF
 * Sizing page's. Each reads the landing zone as every other migration
 * blueprint does.
 */

import { error, info,              } from '../../../core/findings.js';
import { familyOf } from '../../../core/ip.js';
                                                                                            
import { num as numberOf, str as valueOf } from '../../../kit/blueprint.js';
                                             
import {
  LANDING_ZONE_SOURCE,
  MIGRATION_GROUP,
  blk,
  carve,
  consumerPreamble,
  e,
  hcl,
  ident,
  lzRef,
  mainTf,
  opts,
  output,
  q,
  res,
  rname,
  sshKeyVariable,
  terraformBlock,
  x,
} from './common.js';

const failed = (id        , findings                    ) => ({
  files: { 'main.tf': `# ${id}: nothing was generated; see the findings.\n` },
  findings,
});

function commonInputs(sku                                                                , cidr        , cidrHint        )                   {
  return [
    { id: 'sku_name', label: sku.label, control: 'select', default: sku.default, options: opts(sku.options) },
    { id: 'node_count', label: 'Hosts', control: 'number', default: 3, min: 3, max: 16, hint: 'From the plan\'s estimate; size it properly on the VCF Sizing page.' },
    { id: 'management_cidr', label: 'Management range', control: 'text', default: cidr, hint: cidrHint },
    { id: 'network', label: 'Network', control: 'text', default: 'prod', hint: 'The landing-zone network it connects to.' },
  ];
}

// ---------------------------------------------------------------------------
// Azure VMware Solution
// ---------------------------------------------------------------------------

function azureAvs()            {
  return {
    id: 'azure_mig_avs',
    label: 'Azure VMware Solution (relocate)',
    group: MIGRATION_GROUP,
    description: 'An Azure VMware Solution private cloud for the VMs that move unchanged with HCX, and an ExpressRoute authorisation key to connect it to the hub\'s ExpressRoute gateway (Global Reach to on-premises is configured on the circuit).',
    inputs: [
      ...commonInputs({ label: 'Host SKU', options: ['av36p', 'av52', 'av64', 'av36', 'av48'], default: 'av36p' }, '10.200.0.0/22', 'A /22 for vCenter, NSX Manager, HCX and the hosts; it must not overlap anything.'),
      LANDING_ZONE_SOURCE,
    ],
    emits: ['azurerm_vmware_private_cloud', 'azurerm_vmware_express_route_authorization'],
    build: (values                 ) => {
      const findings            = [];
      const lz = lzRef(values);
      const cidr = valueOf(values, 'management_cidr', '10.200.0.0/22');
      if (familyOf(cidr) !== 4 || !cidr.endsWith('/22')) findings.push(error('tf.mig.avs-cidr', `"${cidr}" is not an IPv4 /22, which is what Azure VMware Solution takes.`, { path: 'management_cidr' }));
      if (findings.length > 0) return failed('azure_mig_avs', findings);
      const blocks             = [
        terraformBlock(['azure']),
        ...consumerPreamble('azure', values),
        res('azurerm_vmware_private_cloud', 'relocate', {
          name: x(`"\${${lz}.prefix}-avs"`),
          resource_group_name: x(`${lz}.resource_group["shared"]`),
          location: x(`${lz}.location`),
          sku_name: valueOf(values, 'sku_name', 'av36p'),
          network_subnet_cidr: cidr,
          internet_connection_enabled: false,
        }, [blk('management_cluster', { size: numberOf(values, 'node_count', 3) })], 'The vCenter and NSX Manager passwords are generated by Azure and read from the portal or the API; none is written here.'),
        res('azurerm_vmware_express_route_authorization', 'hub', { name: x(`"\${${lz}.prefix}-hub"`), private_cloud_id: x('azurerm_vmware_private_cloud.relocate.id') }),
        output('private_cloud_id', 'azurerm_vmware_private_cloud.relocate.id'),
        output('express_route_circuit_id', 'azurerm_vmware_private_cloud.relocate.circuit[0].express_route_id', 'Connect it to the hub ExpressRoute gateway with the authorisation key.'),
        output('express_route_authorization_key', 'azurerm_vmware_express_route_authorization.hub.express_route_authorization_key', undefined, true),
        output('hcx_cloud_manager', 'azurerm_vmware_private_cloud.relocate.hcx_cloud_manager_endpoint'),
      ];
      findings.push(info('tf.mig.avs-connect', 'Connect the private cloud\'s ExpressRoute to the hub ExpressRoute gateway (a gateway connection with the authorisation key), and enable Global Reach to the on-premises circuit for HCX.', { path: 'network' }));
      return { files: { 'main.tf': mainTf(blocks, 'Azure VMware Solution for the relocated VMs') }, findings };
    },
  };
}

// ---------------------------------------------------------------------------
// Google Cloud VMware Engine
// ---------------------------------------------------------------------------

function googleGcve()            {
  return {
    id: 'google_mig_gcve',
    label: 'Google Cloud VMware Engine (relocate)',
    group: MIGRATION_GROUP,
    description: 'A VMware Engine network, a private cloud for the VMs that move unchanged with HCX, and the peering that joins it to the landing zone\'s VPC.',
    inputs: [
      ...commonInputs({ label: 'Node type', options: ['standard-72', 've1-standard-72', 've2-standard-128'], default: 'standard-72' }, '10.200.0.0/22', 'The management range (a /22 or larger); it must not overlap anything.'),
      LANDING_ZONE_SOURCE,
    ],
    emits: ['google_vmwareengine_network', 'google_vmwareengine_private_cloud', 'google_vmwareengine_network_peering'],
    build: (values                 ) => {
      const findings            = [];
      const lz = lzRef(values);
      const cidr = valueOf(values, 'management_cidr', '10.200.0.0/22');
      const net = rname(valueOf(values, 'network', 'prod'));
      if (familyOf(cidr) !== 4 || Number(cidr.split('/')[1]) > 22) findings.push(error('tf.mig.gcve-cidr', `"${cidr}" is not an IPv4 /22 or larger.`, { path: 'management_cidr' }));
      if (findings.length > 0) return failed('google_mig_gcve', findings);
      const blocks             = [
        terraformBlock(['google']),
        ...consumerPreamble('google', values),
        res('google_vmwareengine_network', 'relocate', { name: x(`"\${${lz}.prefix}-vmware"`), location: 'global', type: 'STANDARD', description: 'VMware Engine network for relocated VMs' }),
        res('google_vmwareengine_private_cloud', 'relocate', {
          name: x(`"\${${lz}.prefix}-gcve"`),
          location: x(`element(${lz}.zones, 0)`),
          description: 'Private cloud for the VMs HCX relocates',
        }, [
          blk('network_config', { management_cidr: cidr, vmware_engine_network: x('google_vmwareengine_network.relocate.id') }),
          blk('management_cluster', { cluster_id: x(`"\${${lz}.prefix}-mgmt"`) }, [blk('node_type_configs', { node_type_id: valueOf(values, 'sku_name', 'standard-72'), node_count: numberOf(values, 'node_count', 3) })]),
        ]),
        res('google_vmwareengine_network_peering', 'relocate', {
          name: x(`"\${${lz}.prefix}-vmware-${net}"`),
          vmware_engine_network: x('google_vmwareengine_network.relocate.id'),
          peer_network: x(`${lz}.network_ids[${q(net)}]`),
          peer_network_type: 'STANDARD',
          export_custom_routes: true,
          import_custom_routes: true,
        }),
        output('private_cloud_id', 'google_vmwareengine_private_cloud.relocate.id'),
        output('hcx', 'google_vmwareengine_private_cloud.relocate.hcx'),
      ];
      return { files: { 'main.tf': mainTf(blocks, 'Google Cloud VMware Engine for the relocated VMs') }, findings };
    },
  };
}

// ---------------------------------------------------------------------------
// Oracle Cloud VMware Solution
// ---------------------------------------------------------------------------

/** The VLANs an OCVS SDDC needs, each with its own /25 of the SDDC range. */
const OCVS_VLANS = [
  ['nsx_edge_uplink1', 'NSX Edge uplink 1'],
  ['nsx_edge_uplink2', 'NSX Edge uplink 2'],
  ['nsx_edge_vtep', 'NSX Edge VTEP'],
  ['nsx_vtep', 'NSX VTEP'],
  ['vmotion', 'vMotion'],
  ['vsan', 'vSAN'],
  ['vsphere', 'vSphere'],
  ['hcx', 'HCX'],
  ['replication', 'Replication'],
  ['provisioning', 'Provisioning'],
]         ;

function ociOcvs()            {
  return {
    id: 'oci_mig_ocvs',
    label: 'Oracle Cloud VMware Solution (relocate)',
    group: MIGRATION_GROUP,
    description: 'An Oracle Cloud VMware Solution SDDC for the VMs that move unchanged with HCX, with its VLANs and provisioning subnet carved in the landing zone\'s VCN, and a workload cluster when asked.',
    inputs: [
      ...commonInputs({ label: 'Host shape', options: ['BM.DenseIO.E5.128', 'BM.DenseIO.E4.128', 'BM.DenseIO2.52'], default: 'BM.DenseIO.E5.128' }, '10.200.0.0/21', 'A /21: ten VLANs and the provisioning subnet each take a /25 of it.'),
      { id: 'vmware_software_version', label: 'VMware software version', control: 'text', default: '8.0 update 3', hint: 'As OCVS lists it for the region (oci ocvs supported-vmware-software-version-summary list).' },
      { id: 'workload_hosts', label: 'Workload cluster hosts', control: 'number', default: 0, min: 0, max: 64, hint: '0: management cluster only.' },
      { id: 'vcf_byol_allocation_id', label: 'VCF BYOL allocation', control: 'text', default: '', hint: 'The OCID of a portable VCF subscription allocation, when the licence is brought.' },
      { id: 'ssh_public_key_var', label: 'SSH key variable', control: 'text', default: 'ssh_public_key' },
      LANDING_ZONE_SOURCE,
    ],
    emits: ['oci_core_vlan', 'oci_core_subnet', 'oci_ocvp_sddc', 'oci_ocvp_cluster'],
    build: (values                 ) => {
      const findings            = [];
      const lz = lzRef(values);
      const cidr = valueOf(values, 'management_cidr', '10.200.0.0/21');
      const net = rname(valueOf(values, 'network', 'prod'));
      const prefix = Number(cidr.split('/')[1]);
      const pieces = familyOf(cidr) === 4 && prefix <= 21 ? carve(cidr, [...OCVS_VLANS.map(() => 25), 25]) : null;
      if (!pieces) findings.push(error('tf.mig.ocvs-cidr', `"${cidr}" is not an IPv4 /21 or larger, which the SDDC's VLANs and subnet need.`, { path: 'management_cidr' }));
      if (!pieces) return failed('oci_mig_ocvs', findings);
      const ssh = ident(valueOf(values, 'ssh_public_key_var', 'ssh_public_key'));
      const byol = valueOf(values, 'vcf_byol_allocation_id');
      const workload = numberOf(values, 'workload_hosts', 0);
      const ad = `element(${lz}.zones, 0)`;
      const vcn = `${lz}.network_ids[${q(net)}]`;
      const blocks             = [terraformBlock(['oci']), ...consumerPreamble('oci', values), sshKeyVariable(ssh)];
      OCVS_VLANS.forEach(([id, label], i) => {
        blocks.push(
          res('oci_core_vlan', `ocvs_${id}`, {
            compartment_id: x(`${lz}.compartment_id`),
            vcn_id: x(vcn),
            availability_domain: x(ad),
            cidr_block: pieces[i]          ,
            vlan_tag: 100 + i,
            display_name: x(`"\${${lz}.prefix}-ocvs-${id.replace(/_/g, '-')}"`),
            nsg_ids: x(`[${lz}.security_group_ids[${q(`${net}/mgmt`)}]]`),
          }, [], `${label}.`),
        );
      });
      blocks.push(
        res('oci_core_subnet', 'ocvs_provisioning', {
          compartment_id: x(`${lz}.compartment_id`),
          vcn_id: x(vcn),
          cidr_block: pieces[OCVS_VLANS.length]          ,
          display_name: x(`"\${${lz}.prefix}-ocvs-provisioning"`),
          prohibit_public_ip_on_vnic: true,
        }),
      );
      const vlan = (id        ) => x(`oci_core_vlan.ocvs_${id}.id`);
      const networkConfig = blk('network_configuration', {
        provisioning_subnet_id: x('oci_core_subnet.ocvs_provisioning.id'),
        nsx_edge_uplink1vlan_id: vlan('nsx_edge_uplink1'),
        nsx_edge_uplink2vlan_id: vlan('nsx_edge_uplink2'),
        nsx_edge_vtep_vlan_id: vlan('nsx_edge_vtep'),
        nsx_vtep_vlan_id: vlan('nsx_vtep'),
        vmotion_vlan_id: vlan('vmotion'),
        vsan_vlan_id: vlan('vsan'),
        vsphere_vlan_id: vlan('vsphere'),
        hcx_vlan_id: vlan('hcx'),
        replication_vlan_id: vlan('replication'),
        provisioning_vlan_id: vlan('provisioning'),
      });
      blocks.push(
        res('oci_ocvp_sddc', 'relocate', {
          compartment_id: x(`${lz}.compartment_id`),
          display_name: x(`"\${${lz}.prefix}-ocvs"`),
          vmware_software_version: valueOf(values, 'vmware_software_version', '8.0 update 3'),
          ssh_authorized_keys: x(`var.${ssh}`),
          hcx_action: 'UPGRADE',
        }, [
          blk('initial_configuration', {}, [
            blk('initial_cluster_configurations', {
              compute_availability_domain: x(ad),
              esxi_hosts_count: numberOf(values, 'node_count', 3),
              vsphere_type: 'MANAGEMENT',
              initial_host_shape_name: valueOf(values, 'sku_name', 'BM.DenseIO.E5.128'),
              initial_vcf_byol_allocation_id: byol || undefined,
              display_name: 'management',
              instance_display_name_prefix: 'esx',
            }, [networkConfig]),
          ]),
        ], 'HCX Enterprise (hcx_action UPGRADE) for bulk and vMotion migration.'),
      );
      if (workload > 0) {
        blocks.push(
          res('oci_ocvp_cluster', 'workload', {
            sddc_id: x('oci_ocvp_sddc.relocate.id'),
            compute_availability_domain: x(ad),
            esxi_hosts_count: workload,
            initial_host_shape_name: valueOf(values, 'sku_name', 'BM.DenseIO.E5.128'),
            display_name: 'workload',
            initial_vcf_byol_allocation_id: byol || undefined,
          }, [networkConfig]),
        );
      }
      blocks.push(output('sddc_id', 'oci_ocvp_sddc.relocate.id'), output('vlans', hcl(Object.fromEntries(OCVS_VLANS.map(([id]) => [id, e(`oci_core_vlan.ocvs_${id}.cidr_block`)])), 1)));
      findings.push(info('tf.mig.ocvs-version', 'The VMware software versions OCVS offers change by region; check the version before applying.', { path: 'vmware_software_version' }));
      return { files: { 'main.tf': mainTf(blocks, 'Oracle Cloud VMware Solution for the relocated VMs') }, findings };
    },
  };
}

export const RELOCATE_AZURE                       = [azureAvs()];
export const RELOCATE_GOOGLE                       = [googleGcve()];
export const RELOCATE_OCI                       = [ociOcvs()];
