/**
 * Pipelines and runners: the glue that runs everything else.
 *
 * The toolkit already writes Terraform, Ansible, PowerShell and Python. What it
 * did not write is the thing that runs them on a schedule, with credentials
 * that are not in the file, and a record afterwards. That is this.
 *
 * Every runner here is generated with the same four properties, because they
 * are the four that are missing when an automation goes wrong at 3am: the
 * schedule is created disabled, the credential comes from the runner's own
 * store, there is a dry run, and the run says where it went afterwards.
 */

import { bool, num, str, type BlueprintValues } from '../../kit/blueprint.ts';
import { error, warning, type Finding } from '../../core/findings.ts';
import { automationBlueprint, type AutomationBlueprint } from '../from-automation.ts';
import { listOf, slugOf, type Automation } from '../automation.ts';

const PLATFORM = 'pipeline' as const;

export const PIPELINE_AUTOMATIONS: readonly AutomationBlueprint[] = [
  automationBlueprint({
    id: 'pipe_azure_runbook',
    platform: PLATFORM,
    label: 'Azure Automation runbook on a schedule',
    group: 'Azure',
    description:
      'A PowerShell runbook with a managed identity rather than a stored credential, a dry run that is on by default, and a schedule created disabled. The runbook that does the work is yours; everything around it is the part people skip.',
    inputs: [
      { id: 'runbook_name', label: 'Runbook name', control: 'text', default: 'Nightly tag compliance' },
      { id: 'what_it_does', label: 'What it does', control: 'text', default: 'Reports resources missing a cost-centre tag' },
      { id: 'schedule', label: 'Runs', control: 'text', default: 'Daily 02:00' },
      {
        id: 'identity',
        label: 'Authenticates with',
        control: 'select',
        options: [
          { value: 'system', label: 'System-assigned managed identity' },
          { value: 'user', label: 'User-assigned managed identity' },
          { value: 'runas', label: 'A Run As account — retired, see the finding' },
        ],
        default: 'system',
      },
      { id: 'scope', label: 'Over', control: 'text', default: 'the subscription the account is in' },
      { id: 'changes_things', label: 'It changes things', control: 'toggle', default: false },
    ],
    automation: (values: BlueprintValues, name: string): Automation => {
      const runbookName = str(values, 'runbook_name', 'Runbook');
      const whatItDoes = str(values, 'what_it_does', 'Reports something');
      const schedule = str(values, 'schedule', 'Daily 02:00');
      const identity = str(values, 'identity', 'system');
      const scope = str(values, 'scope', 'the subscription');
      const changes = bool(values, 'changes_things', false);
      const base = slugOf(name || runbookName, 'runbook');

      const findings: Finding[] = [];
      if (identity === 'runas') {
        findings.push(
          error('pipe.azure.runas', 'Run As accounts are retired and their certificates expire silently.', {
            remediation: 'Use a managed identity. There is no credential to rotate and nothing to expire at the worst moment.',
            source: 'ArchToolKit',
          }),
        );
      }

      const ps = [
        '<#',
        `.SYNOPSIS`,
        `    ${runbookName} — ${whatItDoes}`,
        '',
        '.DESCRIPTION',
        '    Generated by ArchToolKit. Runs in Azure Automation.',
        '',
        '    The dry run is on by default. Pass -Execute to make it act, and read',
        `    what the dry run listed before you do.${changes ? '' : ' This runbook only reads.'}`,
        '',
        '.NOTES',
        `    Authenticates with a ${identity === 'system' ? 'system-assigned' : identity === 'user' ? 'user-assigned' : 'Run As'} identity.`,
        '    No credential is stored in this file.',
        '#>',
        '[CmdletBinding(SupportsShouldProcess)]',
        'param(',
        '    [Parameter()][switch]$Execute,',
        '    [Parameter()][string]$UserAssignedClientId',
        ')',
        '',
        'Set-StrictMode -Version Latest',
        "$ErrorActionPreference = 'Stop'",
        '',
        'function Write-Log {',
        "    param([string]$Message, [ValidateSet('INFO','WARN','ERROR')][string]$Level = 'INFO')",
        "    Write-Output ('{0} [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message)",
        '}',
        '',
        '# The identity is the whole point: nothing to rotate, nothing to expire.',
        'try {',
        identity === 'user'
          ? '    Connect-AzAccount -Identity -AccountId $UserAssignedClientId | Out-Null'
          : '    Connect-AzAccount -Identity | Out-Null',
        "    Write-Log \"Connected as $((Get-AzContext).Account.Id)\"",
        '} catch {',
        "    Write-Log \"Could not authenticate: $($_.Exception.Message)\" -Level ERROR",
        '    throw',
        '}',
        '',
        '# Assert the subscription before doing anything. The context is per-session',
        '# and a runbook that assumes it is a subscription it is not will act on the',
        '# wrong estate without saying so.',
        "Write-Log \"Subscription: $((Get-AzContext).Subscription.Name)\"",
        '',
        `if (-not $Execute) { $WhatIfPreference = $true; Write-Log 'DRY RUN — nothing will be changed. Re-run with -Execute.' -Level WARN }`,
        '',
        'try {',
        `    # --- the work: ${whatItDoes} ---`,
        '    # Replace this block. Everything above and below it is the scaffolding',
        '    # that makes the run safe and the result findable afterwards.',
        '    $found = @()',
        '',
        '    Write-Log "$($found.Count) item(s) matched"',
        '    foreach ($item in $found) {',
        changes
          ? "        if ($PSCmdlet.ShouldProcess($item.Name, '" + runbookName + "')) {\n            # act on $item\n        }"
          : '        Write-Log "would report: $($item.Name)"',
        '    }',
        '} catch {',
        "    Write-Log $_.Exception.Message -Level ERROR",
        '    throw',
        '} finally {',
        "    Write-Log 'finished'",
        '}',
        '',
      ].join('\n');

      const bicep = [
        '// Schedule and job for the runbook. Created disabled, on purpose.',
        '//',
        '// A schedule that starts the moment it is deployed is how an automation',
        '// first runs before anybody has read what it does.',
        "param automationAccountName string",
        "param location string = resourceGroup().location",
        `param runbookName string = '${runbookName}'`,
        '',
        "resource account 'Microsoft.Automation/automationAccounts@2023-11-01' existing = {",
        '  name: automationAccountName',
        '}',
        '',
        "resource schedule 'Microsoft.Automation/automationAccounts/schedules@2023-11-01' = {",
        '  parent: account',
        `  name: '${base}-schedule'`,
        '  properties: {',
        `    description: '${schedule} — ${whatItDoes}'`,
        '    frequency: \'Day\'',
        '    interval: 1',
        '    // Disabled until somebody turns it on deliberately.',
        '    isEnabled: false',
        '    startTime: \'<REQUIRED — an ISO 8601 time at least 5 minutes from deployment>\'',
        '    timeZone: \'<REQUIRED — e.g. America/New_York>\'',
        '  }',
        '}',
        '',
        '',
        'output scheduleName string = schedule.name',
        '',
      ].join('\n');

      return {
        platform: PLATFORM,
        title: `${runbookName} — ${whatItDoes}`,
        effect: changes ? 'reversible' : 'read',
        trigger: { kind: 'schedule', detail: schedule, worstCase: 'once a day, plus whenever somebody starts it by hand' },
        scope: {
          what: `Whatever the identity can see in ${scope}.`,
          decidedBy: [
            `The ${identity === 'runas' ? 'Run As account' : 'managed identity'} and the roles assigned to it.`,
            'The subscription the automation account is in — assert it, do not assume it.',
            'Whatever filter the work block applies.',
          ],
          ifWrong: 'An over-privileged identity is the real blast radius here, not the script. Give it exactly the role it needs and the scope is bounded by Azure rather than by the code.',
        },
        guardrails: [
          { rule: 'Dry run by default; -Execute takes it off', because: 'Nobody reads a runbook before the first scheduled run. This way the first run reports.' },
          { rule: 'The schedule is created disabled', because: 'Deploying a template should not start something running.' },
          { rule: 'No credential in the file', because: 'A runbook is exported, versioned and read by more people than the person who wrote it.' },
          { rule: 'The subscription is logged before any work', because: 'The context is per-session. A runbook that acts on the wrong subscription does so silently.' },
        ],
        dryRun: ['Start it by hand with -Execute absent and read the output stream in full.', 'Only then enable the schedule.'],
        undo: changes ? ['Whatever the work block changed has to be put back by the same means. Record the previous values in the run output — that log is the only undo.'] : ['Nothing to undo. It reads.'],
        told: ['The job output in Azure Automation, kept for the account’s retention period. Forward it to a log workspace if the record needs to outlive that.'],
        requires: [
          'An Automation account with the Az modules imported — the built-in versions lag, and a runbook that works locally can fail there on a missing cmdlet.',
          `${identity === 'user' ? 'A user-assigned identity and its client id' : identity === 'system' ? 'A system-assigned identity on the account' : 'A Run As account, which is retired'}, with exactly the roles this needs.`,
        ],
        files: { [`${base}.ps1`]: ps, [`${base}-schedule.bicep`]: bicep },
        notes: [
          'Module versions in Azure Automation are not the versions on your laptop. Pin them in the account and test there, not locally.',
          'The output stream is the record. Write what you did to it, not just that you finished.',
        ],
        findings,
      };
    },
  }),

  automationBlueprint({
    id: 'pipe_ssm_document',
    platform: PLATFORM,
    label: 'AWS Systems Manager document',
    group: 'AWS',
    description:
      'An SSM document with the two things that separate a safe run from a bad afternoon: a targeted resource group rather than every instance, and a rate control that stops it doing all of them at once when the first one fails.',
    inputs: [
      { id: 'doc_name', label: 'Document name', control: 'text', default: 'PatchAndReport' },
      { id: 'what_it_does', label: 'What it does', control: 'text', default: 'Applies the patch baseline and reports what changed' },
      { id: 'target_tag', label: 'Targets instances tagged', control: 'text', default: 'PatchGroup=standard' },
      { id: 'concurrency', label: 'At most (instances at once)', control: 'text', default: '10%', hint: 'A count or a percentage' },
      { id: 'error_threshold', label: 'Stop after (failures)', control: 'text', default: '1', hint: 'A count or a percentage. 1 is the safe first answer' },
      { id: 'reboot', label: 'May reboot', control: 'toggle', default: false },
    ],
    automation: (values: BlueprintValues, name: string): Automation => {
      const docName = str(values, 'doc_name', 'Document');
      const whatItDoes = str(values, 'what_it_does', 'Does something');
      const targetTag = str(values, 'target_tag', '');
      const concurrency = str(values, 'concurrency', '10%');
      const errorThreshold = str(values, 'error_threshold', '1');
      const reboot = bool(values, 'reboot', false);
      const base = slugOf(name || docName, 'ssm-document');

      const findings: Finding[] = [];
      if (!targetTag) {
        findings.push(
          error('pipe.ssm.no-target', 'No target tag, so this can be run against every managed instance in the account.', {
            remediation: 'Target by tag. An SSM document with no target is one console click away from the whole estate.',
            source: 'ArchToolKit',
          }),
        );
      }
      if (/^100%$|^0$/.test(errorThreshold)) {
        findings.push(
          warning('pipe.ssm.no-stop', 'Nothing stops this if instances start failing.', {
            remediation: 'Set the error threshold to 1 for the first few runs. If the first instance fails, the other four hundred should not be attempted.',
            source: 'ArchToolKit',
          }),
        );
      }

      const doc = [
        `# ${docName} — ${whatItDoes}`,
        '#',
        '# Generated by ArchToolKit. Run it with --dry-run first; the document',
        '# honours it and reports rather than acting.',
        "schemaVersion: '2.2'",
        `description: ${JSON.stringify(whatItDoes)}`,
        'parameters:',
        '  DryRun:',
        '    type: String',
        "    default: 'true'",
        "    allowedValues: ['true', 'false']",
        '    description: Report what would be done without doing it',
        ...(reboot
          ? [
              '  RebootOption:',
              '    type: String',
              "    default: 'NoReboot'",
              "    allowedValues: ['NoReboot', 'RebootIfNeeded']",
              '    description: Rebooting is a separate decision from patching',
            ]
          : []),
        'mainSteps:',
        '  - action: aws:runShellScript',
        '    name: run',
        '    precondition:',
        '      StringEquals: [platformType, Linux]',
        '    inputs:',
        '      timeoutSeconds: 3600',
        '      runCommand:',
        '        - set -euo pipefail',
        '        - |',
        '          if [ "{{ DryRun }}" = "true" ]; then',
        `            echo "DRY RUN: would ${whatItDoes.toLowerCase()} on $(hostname)"`,
        '            exit 0',
        '          fi',
        `        - '# --- the work: ${whatItDoes} ---'`,
        '        - echo "replace this step"',
        '',
      ].join('\n');

      const association = {
        Name: docName,
        AssociationName: `${base}-association`,
        Targets: targetTag
          ? [{ Key: `tag:${targetTag.split('=')[0]}`, Values: [targetTag.split('=')[1] ?? '<REQUIRED>'] }]
          : [{ Key: 'tag:<REQUIRED>', Values: ['<REQUIRED>'] }],
        Parameters: { DryRun: ['true'] },
        ScheduleExpression: 'cron(0 3 ? * SUN *)',
        MaxConcurrency: concurrency,
        MaxErrors: errorThreshold,
        ComplianceSeverity: 'MEDIUM',
        ApplyOnlyAtCronInterval: true,
      };

      return {
        platform: PLATFORM,
        title: `${docName} — ${whatItDoes}`,
        effect: reboot ? 'irreversible' : 'reversible',
        trigger: { kind: 'schedule', detail: 'Weekly, Sunday 03:00 UTC, through a State Manager association', worstCase: `once a week across every instance tagged ${targetTag || '(nothing — see the finding)'}` },
        scope: {
          what: targetTag ? `Managed instances tagged ${targetTag}.` : 'Every managed instance — no target is set.',
          decidedBy: ['The target tag on the association.', 'Which instances have the SSM agent and an instance profile.', `The concurrency: ${concurrency} at a time.`],
          ifWrong: `It runs on instances you did not mean, ${concurrency} at a time, stopping after ${errorThreshold} failures. Those last two numbers are what turn a mistake into a contained one.`,
        },
        guardrails: [
          { rule: `Targets by tag: ${targetTag || 'NOT SET'}`, because: 'The alternative is every managed instance in the account, and that is a single click in the console.' },
          { rule: `At most ${concurrency} at a time`, because: 'If it is going to break them, it should break a few before anybody notices, not all of them.' },
          { rule: `Stops after ${errorThreshold} failures`, because: 'The first failure is information. The four hundredth is an incident review.' },
          { rule: 'DryRun defaults to true', because: 'The association is created reporting. Flip the parameter when the report reads correctly.' },
          ...(reboot ? [{ rule: 'Rebooting is a separate parameter', because: 'Patching and rebooting are two decisions and two maintenance windows.' }] : []),
        ],
        dryRun: ['The association is created with DryRun=true. Let it run once on the schedule and read the command output for a sample of instances.'],
        undo: reboot
          ? ['A reboot cannot be undone. Whatever was in memory on those instances is gone, which is why the reboot option is separate and off.']
          : ['Depends on the work. Record enough in the output to put it back, and treat that output as the undo.'],
        told: ['Command history in Systems Manager, and compliance status on the association. Neither pages anybody — wire a CloudWatch Events rule to the failure if somebody needs to know.'],
        requires: ['The SSM agent and an instance profile with the managed policy on every target.', 'The tag actually applied to the instances you mean — check with a Resource Groups query first.'],
        files: { [`${base}.yaml`]: doc, [`${base}-association.json`]: `${JSON.stringify(association, null, 2)}\n` },
        notes: [
          'Targeting by tag means the estate can add itself to the automation by tagging. That is the feature and the risk in the same sentence.',
          'ApplyOnlyAtCronInterval stops the association running the moment it is created, which is otherwise the default and a surprise.',
        ],
        findings,
      };
    },
  }),

  automationBlueprint({
    id: 'pipe_awx_template',
    platform: PLATFORM,
    label: 'AWX or Tower job template',
    group: 'Ansible',
    description:
      'A job template for the playbooks this toolkit already writes: credentials from AWX rather than from the repository, a check-mode run first, limits so a wrong inventory does not become a wrong estate, and a survey when a human has to choose.',
    inputs: [
      { id: 'template_name', label: 'Template name', control: 'text', default: 'Patch Linux — standard group' },
      { id: 'playbook', label: 'Playbook', control: 'text', default: 'playbooks/patch.yml' },
      { id: 'inventory', label: 'Inventory', control: 'text', default: 'Production Linux' },
      { id: 'limit', label: 'Limit to', control: 'text', default: 'linux_standard', hint: 'A group. An empty limit is the whole inventory' },
      { id: 'forks', label: 'Hosts at a time', control: 'number', default: 10, min: 1, max: 200 },
      { id: 'check_first', label: 'Run in check mode first', control: 'toggle', default: true },
      { id: 'ask_for_approval', label: 'Needs approval in the workflow', control: 'toggle', default: false },
    ],
    automation: (values: BlueprintValues, name: string): Automation => {
      const templateName = str(values, 'template_name', 'Job template');
      const playbook = str(values, 'playbook', 'site.yml');
      const inventory = str(values, 'inventory', 'Production');
      const limit = str(values, 'limit', '');
      const forks = num(values, 'forks', 10);
      const checkFirst = bool(values, 'check_first', true);
      const approval = bool(values, 'ask_for_approval', false);
      const base = slugOf(name || templateName, 'job-template');

      const findings: Finding[] = [];
      if (!limit) {
        findings.push(
          warning('pipe.awx.no-limit', `No limit is set, so this runs against every host in "${inventory}".`, {
            remediation: 'Set a limit to a group. An inventory grows; a limit is a deliberate statement about what this template is for.',
            source: 'ArchToolKit',
          }),
        );
      }

      const template = {
        name: templateName,
        job_type: 'run',
        inventory,
        playbook,
        limit,
        forks,
        ask_limit_on_launch: true,
        ask_variables_on_launch: true,
        job_tags: '',
        become_enabled: true,
        // Credentials are attached in AWX, never in the repository.
        credentials: ['<REQUIRED — machine credential>', '<OPTIONAL — vault credential>'],
        survey_enabled: true,
        verbosity: 1,
      };

      const workflow = {
        name: `${templateName} — workflow`,
        description: 'ArchToolKit: check mode, then approval, then the real run.',
        nodes: [
          ...(checkFirst ? [{ identifier: 'check', unified_job_template: templateName, job_type: 'check', success_nodes: approval ? ['approve'] : ['run'] }] : []),
          ...(approval ? [{ identifier: 'approve', approval_node: { name: 'Read the check-mode output before approving', timeout: 86400 }, success_nodes: ['run'] }] : []),
          { identifier: 'run', unified_job_template: templateName, job_type: 'run' },
        ],
      };

      return {
        platform: PLATFORM,
        title: `${templateName} — ${playbook} against ${limit || inventory}`,
        effect: 'reversible',
        trigger: { kind: 'schedule', detail: 'Whatever schedule you attach in AWX, or launched by hand', worstCase: `every host in ${limit || inventory}, ${forks} at a time` },
        scope: {
          what: limit ? `Hosts in the group "${limit}" of inventory "${inventory}".` : `Every host in inventory "${inventory}".`,
          decidedBy: ['The inventory and how it is populated — a dynamic inventory changes under you.', limit ? `The limit: ${limit}.` : 'No limit.', 'Any limit typed at launch, which overrides the one above.'],
          ifWrong: 'The playbook runs somewhere it should not. Ansible is idempotent, which helps, and not harmless, which people forget.',
        },
        guardrails: [
          ...(checkFirst ? [{ rule: 'Check mode runs first in the workflow', because: 'Check mode is Ansible’s dry run and it is free. The output is the list of what would change.' }] : []),
          ...(approval ? [{ rule: 'A human approves between check and run', because: 'The approval is only worth having if the check-mode output is in front of the approver. Link it in the approval description.' }] : []),
          { rule: `${forks} hosts at a time`, because: 'A playbook that breaks things should break a few first.' },
          { rule: 'Credentials come from AWX', because: 'A vault password in the repository is a vault password in everyone’s clone.' },
        ],
        dryRun: ['Launch the check-mode node on its own and read the changed list.', 'Not every module supports check mode — the ones that do not are the ones to read twice.'],
        undo: ['Ansible does not roll back. The undo is another playbook, and if the change is significant it should be written before the change is run.'],
        told: ['The job output in AWX, kept per its retention. Set a notification on failure — a silent failed job is worse than a loud one.'],
        requires: [`The inventory "${inventory}" and the group "${limit || '(none)'}".`, 'A machine credential in AWX, and a vault credential if the playbook uses one.'],
        files: { [`${base}.json`]: `${JSON.stringify(template, null, 2)}\n`, [`${base}-workflow.json`]: `${JSON.stringify(workflow, null, 2)}\n` },
        notes: [
          'ask_limit_on_launch is on, which lets somebody narrow the run at launch. It also lets them widen it — the limit on the template is a default, not a ceiling.',
          'A dynamic inventory means the scope is decided at launch by something else entirely. Check what populates it before trusting the limit.',
        ],
        findings,
      };
    },
  }),

  automationBlueprint({
    id: 'pipe_ci_terraform',
    platform: PLATFORM,
    label: 'Plan on a pull request, apply on merge',
    group: 'CI',
    description:
      'The pipeline for the Terraform this toolkit writes: plan on every pull request with the output posted back, apply only from the default branch, state locked, and credentials from the platform’s identity rather than a secret in the repository.',
    inputs: [
      {
        id: 'ci',
        label: 'Runs on',
        control: 'select',
        options: [
          { value: 'github', label: 'GitHub Actions' },
          { value: 'azdo', label: 'Azure Pipelines' },
        ],
        default: 'github',
      },
      { id: 'working_dir', label: 'Terraform lives in', control: 'text', default: 'infra/' },
      {
        id: 'cloud',
        label: 'Against',
        control: 'select',
        options: [
          { value: 'azure', label: 'Azure' },
          { value: 'aws', label: 'AWS' },
          { value: 'vsphere', label: 'vSphere' },
        ],
        default: 'azure',
      },
      { id: 'require_approval', label: 'Apply needs an environment approval', control: 'toggle', default: true },
      { id: 'auto_apply', label: 'Apply automatically on merge', control: 'toggle', default: false },
    ],
    automation: (values: BlueprintValues, name: string): Automation => {
      const ci = str(values, 'ci', 'github');
      const dir = str(values, 'working_dir', 'infra/');
      const cloud = str(values, 'cloud', 'azure');
      const approval = bool(values, 'require_approval', true);
      const autoApply = bool(values, 'auto_apply', false);
      const base = slugOf(name || `terraform-${ci}`, 'terraform-pipeline');

      const findings: Finding[] = [];
      if (autoApply && !approval) {
        findings.push(
          error('pipe.ci.unattended-apply', 'A merge applies to the estate with no human in the loop.', {
            remediation: 'For a well-tested module set that is a deliberate choice. For anything else, put an environment approval on the apply — the plan is only useful if somebody reads it.',
            source: 'ArchToolKit',
          }),
        );
      }
      if (cloud === 'vsphere') {
        findings.push(
          warning('pipe.ci.vsphere-credentials', 'vSphere has no workload identity, so this needs a real credential in the CI secret store.', {
            remediation: 'Use a service account scoped to exactly what the Terraform manages, rotate it on a schedule, and never put it in the repository.',
            source: 'ArchToolKit',
          }),
        );
      }

      const githubYaml = [
        'name: Terraform',
        '',
        '# Generated by ArchToolKit.',
        '#',
        '# Plan on every pull request; apply only from the default branch. The',
        '# credential comes from OIDC rather than a stored secret, so there is',
        '# nothing to rotate and nothing to leak.',
        'on:',
        '  pull_request:',
        `    paths: ['${dir}**']`,
        '  push:',
        '    branches: [main]',
        `    paths: ['${dir}**']`,
        '',
        'permissions:',
        '  contents: read',
        '  id-token: write        # OIDC. This is what replaces a stored credential.',
        '  pull-requests: write   # so the plan can be posted back',
        '',
        'concurrency:',
        '  # One run at a time against the same state. Terraform locks, but a',
        '  # queued second run holding a lock is a confusing way to find that out.',
        '  group: terraform-${{ github.ref }}',
        '  cancel-in-progress: false',
        '',
        'jobs:',
        '  plan:',
        '    runs-on: ubuntu-latest',
        '    defaults:',
        '      run:',
        `        working-directory: ${dir}`,
        '    steps:',
        '      - uses: actions/checkout@v4',
        ...(cloud === 'azure'
          ? [
              '      - uses: azure/login@v2',
              '        with:',
              '          client-id: ${{ vars.AZURE_CLIENT_ID }}',
              '          tenant-id: ${{ vars.AZURE_TENANT_ID }}',
              '          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}',
            ]
          : cloud === 'aws'
            ? [
                '      - uses: aws-actions/configure-aws-credentials@v4',
                '        with:',
                '          role-to-assume: ${{ vars.AWS_ROLE_ARN }}',
                '          aws-region: ${{ vars.AWS_REGION }}',
              ]
            : [
                '      # vSphere has no workload identity. These come from the secret',
                '      # store, scoped to exactly what this Terraform manages.',
                '      - name: vSphere credentials',
                '        run: |',
                '          echo "TF_VAR_vsphere_user=${{ secrets.VSPHERE_USER }}" >> $GITHUB_ENV',
                '          echo "TF_VAR_vsphere_password=${{ secrets.VSPHERE_PASSWORD }}" >> $GITHUB_ENV',
              ]),
        '      - uses: hashicorp/setup-terraform@v3',
        '      - run: terraform fmt -check -recursive',
        '      - run: terraform init',
        '      - run: terraform validate',
        '      - name: Plan',
        '        id: plan',
        '        run: terraform plan -no-color -lock-timeout=5m -out=tfplan',
        '      - name: Post the plan on the pull request',
        "        if: github.event_name == 'pull_request'",
        '        uses: actions/github-script@v7',
        '        with:',
        '          script: |',
        '            const fs = require("fs");',
        '            const plan = fs.readFileSync(process.env.GITHUB_WORKSPACE + "/plan.txt", "utf8").slice(0, 60000);',
        '            await github.rest.issues.createComment({',
        '              issue_number: context.issue.number,',
        '              owner: context.repo.owner,',
        '              repo: context.repo.repo,',
        '              body: "```\\n" + plan + "\\n```",',
        '            });',
        '        continue-on-error: true',
        '      - uses: actions/upload-artifact@v4',
        '        with:',
        '          name: tfplan',
        `          path: ${dir}tfplan`,
        '',
        '  apply:',
        "    if: github.ref == 'refs/heads/main' && github.event_name == 'push'",
        '    needs: plan',
        '    runs-on: ubuntu-latest',
        ...(approval ? ['    # The environment carries the approval. That is where a human reads', '    # the plan before anything reaches the estate.', '    environment: production'] : []),
        '    defaults:',
        '      run:',
        `        working-directory: ${dir}`,
        '    steps:',
        '      - uses: actions/checkout@v4',
        '      - uses: actions/download-artifact@v4',
        '        with:',
        '          name: tfplan',
        `          path: ${dir}`,
        '      - uses: hashicorp/setup-terraform@v3',
        '      - run: terraform init',
        '      - name: Apply the plan that was reviewed',
        '        run: terraform apply -auto-approve -lock-timeout=5m tfplan',
        '',
      ].join('\n');

      const azdoYaml = [
        '# Generated by ArchToolKit.',
        '#',
        '# Plan on a pull request, apply from main behind an environment approval.',
        'trigger:',
        '  branches: { include: [main] }',
        `  paths: { include: ['${dir}'] }`,
        'pr:',
        '  branches: { include: ["*"] }',
        `  paths: { include: ['${dir}'] }`,
        '',
        'pool:',
        '  vmImage: ubuntu-latest',
        '',
        'variables:',
        `  workingDirectory: ${dir}`,
        '',
        'stages:',
        '  - stage: plan',
        '    jobs:',
        '      - job: plan',
        '        steps:',
        '          - task: TerraformInstaller@1',
        '          - script: terraform init',
        '            workingDirectory: $(workingDirectory)',
        '          - script: terraform validate',
        '            workingDirectory: $(workingDirectory)',
        '          - script: terraform plan -no-color -lock-timeout=5m -out=tfplan',
        '            workingDirectory: $(workingDirectory)',
        '          - publish: $(workingDirectory)/tfplan',
        '            artifact: tfplan',
        '',
        '  - stage: apply',
        "    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))",
        '    jobs:',
        '      - deployment: apply',
        '        # The environment is where the approval lives.',
        `        environment: ${approval ? 'production' : 'production-unattended'}`,
        '        strategy:',
        '          runOnce:',
        '            deploy:',
        '              steps:',
        '                - download: current',
        '                  artifact: tfplan',
        '                - task: TerraformInstaller@1',
        '                - script: terraform init',
        '                  workingDirectory: $(workingDirectory)',
        '                - script: terraform apply -auto-approve -lock-timeout=5m $(Pipeline.Workspace)/tfplan/tfplan',
        '                  workingDirectory: $(workingDirectory)',
        '',
      ].join('\n');

      return {
        platform: PLATFORM,
        title: `Terraform on ${ci === 'github' ? 'GitHub Actions' : 'Azure Pipelines'} — plan on a pull request, apply from main`,
        effect: 'reversible',
        trigger: { kind: 'commit', detail: `A pull request touching ${dir} plans; a merge to main applies${approval ? ' after an approval' : ''}`, worstCase: 'as often as people merge' },
        scope: {
          what: `Whatever the Terraform in ${dir} manages, against ${cloud}.`,
          decidedBy: ['The state file the backend points at.', 'The identity the pipeline assumes and what it is allowed to touch.', 'The contents of the plan, which is the only place this is visible before it happens.'],
          ifWrong: 'Terraform destroys and recreates without being asked twice. The plan is where that is visible, which is why it is posted on the pull request rather than buried in a log.',
        },
        guardrails: [
          { rule: 'Apply runs the plan that was reviewed, not a fresh one', because: 'A re-planned apply can do something the reviewer never saw, because the world changed in between.' },
          ...(approval ? [{ rule: 'An environment approval gates the apply', because: 'The plan is only worth producing if somebody reads it.' }] : []),
          { rule: 'One run at a time against the same state', because: 'Terraform locks, but a queued run holding a lock is a confusing way to discover that.' },
          { rule: 'A lock timeout of five minutes', because: 'The default waits forever, and a job that hangs forever is a job nobody notices has hung.' },
          ...(cloud !== 'vsphere' ? [{ rule: 'OIDC rather than a stored credential', because: 'Nothing to rotate, nothing to leak, and it expires on its own.' }] : []),
        ],
        dryRun: ['The plan job is the dry run, and it runs on every pull request. Read it — particularly the destroy lines.'],
        undo: ['Revert the commit and let the pipeline apply the revert. That is the only undo that leaves state and code agreeing.'],
        told: ['The plan is posted on the pull request. The apply is in the run log. Add a notification on apply failure — a half-applied change is the one to know about.'],
        requires: [
          'A remote backend with locking. Local state in CI is a corrupted state file waiting for a concurrent run.',
          cloud === 'vsphere' ? 'A vSphere service account in the secret store.' : 'A federated identity credential trusting this repository, and the roles it needs.',
        ],
        files: ci === 'github' ? { '.github/workflows/terraform.yml': githubYaml } : { 'azure-pipelines-terraform.yml': azdoYaml },
        notes: [
          'Apply the saved plan rather than re-planning. It is the difference between applying what was reviewed and applying what is true now.',
          'terraform fmt -check in the plan job keeps the diff about the change rather than about whitespace.',
        ],
        findings,
      };
    },
  }),
];
