/**
 * VCF Operations: setting it up.
 *
 * Before any alert or automation means anything, VCF Operations has to be
 * collecting from the right places, able to tell somebody, and giving the right
 * people the right view. Three things, and each has a way of going wrong that
 * nobody notices until an incident: an adapter on an administrator's personal
 * account that stops when they leave, an outbound plugin that has never sent a
 * message, a role granted on the whole estate because scoping it was fiddly.
 */

import { bool, str, type BlueprintValues } from '../../kit/blueprint.ts';
import { error, warning, type Finding } from '../../core/findings.ts';
import { automationBlueprint, type AutomationBlueprint } from '../from-automation.ts';
import { listOf, slugOf, type Automation } from '../automation.ts';
import { applyScript, authHeader, authPreamble } from '../apply.ts';

const PLATFORM = 'vcf-operations' as const;
const SRC = 'ArchToolKit';

export const VCF_OPERATIONS_SETUP: readonly AutomationBlueprint[] = [
  // -------------------------------------------------------------------------
  automationBlueprint({
    id: 'vcfops_adapter_instance',
    platform: PLATFORM,
    label: 'Collect from a vCenter',
    group: 'Setup',
    description:
      'A vCenter adapter instance on a named collector group, with its credential created separately and read from the environment at apply time. Written with a service account in mind, because the commonest reason an estate goes quiet in VCF Operations is an adapter running on somebody’s personal login.',
    inputs: [
      { id: 'vcenter', label: 'vCenter', control: 'text', default: 'vcenter01.example.com' },
      { id: 'account', label: 'Service account', control: 'text', default: 'svc-vcfops-collect@vsphere.local', hint: 'Read-only, plus the action rights if you will run actions' },
      { id: 'collector_group', label: 'Collector group', control: 'text', default: 'Site A collectors' },
      { id: 'actions', label: 'Enable actions on this vCenter', control: 'toggle', default: false },
    ],
    automation: (values: BlueprintValues, name: string): Automation => {
      const vcenter = str(values, 'vcenter', '');
      const account = str(values, 'account', '');
      const group = str(values, 'collector_group', '');
      const actions = bool(values, 'actions', false);
      const base = slugOf(name || vcenter, 'adapter');

      const findings: Finding[] = [];
      if (/^administrator@|^root$|^admin/i.test(account)) {
        findings.push(
          error('vcfops.adapter.admin-account', `${account} is a built-in administrator.`, {
            remediation: 'Create a service account with read-only rights (and the action rights, if needed). An administrator credential in a monitoring tool is the widest credential in the estate held by the least-watched system.',
            source: SRC,
          }),
        );
      } else if (!/svc|service|srv|collect/i.test(account)) {
        findings.push(
          warning('vcfops.adapter.personal', `${account} does not look like a service account.`, {
            remediation: 'When a person leaves, their account is disabled and collection stops. Nothing in VCF Operations alerts on that loudly — see the self-check in this kit.',
            source: SRC,
          }),
        );
      }
      if (!group.trim()) {
        findings.push(warning('vcfops.adapter.no-group', 'No collector group, so the adapter lands on whichever collector is chosen for it and cannot fail over.', { source: SRC }));
      }

      const credential = {
        name: `${vcenter} — ${account}`,
        adapterKindKey: 'VMWARE',
        credentialKindKey: 'PRINCIPALCREDENTIAL',
        fields: [
          { name: 'USER', value: account },
          { name: 'PASSWORD', value: '__FROM_ENVIRONMENT__' },
        ],
      };
      const adapter = {
        name: vcenter,
        description: 'Generated by ArchToolKit.',
        collectorGroupId: '<REQUIRED — GET /suite-api/api/collectorgroups and take the id of ' + (group || 'the group') + '>',
        adapterKindKey: 'VMWARE',
        resourceIdentifiers: [
          { name: 'VCURL', value: vcenter },
          { name: 'AUTODISCOVERY', value: 'true' },
          { name: 'PROCESSCHANGEEVENTS', value: 'true' },
          { name: 'VM_LIMIT', value: '' },
        ],
        credential: { id: '__CREDENTIAL_ID__' },
      };

      const apply = [
        '#!/usr/bin/env bash',
        `# Add ${vcenter} to VCF Operations: the credential first, then the adapter`,
        '# instance that uses it. The password comes from VCENTER_PASSWORD and is',
        '# only ever in memory. Without --execute this prints what it would send.',
        'set -euo pipefail',
        ...authPreamble('vcf-operations'),
        ': "${VCENTER_PASSWORD:?set VCENTER_PASSWORD for the service account}"',
        'command -v jq >/dev/null || { echo "jq is required" >&2; exit 2; }',
        'DRY_RUN=1; [[ "${1:-}" == "--execute" ]] && DRY_RUN=0',
        'post() {',
        '  curl -sS -f -X POST "https://${VCFOPS_HOST}/suite-api/api/$1" \\',
        `    -H "${authHeader('vcf-operations')}" -H "Accept: application/json" -H "Content-Type: application/json" \\`,
        '    --data-binary @-',
        '}',
        '# post PATH reads the body from stdin, so nothing sensitive is ever an argument.',
        'if (( DRY_RUN )); then',
        `  echo "DRY RUN: would create the credential and the adapter instance for ${vcenter}. Re-run with --execute."`,
        '  exit 0',
        'fi',
        '# The password travels through the environment into jq and on stdin into',
        '# curl, so it is never on a command line where ps or /proc could show it.',
        'export VCENTER_PASSWORD',
        `CRED_ID=$(jq '(.fields[] | select(.name=="PASSWORD") | .value) = env.VCENTER_PASSWORD' ${base}-credential.json | post credentials | jq -r .id)`,
        `ADAPTER_ID=$(sed "s/__CREDENTIAL_ID__/$CRED_ID/" ${base}-adapter.json | post adapters | jq -r .id)`,
        'echo "credential $CRED_ID, adapter $ADAPTER_ID"',
        '# The adapter is created stopped. Accept its certificate, then start it:',
        'echo "Next: accept the vCenter certificate in the interface, then PUT /suite-api/api/adapters/$ADAPTER_ID/monitoringstate/start"',
        '',
      ].join('\n');

      return {
        platform: PLATFORM,
        title: `Collect from ${vcenter} as ${account}`,
        effect: 'reversible',
        trigger: { kind: 'manual', detail: 'Applied once, when a vCenter is added to monitoring.' },
        scope: {
          what: `Every object in ${vcenter} that ${account} can see.`,
          decidedBy: [`The permissions of ${account} in vCenter — collection sees exactly what the account sees.`, `The collector group "${group}", which decides which proxies do the work.`],
          ifWrong: 'An account with too little visibility produces a monitoring gap that looks like an empty cluster; one with too much is a credential worth stealing.',
        },
        guardrails: [
          { rule: 'The password is read from the environment at apply time', because: 'A credential in a payload file is a credential in every copy of the repository.' },
          { rule: 'Created stopped, started deliberately', because: 'Accepting the certificate is a check that you are talking to the vCenter you think you are.' },
          ...(actions ? [{ rule: 'Actions enabled on purpose, with an account that has exactly the action rights', because: 'Actions run as this account. Its rights are the ceiling on anything automated in this kit.' }] : []),
        ],
        dryRun: ['Run apply.sh without --execute, then check the account in vCenter: Menu → Administration → Access Control → Global Permissions.'],
        undo: ['DELETE /suite-api/api/adapters/{id}. Its objects and their history are removed with it — stop it instead if you may want the history.'],
        told: ['Nobody. The self-check in this kit is what reports an adapter that stops collecting.'],
        requires: [`${account} in vCenter with read-only rights at the root${actions ? ', plus the privileges for the actions you will run' : ''}.`, `The collector group "${group}".`],
        files: {
          [`${base}-credential.json`]: `${JSON.stringify(credential, null, 2)}\n`,
          [`${base}-adapter.json`]: `${JSON.stringify(adapter, null, 2)}\n`,
          'apply.sh': apply,
        },
        notes: ['In VCF 9.1 the management vCenter is usually added by fleet management rather than by hand. Use this for workload vCenters and anything outside the fleet.', 'The resource identifier names (VCURL and the rest) are the VMware adapter’s. Check them against GET /suite-api/api/adapterkinds/VMWARE/resourcekinds on your version.'],
        findings,
      };
    },
  }),

  // -------------------------------------------------------------------------
  automationBlueprint({
    id: 'vcfops_outbound_plugin',
    platform: PLATFORM,
    label: 'An outbound plugin: email, webhook, syslog or SNMP',
    group: 'Setup',
    description:
      'The instance that notification rules send through. Generated with a test step, because an outbound plugin that has never sent a message is indistinguishable from one that works — until the night it matters.',
    inputs: [
      {
        id: 'kind',
        label: 'Type',
        control: 'select',
        options: [
          { value: 'StandardEmailPlugin', label: 'Email (SMTP)' },
          { value: 'WebhookPlugin', label: 'Webhook' },
          { value: 'SyslogPlugin', label: 'Syslog' },
          { value: 'SNMPTrapPlugin', label: 'SNMP trap' },
        ],
        default: 'StandardEmailPlugin',
      },
      { id: 'instance_name', label: 'Instance name', control: 'text', default: 'Platform team mail relay' },
      { id: 'host', label: 'Server or URL', control: 'text', default: 'smtp.example.com' },
      { id: 'port', label: 'Port', control: 'text', default: '587' },
      { id: 'secure', label: 'Encrypted (TLS)', control: 'toggle', default: true },
      { id: 'sender', label: 'Send as', control: 'text', default: 'vcf-operations@example.com', showWhen: { input: 'kind', equals: ['StandardEmailPlugin'] } },
    ],
    automation: (values: BlueprintValues, name: string): Automation => {
      const kind = str(values, 'kind', 'StandardEmailPlugin');
      const instance = str(values, 'instance_name', 'Outbound');
      const host = str(values, 'host', '');
      const port = str(values, 'port', '');
      const secure = bool(values, 'secure', true);
      const sender = str(values, 'sender', '');
      const base = slugOf(name || instance, 'outbound');

      const findings: Finding[] = [];
      if (!secure) {
        findings.push(warning('vcfops.outbound.cleartext', 'Alerts will leave VCF Operations unencrypted, and they name hosts, VMs and faults.', { source: SRC }));
      }
      if (kind === 'SNMPTrapPlugin') {
        findings.push(warning('vcfops.outbound.snmp', 'SNMP traps are fire-and-forget: nothing confirms one arrived.', { remediation: 'Use SNMPv3, and prefer a webhook where the receiver can acknowledge.', source: SRC }));
      }

      const configValues: { name: string; value: string }[] =
        kind === 'StandardEmailPlugin'
          ? [
              { name: 'SMTP_HOST', value: host },
              { name: 'SMTP_PORT', value: port },
              { name: 'IS_SECURE_CONNECTION', value: String(secure) },
              { name: 'senderEmailAddress', value: sender },
              { name: 'senderName', value: 'VCF Operations' },
            ]
          : kind === 'WebhookPlugin'
            ? [{ name: 'Url', value: host }, { name: 'ConnectionCount', value: '20' }]
            : kind === 'SyslogPlugin'
              ? [{ name: 'host', value: host }, { name: 'port', value: port }, { name: 'protocol', value: secure ? 'TCP' : 'UDP' }]
              : [{ name: 'destination_host', value: host }, { name: 'port', value: port }, { name: 'version', value: 'v3' }];

      const payload = { pluginTypeId: kind, name: instance, configValues };

      return {
        platform: PLATFORM,
        title: `${instance} — ${kind.replace('Plugin', '').replace('Standard', '')} outbound to ${host}`,
        effect: 'reversible',
        trigger: { kind: 'manual', detail: 'Applied once. It sends only when a notification rule uses it.' },
        scope: {
          what: `Every notification rule that names "${instance}".`,
          decidedBy: ['The notification rules attached to it — the plugin itself decides nothing about what is sent.'],
          ifWrong: 'Notifications go nowhere, silently. The rules look configured and the alerts look raised.',
        },
        guardrails: [
          { rule: 'Tested before any rule depends on it', because: 'The Test button in the plugin editor is the only moment anyone sees it fail.' },
          ...(secure ? [{ rule: 'Encrypted in transit', because: 'Alert text names systems and faults; it is reconnaissance for anyone on the path.' }] : []),
        ],
        dryRun: ['Run apply.sh without --execute. After applying, open the instance and press Test — then check the message actually arrived.'],
        undo: ['DELETE /suite-api/api/alertplugins/{id}. Rules that use it stop sending; they do not fail loudly.'],
        told: ['Whoever the rules send to, through this instance.'],
        requires: [kind === 'StandardEmailPlugin' ? `Your mail relay to accept ${sender} from the VCF Operations nodes.` : `A route from the VCF Operations nodes to ${host}:${port}.`, 'Any credential for the target entered in the interface, not in this file.'],
        files: {
          [`${base}.json`]: `${JSON.stringify(payload, null, 2)}\n`,
          'apply.sh': applyScript('vcf-operations', [{ method: 'POST', path: '/suite-api/api/alertplugins', payload: `${base}.json` }], 'DELETE /suite-api/api/alertplugins/{id}.'),
        },
        notes: ['Config value names differ between plugin types and releases. GET /suite-api/api/alertplugins/types lists the fields your version expects; match them before applying.', 'Created disabled until enabled: PUT /suite-api/api/alertplugins/{id}/enable/true once the test has passed.'],
        findings,
      };
    },
  }),

  // -------------------------------------------------------------------------
  automationBlueprint({
    id: 'vcfops_access',
    platform: PLATFORM,
    label: 'Give a team a role on part of the estate',
    group: 'Setup',
    description:
      'A directory group imported with a role and a scope, so an application team sees its own VMs and the platform team sees everything. Written against groups rather than people, and against a scope rather than the whole estate, because both are the shortcuts that get taken.',
    inputs: [
      { id: 'group', label: 'Directory group', control: 'text', default: 'APP-Payments-Ops' },
      { id: 'source', label: 'Authentication source', control: 'text', default: 'Corporate AD' },
      {
        id: 'role',
        label: 'Role',
        control: 'select',
        options: [
          { value: 'ReadOnly', label: 'Read only' },
          { value: 'ContentAdmin', label: 'Content administrator' },
          { value: 'PowerUser', label: 'Power user' },
          { value: 'Administrator', label: 'Administrator — see the finding' },
        ],
        default: 'ReadOnly',
      },
      { id: 'scope_objects', label: 'On these objects', control: 'text', default: 'Payments VMs', hint: 'Custom groups or containers. Empty means everything' },
    ],
    automation: (values: BlueprintValues, name: string): Automation => {
      const group = str(values, 'group', '');
      const source = str(values, 'source', '');
      const role = str(values, 'role', 'ReadOnly');
      const scope = listOf(str(values, 'scope_objects', ''));
      const base = slugOf(name || `${group}-${role}`, 'access');

      const findings: Finding[] = [];
      if (role === 'Administrator') {
        findings.push(warning('vcfops.access.admin', 'Administrator includes managing adapters, credentials and every other user.', { remediation: 'Keep it to the platform team. Content administrator covers dashboards, alerts and policies.', source: SRC }));
      }
      if (scope.length === 0 && role !== 'ReadOnly') {
        findings.push(warning('vcfops.access.unscoped', `${role} on every object in the estate.`, { remediation: 'Scope it to the custom groups the team owns.', source: SRC }));
      }
      if (/@/.test(group)) {
        findings.push(warning('vcfops.access.person', `${group} looks like a person rather than a group.`, { remediation: 'Grant to groups. People move teams, and a grant to a person moves with them.', source: SRC }));
      }

      // Field names are hyphenated in this API. Scope is a traversal spec plus
      // the ids of the objects within it — not the object's name.
      const payload = {
        authSourceId: `<REQUIRED — GET /suite-api/api/auth/sources and take the id of ${source}>`,
        name: group,
        'role-permissions': [
          {
            roleName: role,
            allowAllObjects: scope.length === 0,
            'traversal-spec-instances': scope.length === 0 ? [] : [
              {
                adapterKind: 'Container',
                resourceKind: 'Environment',
                name: '<REQUIRED — GET /suite-api/api/auth/traversalspecs and take the name of the Custom Groups spec>',
                resourceSelection: [
                  {
                    type: 'PROPAGATE',
                    resourceId: scope.map((object) => `<REQUIRED — the id of the custom group "${object}">`),
                  },
                ],
              },
            ],
          },
        ],
      };

      return {
        platform: PLATFORM,
        title: `${group} — ${role} on ${scope.join(', ') || 'the whole estate'}`,
        effect: 'reversible',
        trigger: { kind: 'manual', detail: 'Applied once, as an access change.' },
        scope: {
          what: `Members of ${group}, on ${scope.join(', ') || 'every object'}.`,
          decidedBy: [`Membership of ${group} in ${source} — which is managed outside VCF Operations.`, `The role ${role}.`, scope.length > 0 ? `The objects ${scope.join(', ')} and everything under them.` : 'No scope: every object.'],
          ifWrong: 'People see or change what they should not, and because membership is in the directory, the change that caused it is not in VCF Operations at all.',
        },
        guardrails: [
          { rule: 'Granted to a directory group', because: 'Leavers are removed from the directory once; nobody remembers every tool they had access to.' },
          ...(scope.length > 0 ? [{ rule: `Scoped to ${scope.join(', ')}`, because: 'A team that sees only its own VMs gets dashboards that make sense to it.' }] : []),
        ],
        dryRun: ['After applying, sign in as a member (or use Access Control → the group → Objects) and check what is visible.'],
        undo: ['DELETE /suite-api/api/auth/usergroups/{id}. Members lose access at their next sign-in.'],
        told: ['Nobody automatically. Record the grant with the access request that asked for it.'],
        requires: [`The authentication source "${source}" configured, and ${group} present in it.`, scope.length > 0 ? 'The custom groups named in the scope.' : 'Nothing else.'],
        files: {
          [`${base}.json`]: `${JSON.stringify(payload, null, 2)}\n`,
          'apply.sh': applyScript('vcf-operations', [{ method: 'POST', path: '/suite-api/api/auth/usergroups', payload: `${base}.json` }], 'DELETE /suite-api/api/auth/usergroups/{id}.'),
        },
        notes: ['Compare the payload with GET /suite-api/api/auth/usergroups for a group already scoped the same way in the interface — the traversal spec name and selection type are the parts that differ between releases.', 'Role names are the internal ones. GET /suite-api/api/auth/roles lists what your instance calls them, including any custom roles.', 'In VCF 9.1 identity is shared across the fleet; if the group already has access through VCF SSO, check that before adding a second grant here.'],
        findings,
      };
    },
  }),
];
