/**
 * F5 BIG-IP: the rest of the gaps.
 *
 * The first two files publish applications and the profiles immediately around
 * them. What was missing is the behaviour layer: iRules, persistence, the
 * connection reuse and compression profiles that decide how the BIG-IP talks to
 * the pool, certificate lifecycle, a maintenance page that answers instead of
 * refusing, and GSLB — the one part of a BIG-IP that is not about a single
 * data centre at all.
 *
 * All AS3 declarations, so each one is a whole tenant. AS3 replaces the tenant
 * it is given, so a declaration has to contain everything that tenant should
 * have — which is why each change here says so in its notes.
 */

import { bool, num, str, type BlueprintValues } from '../../kit/blueprint.ts';
import { error, warning, type Finding } from '../../core/findings.ts';
import { deviceBlueprint, type ChangeBlueprint } from '../from-change.ts';
import { isIpv4, listOf, type DeviceChange } from '../device.ts';

const PLATFORM = 'f5' as const;

function declaration(tenant: string, application: string, label: string, body: Record<string, unknown>): string[] {
  return JSON.stringify(
    {
      $schema: 'https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/main/schema/latest/as3-schema.json',
      class: 'AS3',
      action: 'deploy',
      persist: true,
      declaration: {
        class: 'ADC',
        schemaVersion: '3.45.0',
        id: `archtoolkit-${application.toLowerCase()}`,
        label,
        remark: 'Generated by ArchToolKit — review before deploying.',
        [tenant]: { class: 'Tenant', [application]: { class: 'Application', template: 'generic', ...body } },
      },
    },
    null,
    2,
  ).split('\n');
}

const clean = (value: string, fallback: string): string => (str({ v: value }, 'v', fallback) || fallback).replace(/[^A-Za-z0-9_]/g, '_');

const as3Push = (tenant: string, app: string): DeviceChange['push'] => ({
  module: 'f5networks.f5_bigip.bigip_as3_deploy',
  args: { content: `{{ lookup('file', '${app}.json') }}`, tenant, state: 'present' },
  hosts: 'bigips',
});

export const F5_EXTRA_2: readonly ChangeBlueprint[] = [
  deviceBlueprint({
    id: 'f5_persistence',
    platform: PLATFORM,
    label: 'Persistence',
    group: 'Profiles',
    description: 'Keep a client on the same pool member for the life of its session — by cookie, by source address, or by something in the request.',
    inputs: [
      { id: 'tenant', label: 'Tenant', control: 'text', default: 'Prod' },
      { id: 'application', label: 'Application', control: 'text', default: 'app1' },
      { id: 'method', label: 'Method', control: 'select', default: 'cookie', options: [
        { value: 'cookie', label: 'Cookie — the BIG-IP inserts one, HTTP only' },
        { value: 'source-address', label: 'Source address — works for anything, defeated by NAT' },
        { value: 'ssl-session', label: 'TLS session id — survives a source address change' },
        { value: 'universal', label: 'Universal — keyed by an iRule expression' },
      ] },
      { id: 'timeout', label: 'Timeout (seconds)', control: 'number', default: 3600, min: 1, max: 604800 },
      { id: 'cookie_name', label: 'Cookie name', control: 'text', default: 'BIGIPSERVER', showWhen: { input: 'method', equals: ['cookie'] } },
      { id: 'cookie_encrypt', label: 'Encrypt the cookie', control: 'toggle', default: true, showWhen: { input: 'method', equals: ['cookie'] } },
      { id: 'mask', label: 'Source address mask', control: 'text', default: '255.255.255.255', showWhen: { input: 'method', equals: ['source-address'] } },
      { id: 'mirror', label: 'Mirror persistence to the peer', control: 'toggle', default: true },
      { id: 'fallback', label: 'Fallback when the member is gone', control: 'select', default: 'rebalance', options: [
        { value: 'rebalance', label: 'Pick a new member and re-persist' },
        { value: 'none', label: 'Reset the connection' },
      ] },
      { id: 'pool_members', label: 'Pool members', control: 'textarea', default: '10.1.1.10:8080\n10.1.1.11:8080' },
      { id: 'virtual_address', label: 'Virtual address', control: 'text', default: '10.1.10.100' },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const tenant = clean(str(values, 'tenant', 'Prod'), 'Prod');
      const app = clean(str(values, 'application', 'app1'), 'app1');
      const method = str(values, 'method', 'cookie');
      const timeout = num(values, 'timeout', 3600);
      const virtual = str(values, 'virtual_address', '');
      const servers = listOf(str(values, 'pool_members', '').replace(/\n/g, ','));
      const findings: Finding[] = [];
      if (!isIpv4(virtual)) findings.push(error('network.f5.bad-virtual', 'The virtual address is not a valid IPv4 address.', { source: 'ArchToolKit' }));
      if (method === 'source-address' && str(values, 'mask', '') === '255.255.255.255') {
        findings.push(
          warning('network.f5.source-persistence-nat', 'Source address persistence sends every client behind one NAT address to the same pool member. A large office or a mobile carrier then loads one server and leaves the rest idle.', {
            remediation: 'Use cookie persistence for HTTP. Keep source address persistence for protocols that have nothing else to key on.',
            source: 'ArchToolKit',
          }),
        );
      }
      if (method === 'cookie' && !bool(values, 'cookie_encrypt', true)) {
        findings.push(
          warning('network.f5.cookie-plain', 'An unencrypted persistence cookie contains the pool member’s address and port in an easily decoded form, which hands out the internal addressing to anyone who looks.', { source: 'ArchToolKit' }),
        );
      }
      if (timeout > 86400) {
        findings.push(warning('network.f5.persistence-long', 'A persistence record that lives for more than a day keeps clients pinned long after the session that needed it, and makes a member impossible to drain quickly.', { source: 'ArchToolKit' }));
      }

      const persistClass =
        method === 'cookie'
          ? { class: 'Persist', persistenceMethod: 'cookie', cookieMethod: 'insert', cookieName: str(values, 'cookie_name', 'BIGIPSERVER'), encrypt: bool(values, 'cookie_encrypt', true), duration: timeout, mirror: bool(values, 'mirror', true) }
          : method === 'source-address'
            ? { class: 'Persist', persistenceMethod: 'source-address', addressMask: str(values, 'mask', '255.255.255.255'), duration: timeout, mirror: bool(values, 'mirror', true) }
            : method === 'ssl-session'
              ? { class: 'Persist', persistenceMethod: 'tls-session-id', duration: timeout, mirror: bool(values, 'mirror', true) }
              : { class: 'Persist', persistenceMethod: 'universal', iRule: { use: `${app}_persist_rule` }, duration: timeout, mirror: bool(values, 'mirror', true) };

      return {
        platform: PLATFORM,
        title: `${method} persistence for ${tenant}/${app}`,
        impact: 'brief',
        notes: [
          'AS3 replaces the whole tenant. This declaration must contain every application that tenant should have, not only the one being changed — take the current declaration first and merge.',
          'Changing persistence does not move existing connections. Clients already pinned stay where they are until their record expires.',
          'Persistence and load balancing pull in opposite directions. A pool that looks unbalanced under persistence is usually working correctly.',
          ...(method === 'cookie' ? ['Cookie persistence needs an HTTP profile on the virtual server. Without one there is nowhere to insert the cookie and it silently does nothing.'] : []),
        ],
        before: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} > ${tenant}-before.json`,
          `tmsh show ltm persistence persist-records`,
          `tmsh show ltm pool /${tenant}/${app}/${app}_pool members`,
        ],
        config: declaration(tenant, app, `${app} with ${method} persistence`, {
          [`${app}_persist`]: persistClass,
          ...(method === 'universal'
            ? { [`${app}_persist_rule`]: { class: 'iRule', iRule: 'when HTTP_REQUEST {\n  persist uie [HTTP::header "X-Session-Id"]\n}' } }
            : {}),
          [`${app}_pool`]: {
            class: 'Pool',
            monitors: ['http'],
            members: [{ servicePort: Number(servers[0]?.split(':')[1] ?? 8080), serverAddresses: servers.map((s) => s.split(':')[0] ?? s) }],
          },
          serviceMain: {
            class: method === 'cookie' ? 'Service_HTTP' : 'Service_TCP',
            virtualAddresses: [virtual],
            pool: `${app}_pool`,
            persistenceMethods: [{ use: `${app}_persist` }],
            ...(str(values, 'fallback', 'rebalance') === 'rebalance' ? { fallbackPersistenceMethod: 'source-address' } : {}),
          },
        }),
        verify: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} | jq .`,
          'tmsh show ltm persistence persist-records',
          `tmsh show ltm pool /${tenant}/${app}/${app}_pool members`,
          `${'!'} From a client: make several requests and confirm they land on the same member`,
          ...(method === 'cookie' ? [`curl -skI https://${virtual}/ | grep -i ${str(values, 'cookie_name', 'BIGIPSERVER')}`] : []),
        ],
        backout: [`curl -sku $USER -X POST https://bigip/mgmt/shared/appsvcs/declare -d @${tenant}-before.json`],
        push: as3Push(tenant, app),
      };
    },
  }),

  deviceBlueprint({
    id: 'f5_irule',
    platform: PLATFORM,
    label: 'iRule',
    group: 'Behaviour',
    description: 'A small piece of logic on the data path: redirect by host, route by URI, add a security header, or block a path — from a handful of patterns rather than a blank editor.',
    inputs: [
      { id: 'tenant', label: 'Tenant', control: 'text', default: 'Prod' },
      { id: 'application', label: 'Application', control: 'text', default: 'app1' },
      { id: 'pattern', label: 'What it does', control: 'select', default: 'uri-routing', options: [
        { value: 'uri-routing', label: 'Route by URI to a second pool' },
        { value: 'host-redirect', label: 'Redirect one hostname to another' },
        { value: 'security-headers', label: 'Add security response headers' },
        { value: 'block-paths', label: 'Block paths, allow everything else' },
        { value: 'maintenance', label: 'Serve a maintenance page when the pool is empty' },
      ] },
      { id: 'match_uri', label: 'URI prefix', control: 'text', default: '/api', showWhen: { input: 'pattern', equals: ['uri-routing'] } },
      { id: 'second_pool', label: 'Second pool members', control: 'textarea', default: '10.1.2.10:8080\n10.1.2.11:8080', showWhen: { input: 'pattern', equals: ['uri-routing'] } },
      { id: 'from_host', label: 'From hostname', control: 'text', default: 'old.example.com', showWhen: { input: 'pattern', equals: ['host-redirect'] } },
      { id: 'to_host', label: 'To hostname', control: 'text', default: 'new.example.com', showWhen: { input: 'pattern', equals: ['host-redirect'] } },
      { id: 'blocked_paths', label: 'Blocked paths', control: 'text', default: '/admin, /.git, /.env', showWhen: { input: 'pattern', equals: ['block-paths'] } },
      { id: 'hsts_age', label: 'HSTS max-age (seconds)', control: 'number', default: 31536000, min: 0, showWhen: { input: 'pattern', equals: ['security-headers'] } },
      { id: 'maintenance_text', label: 'Maintenance message', control: 'text', default: 'This service is temporarily unavailable. Please try again shortly.', showWhen: { input: 'pattern', equals: ['maintenance'] } },
      { id: 'pool_members', label: 'Primary pool members', control: 'textarea', default: '10.1.1.10:8080\n10.1.1.11:8080' },
      { id: 'virtual_address', label: 'Virtual address', control: 'text', default: '10.1.10.100' },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const tenant = clean(str(values, 'tenant', 'Prod'), 'Prod');
      const app = clean(str(values, 'application', 'app1'), 'app1');
      const pattern = str(values, 'pattern', 'uri-routing');
      const virtual = str(values, 'virtual_address', '');
      const servers = listOf(str(values, 'pool_members', '').replace(/\n/g, ','));
      const second = listOf(str(values, 'second_pool', '').replace(/\n/g, ','));
      const blocked = listOf(str(values, 'blocked_paths', ''));
      const findings: Finding[] = [];
      if (!isIpv4(virtual)) findings.push(error('network.f5.bad-virtual', 'The virtual address is not a valid IPv4 address.', { source: 'ArchToolKit' }));
      findings.push(
        warning('network.f5.irule-cost', 'An iRule runs on every request it is attached to. A rule doing string work per request is a CPU cost that only shows up at peak, and iRules are rarely the first thing anyone looks at.', {
          remediation: 'Prefer a policy (LTM policy) where one will do the same job — it is evaluated in a faster path.',
          source: 'ArchToolKit',
        }),
      );
      if (pattern === 'block-paths' && blocked.length === 0) {
        findings.push(error('network.f5.no-blocked-paths', 'No path was given to block, so this rule does nothing.', { source: 'ArchToolKit' }));
      }
      if (pattern === 'security-headers') {
        findings.push(
          warning('network.f5.hsts-commitment', 'HSTS is not reversible for clients that have already seen it — they will refuse plain HTTP to this name until the max-age expires. Start with a short max-age and raise it once the certificate and redirects are proven.', {
            source: 'ArchToolKit',
          }),
        );
      }

      const rule =
        pattern === 'uri-routing'
          ? `when HTTP_REQUEST {\n  if { [string tolower [HTTP::uri]] starts_with "${str(values, 'match_uri', '/api')}" } {\n    pool /${tenant}/${app}/${app}_pool_second\n  }\n}`
          : pattern === 'host-redirect'
            ? `when HTTP_REQUEST {\n  if { [string tolower [HTTP::host]] equals "${str(values, 'from_host', '')}" } {\n    HTTP::redirect "https://${str(values, 'to_host', '')}[HTTP::uri]"\n  }\n}`
            : pattern === 'security-headers'
              ? `when HTTP_RESPONSE {\n  HTTP::header replace "Strict-Transport-Security" "max-age=${num(values, 'hsts_age', 31536000)}; includeSubDomains"\n  HTTP::header replace "X-Content-Type-Options" "nosniff"\n  HTTP::header replace "X-Frame-Options" "SAMEORIGIN"\n  HTTP::header replace "Referrer-Policy" "strict-origin-when-cross-origin"\n  HTTP::header remove "Server"\n  HTTP::header remove "X-Powered-By"\n}`
              : pattern === 'block-paths'
                ? `when HTTP_REQUEST {\n  set path [string tolower [HTTP::path]]\n  if { ${blocked.map((p) => `$path starts_with "${p.toLowerCase()}"`).join(' or ')} } {\n    log local0. "Blocked [IP::client_addr] -> [HTTP::path]"\n    HTTP::respond 404 content "Not found"\n    return\n  }\n}`
                : `when HTTP_REQUEST {\n  if { [active_members [LB::server pool]] < 1 } {\n    HTTP::respond 503 content "<html><body><h1>Maintenance</h1><p>${str(values, 'maintenance_text', '')}</p></body></html>" "Content-Type" "text/html" "Retry-After" "300"\n    return\n  }\n}`;

      return {
        platform: PLATFORM,
        title: `iRule (${pattern}) on ${tenant}/${app}`,
        impact: 'brief',
        notes: [
          'AS3 replaces the whole tenant. Take the current declaration first and merge this into it.',
          'An iRule takes effect on the next request, not on existing connections. Test it against a copy of the virtual server before attaching it to the live one.',
          'Log lines in an iRule go to /var/log/ltm on every match. A rule that logs on a busy path fills the disk.',
        ],
        before: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} > ${tenant}-before.json`,
          `tmsh list ltm virtual /${tenant}/${app}/serviceMain rules`,
          `tmsh show ltm pool /${tenant}/${app}/${app}_pool members`,
        ],
        config: declaration(tenant, app, `${app} with a ${pattern} iRule`, {
          [`${app}_rule`]: { class: 'iRule', iRule: rule },
          [`${app}_pool`]: {
            class: 'Pool',
            monitors: ['http'],
            members: [{ servicePort: Number(servers[0]?.split(':')[1] ?? 8080), serverAddresses: servers.map((s) => s.split(':')[0] ?? s) }],
          },
          ...(pattern === 'uri-routing' && second.length > 0
            ? {
                [`${app}_pool_second`]: {
                  class: 'Pool',
                  monitors: ['http'],
                  members: [{ servicePort: Number(second[0]?.split(':')[1] ?? 8080), serverAddresses: second.map((s) => s.split(':')[0] ?? s) }],
                },
              }
            : {}),
          serviceMain: {
            class: 'Service_HTTP',
            virtualAddresses: [virtual],
            pool: `${app}_pool`,
            iRules: [{ use: `${app}_rule` }],
          },
        }),
        verify: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} | jq .`,
          `tmsh list ltm rule /${tenant}/${app}/${app}_rule`,
          ...(pattern === 'uri-routing' ? [`curl -sk https://${virtual}${str(values, 'match_uri', '/api')}/ -o /dev/null -w '%{http_code}\\n'`] : []),
          ...(pattern === 'host-redirect' ? [`curl -skI -H "Host: ${str(values, 'from_host', '')}" https://${virtual}/ | head -5`] : []),
          ...(pattern === 'security-headers' ? [`curl -skI https://${virtual}/ | grep -iE 'strict-transport|x-content-type|x-frame'`] : []),
          ...(pattern === 'block-paths' ? blocked.slice(0, 2).map((p) => `curl -sk https://${virtual}${p} -o /dev/null -w '%{http_code}\\n'`) : []),
          'tail -f /var/log/ltm',
        ],
        backout: [`curl -sku $USER -X POST https://bigip/mgmt/shared/appsvcs/declare -d @${tenant}-before.json`],
        push: as3Push(tenant, app),
      };
    },
  }),

  deviceBlueprint({
    id: 'f5_connection_profiles',
    platform: PLATFORM,
    label: 'Connection reuse, compression and caching',
    group: 'Profiles',
    description: 'The profiles that decide how the BIG-IP talks to the pool and how much work it does for the client: OneConnect, compression, caching and TCP tuning for the WAN side.',
    inputs: [
      { id: 'tenant', label: 'Tenant', control: 'text', default: 'Prod' },
      { id: 'application', label: 'Application', control: 'text', default: 'app1' },
      { id: 'oneconnect', label: 'Connection reuse (OneConnect)', control: 'toggle', default: true },
      { id: 'source_mask', label: 'OneConnect source mask', control: 'text', default: '255.255.255.255', hint: '/32 is the safe default; 0.0.0.0 reuses most aggressively', showWhen: { input: 'oneconnect', equals: ['true'] } },
      { id: 'compression', label: 'Compression', control: 'select', default: 'selective', options: [
        { value: 'selective', label: 'Text content only' },
        { value: 'all', label: 'Everything compressible' },
        { value: 'off', label: 'Off — the application already compresses' },
      ] },
      { id: 'caching', label: 'Cache static responses', control: 'toggle', default: false },
      { id: 'cache_size', label: 'Cache size (MB)', control: 'number', default: 100, min: 1, max: 10000, showWhen: { input: 'caching', equals: ['true'] } },
      { id: 'client_tcp', label: 'Client-side TCP', control: 'select', default: 'wan', options: [
        { value: 'wan', label: 'WAN optimised — internet clients' },
        { value: 'lan', label: 'LAN optimised — clients on the local network' },
      ] },
      { id: 'pool_members', label: 'Pool members', control: 'textarea', default: '10.1.1.10:8080\n10.1.1.11:8080' },
      { id: 'virtual_address', label: 'Virtual address', control: 'text', default: '10.1.10.100' },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const tenant = clean(str(values, 'tenant', 'Prod'), 'Prod');
      const app = clean(str(values, 'application', 'app1'), 'app1');
      const virtual = str(values, 'virtual_address', '');
      const servers = listOf(str(values, 'pool_members', '').replace(/\n/g, ','));
      const oneconnect = bool(values, 'oneconnect', true);
      const mask = str(values, 'source_mask', '255.255.255.255');
      const compression = str(values, 'compression', 'selective');
      const findings: Finding[] = [];
      if (!isIpv4(virtual)) findings.push(error('network.f5.bad-virtual', 'The virtual address is not a valid IPv4 address.', { source: 'ArchToolKit' }));
      if (oneconnect && mask === '0.0.0.0') {
        findings.push(
          warning('network.f5.oneconnect-aggressive', 'A 0.0.0.0 source mask lets any client reuse any existing server connection. With an application that keeps state on the connection — NTLM authentication is the classic case — one user can be served as another.', {
            remediation: 'Use a /32 mask unless the application is known to be stateless on the connection.',
            source: 'ArchToolKit',
          }),
        );
      }
      if (oneconnect) {
        findings.push(
          warning('network.f5.oneconnect-persistence', 'OneConnect and source address persistence interact badly: the persistence record is per connection, and reuse breaks the assumption. Confirm which persistence this virtual server uses before enabling reuse.', { source: 'ArchToolKit' }),
        );
      }
      if (compression !== 'off') {
        findings.push(
          warning('network.f5.compression-cost', 'Compression is CPU work on the BIG-IP for every response. If the application already compresses, doing it again here costs throughput and gains nothing.', { source: 'ArchToolKit' }),
        );
      }

      return {
        platform: PLATFORM,
        title: `Connection profiles for ${tenant}/${app}`,
        impact: 'brief',
        notes: [
          'AS3 replaces the whole tenant. Merge this into the current declaration rather than sending it alone.',
          'These change behaviour for new connections. Existing ones keep whatever they were using.',
          'Measure before and after. Every one of these has a plausible story and a measurable cost, and the only way to know which won is to look at the throughput and CPU graphs.',
        ],
        before: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} > ${tenant}-before.json`,
          `tmsh show ltm virtual /${tenant}/${app}/serviceMain`,
          'tmsh show sys performance throughput',
          'tmsh show sys cpu',
        ],
        config: declaration(tenant, app, `${app} connection and content profiles`, {
          ...(oneconnect ? { [`${app}_oneconnect`]: { class: 'Multiplex_Profile', sourceMask: mask, maxConnections: 10000, maxConnectionAge: 86400, maxConnectionReuse: 1000, idleTimeoutOverride: 60 } } : {}),
          ...(compression !== 'off'
            ? {
                [`${app}_compress`]: {
                  class: 'HTTP_Compress',
                  ...(compression === 'selective'
                    ? { contentTypeIncludes: ['text/', 'application/json', 'application/javascript', 'application/xml', 'image/svg+xml'] }
                    : {}),
                  gzipLevel: 1,
                  minimumSize: 1024,
                },
              }
            : {}),
          ...(bool(values, 'caching', false) ? { [`${app}_cache`]: { class: 'HTTP_Acceleration_Profile', cacheSize: num(values, 'cache_size', 100), maximumObjectSize: 1048576, insertAgeHeader: true } } : {}),
          [`${app}_tcp_client`]: { class: 'TCP_Profile', idleTimeout: 300, nagle: str(values, 'client_tcp', 'wan') === 'wan' ? 'disable' : 'enable', congestionControl: str(values, 'client_tcp', 'wan') === 'wan' ? 'woodside' : 'high-speed' },
          [`${app}_pool`]: {
            class: 'Pool',
            monitors: ['http'],
            members: [{ servicePort: Number(servers[0]?.split(':')[1] ?? 8080), serverAddresses: servers.map((s) => s.split(':')[0] ?? s) }],
          },
          serviceMain: {
            class: 'Service_HTTP',
            virtualAddresses: [virtual],
            pool: `${app}_pool`,
            ...(oneconnect ? { profileMultiplex: { use: `${app}_oneconnect` } } : {}),
            ...(compression !== 'off' ? { profileHTTPCompression: { use: `${app}_compress` } } : {}),
            ...(bool(values, 'caching', false) ? { profileHTTPAcceleration: { use: `${app}_cache` } } : {}),
            profileTCP: { ingress: { use: `${app}_tcp_client` }, egress: 'lan' },
          },
        }),
        verify: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} | jq .`,
          ...(oneconnect ? [`tmsh show ltm profile one-connect /${tenant}/${app}/${app}_oneconnect`] : []),
          ...(compression !== 'off' ? [`curl -skI -H "Accept-Encoding: gzip" https://${virtual}/ | grep -i encoding`] : []),
          'tmsh show sys performance throughput',
          'tmsh show sys cpu',
          `${'!'} Compare the connection count on the pool members before and after`,
        ],
        backout: [`curl -sku $USER -X POST https://bigip/mgmt/shared/appsvcs/declare -d @${tenant}-before.json`],
        push: as3Push(tenant, app),
      };
    },
  }),

  deviceBlueprint({
    id: 'f5_certificate',
    platform: PLATFORM,
    label: 'Certificate replacement',
    group: 'TLS',
    description: 'Replace the certificate on a virtual server, with the chain, the key reference and the cutover order written down — the change most often done at the last minute and under pressure.',
    inputs: [
      { id: 'tenant', label: 'Tenant', control: 'text', default: 'Prod' },
      { id: 'application', label: 'Application', control: 'text', default: 'app1' },
      { id: 'certificate_name', label: 'Certificate object name', control: 'text', default: 'app1_2026' },
      { id: 'common_name', label: 'Common name', control: 'text', default: 'app1.example.com' },
      { id: 'sans', label: 'Subject alternative names', control: 'text', default: 'app1.example.com, www.app1.example.com' },
      { id: 'key_source', label: 'Key', control: 'select', default: 'existing', options: [
        { value: 'existing', label: 'Already installed on the BIG-IP' },
        { value: 'hsm', label: 'Held in an HSM or key manager' },
      ] },
      { id: 'chain', label: 'Include the intermediate chain', control: 'toggle', default: true },
      { id: 'min_tls', label: 'Minimum TLS version', control: 'select', default: 'tls1.2', options: [
        { value: 'tls1.2', label: 'TLS 1.2' },
        { value: 'tls1.3', label: 'TLS 1.3 only' },
      ] },
      { id: 'ciphers', label: 'Cipher group', control: 'select', default: 'strong', options: [
        { value: 'strong', label: 'Forward secrecy only' },
        { value: 'compatible', label: 'Broader compatibility' },
      ] },
      { id: 'pool_members', label: 'Pool members', control: 'textarea', default: '10.1.1.10:8080\n10.1.1.11:8080' },
      { id: 'virtual_address', label: 'Virtual address', control: 'text', default: '10.1.10.100' },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const tenant = clean(str(values, 'tenant', 'Prod'), 'Prod');
      const app = clean(str(values, 'application', 'app1'), 'app1');
      const certName = clean(str(values, 'certificate_name', 'cert'), 'cert');
      const cn = str(values, 'common_name', '');
      const sans = listOf(str(values, 'sans', ''));
      const virtual = str(values, 'virtual_address', '');
      const servers = listOf(str(values, 'pool_members', '').replace(/\n/g, ','));
      const findings: Finding[] = [];
      if (!isIpv4(virtual)) findings.push(error('network.f5.bad-virtual', 'The virtual address is not a valid IPv4 address.', { source: 'ArchToolKit' }));
      if (cn && !sans.some((s) => s.toLowerCase() === cn.toLowerCase())) {
        findings.push(
          error('network.f5.cn-not-in-san', 'The common name is not in the subject alternative names. Every current browser ignores the common name entirely, so clients connecting to that name will see a certificate error.', {
            remediation: 'Include the common name in the SAN list.',
            source: 'ArchToolKit',
          }),
        );
      }
      if (!bool(values, 'chain', true)) {
        findings.push(
          warning('network.f5.no-chain', 'Without the intermediate chain, clients that do not already hold the intermediate will fail to validate. Browsers often recover by fetching it; API clients and mobile apps usually do not, so this breaks exactly the traffic nobody tests.', {
            source: 'ArchToolKit',
          }),
        );
      }
      if (str(values, 'min_tls', 'tls1.2') === 'tls1.3') {
        findings.push(warning('network.f5.tls13-only', 'TLS 1.3 only will refuse anything older, including some payment terminals, embedded clients and older Java runtimes. Check the client population before choosing it.', { source: 'ArchToolKit' }));
      }
      findings.push(
        warning('network.f5.certificate-key-handling', 'The private key is never written into this change. Install it on the BIG-IP separately, or reference the key manager. A key that has been in a change record has to be treated as compromised.', {
          source: 'ArchToolKit',
        }),
      );

      return {
        platform: PLATFORM,
        title: `Certificate ${certName} on ${tenant}/${app}`,
        impact: 'brief',
        notes: [
          'AS3 replaces the whole tenant. Merge this into the current declaration.',
          'Do this before the old certificate expires, not on the day. A rollback needs the old certificate still installed, which it will not be if the window is the expiry date.',
          'Existing TLS sessions keep the old certificate until they renegotiate. The change is visible to new connections first.',
          'Check the chain from outside the network, not from a management host that may already trust the intermediate.',
        ],
        before: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} > ${tenant}-before.json`,
          `tmsh list sys crypto cert ${certName}`,
          `tmsh list ltm profile client-ssl /${tenant}/${app}/${app}_clientssl`,
          `echo | openssl s_client -connect ${virtual}:443 -servername ${cn} 2>/dev/null | openssl x509 -noout -dates -subject`,
        ],
        config: declaration(tenant, app, `${app} with certificate ${certName}`, {
          [certName]: {
            class: 'Certificate',
            certificate: { bigip: `/Common/${certName}.crt` },
            privateKey: { bigip: `/Common/${certName}.key` },
            ...(bool(values, 'chain', true) ? { chainCA: { bigip: `/Common/${certName}-chain.crt` } } : {}),
          },
          [`${app}_clientssl`]: {
            class: 'TLS_Server',
            certificates: [{ certificate: certName }],
            ciphers: str(values, 'ciphers', 'strong') === 'strong' ? 'ECDHE:!SSLv3:!RC4:!EXP:!DES:!MD5:!3DES' : 'DEFAULT:!SSLv3:!RC4:!EXP:!MD5',
            tls1_2Enabled: true,
            tls1_1Enabled: false,
            tls1_0Enabled: false,
            ...(str(values, 'min_tls', 'tls1.2') === 'tls1.3' ? { tls1_2Enabled: false, tls1_3Enabled: true } : {}),
          },
          [`${app}_pool`]: {
            class: 'Pool',
            monitors: ['http'],
            members: [{ servicePort: Number(servers[0]?.split(':')[1] ?? 8080), serverAddresses: servers.map((s) => s.split(':')[0] ?? s) }],
          },
          serviceMain: {
            class: 'Service_HTTPS',
            virtualAddresses: [virtual],
            pool: `${app}_pool`,
            serverTLS: `${app}_clientssl`,
            redirect80: true,
          },
        }),
        verify: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} | jq .`,
          `echo | openssl s_client -connect ${virtual}:443 -servername ${cn} 2>/dev/null | openssl x509 -noout -dates -subject -issuer`,
          `echo | openssl s_client -connect ${virtual}:443 -servername ${cn} -showcerts 2>/dev/null | grep -c 'BEGIN CERTIFICATE'`,
          ...sans.slice(0, 3).map((san) => `curl -skI https://${san}/ --resolve ${san}:443:${virtual} | head -3`),
          `${'!'} Check from outside the network, and from one client that is not a browser`,
        ],
        backout: [`curl -sku $USER -X POST https://bigip/mgmt/shared/appsvcs/declare -d @${tenant}-before.json`],
        push: as3Push(tenant, app),
      };
    },
  }),

  deviceBlueprint({
    id: 'f5_gslb',
    platform: PLATFORM,
    label: 'GSLB wide IP',
    group: 'DNS',
    description: 'Answer a name with whichever data centre should serve it — active/standby, weighted, or by where the client is — which is a DNS decision rather than a load balancing one.',
    inputs: [
      { id: 'tenant', label: 'Tenant', control: 'text', default: 'GSLB' },
      { id: 'application', label: 'Application', control: 'text', default: 'app1' },
      { id: 'domain', label: 'Wide IP name', control: 'text', default: 'app1.example.com' },
      { id: 'method', label: 'How a site is chosen', control: 'select', default: 'global-availability', options: [
        { value: 'global-availability', label: 'Global availability — first healthy site in order' },
        { value: 'ratio', label: 'Ratio — split by weight' },
        { value: 'topology', label: 'Topology — nearest site to the client' },
        { value: 'round-robin', label: 'Round robin' },
      ] },
      { id: 'primary_site', label: 'Primary site virtual address', control: 'text', default: '203.0.113.10' },
      { id: 'secondary_site', label: 'Secondary site virtual address', control: 'text', default: '198.51.100.10' },
      { id: 'primary_ratio', label: 'Primary weight', control: 'number', default: 80, min: 1, max: 100, showWhen: { input: 'method', equals: ['ratio'] } },
      { id: 'ttl', label: 'Record TTL (seconds)', control: 'number', default: 30, min: 1, max: 86400 },
      { id: 'monitor', label: 'Health monitor', control: 'select', default: 'https', options: [
        { value: 'https', label: 'HTTPS' },
        { value: 'http', label: 'HTTP' },
        { value: 'tcp', label: 'TCP' },
      ] },
      { id: 'persist_cidr', label: 'Persist clients by network', control: 'toggle', default: false },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const tenant = clean(str(values, 'tenant', 'GSLB'), 'GSLB');
      const app = clean(str(values, 'application', 'app1'), 'app1');
      const domain = str(values, 'domain', '');
      const method = str(values, 'method', 'global-availability');
      const primary = str(values, 'primary_site', '');
      const secondary = str(values, 'secondary_site', '');
      const ttl = num(values, 'ttl', 30);
      const findings: Finding[] = [];
      if (!isIpv4(primary)) findings.push(error('network.f5.bad-primary', 'The primary site address is not a valid IPv4 address.', { source: 'ArchToolKit' }));
      if (!domain.includes('.')) findings.push(error('network.f5.bad-domain', 'The wide IP name is not a domain name.', { source: 'ArchToolKit' }));
      findings.push(
        warning('network.f5.gslb-dns-caching', `A ${ttl}s TTL is what this BIG-IP asks for. Resolvers, browsers and operating systems all cache independently and some ignore short TTLs entirely — plan for clients to keep using the old site for minutes after a failover, not seconds.`, {
          remediation: 'Do not rely on GSLB alone for a fast failover. It moves new clients, not existing ones.',
          source: 'ArchToolKit',
        }),
      );
      if (method === 'topology') {
        findings.push(warning('network.f5.gslb-topology-records', 'Topology load balancing needs topology records and an up-to-date geolocation database. Without them every client resolves to the same site and the configuration looks correct while doing nothing.', { source: 'ArchToolKit' }));
      }
      if (ttl > 300) {
        findings.push(warning('network.f5.gslb-long-ttl', 'A long TTL means a failover takes that long to reach clients that resolved recently.', { source: 'ArchToolKit' }));
      }

      return {
        platform: PLATFORM,
        title: `GSLB wide IP ${domain}`,
        impact: 'brief',
        notes: [
          'GSLB decides what a name resolves to. It cannot move a connection that has already been made, and it cannot help a client that cached the answer.',
          'Both sites need the BIG-IPs to be in a sync group and to see each other, or each will answer with only its own virtual servers.',
          'The data centres, servers and virtual servers referenced here must already exist in the GSLB configuration. This declaration builds the pool and the wide IP on top of them.',
          'Delegation matters: this only answers if the parent zone delegates the name to these BIG-IPs.',
        ],
        before: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} > ${tenant}-before.json`,
          'tmsh show gtm wideip a',
          'tmsh show gtm pool a',
          'tmsh show gtm server',
          `dig +short ${domain}`,
        ],
        config: declaration(tenant, app, `GSLB for ${domain}`, {
          [`${app}_monitor`]: { class: 'Monitor', monitorType: str(values, 'monitor', 'https'), interval: 10, timeout: 31 },
          [`${app}_pool`]: {
            class: 'GSLB_Pool',
            resourceRecordType: 'A',
            lbModePreferred: method,
            lbModeAlternate: 'round-robin',
            lbModeFallback: 'return-to-dns',
            ttl,
            monitors: [{ use: `${app}_monitor` }],
            members: [
              { server: { bigip: '/Common/dc1-bigip' }, virtualServer: primary, ratio: method === 'ratio' ? num(values, 'primary_ratio', 80) : 1 },
              { server: { bigip: '/Common/dc2-bigip' }, virtualServer: secondary, ratio: method === 'ratio' ? 100 - num(values, 'primary_ratio', 80) : 1 },
            ],
          },
          [`${app}_wideip`]: {
            class: 'GSLB_Domain',
            domainName: domain,
            resourceRecordType: 'A',
            poolLbMode: method,
            pools: [{ use: `${app}_pool` }],
            ...(bool(values, 'persist_cidr', false) ? { persistenceEnabled: true, persistCidrIpv4: 24, ttlPersistence: 3600 } : {}),
          },
        }),
        verify: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} | jq .`,
          `tmsh show gtm wideip a ${domain}`,
          `tmsh show gtm pool a /${tenant}/${app}/${app}_pool`,
          `dig @<this bigip> ${domain}`,
          `${'!'} Take the primary site out of service and confirm the answer changes within the TTL`,
          `dig +short ${domain}`,
        ],
        backout: [`curl -sku $USER -X POST https://bigip/mgmt/shared/appsvcs/declare -d @${tenant}-before.json`],
        push: as3Push(tenant, app),
      };
    },
  }),

  deviceBlueprint({
    id: 'f5_ltm_policy',
    platform: PLATFORM,
    label: 'LTM policy',
    group: 'Behaviour',
    description: 'Route, redirect and rewrite by rule rather than by script — the faster path an iRule should be traded for whenever the logic fits.',
    inputs: [
      { id: 'tenant', label: 'Tenant', control: 'text', default: 'Prod' },
      { id: 'application', label: 'Application', control: 'text', default: 'app1' },
      { id: 'rules', label: 'Rules', control: 'textarea', default: 'api  /api    pool  api\nimg  /images pool  static\nold  /legacy redirect https://new.example.com', hint: 'One per line: name  path-prefix  pool|redirect  target' },
      { id: 'api_members', label: 'Second pool members', control: 'textarea', default: '10.1.2.10:8080\n10.1.2.11:8080' },
      { id: 'static_members', label: 'Third pool members', control: 'textarea', default: '10.1.3.10:8080' },
      { id: 'pool_members', label: 'Default pool members', control: 'textarea', default: '10.1.1.10:8080\n10.1.1.11:8080' },
      { id: 'virtual_address', label: 'Virtual address', control: 'text', default: '10.1.10.100' },
      { id: 'strategy', label: 'When more than one rule matches', control: 'select', default: 'best-match', options: [
        { value: 'best-match', label: 'Best match — the most specific rule wins' },
        { value: 'first-match', label: 'First match — the order in the list wins' },
        { value: 'all-match', label: 'All match — every matching rule applies' },
      ] },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const tenant = clean(str(values, 'tenant', 'Prod'), 'Prod');
      const app = clean(str(values, 'application', 'app1'), 'app1');
      const virtual = str(values, 'virtual_address', '');
      const servers = listOf(str(values, 'pool_members', '').replace(/\n/g, ','));
      const api = listOf(str(values, 'api_members', '').replace(/\n/g, ','));
      const staticPool = listOf(str(values, 'static_members', '').replace(/\n/g, ','));
      const parsed = str(values, 'rules', '')
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .map((line) => line.split(/\s+/))
        .filter((parts) => parts.length >= 4);
      const findings: Finding[] = [];
      if (!isIpv4(virtual)) findings.push(error('network.f5.bad-virtual', 'The virtual address is not a valid IPv4 address.', { source: 'ArchToolKit' }));
      if (parsed.length === 0) {
        findings.push(error('network.f5.no-policy-rules', 'No rule could be read. Each line needs a name, a path prefix, "pool" or "redirect", and a target.', { source: 'ArchToolKit' }));
      }
      if (str(values, 'strategy', 'best-match') === 'all-match') {
        findings.push(
          warning('network.f5.all-match', 'With all-match every matching rule applies, in order, and a later rule can undo an earlier one. It is the strategy that produces behaviour nobody can predict from reading the list.', {
            remediation: 'Use best-match unless the rules are genuinely independent.',
            source: 'ArchToolKit',
          }),
        );
      }

      const pools: Record<string, unknown> = {
        [`${app}_pool`]: { class: 'Pool', monitors: ['http'], members: [{ servicePort: Number(servers[0]?.split(':')[1] ?? 8080), serverAddresses: servers.map((s) => s.split(':')[0] ?? s) }] },
      };
      if (api.length > 0) pools[`${app}_pool_api`] = { class: 'Pool', monitors: ['http'], members: [{ servicePort: Number(api[0]?.split(':')[1] ?? 8080), serverAddresses: api.map((s) => s.split(':')[0] ?? s) }] };
      if (staticPool.length > 0) pools[`${app}_pool_static`] = { class: 'Pool', monitors: ['http'], members: [{ servicePort: Number(staticPool[0]?.split(':')[1] ?? 8080), serverAddresses: staticPool.map((s) => s.split(':')[0] ?? s) }] };

      return {
        platform: PLATFORM,
        title: `LTM policy with ${parsed.length} rule${parsed.length === 1 ? '' : 's'} on ${tenant}/${app}`,
        impact: 'brief',
        notes: [
          'AS3 replaces the whole tenant. Merge this into the current declaration.',
          'A policy is evaluated in a faster path than an iRule and is far easier to read six months later. Anything a policy can express should be a policy.',
          'Rules are matched against the request. A request that matches nothing goes to the default pool, which is why the default pool still matters.',
        ],
        before: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} > ${tenant}-before.json`,
          `tmsh list ltm policy /${tenant}/${app}/${app}_policy`,
          `tmsh show ltm virtual /${tenant}/${app}/serviceMain`,
        ],
        config: declaration(tenant, app, `${app} with an LTM policy`, {
          ...pools,
          [`${app}_policy`]: {
            class: 'Endpoint_Policy',
            strategy: str(values, 'strategy', 'best-match'),
            rules: parsed.map(([name, path, action, target], index) => ({
              name: clean(name ?? `rule${index}`, `rule${index}`),
              conditions: [{ type: 'httpUri', path: { operand: 'starts-with', values: [path ?? '/'] } }],
              actions:
                action === 'redirect'
                  ? [{ type: 'httpRedirect', location: target ?? '/' }]
                  : [{ type: 'forward', event: 'request', select: { pool: { use: target === 'api' ? `${app}_pool_api` : target === 'static' ? `${app}_pool_static` : `${app}_pool` } } }],
            })),
          },
          serviceMain: {
            class: 'Service_HTTP',
            virtualAddresses: [virtual],
            pool: `${app}_pool`,
            policyEndpoint: `${app}_policy`,
          },
        }),
        verify: [
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} | jq .`,
          `tmsh list ltm policy /${tenant}/${app}/${app}_policy`,
          ...parsed.slice(0, 3).map(([, path]) => `curl -sk https://${virtual}${path ?? '/'}/ -o /dev/null -w '%{http_code}\\n'`),
          `tmsh show ltm pool /${tenant}/${app}/${app}_pool members`,
          `${'!'} Confirm each path reaches the pool it was meant to`,
        ],
        backout: [`curl -sku $USER -X POST https://bigip/mgmt/shared/appsvcs/declare -d @${tenant}-before.json`],
        push: as3Push(tenant, app),
      };
    },
  }),
];
