/**
 * F5 BIG-IP, as AS3 declarations.
 *
 * A BIG-IP can be configured three ways: tmsh by hand, iControl REST object by
 * object, or a declaration that says what the application should look like and
 * lets the device work out the difference. The declaration is the one worth
 * generating: it is idempotent, it is reviewable as a whole, and it is the same
 * artefact whether it is posted by hand, by Ansible, or by a pipeline.
 *
 * So these blueprints emit AS3 JSON rather than tmsh, and the Data Editor
 * already carries the AS3 schema — a declaration generated here can be opened
 * there and checked against it.
 *
 * Certificates and keys are never written into a declaration here. Where TLS is
 * wanted, the declaration references a certificate that already exists on the
 * device, and says so.
 */

import { bool, num, str, type BlueprintValues, type BlueprintGroup } from '../../kit/blueprint.ts';
import { error, warning, type Finding } from '../../core/findings.ts';
import { deviceBlueprint, type ChangeBlueprint } from '../from-change.ts';
import { F5_EXTRA } from './f5-extra.ts';
import { F5_EXTRA_2 } from './f5-extra2.ts';
import { isIpv4, listOf, type DeviceChange } from '../device.ts';

const PLATFORM = 'f5' as const;

/** AS3 wraps everything in a declaration with a tenant and an application. */
interface As3Options {
  readonly tenant: string;
  readonly application: string;
  readonly label: string;
  readonly body: Record<string, unknown>;
}

function declaration({ tenant, application, label, body }: As3Options): Record<string, unknown> {
  return {
    $schema: 'https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/main/schema/latest/as3-schema.json',
    class: 'AS3',
    action: 'deploy',
    persist: true,
    declaration: {
      class: 'ADC',
      schemaVersion: '3.45.0',
      id: `archtoolkit-${application.toLowerCase()}`,
      label,
      remark: 'Generated by ArchToolKit — review before deploying.',
      [tenant]: {
        class: 'Tenant',
        [application]: {
          class: 'Application',
          template: 'generic',
          ...body,
        },
      },
    },
  };
}

const json = (value: unknown): string[] => JSON.stringify(value, null, 2).split('\n');

/** Members typed as "10.20.30.11:443, 10.20.30.12:443". */
function members(value: string, defaultPort: number): { servers: string[]; port: number } {
  const parts = listOf(value);
  let port = defaultPort;
  const servers: string[] = [];
  for (const part of parts) {
    const [address, typed] = part.split(':');
    if (address) servers.push(address);
    if (typed && Number.isFinite(Number(typed))) port = Number(typed);
  }
  return { servers, port };
}

const BLUEPRINTS: readonly ChangeBlueprint[] = [
  deviceBlueprint({
    id: 'f5_http_virtual',
    platform: PLATFORM,
    label: 'HTTP or HTTPS virtual server',
    group: 'Applications',
    description: 'A virtual server with a pool, a health monitor and optional TLS — the whole application as one AS3 declaration.',
    inputs: [
      { id: 'tenant', label: 'Tenant (partition)', control: 'text', default: 'Prod' },
      { id: 'application', label: 'Application name', control: 'text', default: 'web_app' },
      { id: 'virtual_address', label: 'Virtual address', control: 'text', default: '203.0.113.20' },
      { id: 'port', label: 'Virtual port', control: 'number', default: 443, min: 1, max: 65535 },
      { id: 'pool_members', label: 'Pool members', control: 'textarea', default: '10.20.30.11:8080\n10.20.30.12:8080', hint: 'One per line: address:port' },
      { id: 'monitor', label: 'Health monitor', control: 'select', default: 'http', options: [
        { value: 'http', label: 'HTTP — a request and an expected response' },
        { value: 'https', label: 'HTTPS' },
        { value: 'tcp', label: 'TCP — the port answers' },
      ] },
      { id: 'monitor_path', label: 'Monitor path', control: 'text', default: '/health', showWhen: { input: 'monitor', equals: ['http', 'https'] } },
      { id: 'monitor_expect', label: 'Expected in the response', control: 'text', default: 'HTTP/1.1 200', showWhen: { input: 'monitor', equals: ['http', 'https'] } },
      { id: 'lb_method', label: 'Load balancing method', control: 'select', default: 'least-connections-member', options: [
        { value: 'least-connections-member', label: 'Least connections' },
        { value: 'round-robin', label: 'Round robin' },
        { value: 'predictive-member', label: 'Predictive' },
      ] },
      { id: 'tls', label: 'Terminate TLS', control: 'toggle', default: true },
      { id: 'certificate', label: 'Certificate on the device', control: 'text', default: '/Common/wildcard-corp', hint: 'A certificate that already exists. None is generated here.', showWhen: { input: 'tls', equals: ['true'] } },
      { id: 'redirect_http', label: 'Redirect port 80 to HTTPS', control: 'toggle', default: true, showWhen: { input: 'tls', equals: ['true'] } },
      { id: 'persistence', label: 'Persistence', control: 'select', default: 'cookie', options: [
        { value: 'cookie', label: 'Cookie' },
        { value: 'source-address', label: 'Source address' },
        { value: 'none', label: 'None' },
      ] },
      { id: 'snat', label: 'SNAT automap', control: 'toggle', default: true, hint: 'On unless the servers route back through the BIG-IP' },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const tenant = str(values, 'tenant', 'Prod').replace(/[^A-Za-z0-9_]/g, '_');
      const app = str(values, 'application', 'app').replace(/[^A-Za-z0-9_]/g, '_');
      const address = str(values, 'virtual_address', '');
      const port = num(values, 'port', 443);
      const tls = bool(values, 'tls', true);
      const monitorKind = str(values, 'monitor', 'http');
      const pool = members(str(values, 'pool_members', '').replace(/\n/g, ','), 8080);
      const persistence = str(values, 'persistence', 'cookie');
      const findings: Finding[] = [];

      if (!isIpv4(address)) findings.push(error('network.f5.bad-virtual-address', 'The virtual address is not a valid IPv4 address.', { source: 'ArchToolKit' }));
      if (pool.servers.length === 0) findings.push(error('network.f5.no-members', 'The pool has no members, so the virtual server would be down the moment it is created.', { source: 'ArchToolKit' }));
      if (pool.servers.length === 1) {
        findings.push(warning('network.f5.single-member', 'One pool member is a load balancer in front of a single point of failure.', { source: 'ArchToolKit' }));
      }
      if (tls) {
        findings.push(
          warning('network.f5.certificate-reference', `The declaration references the certificate ${str(values, 'certificate', '')} rather than carrying one. It must already exist on the device.`, {
            remediation: 'Import the certificate and key on the BIG-IP first; nothing here generates or uploads them.',
            source: 'ArchToolKit',
          }),
        );
      }

      const monitorName = `${app}_monitor`;
      const body: Record<string, unknown> = {
        [monitorName]:
          monitorKind === 'tcp'
            ? { class: 'Monitor', monitorType: 'tcp', interval: 5, timeout: 16 }
            : {
                class: 'Monitor',
                monitorType: monitorKind,
                interval: 5,
                timeout: 16,
                send: `GET ${str(values, 'monitor_path', '/health')} HTTP/1.1\\r\\nHost: ${address}\\r\\nConnection: Close\\r\\n\\r\\n`,
                receive: str(values, 'monitor_expect', 'HTTP/1.1 200'),
              },
        [`${app}_pool`]: {
          class: 'Pool',
          loadBalancingMode: str(values, 'lb_method', 'least-connections-member'),
          monitors: [{ use: monitorName }],
          members: [{ servicePort: pool.port, serverAddresses: pool.servers, shareNodes: true }],
        },
        service: {
          class: tls ? 'Service_HTTPS' : 'Service_HTTP',
          virtualAddresses: [address],
          virtualPort: port,
          pool: `${app}_pool`,
          snat: bool(values, 'snat', true) ? 'auto' : 'none',
          ...(persistence !== 'none' ? { persistenceMethods: [persistence] } : { persistenceMethods: [] }),
          ...(tls
            ? {
                serverTLS: {
                  bigip: str(values, 'certificate', '/Common/default.crt'),
                },
                redirect80: bool(values, 'redirect_http', true),
              }
            : {}),
        },
      };

      const config = json(declaration({ tenant, application: app, label: `${app} on ${address}:${port}`, body }));

      return {
        platform: PLATFORM,
        title: `${tls ? 'HTTPS' : 'HTTP'} virtual server ${address}:${port} for ${app}`,
        impact: 'brief',
        notes: [
          'AS3 replaces the whole tenant it is given. Anything in this tenant that is not in the declaration is removed — so deploy to a tenant this application owns, not a shared one.',
          'Post it to /mgmt/shared/appsvcs/declare. The AS3 extension has to be installed on the BIG-IP first.',
          ...(tls ? ['The certificate is referenced, not supplied. Import it on the device beforehand.'] : []),
        ],
        before: [
          'curl -sku $USER https://bigip/mgmt/shared/appsvcs/info',
          `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} > ${tenant}-before.json`,
          `tmsh list ltm virtual /${tenant}/${app}/service`,
        ],
        config,
        verify: [
          `tmsh show ltm pool /${tenant}/${app}/${app}_pool members`,
          `tmsh show ltm virtual /${tenant}/${app}/service`,
          `curl -skI https://${address}:${port}/`,
        ],
        backout: [
          `# Re-post the declaration captured before the change:`,
          `curl -sku $USER -X POST https://bigip/mgmt/shared/appsvcs/declare -d @${tenant}-before.json`,
          `# Or remove the tenant entirely:`,
          `curl -sku $USER -X DELETE https://bigip/mgmt/shared/appsvcs/declare/${tenant}`,
        ],
        push: {
          module: 'f5networks.f5_modules.bigip_as3_deploy',
          args: { content: `{{ lookup('file', '${app}.json') }}`, tenant, provider: '{{ provider }}', state: 'present' },
          hosts: 'bigips',
        },
        findings,
      };
    },
  }),

  deviceBlueprint({
    id: 'f5_tcp_virtual',
    platform: PLATFORM,
    label: 'TCP virtual server',
    group: 'Applications',
    description: 'A layer 4 virtual server for a non-HTTP service — a database, a message broker, a custom protocol.',
    inputs: [
      { id: 'tenant', label: 'Tenant (partition)', control: 'text', default: 'Prod' },
      { id: 'application', label: 'Application name', control: 'text', default: 'db_service' },
      { id: 'virtual_address', label: 'Virtual address', control: 'text', default: '203.0.113.30' },
      { id: 'port', label: 'Virtual port', control: 'number', default: 5432, min: 1, max: 65535 },
      { id: 'pool_members', label: 'Pool members', control: 'textarea', default: '10.20.40.11:5432\n10.20.40.12:5432' },
      { id: 'lb_method', label: 'Load balancing method', control: 'select', default: 'least-connections-member', options: [
        { value: 'least-connections-member', label: 'Least connections' },
        { value: 'round-robin', label: 'Round robin' },
      ] },
      { id: 'persistence', label: 'Persistence', control: 'select', default: 'source-address', options: [
        { value: 'source-address', label: 'Source address' },
        { value: 'none', label: 'None' },
      ] },
      { id: 'idle_timeout', label: 'Idle timeout (seconds)', control: 'number', default: 300, min: 5, hint: 'Long-lived connections need this raised' },
      { id: 'snat', label: 'SNAT automap', control: 'toggle', default: true },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const tenant = str(values, 'tenant', 'Prod').replace(/[^A-Za-z0-9_]/g, '_');
      const app = str(values, 'application', 'service').replace(/[^A-Za-z0-9_]/g, '_');
      const address = str(values, 'virtual_address', '');
      const port = num(values, 'port', 5432);
      const pool = members(str(values, 'pool_members', '').replace(/\n/g, ','), port);
      const persistence = str(values, 'persistence', 'source-address');
      const findings: Finding[] = [];
      if (!isIpv4(address)) findings.push(error('network.f5.bad-virtual-address', 'The virtual address is not a valid IPv4 address.', { source: 'ArchToolKit' }));
      if (pool.servers.length === 0) findings.push(error('network.f5.no-members', 'The pool has no members.', { source: 'ArchToolKit' }));

      const body: Record<string, unknown> = {
        [`${app}_monitor`]: { class: 'Monitor', monitorType: 'tcp', interval: 5, timeout: 16 },
        [`${app}_tcp`]: { class: 'TCP_Profile', idleTimeout: num(values, 'idle_timeout', 300) },
        [`${app}_pool`]: {
          class: 'Pool',
          loadBalancingMode: str(values, 'lb_method', 'least-connections-member'),
          monitors: [{ use: `${app}_monitor` }],
          members: [{ servicePort: pool.port, serverAddresses: pool.servers, shareNodes: true }],
        },
        service: {
          class: 'Service_TCP',
          virtualAddresses: [address],
          virtualPort: port,
          pool: `${app}_pool`,
          profileTCP: { use: `${app}_tcp` },
          snat: bool(values, 'snat', true) ? 'auto' : 'none',
          persistenceMethods: persistence === 'none' ? [] : [persistence],
        },
      };

      return {
        platform: PLATFORM,
        title: `TCP virtual server ${address}:${port} for ${app}`,
        impact: 'brief',
        notes: [
          'AS3 replaces the whole tenant. Capture the current declaration first — the back-out is re-posting it.',
          'A TCP monitor only proves the port answers. If the service can accept a connection while being broken, write a receive string instead.',
        ],
        before: [`curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} > ${tenant}-before.json`, `tmsh list ltm virtual /${tenant}/${app}/service`],
        config: json(declaration({ tenant, application: app, label: `${app} on ${address}:${port}`, body })),
        verify: [`tmsh show ltm pool /${tenant}/${app}/${app}_pool members`, `tmsh show ltm virtual /${tenant}/${app}/service`],
        backout: [`curl -sku $USER -X POST https://bigip/mgmt/shared/appsvcs/declare -d @${tenant}-before.json`],
        push: {
          module: 'f5networks.f5_modules.bigip_as3_deploy',
          args: { content: `{{ lookup('file', '${app}.json') }}`, tenant, provider: '{{ provider }}', state: 'present' },
          hosts: 'bigips',
        },
        findings,
      };
    },
  }),

  deviceBlueprint({
    id: 'f5_waf_policy',
    platform: PLATFORM,
    label: 'HTTPS virtual server with a WAF policy',
    group: 'Applications',
    description: 'The same application, with an Advanced WAF policy attached in blocking or transparent mode.',
    inputs: [
      { id: 'tenant', label: 'Tenant (partition)', control: 'text', default: 'Prod' },
      { id: 'application', label: 'Application name', control: 'text', default: 'public_web' },
      { id: 'virtual_address', label: 'Virtual address', control: 'text', default: '203.0.113.40' },
      { id: 'pool_members', label: 'Pool members', control: 'textarea', default: '10.20.50.11:8080\n10.20.50.12:8080' },
      { id: 'certificate', label: 'Certificate on the device', control: 'text', default: '/Common/wildcard-corp' },
      { id: 'policy_template', label: 'WAF policy template', control: 'select', default: 'POLICY_TEMPLATE_RAPID_DEPLOYMENT', options: [
        { value: 'POLICY_TEMPLATE_RAPID_DEPLOYMENT', label: 'Rapid deployment' },
        { value: 'POLICY_TEMPLATE_API_SECURITY', label: 'API security' },
        { value: 'POLICY_TEMPLATE_FUNDAMENTAL', label: 'Fundamental' },
      ] },
      { id: 'enforcement', label: 'Enforcement mode', control: 'select', default: 'transparent', options: [
        { value: 'transparent', label: 'Transparent — log only' },
        { value: 'blocking', label: 'Blocking — enforce' },
      ] },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const tenant = str(values, 'tenant', 'Prod').replace(/[^A-Za-z0-9_]/g, '_');
      const app = str(values, 'application', 'app').replace(/[^A-Za-z0-9_]/g, '_');
      const address = str(values, 'virtual_address', '');
      const pool = members(str(values, 'pool_members', '').replace(/\n/g, ','), 8080);
      const enforcement = str(values, 'enforcement', 'transparent');
      const findings: Finding[] = [];
      if (!isIpv4(address)) findings.push(error('network.f5.bad-virtual-address', 'The virtual address is not a valid IPv4 address.', { source: 'ArchToolKit' }));
      if (enforcement === 'blocking') {
        findings.push(
          warning('network.f5.waf-blocking', 'Blocking mode from day one will drop legitimate traffic that the policy has not learned yet.', {
            remediation: 'Run it transparent, read the violations for a week, then switch to blocking.',
            source: 'ArchToolKit',
          }),
        );
      }

      const body: Record<string, unknown> = {
        [`${app}_monitor`]: { class: 'Monitor', monitorType: 'http', interval: 5, timeout: 16, send: 'GET /health HTTP/1.1\\r\\nConnection: Close\\r\\n\\r\\n', receive: '200' },
        [`${app}_pool`]: {
          class: 'Pool',
          loadBalancingMode: 'least-connections-member',
          monitors: [{ use: `${app}_monitor` }],
          members: [{ servicePort: pool.port, serverAddresses: pool.servers, shareNodes: true }],
        },
        [`${app}_waf`]: {
          class: 'WAF_Policy',
          policy: {
            text: JSON.stringify({
              policy: {
                name: `${app}_waf`,
                template: { name: str(values, 'policy_template', 'POLICY_TEMPLATE_RAPID_DEPLOYMENT') },
                enforcementMode: enforcement,
              },
            }),
          },
          ignoreChanges: true,
        },
        service: {
          class: 'Service_HTTPS',
          virtualAddresses: [address],
          virtualPort: 443,
          pool: `${app}_pool`,
          snat: 'auto',
          policyWAF: { use: `${app}_waf` },
          serverTLS: { bigip: str(values, 'certificate', '/Common/default.crt') },
          redirect80: true,
          persistenceMethods: ['cookie'],
        },
      };

      return {
        platform: PLATFORM,
        title: `HTTPS virtual server with WAF (${enforcement}) for ${app}`,
        impact: 'brief',
        notes: [
          'Advanced WAF has to be provisioned on the BIG-IP (`tmsh list sys provision asm`) or the declaration will fail.',
          'Transparent first. A policy that has never seen the application will block things it should not.',
          'AS3 replaces the whole tenant: capture the current declaration first.',
        ],
        before: ['tmsh list sys provision asm', `curl -sku $USER https://bigip/mgmt/shared/appsvcs/declare/${tenant} > ${tenant}-before.json`],
        config: json(declaration({ tenant, application: app, label: `${app} with WAF`, body })),
        verify: [
          `tmsh show ltm virtual /${tenant}/${app}/service`,
          `tmsh show asm policy /${tenant}/${app}/${app}_waf`,
          'Check the Event Log for violations before switching to blocking.',
        ],
        backout: [`curl -sku $USER -X POST https://bigip/mgmt/shared/appsvcs/declare -d @${tenant}-before.json`],
        push: {
          module: 'f5networks.f5_modules.bigip_as3_deploy',
          args: { content: `{{ lookup('file', '${app}.json') }}`, tenant, provider: '{{ provider }}', state: 'present' },
          hosts: 'bigips',
        },
        findings,
      };
    },
  }),
];

/** The rest of the platform's changes live in f5-extra.ts. */
const ALL: readonly ChangeBlueprint[] = [...BLUEPRINTS, ...F5_EXTRA, ...F5_EXTRA_2];

export const F5_NETWORK: BlueprintGroup = { target: PLATFORM, label: 'F5 BIG-IP (AS3)', blueprints: ALL };
export const F5_CHANGES: readonly ChangeBlueprint[] = ALL;
