/**
 * Fortinet FortiOS.
 *
 * FortiOS configuration is entered as `config` blocks and applies as each
 * `end` is typed — there is no staged candidate to review, so the back-out
 * matters more here than anywhere else, and every change in this group carries
 * one that can be pasted straight back.
 *
 * The push half uses the object modules (`fortios_firewall_policy`,
 * `fortios_firewall_address`), which speak to the REST API over the httpapi
 * connection with a token from the vault.
 */

import { bool, num, str, type BlueprintValues, type BlueprintGroup } from '../../kit/blueprint.ts';
import { error, warning, type Finding } from '../../core/findings.ts';
import { deviceBlueprint, type ChangeBlueprint } from '../from-change.ts';
import { FORTIOS_EXTRA } from './fortios-extra.ts';
import { listOf, netmask, parseCidr, type DeviceChange } from '../device.ts';

const PLATFORM = 'fortios' as const;
const VDOM = '{{ vdom | default("root") }}';

const BLUEPRINTS: readonly ChangeBlueprint[] = [
  deviceBlueprint({
    id: 'fortios_address_objects',
    platform: PLATFORM,
    label: 'Address objects and a group',
    group: 'Objects',
    description: 'Address objects from a list of prefixes, collected into a group for policies to use.',
    inputs: [
      { id: 'group_name', label: 'Group name', control: 'text', default: 'GRP-APP-SERVERS' },
      { id: 'addresses', label: 'Addresses', control: 'textarea', default: 'APP-WEB-01 10.20.30.11/32\nAPP-WEB-02 10.20.30.12/32', hint: 'One per line: NAME prefix' },
      { id: 'vdom', label: 'VDOM', control: 'text', default: 'root' },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const group = str(values, 'group_name', 'GRP').toUpperCase().replace(/\s+/g, '-');
      const entries = str(values, 'addresses', '')
        .split(/\n+/)
        .map((line) => line.trim().split(/\s+/))
        .filter((parts) => parts.length >= 2)
        .map(([name, cidr]) => ({ name: String(name), cidr: String(cidr), parsed: parseCidr(String(cidr)) }));
      const findings: Finding[] = [];
      for (const entry of entries) {
        if (!entry.parsed) findings.push(error('network.fortios.bad-address', `"${entry.cidr}" for ${entry.name} is not a valid prefix.`, { source: 'ArchToolKit' }));
      }
      if (entries.length === 0) findings.push(error('network.fortios.no-addresses', 'No address objects were given.', { source: 'ArchToolKit' }));

      return {
        platform: PLATFORM,
        title: `${entries.length} address object(s) and the group ${group}`,
        impact: 'none',
        notes: ['Objects change no traffic on their own. The policy that uses them does.'],
        before: ['show firewall address', `show firewall addrgrp ${group}`],
        config: [
          'config firewall address',
          ...entries.flatMap((entry) => [
            `    edit "${entry.name}"`,
            '        set type ipmask',
            `        set subnet ${entry.parsed ? `${entry.parsed.address} ${netmask(entry.parsed.prefix)}` : '<REQUIRED>'}`,
            '        set comment "Generated by ArchToolKit"',
            '    next',
          ]),
          'end',
          '',
          'config firewall addrgrp',
          `    edit "${group}"`,
          `        set member ${entries.map((e) => `"${e.name}"`).join(' ')}`,
          '    next',
          'end',
        ],
        verify: [`show firewall addrgrp ${group}`, 'show firewall address | grep APP-'],
        backout: [
          'config firewall addrgrp',
          `    delete "${group}"`,
          'end',
          'config firewall address',
          ...entries.map((entry) => `    delete "${entry.name}"`),
          'end',
        ],
        push: {
          module: 'fortinet.fortios.fortios_firewall_address',
          args: {
            vdom: VDOM,
            state: 'present',
            firewall_address: {
              name: '{{ item.name }}',
              type: 'ipmask',
              subnet: '{{ item.subnet }}',
              comment: 'Generated by ArchToolKit',
            },
          },
          after: [
            {
              name: `Collect them into ${group}`,
              module: 'fortinet.fortios.fortios_firewall_addrgrp',
              args: { vdom: VDOM, state: 'present', firewall_addrgrp: { name: group, member: entries.map((e) => ({ name: e.name })) } },
            },
          ],
        },
        findings,
      };
    },
  }),

  deviceBlueprint({
    id: 'fortios_firewall_policy',
    platform: PLATFORM,
    label: 'Firewall policy',
    group: 'Policy',
    description: 'A policy between two interfaces with addresses, services, NAT, logging and the security profiles attached.',
    inputs: [
      { id: 'policy_id', label: 'Policy id', control: 'number', default: 100, min: 1, hint: 'Must not already exist' },
      { id: 'policy_name', label: 'Name', control: 'text', default: 'Users-to-App' },
      { id: 'src_intf', label: 'Incoming interface', control: 'text', default: 'port1' },
      { id: 'dst_intf', label: 'Outgoing interface', control: 'text', default: 'port2' },
      { id: 'source', label: 'Source addresses', control: 'text', default: 'GRP-USERS' },
      { id: 'destination', label: 'Destination addresses', control: 'text', default: 'GRP-APP-SERVERS' },
      { id: 'service', label: 'Services', control: 'text', default: 'HTTPS, DNS', hint: 'Service object names' },
      { id: 'action', label: 'Action', control: 'select', default: 'accept', options: [{ value: 'accept', label: 'Accept' }, { value: 'deny', label: 'Deny' }] },
      { id: 'nat', label: 'NAT (hide behind the outgoing interface)', control: 'toggle', default: false },
      { id: 'log', label: 'Log all sessions', control: 'toggle', default: true },
      { id: 'inspection', label: 'Security profiles', control: 'select', default: 'certificate-inspection', options: [
        { value: 'none', label: 'None' },
        { value: 'certificate-inspection', label: 'Certificate inspection' },
        { value: 'deep-inspection', label: 'Deep inspection' },
      ] },
      { id: 'vdom', label: 'VDOM', control: 'text', default: 'root' },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const id = num(values, 'policy_id', 100);
      const name = str(values, 'policy_name', 'policy');
      const action = str(values, 'action', 'accept');
      const log = bool(values, 'log', true);
      const inspection = str(values, 'inspection', 'certificate-inspection');
      const source = listOf(str(values, 'source', 'all'));
      const destination = listOf(str(values, 'destination', 'all'));
      const services = listOf(str(values, 'service', 'ALL'));
      const findings: Finding[] = [];

      if (services.some((s) => s.toUpperCase() === 'ALL') && action === 'accept') {
        findings.push(warning('network.fortios.service-all', 'This policy accepts every service between the two interfaces.', { remediation: 'Name the service objects the traffic uses.', source: 'ArchToolKit' }));
      }
      if (action === 'accept' && inspection === 'none') {
        findings.push(warning('network.fortios.no-inspection', 'An accept policy with no inspection profile passes the traffic unexamined.', { source: 'ArchToolKit' }));
      }
      if (!log) findings.push(warning('network.fortios.no-logging', 'Logging is off, so this policy leaves no record of what it passed.', { source: 'ArchToolKit' }));

      return {
        platform: PLATFORM,
        title: `Firewall policy ${id} (${name}): ${str(values, 'src_intf', '')} → ${str(values, 'dst_intf', '')}`,
        impact: 'brief',
        notes: [
          'FortiOS applies each block as `end` is entered. There is no commit to hold it back, so check the addresses and services before pasting.',
          'Policies match in order. A new policy goes to the bottom of the sequence; move it with `move <id> before <id>` if something above would match first.',
        ],
        before: [`show firewall policy ${id}`, 'show firewall policy | grep -f name', 'get router info routing-table all'],
        config: [
          'config firewall policy',
          `    edit ${id}`,
          `        set name "${name}"`,
          `        set srcintf "${str(values, 'src_intf', 'port1')}"`,
          `        set dstintf "${str(values, 'dst_intf', 'port2')}"`,
          `        set srcaddr ${source.map((s) => `"${s}"`).join(' ')}`,
          `        set dstaddr ${destination.map((s) => `"${s}"`).join(' ')}`,
          `        set action ${action}`,
          '        set schedule "always"',
          `        set service ${services.map((s) => `"${s}"`).join(' ')}`,
          ...(log ? ['        set logtraffic all'] : ['        set logtraffic disable']),
          ...(bool(values, 'nat', false) ? ['        set nat enable'] : []),
          ...(inspection !== 'none' && action === 'accept'
            ? [`        set ssl-ssh-profile "${inspection}"`, '        set av-profile "default"', '        set ips-sensor "default"', '        set utm-status enable']
            : []),
          '        set comments "Generated by ArchToolKit"',
          '    next',
          'end',
        ],
        verify: [`show firewall policy ${id}`, `diagnose firewall iprope show 100004 ${id}`, 'get system status'],
        backout: ['config firewall policy', `    delete ${id}`, 'end'],
        push: {
          module: 'fortinet.fortios.fortios_firewall_policy',
          args: {
            vdom: VDOM,
            state: 'present',
            firewall_policy: {
              policyid: id,
              name,
              srcintf: [{ name: str(values, 'src_intf', 'port1') }],
              dstintf: [{ name: str(values, 'dst_intf', 'port2') }],
              srcaddr: source.map((s) => ({ name: s })),
              dstaddr: destination.map((s) => ({ name: s })),
              action,
              schedule: 'always',
              service: services.map((s) => ({ name: s })),
              logtraffic: log ? 'all' : 'disable',
              nat: bool(values, 'nat', false) ? 'enable' : 'disable',
              ...(inspection !== 'none' && action === 'accept' ? { ssl_ssh_profile: inspection, utm_status: 'enable', av_profile: 'default', ips_sensor: 'default' } : {}),
              comments: 'Generated by ArchToolKit',
            },
          },
        },
        findings,
      };
    },
  }),

  deviceBlueprint({
    id: 'fortios_vip',
    platform: PLATFORM,
    label: 'Virtual IP (publish a server)',
    group: 'Policy',
    description: 'A VIP that maps an external address and port to an internal server, with the policy that permits it.',
    inputs: [
      { id: 'vip_name', label: 'VIP name', control: 'text', default: 'VIP-WEB' },
      { id: 'external', label: 'External address', control: 'text', default: '203.0.113.10' },
      { id: 'internal', label: 'Internal address', control: 'text', default: '10.20.30.11' },
      { id: 'external_port', label: 'External port', control: 'number', default: 443, min: 1, max: 65535 },
      { id: 'internal_port', label: 'Internal port', control: 'number', default: 443, min: 1, max: 65535 },
      { id: 'interface', label: 'External interface', control: 'text', default: 'port1' },
      { id: 'vdom', label: 'VDOM', control: 'text', default: 'root' },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const name = str(values, 'vip_name', 'VIP');
      const external = str(values, 'external', '');
      const internal = str(values, 'internal', '');
      const extPort = num(values, 'external_port', 443);
      const intPort = num(values, 'internal_port', 443);

      return {
        platform: PLATFORM,
        title: `VIP ${name}: ${external}:${extPort} → ${internal}:${intPort}`,
        impact: 'brief',
        notes: [
          'A VIP on its own publishes nothing: a firewall policy with this VIP as the destination is what lets the traffic in. Add one after this.',
          'If the external address is not on the interface, the firewall needs to answer ARP for it — `set arp-reply enable` does that and is included.',
        ],
        before: [`show firewall vip ${name}`, 'get system arp'],
        config: [
          'config firewall vip',
          `    edit "${name}"`,
          `        set extip ${external}`,
          `        set mappedip "${internal}"`,
          `        set extintf "${str(values, 'interface', 'port1')}"`,
          '        set portforward enable',
          '        set protocol tcp',
          `        set extport ${extPort}`,
          `        set mappedport ${intPort}`,
          '        set arp-reply enable',
          '        set comment "Generated by ArchToolKit"',
          '    next',
          'end',
        ],
        verify: [`show firewall vip ${name}`, `diagnose sys session filter dport ${extPort}`, 'get system arp | grep ' + external],
        backout: ['config firewall vip', `    delete "${name}"`, 'end'],
        push: {
          module: 'fortinet.fortios.fortios_firewall_vip',
          args: {
            vdom: VDOM,
            state: 'present',
            firewall_vip: {
              name,
              extip: external,
              mappedip: [{ range: internal }],
              extintf: str(values, 'interface', 'port1'),
              portforward: 'enable',
              protocol: 'tcp',
              extport: String(extPort),
              mappedport: String(intPort),
              arp_reply: 'enable',
              comment: 'Generated by ArchToolKit',
            },
          },
        },
      };
    },
  }),

  deviceBlueprint({
    id: 'fortios_static_route',
    platform: PLATFORM,
    label: 'Static route',
    group: 'Network',
    description: 'A static route out of an interface, optionally as a backup behind a lower distance.',
    inputs: [
      { id: 'sequence', label: 'Sequence number', control: 'number', default: 10, min: 1 },
      { id: 'prefix', label: 'Destination', control: 'text', default: '0.0.0.0/0' },
      { id: 'gateway', label: 'Gateway', control: 'text', default: '203.0.113.1' },
      { id: 'device', label: 'Interface', control: 'text', default: 'port1' },
      { id: 'distance', label: 'Distance', control: 'number', default: 10, min: 1, max: 255 },
      { id: 'vdom', label: 'VDOM', control: 'text', default: 'root' },
    ],
    change: (values: BlueprintValues): DeviceChange => {
      const seq = num(values, 'sequence', 10);
      const cidr = parseCidr(str(values, 'prefix', '0.0.0.0/0'));
      const gateway = str(values, 'gateway', '');
      const device = str(values, 'device', 'port1');
      const distance = num(values, 'distance', 10);
      const findings: Finding[] = [];
      if (!cidr) findings.push(error('network.fortios.bad-prefix', 'The destination is not a valid prefix.', { source: 'ArchToolKit' }));

      return {
        platform: PLATFORM,
        title: `Static route ${cidr ? `${cidr.address}/${cidr.prefix}` : '(invalid)'} via ${gateway}`,
        impact: cidr && cidr.prefix === 0 ? 'outage' : 'brief',
        notes: cidr && cidr.prefix === 0 ? ['This is the default route. If the gateway is wrong, the firewall loses its path out — including the session you are on.'] : [],
        before: ['get router info routing-table all', 'show router static'],
        config: [
          'config router static',
          `    edit ${seq}`,
          `        set dst ${cidr ? `${cidr.address} ${netmask(cidr.prefix)}` : '<REQUIRED>'}`,
          `        set gateway ${gateway}`,
          `        set device "${device}"`,
          `        set distance ${distance}`,
          '        set comment "Generated by ArchToolKit"',
          '    next',
          'end',
        ],
        verify: ['get router info routing-table all', `execute ping ${gateway}`],
        backout: ['config router static', `    delete ${seq}`, 'end'],
        push: {
          module: 'fortinet.fortios.fortios_router_static',
          args: {
            vdom: VDOM,
            state: 'present',
            router_static: {
              seq_num: seq,
              dst: cidr ? `${cidr.address} ${netmask(cidr.prefix)}` : '',
              gateway,
              device,
              distance,
              comment: 'Generated by ArchToolKit',
            },
          },
        },
        findings,
      };
    },
  }),
];

/** The rest of the platform's changes live in fortios-extra.ts. */
const ALL: readonly ChangeBlueprint[] = [...BLUEPRINTS, ...FORTIOS_EXTRA];

export const FORTIOS_NETWORK: BlueprintGroup = { target: PLATFORM, label: 'Fortinet FortiOS', blueprints: ALL };
export const FORTIOS_CHANGES: readonly ChangeBlueprint[] = ALL;
