/**
 * Pipelines and runners: the glue that runs everything else.
 *
 * The toolkit already writes Terraform, Ansible, PowerShell and Python. What it
 * did not write is the thing that runs them on a schedule, with credentials
 * that are not in the file, and a record afterwards. That is this.
 *
 * Every runner here is generated with the same four properties, because they
 * are the four that are missing when an automation goes wrong at 3am: the
 * schedule is created disabled, the credential comes from the runner's own
 * store, there is a dry run, and the run says where it went afterwards.
 */

import { bool, num, str,                      } from '../../kit/blueprint.js';
import { error, warning,              } from '../../core/findings.js';
import { automationBlueprint,                          } from '../from-automation.js';
import { listOf, slugOf,                 } from '../automation.js';

const PLATFORM = 'pipeline'         ;

export const PIPELINE_AUTOMATIONS                                 = [
  automationBlueprint({
    id: 'pipe_azure_runbook',
    platform: PLATFORM,
    label: 'Azure Automation runbook on a schedule',
    group: 'Azure',
    description:
      'A PowerShell runbook with a managed identity rather than a stored credential, a dry run that is on by default, and a schedule created disabled. The runbook that does the work is yours; everything around it is the part people skip.',
    inputs: [
      { id: 'runbook_name', label: 'Runbook name', control: 'text', default: 'Nightly tag compliance' },
      { id: 'what_it_does', label: 'What it does', control: 'text', default: 'Reports resources missing a cost-centre tag' },
      { id: 'schedule', label: 'Runs', control: 'text', default: 'Daily 02:00' },
      {
        id: 'identity',
        label: 'Authenticates with',
        control: 'select',
        options: [
          { value: 'system', label: 'System-assigned managed identity' },
          { value: 'user', label: 'User-assigned managed identity' },
          { value: 'runas', label: 'A Run As account — retired, see the finding' },
        ],
        default: 'system',
      },
      { id: 'scope', label: 'Over', control: 'text', default: 'the subscription the account is in' },
      { id: 'changes_things', label: 'It changes things', control: 'toggle', default: false },
    ],
    automation: (values                 , name        )             => {
      const runbookName = str(values, 'runbook_name', 'Runbook');
      const whatItDoes = str(values, 'what_it_does', 'Reports something');
      const schedule = str(values, 'schedule', 'Daily 02:00');
      const identity = str(values, 'identity', 'system');
      const scope = str(values, 'scope', 'the subscription');
      const changes = bool(values, 'changes_things', false);

      const findings            = [];
      if (identity === 'runas') {
        findings.push(
          error('pipe.azure.runas', 'Run As accounts are retired and their certificates expire silently.', {
            remediation: 'Use a managed identity. There is no credential to rotate and nothing to expire at the worst moment.',
            source: 'ArchToolKit',
          }),
        );
      }

      const ps = [
        '<#',
        `.SYNOPSIS`,
        `    ${runbookName} — ${whatItDoes}`,
        '',
        '.DESCRIPTION',
        '    Generated by ArchToolKit. Runs in Azure Automation.',
        '',
        '    The dry run is on by default. Pass -Execute to make it act, and read',
        `    what the dry run listed before you do.${changes ? '' : ' This runbook only reads.'}`,
        '',
        '.NOTES',
        `    Authenticates with a ${identity === 'system' ? 'system-assigned' : identity === 'user' ? 'user-assigned' : 'Run As'} identity.`,
        '    No credential is stored in this file.',
        '#>',
        '[CmdletBinding(SupportsShouldProcess)]',
        'param(',
        '    [Parameter()][switch]$Execute,',
        '    [Parameter()][string]$UserAssignedClientId',
        ')',
        '',
        'Set-StrictMode -Version Latest',
        "$ErrorActionPreference = 'Stop'",
        '',
        'function Write-Log {',
        "    param([string]$Message, [ValidateSet('INFO','WARN','ERROR')][string]$Level = 'INFO')",
        "    Write-Output ('{0} [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message)",
        '}',
        '',
        '# The identity is the whole point: nothing to rotate, nothing to expire.',
        'try {',
        identity === 'user'
          ? '    Connect-AzAccount -Identity -AccountId $UserAssignedClientId | Out-Null'
          : '    Connect-AzAccount -Identity | Out-Null',
        "    Write-Log \"Connected as $((Get-AzContext).Account.Id)\"",
        '} catch {',
        "    Write-Log \"Could not authenticate: $($_.Exception.Message)\" -Level ERROR",
        '    throw',
        '}',
        '',
        '# Assert the subscription before doing anything. The context is per-session',
        '# and a runbook that assumes it is a subscription it is not will act on the',
        '# wrong estate without saying so.',
        "Write-Log \"Subscription: $((Get-AzContext).Subscription.Name)\"",
        '',
        `if (-not $Execute) { $WhatIfPreference = $true; Write-Log 'DRY RUN — nothing will be changed. Re-run with -Execute.' -Level WARN }`,
        '',
        'try {',
        `    # --- the work: ${whatItDoes} ---`,
        '    # Replace this block. Everything above and below it is the scaffolding',
        '    # that makes the run safe and the result findable afterwards.',
        '    $found = @()',
        '',
        '    Write-Log "$($found.Count) item(s) matched"',
        '    foreach ($item in $found) {',
        changes
          ? "        if ($PSCmdlet.ShouldProcess($item.Name, '" + runbookName + "')) {\n            # act on $item\n        }"
          : '        Write-Log "would report: $($item.Name)"',
        '    }',
        '} catch {',
        "    Write-Log $_.Exception.Message -Level ERROR",
        '    throw',
        '} finally {',
        "    Write-Log 'finished'",
        '}',
        '',
      ].join('\n');

      // Azure Automation names an imported runbook after its file: letters,
      // digits, - and _, starting with a letter, at most 63 characters.
      const rbSlug = slugOf(runbookName, 'runbook');
      const rb = (/^[a-z]/.test(rbSlug) ? rbSlug : `rb-${rbSlug}`).slice(0, 63);
      const time = /(\d{1,2}):(\d{2})/.exec(schedule);
      const hh = String(Math.min(23, Number(time?.[1] ?? 2))).padStart(2, '0');
      const mm = String(Math.min(59, Number(time?.[2] ?? 0))).padStart(2, '0');
      const frequency = /hour/i.test(schedule) ? 'Hour' : /week|monday|tuesday|wednesday|thursday|friday|saturday|sunday/i.test(schedule) ? 'Week' : /month/i.test(schedule) ? 'Month' : 'Day';
      const scheduleName = `${rb}-schedule`;
      const scheduleDescription = `${schedule} — ${whatItDoes}`;
      const bicepString = (text        )         => `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$\{/g, '\\${')}'`;

      const bicep = [
        '// Schedule for the runbook, and the job schedule that links the two.',
        '//',
        '// Azure has no create-time switch for a schedule — isEnabled: false can',
        '// only be set by an update — so "created disabled" is done the documented',
        '// way: the job schedule that makes the runbook run is only deployed when',
        '// linkRunbook is true. Deploy with the default, start the runbook by hand',
        '// and read its output, then deploy again with linkRunbook=true.',
        '//',
        `//   az deployment group create -g <resource group> -f ${rb}-schedule.bicep -p automationAccountName=<account>`,
        '',
        "@description('The Automation account the runbook was imported into.')",
        'param automationAccountName string',
        '',
        "@description('The runbook, exactly as imported.')",
        `param runbookName string = ${bicepString(rb)}`,
        '',
        `@description('First run. Defaults to tomorrow ${hh}:${mm} UTC; must be at least 5 minutes after the deployment.')`,
        `param startTime string = dateTimeAdd('\${utcNow('yyyy-MM-dd')}T${hh}:${mm}:00Z', 'P1D')`,
        '',
        "@description('Time zone for startTime, e.g. UTC or Europe/London.')",
        "param timeZone string = 'UTC'",
        '',
        "@description('False: the schedule exists and nothing runs. True: the runbook runs on it.')",
        'param linkRunbook bool = false',
        ...(identity === 'user' ? ['', "@description('Client id of the user-assigned identity the runbook connects as.')", 'param userAssignedClientId string'] : []),
        '',
        "resource account 'Microsoft.Automation/automationAccounts@2023-11-01' existing = {",
        '  name: automationAccountName',
        '}',
        '',
        "resource schedule 'Microsoft.Automation/automationAccounts/schedules@2023-11-01' = {",
        '  parent: account',
        `  name: ${bicepString(scheduleName)}`,
        '  properties: {',
        `    description: ${bicepString(scheduleDescription)}`,
        `    frequency: '${frequency}'`,
        '    interval: 1',
        '    startTime: startTime',
        '    timeZone: timeZone',
        '  }',
        '}',
        '',
        "resource jobSchedule 'Microsoft.Automation/automationAccounts/jobSchedules@2023-11-01' = if (linkRunbook) {",
        '  parent: account',
        '  name: guid(account.id, runbookName, schedule.name)',
        '  properties: {',
        '    runbook: { name: runbookName }',
        '    schedule: { name: schedule.name }',
        identity === 'user' ? '    parameters: { UserAssignedClientId: userAssignedClientId }' : '    parameters: {}',
        '  }',
        '}',
        '',
        'output scheduleName string = schedule.name',
        'output linked bool = linkRunbook',
        '',
      ].join('\n');

      // The same deployment as ARM JSON, for the portal's "Deploy a custom
      // template" (which takes JSON only) and for anyone without Bicep.
      const arm = {
        $schema: 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#',
        contentVersion: '1.0.0.0',
        parameters: {
          automationAccountName: { type: 'string', metadata: { description: 'The Automation account the runbook was imported into.' } },
          runbookName: { type: 'string', defaultValue: rb, metadata: { description: 'The runbook, exactly as imported.' } },
          startTime: { type: 'string', defaultValue: `[dateTimeAdd(concat(utcNow('yyyy-MM-dd'), 'T${hh}:${mm}:00Z'), 'P1D')]`, metadata: { description: 'First run; at least 5 minutes after the deployment.' } },
          timeZone: { type: 'string', defaultValue: 'UTC' },
          linkRunbook: { type: 'bool', defaultValue: false, metadata: { description: 'False: the schedule exists and nothing runs. True: the runbook runs on it.' } },
          ...(identity === 'user' ? { userAssignedClientId: { type: 'string' } } : {}),
        },
        resources: [
          {
            type: 'Microsoft.Automation/automationAccounts/schedules',
            apiVersion: '2023-11-01',
            name: `[format('{0}/{1}', parameters('automationAccountName'), '${scheduleName}')]`,
            properties: {
              description: scheduleDescription.replace(/^\[/, '[['),
              frequency,
              interval: 1,
              startTime: "[parameters('startTime')]",
              timeZone: "[parameters('timeZone')]",
            },
          },
          {
            condition: "[parameters('linkRunbook')]",
            type: 'Microsoft.Automation/automationAccounts/jobSchedules',
            apiVersion: '2023-11-01',
            name: `[format('{0}/{1}', parameters('automationAccountName'), guid(resourceId('Microsoft.Automation/automationAccounts', parameters('automationAccountName')), parameters('runbookName'), '${scheduleName}'))]`,
            properties: {
              runbook: { name: "[parameters('runbookName')]" },
              schedule: { name: scheduleName },
              parameters: identity === 'user' ? { UserAssignedClientId: "[parameters('userAssignedClientId')]" } : {},
            },
            dependsOn: [`[resourceId('Microsoft.Automation/automationAccounts/schedules', parameters('automationAccountName'), '${scheduleName}')]`],
          },
        ],
        outputs: { scheduleName: { type: 'string', value: scheduleName } },
      };

      const importMd = [
        '# Importing this into Azure Automation',
        '',
        'Do the steps in order. `RG` is the resource group and `ACCT` the Automation account.',
        '',
        `## 1. The runbook — \`import/azure/${rb}.ps1\``,
        '',
        `Portal: Automation account → Process Automation → **Runbooks** → **Import a runbook** → browse for \`${rb}.ps1\`, Runbook type **PowerShell**, Runtime version 7.2 (5.1 also works) → **Import**, then **Publish**. The runbook is named after the file.`,
        '',
        'Azure CLI (the `automation` extension: `az extension add --name automation`):',
        '',
        '```bash',
        `az automation runbook create -g RG --automation-account-name ACCT --name ${rb} --type PowerShell`,
        `az automation runbook replace-content -g RG --automation-account-name ACCT --name ${rb} --content @import/azure/${rb}.ps1`,
        `az automation runbook publish -g RG --automation-account-name ACCT --name ${rb}`,
        '```',
        '',
        'Or Az PowerShell:',
        '',
        '```powershell',
        `Import-AzAutomationRunbook -Path ./import/azure/${rb}.ps1 -Type PowerShell -ResourceGroupName RG -AutomationAccountName ACCT -Published`,
        '```',
        '',
        '## 2. Run it once by hand',
        '',
        `Portal: the runbook → **Start** with Execute left empty, or \`az automation runbook start -g RG --automation-account-name ACCT --name ${rb}\`. Read the output stream: it is a dry run.`,
        '',
        `## 3. The schedule — \`import/azure/${rb}-schedule.bicep\` (or \`${rb}-schedule.json\`)`,
        '',
        '```bash',
        `az deployment group create -g RG --template-file import/azure/${rb}-schedule.bicep --parameters automationAccountName=ACCT${identity === 'user' ? ' userAssignedClientId=<client id>' : ''}`,
        '```',
        '',
        `Portal alternative: **Deploy a custom template** → **Build your own template in the editor** → **Load file** → \`${rb}-schedule.json\`.`,
        '',
        'This creates the schedule and does not link the runbook to it, so nothing runs yet.',
        '',
        '## 4. Turn it on',
        '',
        '```bash',
        `az deployment group create -g RG --template-file import/azure/${rb}-schedule.bicep --parameters automationAccountName=ACCT linkRunbook=true${identity === 'user' ? ' userAssignedClientId=<client id>' : ''}`,
        '```',
        '',
        'The scheduled run is still a dry run: the job schedule passes no `Execute`. When the reports read right, add `Execute: \'true\'` to the job schedule parameters (a job schedule cannot be changed in place — delete it and deploy again).',
        '',
        '## Confirmed, and what to verify',
        '',
        '- `az automation runbook create / replace-content --content @file / publish` and the `--type` values: Microsoft Learn, az automation runbook (extension).',
        '- The schedules and jobSchedules resource shapes (a job schedule name is a GUID; `isEnabled` is not a create property): Microsoft Learn, Microsoft.Automation template reference.',
        '- startTime defaults to tomorrow ${hh}:${mm} UTC (the time in the schedule text, read as UTC). To run in local time, pass startTime without the Z and timeZone as an IANA name such as `Europe/London` — VERIFY the result in the schedule blade before linking.',
        '',
      ].join('\n');

      return {
        platform: PLATFORM,
        title: `${runbookName} — ${whatItDoes}`,
        effect: changes ? 'reversible' : 'read',
        trigger: { kind: 'schedule', detail: schedule, worstCase: 'once a day, plus whenever somebody starts it by hand' },
        scope: {
          what: `Whatever the identity can see in ${scope}.`,
          decidedBy: [
            `The ${identity === 'runas' ? 'Run As account' : 'managed identity'} and the roles assigned to it.`,
            'The subscription the automation account is in — assert it, do not assume it.',
            'Whatever filter the work block applies.',
          ],
          ifWrong: 'An over-privileged identity is the real blast radius here, not the script. Give it exactly the role it needs and the scope is bounded by Azure rather than by the code.',
        },
        guardrails: [
          { rule: 'Dry run by default; -Execute takes it off', because: 'Nobody reads a runbook before the first scheduled run. This way the first run reports.' },
          { rule: 'The schedule is created disabled', because: 'Deploying a template should not start something running.' },
          { rule: 'No credential in the file', because: 'A runbook is exported, versioned and read by more people than the person who wrote it.' },
          { rule: 'The subscription is logged before any work', because: 'The context is per-session. A runbook that acts on the wrong subscription does so silently.' },
        ],
        dryRun: ['Start it by hand with -Execute absent and read the output stream in full.', 'Only then enable the schedule.'],
        undo: changes ? ['Whatever the work block changed has to be put back by the same means. Record the previous values in the run output — that log is the only undo.'] : ['Nothing to undo. It reads.'],
        told: ['The job output in Azure Automation, kept for the account’s retention period. Forward it to a log workspace if the record needs to outlive that.'],
        requires: [
          'An Automation account with the Az modules imported — the built-in versions lag, and a runbook that works locally can fail there on a missing cmdlet.',
          `${identity === 'user' ? 'A user-assigned identity and its client id' : identity === 'system' ? 'A system-assigned identity on the account' : 'A Run As account, which is retired'}, with exactly the roles this needs.`,
        ],
        files: {
          [`import/azure/${rb}.ps1`]: ps,
          [`import/azure/${rb}-schedule.bicep`]: bicep,
          [`import/azure/${rb}-schedule.json`]: `${JSON.stringify(arm, null, 2)}\n`,
          'IMPORT.md': importMd,
        },
        notes: [
          'Module versions in Azure Automation are not the versions on your laptop. Pin them in the account and test there, not locally.',
          'The output stream is the record. Write what you did to it, not just that you finished.',
        ],
        findings,
      };
    },
  }),

  automationBlueprint({
    id: 'pipe_ssm_document',
    platform: PLATFORM,
    label: 'AWS Systems Manager document',
    group: 'AWS',
    description:
      'An SSM document with the two things that separate a safe run from a bad afternoon: a targeted resource group rather than every instance, and a rate control that stops it doing all of them at once when the first one fails.',
    inputs: [
      { id: 'doc_name', label: 'Document name', control: 'text', default: 'PatchAndReport' },
      { id: 'what_it_does', label: 'What it does', control: 'text', default: 'Applies the patch baseline and reports what changed' },
      { id: 'target_tag', label: 'Targets instances tagged', control: 'text', default: 'PatchGroup=standard' },
      { id: 'concurrency', label: 'At most (instances at once)', control: 'text', default: '10%', hint: 'A count or a percentage' },
      { id: 'error_threshold', label: 'Stop after (failures)', control: 'text', default: '1', hint: 'A count or a percentage. 1 is the safe first answer' },
      { id: 'reboot', label: 'May reboot', control: 'toggle', default: false },
    ],
    automation: (values                 , name        )             => {
      const docName = str(values, 'doc_name', 'Document');
      const whatItDoes = str(values, 'what_it_does', 'Does something');
      const targetTag = str(values, 'target_tag', '');
      const concurrency = str(values, 'concurrency', '10%');
      const errorThreshold = str(values, 'error_threshold', '1');
      const reboot = bool(values, 'reboot', false);
      const base = slugOf(name || docName, 'ssm-document');
      // SSM document names: letters, digits, _ - and ., 3 to 128 characters, and
      // not starting with aws or amazon (those prefixes are reserved).
      const cleanName = docName.replace(/[^A-Za-z0-9_.-]+/g, '-').replace(/^-+|-+$/g, '');
      const ssmName = (/^(aws|amazon)/i.test(cleanName) || cleanName.length < 3 ? `ATK-${cleanName || 'Document'}` : cleanName).slice(0, 128);

      const findings            = [];
      if (!targetTag) {
        findings.push(
          error('pipe.ssm.no-target', 'No target tag, so this can be run against every managed instance in the account.', {
            remediation: 'Target by tag. An SSM document with no target is one console click away from the whole estate.',
            source: 'ArchToolKit',
          }),
        );
      }
      if (/^100%$|^0$/.test(errorThreshold)) {
        findings.push(
          warning('pipe.ssm.no-stop', 'Nothing stops this if instances start failing.', {
            remediation: 'Set the error threshold to 1 for the first few runs. If the first instance fails, the other four hundred should not be attempted.',
            source: 'ArchToolKit',
          }),
        );
      }

      const doc = [
        `# ${docName} — ${whatItDoes}`,
        '#',
        '# Generated by ArchToolKit. Run it with --dry-run first; the document',
        '# honours it and reports rather than acting.',
        "schemaVersion: '2.2'",
        `description: ${JSON.stringify(whatItDoes)}`,
        'parameters:',
        '  DryRun:',
        '    type: String',
        "    default: 'true'",
        "    allowedValues: ['true', 'false']",
        '    description: Report what would be done without doing it',
        ...(reboot
          ? [
              '  RebootOption:',
              '    type: String',
              "    default: 'NoReboot'",
              "    allowedValues: ['NoReboot', 'RebootIfNeeded']",
              '    description: Rebooting is a separate decision from patching',
            ]
          : []),
        'mainSteps:',
        '  - action: aws:runShellScript',
        '    name: run',
        '    precondition:',
        '      StringEquals: [platformType, Linux]',
        '    inputs:',
        '      timeoutSeconds: 3600',
        '      runCommand:',
        '        # runShellScript runs the lines with sh, which may be dash: no pipefail.',
        '        - set -eu',
        '        - |',
        '          if [ "{{ DryRun }}" = "true" ]; then',
        `            echo "DRY RUN: would ${whatItDoes.toLowerCase()} on $(hostname)"`,
        '            exit 0',
        '          fi',
        `        - '# --- the work: ${whatItDoes.replace(/'/g, "''")} ---'`,
        '        - echo "replace this step"',
        ...(reboot
          ? [
              '        # Exit code 194 asks the agent to reboot and run the document again;',
              '        # the second pass finds no reboot pending and ends.',
              '        - |',
              '          if [ "{{ RebootOption }}" = "RebootIfNeeded" ] && [ -f /var/run/reboot-required ]; then',
              '            exit 194',
              '          fi',
            ]
          : []),
        '',
      ].join('\n');

      // The CreateAssociation request, as aws ssm create-association --cli-input-json takes it.
      const association = {
        Name: ssmName,
        DocumentVersion: '$DEFAULT',
        AssociationName: `${base}-association`,
        Targets: targetTag
          ? [{ Key: `tag:${targetTag.split('=')[0]}`, Values: [targetTag.split('=')[1] ?? '<REQUIRED>'] }]
          : [{ Key: 'tag:<REQUIRED>', Values: ['<REQUIRED>'] }],
        Parameters: { DryRun: ['true'] },
        ScheduleExpression: 'cron(0 3 ? * SUN *)',
        MaxConcurrency: concurrency,
        MaxErrors: errorThreshold,
        ComplianceSeverity: 'MEDIUM',
        ApplyOnlyAtCronInterval: true,
      };

      return {
        platform: PLATFORM,
        title: `${docName} — ${whatItDoes}`,
        effect: reboot ? 'irreversible' : 'reversible',
        trigger: { kind: 'schedule', detail: 'Weekly, Sunday 03:00 UTC, through a State Manager association', worstCase: `once a week across every instance tagged ${targetTag || '(nothing — see the finding)'}` },
        scope: {
          what: targetTag ? `Managed instances tagged ${targetTag}.` : 'Every managed instance — no target is set.',
          decidedBy: ['The target tag on the association.', 'Which instances have the SSM agent and an instance profile.', `The concurrency: ${concurrency} at a time.`],
          ifWrong: `It runs on instances you did not mean, ${concurrency} at a time, stopping after ${errorThreshold} failures. Those last two numbers are what turn a mistake into a contained one.`,
        },
        guardrails: [
          { rule: `Targets by tag: ${targetTag || 'NOT SET'}`, because: 'The alternative is every managed instance in the account, and that is a single click in the console.' },
          { rule: `At most ${concurrency} at a time`, because: 'If it is going to break them, it should break a few before anybody notices, not all of them.' },
          { rule: `Stops after ${errorThreshold} failures`, because: 'The first failure is information. The four hundredth is an incident review.' },
          { rule: 'DryRun defaults to true', because: 'The association is created reporting. Flip the parameter when the report reads correctly.' },
          ...(reboot ? [{ rule: 'Rebooting is a separate parameter', because: 'Patching and rebooting are two decisions and two maintenance windows.' }] : []),
        ],
        dryRun: ['The association is created with DryRun=true. Let it run once on the schedule and read the command output for a sample of instances.'],
        undo: reboot
          ? ['A reboot cannot be undone. Whatever was in memory on those instances is gone, which is why the reboot option is separate and off.']
          : ['Depends on the work. Record enough in the output to put it back, and treat that output as the undo.'],
        told: ['Command history in Systems Manager, and compliance status on the association. Neither pages anybody — wire a CloudWatch Events rule to the failure if somebody needs to know.'],
        requires: ['The SSM agent and an instance profile with the managed policy on every target.', 'The tag actually applied to the instances you mean — check with a Resource Groups query first.'],
        files: {
          [`import/ssm/${ssmName}.yaml`]: doc,
          [`import/ssm/${base}-association.json`]: `${JSON.stringify(association, null, 2)}\n`,
          'IMPORT.md': [
            '# Importing this into AWS Systems Manager',
            '',
            'Run from the folder this file is in, with credentials for the target account and region.',
            '',
            `## 1. The document — \`import/ssm/${ssmName}.yaml\``,
            '',
            '```bash',
            `aws ssm create-document --name ${ssmName} --document-type Command --document-format YAML --content file://import/ssm/${ssmName}.yaml`,
            '```',
            '',
            `Console alternative: Systems Manager → Documents → **Create document** → **Command or Session**, name \`${ssmName}\`, Document type Command, Content **YAML**, paste the file.`,
            '',
            `To change it later: \`aws ssm update-document --name ${ssmName} --document-format YAML --content file://import/ssm/${ssmName}.yaml --document-version '$LATEST'\`, then \`aws ssm update-document-default-version --name ${ssmName} --document-version <n>\`.`,
            '',
            '## 2. Try it on one instance',
            '',
            '```bash',
            `aws ssm send-command --document-name ${ssmName} --targets Key=InstanceIds,Values=<one instance id> --parameters DryRun=true`,
            '```',
            '',
            `## 3. The association — \`import/ssm/${base}-association.json\``,
            '',
            '```bash',
            `aws ssm create-association --cli-input-json file://import/ssm/${base}-association.json`,
            '```',
            '',
            'It is created with DryRun=true and ApplyOnlyAtCronInterval, so it runs first at the next scheduled time and only reports. When the reports read right: `aws ssm update-association --association-id <id> --parameters DryRun=false` (update-association replaces the parameters you pass).',
            '',
            '## Confirmed',
            '',
            '- create-document with `--document-format YAML --content file://…` and schema 2.2 `mainSteps` / `aws:runShellScript`: AWS CLI reference and the SSM document syntax reference.',
            '- The association file uses only CreateAssociation request members (Name, DocumentVersion, AssociationName, Targets, Parameters, ScheduleExpression, MaxConcurrency, MaxErrors, ComplianceSeverity, ApplyOnlyAtCronInterval), which is what `--cli-input-json` takes.',
            '',
          ].join('\n'),
        },
        notes: [
          'Targeting by tag means the estate can add itself to the automation by tagging. That is the feature and the risk in the same sentence.',
          'ApplyOnlyAtCronInterval stops the association running the moment it is created, which is otherwise the default and a surprise.',
        ],
        findings,
      };
    },
  }),

  automationBlueprint({
    id: 'pipe_awx_template',
    platform: PLATFORM,
    label: 'AWX or Tower job template',
    group: 'Ansible',
    description:
      'A job template for the playbooks this toolkit already writes: credentials from AWX rather than from the repository, a check-mode run first, limits so a wrong inventory does not become a wrong estate, and a survey when a human has to choose.',
    inputs: [
      { id: 'template_name', label: 'Template name', control: 'text', default: 'Patch Linux — standard group' },
      { id: 'playbook', label: 'Playbook', control: 'text', default: 'playbooks/patch.yml' },
      { id: 'organization', label: 'Organization', control: 'text', default: 'Default' },
      { id: 'project', label: 'Project (where the playbook lives)', control: 'text', default: 'Infrastructure playbooks' },
      { id: 'inventory', label: 'Inventory', control: 'text', default: 'Production Linux' },
      { id: 'machine_credential', label: 'Machine credential', control: 'text', default: 'Linux — patching service account', hint: 'The name of a credential already in AWX. Nothing secret goes in the file' },
      { id: 'limit', label: 'Limit to', control: 'text', default: 'linux_standard', hint: 'A group. An empty limit is the whole inventory' },
      { id: 'forks', label: 'Hosts at a time', control: 'number', default: 10, min: 1, max: 200 },
      { id: 'check_first', label: 'Run in check mode first', control: 'toggle', default: true },
      { id: 'ask_for_approval', label: 'Needs approval in the workflow', control: 'toggle', default: false },
    ],
    automation: (values                 , name        )             => {
      const templateName = str(values, 'template_name', 'Job template');
      const playbook = str(values, 'playbook', 'site.yml');
      const inventory = str(values, 'inventory', 'Production');
      const organization = str(values, 'organization', 'Default');
      const project = str(values, 'project', 'Playbooks');
      const machineCredential = str(values, 'machine_credential', 'Machine credential');
      const limit = str(values, 'limit', '');
      const forks = num(values, 'forks', 10);
      const checkFirst = bool(values, 'check_first', true);
      const approval = bool(values, 'ask_for_approval', false);
      const base = slugOf(name || templateName, 'job-template');

      const findings            = [];
      if (!limit) {
        findings.push(
          warning('pipe.awx.no-limit', `No limit is set, so this runs against every host in "${inventory}".`, {
            remediation: 'Set a limit to a group. An inventory grows; a limit is a deliberate statement about what this template is for.',
            source: 'ArchToolKit',
          }),
        );
      }

      // The awxkit export format — what `awx export` writes and `awx import`
      // reads: one key per resource type, every reference a natural key (names,
      // qualified by organization) rather than an id, so it imports into any
      // instance that has objects with those names.
      const org = { name: organization, type: 'organization' };
      const jtKey = { organization: org, name: templateName, type: 'job_template' };
      const workflowName = `${templateName} — workflow`;
      const wfKey = { organization: org, name: workflowName, type: 'workflow_job_template' };
      const nodeKey = (identifier        ) => ({ workflow_job_template: wfKey, identifier, type: 'workflow_job_template_node' });

      const template = {
        name: templateName,
        description: 'ArchToolKit. Credentials are attached in AWX, never in the repository.',
        job_type: 'run',
        inventory: { organization: org, name: inventory, type: 'inventory' },
        project: { organization: org, name: project, type: 'project' },
        playbook,
        scm_branch: '',
        forks,
        limit,
        verbosity: 1,
        extra_vars: '---',
        job_tags: '',
        skip_tags: '',
        timeout: 0,
        become_enabled: true,
        diff_mode: true,
        allow_simultaneous: false,
        ask_limit_on_launch: true,
        ask_variables_on_launch: true,
        // A workflow node can only run the template in check mode if the
        // template prompts for the job type.
        ask_job_type_on_launch: checkFirst,
        survey_enabled: true,
        related: {
          credentials: [{ organization: org, name: machineCredential, credential_type: { name: 'Machine', kind: 'ssh', type: 'credential_type' }, type: 'credential' }],
          labels: [],
          survey_spec: {
            name: '',
            description: '',
            spec: [
              {
                question_name: 'Change reference',
                question_description: 'The change or ticket this run belongs to. It is written into the job so the record says why.',
                required: true,
                type: 'text',
                variable: 'change_reference',
                min: 1,
                max: 128,
                default: '',
                choices: '',
                new_question: true,
              },
            ],
          },
        },
        natural_key: jtKey,
      };

      const order = [...(checkFirst ? ['check'] : []), ...(approval ? ['approve'] : []), 'run'];
      const node = (identifier        ) => {
        const next = order[order.indexOf(identifier) + 1];
        const base = {
          identifier,
          all_parents_must_converge: false,
          extra_data: {},
          job_type: identifier === 'check' ? 'check' : null,
          limit: null,
          inventory: null,
          scm_branch: null,
          job_tags: null,
          skip_tags: null,
          diff_mode: null,
          verbosity: null,
          workflow_job_template: wfKey,
          natural_key: nodeKey(identifier),
        };
        const related = { success_nodes: next ? [nodeKey(next)] : [], failure_nodes: [], always_nodes: [], credentials: [] };
        // An approval node has no job template: awxkit exports it with the
        // approval template's own fields under create_approval_template.
        return identifier === 'approve'
          ? { ...base, related: { ...related, create_approval_template: { name: `${templateName} — read the check-mode output before approving`, description: 'The check-mode job is the node before this one. Open it and read what would change.', timeout: 86400 } } }
          : { ...base, unified_job_template: jtKey, related };
      };

      const workflow = {
        name: workflowName,
        description: 'ArchToolKit: check mode, then approval, then the real run.',
        organization: org,
        extra_vars: '---',
        inventory: null,
        limit: null,
        scm_branch: null,
        allow_simultaneous: false,
        ask_variables_on_launch: false,
        ask_inventory_on_launch: false,
        ask_limit_on_launch: false,
        survey_enabled: false,
        related: { workflow_nodes: order.map(node), labels: [] },
        natural_key: wfKey,
      };

      const exportJson = { job_templates: [template], workflow_job_templates: [workflow] };

      const importMd = [
        '# Importing this into AWX or Automation Platform',
        '',
        `\`import/awx/${base}.json\` is in the format \`awx export\` writes and \`awx import\` reads (awxkit): a job template and a workflow, every reference by name.`,
        '',
        '## 1. What must exist first, with exactly these names',
        '',
        `- Organization **${organization}**`,
        `- Project **${project}**, containing \`${playbook}\``,
        `- Inventory **${inventory}**${limit ? ` with a group **${limit}**` : ''}`,
        `- Machine credential **${machineCredential}** (and a vault credential, attached by hand afterwards, if the playbook uses one)`,
        '',
        'The import resolves each of these by name and stops if one is missing.',
        '',
        '## 2. Import',
        '',
        '```bash',
        'pip install awxkit            # the version that matches your AWX / controller',
        'export CONTROLLER_HOST=https://awx.example.com',
        'export CONTROLLER_USERNAME=<an account that can create templates in the organization>',
        'read -rs CONTROLLER_PASSWORD && export CONTROLLER_PASSWORD',
        '# Automation Platform 2.5 and later, through the gateway:',
        '# export AWXKIT_API_BASE_PATH=/api/controller/',
        `awx import < import/awx/${base}.json`,
        '```',
        '',
        '## 3. Before the first real run',
        '',
        `Launch **${workflowName}**${checkFirst ? ' and read the check-mode job' : ''}${approval ? ', then approve or deny the approval node' : ''}. Attach a failure notification in the template’s Notifications tab.`,
        '',
        '## Confirmed, and what to verify',
        '',
        '- The top-level keys (`job_templates`, `workflow_job_templates`), natural keys, `related.credentials`, `related.survey_spec` and `related.workflow_nodes` with `success_nodes` as node natural keys: awxkit (awxkit/api/pages/api.py) and exports shown in ansible/awx issues #7946 and #14292.',
        ...(approval ? ['- VERIFY: the approval node. awxkit exports approval nodes through `create_approval_template` (name, description, timeout) rather than a natural key; if your awxkit version rejects it, delete that node from the file and add the approval in the workflow visualizer.'] : []),
        '- awxkit 22.4.0 to 23.x had a bug that dropped success_nodes on export (issue #14292). Import with a current awxkit.',
        '',
      ].join('\n');

      return {
        platform: PLATFORM,
        title: `${templateName} — ${playbook} against ${limit || inventory}`,
        effect: 'reversible',
        trigger: { kind: 'schedule', detail: 'Whatever schedule you attach in AWX, or launched by hand', worstCase: `every host in ${limit || inventory}, ${forks} at a time` },
        scope: {
          what: limit ? `Hosts in the group "${limit}" of inventory "${inventory}".` : `Every host in inventory "${inventory}".`,
          decidedBy: ['The inventory and how it is populated — a dynamic inventory changes under you.', limit ? `The limit: ${limit}.` : 'No limit.', 'Any limit typed at launch, which overrides the one above.'],
          ifWrong: 'The playbook runs somewhere it should not. Ansible is idempotent, which helps, and not harmless, which people forget.',
        },
        guardrails: [
          ...(checkFirst ? [{ rule: 'Check mode runs first in the workflow', because: 'Check mode is Ansible’s dry run and it is free. The output is the list of what would change.' }] : []),
          ...(approval ? [{ rule: 'A human approves between check and run', because: 'The approval is only worth having if the check-mode output is in front of the approver. Link it in the approval description.' }] : []),
          { rule: `${forks} hosts at a time`, because: 'A playbook that breaks things should break a few first.' },
          { rule: 'Credentials come from AWX', because: 'A vault password in the repository is a vault password in everyone’s clone.' },
        ],
        dryRun: ['Launch the check-mode node on its own and read the changed list.', 'Not every module supports check mode — the ones that do not are the ones to read twice.'],
        undo: ['Ansible does not roll back. The undo is another playbook, and if the change is significant it should be written before the change is run.'],
        told: ['The job output in AWX, kept per its retention. Set a notification on failure — a silent failed job is worse than a loud one.'],
        requires: [`The organization "${organization}", project "${project}", inventory "${inventory}" and the group "${limit || '(none)'}".`, `The machine credential "${machineCredential}" in AWX, and a vault credential if the playbook uses one.`],
        files: { [`import/awx/${base}.json`]: `${JSON.stringify(exportJson, null, 2)}\n`, 'IMPORT.md': importMd },
        notes: [
          'ask_limit_on_launch is on, which lets somebody narrow the run at launch. It also lets them widen it — the limit on the template is a default, not a ceiling.',
          'A dynamic inventory means the scope is decided at launch by something else entirely. Check what populates it before trusting the limit.',
        ],
        findings,
      };
    },
  }),

  automationBlueprint({
    id: 'pipe_ci_terraform',
    platform: PLATFORM,
    label: 'Plan on a pull request, apply on merge',
    group: 'CI',
    description:
      'The pipeline for the Terraform this toolkit writes: plan on every pull request with the output posted back, apply only from the default branch, state locked, and credentials from the platform’s identity rather than a secret in the repository.',
    inputs: [
      {
        id: 'ci',
        label: 'Runs on',
        control: 'select',
        options: [
          { value: 'github', label: 'GitHub Actions' },
          { value: 'azdo', label: 'Azure Pipelines' },
        ],
        default: 'github',
      },
      { id: 'working_dir', label: 'Terraform lives in', control: 'text', default: 'infra/' },
      {
        id: 'cloud',
        label: 'Against',
        control: 'select',
        options: [
          { value: 'azure', label: 'Azure' },
          { value: 'aws', label: 'AWS' },
          { value: 'vsphere', label: 'vSphere' },
        ],
        default: 'azure',
      },
      { id: 'require_approval', label: 'Apply needs an environment approval', control: 'toggle', default: true },
      { id: 'auto_apply', label: 'Apply automatically on merge', control: 'toggle', default: false },
    ],
    automation: (values                 , name        )             => {
      const ci = str(values, 'ci', 'github');
      const dir = str(values, 'working_dir', 'infra/');
      const cloud = str(values, 'cloud', 'azure');
      const approval = bool(values, 'require_approval', true);
      const autoApply = bool(values, 'auto_apply', false);
      const base = slugOf(name || `terraform-${ci}`, 'terraform-pipeline');

      const findings            = [];
      if (autoApply && !approval) {
        findings.push(
          error('pipe.ci.unattended-apply', 'A merge applies to the estate with no human in the loop.', {
            remediation: 'For a well-tested module set that is a deliberate choice. For anything else, put an environment approval on the apply — the plan is only useful if somebody reads it.',
            source: 'ArchToolKit',
          }),
        );
      }
      if (cloud === 'vsphere') {
        findings.push(
          warning('pipe.ci.vsphere-credentials', 'vSphere has no workload identity, so this needs a real credential in the CI secret store.', {
            remediation: 'Use a service account scoped to exactly what the Terraform manages, rotate it on a schedule, and never put it in the repository.',
            source: 'ArchToolKit',
          }),
        );
      }

      const githubYaml = [
        'name: Terraform',
        '',
        '# Generated by ArchToolKit.',
        '#',
        '# Plan on every pull request; apply only from the default branch. The',
        '# credential comes from OIDC rather than a stored secret, so there is',
        '# nothing to rotate and nothing to leak.',
        'on:',
        '  pull_request:',
        `    paths: ['${dir}**']`,
        '  push:',
        '    branches: [main]',
        `    paths: ['${dir}**']`,
        '',
        'permissions:',
        '  contents: read',
        '  id-token: write        # OIDC. This is what replaces a stored credential.',
        '  pull-requests: write   # so the plan can be posted back',
        '',
        'concurrency:',
        '  # One run at a time against the same state. Terraform locks, but a',
        '  # queued second run holding a lock is a confusing way to find that out.',
        '  group: terraform-${{ github.ref }}',
        '  cancel-in-progress: false',
        '',
        'jobs:',
        '  plan:',
        '    runs-on: ubuntu-latest',
        '    defaults:',
        '      run:',
        `        working-directory: ${dir}`,
        '    steps:',
        '      - uses: actions/checkout@v4',
        ...(cloud === 'azure'
          ? [
              '      - uses: azure/login@v2',
              '        with:',
              '          client-id: ${{ vars.AZURE_CLIENT_ID }}',
              '          tenant-id: ${{ vars.AZURE_TENANT_ID }}',
              '          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}',
            ]
          : cloud === 'aws'
            ? [
                '      - uses: aws-actions/configure-aws-credentials@v4',
                '        with:',
                '          role-to-assume: ${{ vars.AWS_ROLE_ARN }}',
                '          aws-region: ${{ vars.AWS_REGION }}',
              ]
            : [
                '      # vSphere has no workload identity. These come from the secret',
                '      # store, scoped to exactly what this Terraform manages.',
                '      - name: vSphere credentials',
                '        run: |',
                '          echo "TF_VAR_vsphere_user=${{ secrets.VSPHERE_USER }}" >> $GITHUB_ENV',
                '          echo "TF_VAR_vsphere_password=${{ secrets.VSPHERE_PASSWORD }}" >> $GITHUB_ENV',
              ]),
        '      - uses: hashicorp/setup-terraform@v3',
        '      - run: terraform fmt -check -recursive',
        '      - run: terraform init',
        '      - run: terraform validate',
        '      - name: Plan',
        '        id: plan',
        '        run: |',
        '          terraform plan -no-color -lock-timeout=5m -out=tfplan',
        '          terraform show -no-color tfplan > "$GITHUB_WORKSPACE/plan.txt"',
        '      - name: Post the plan on the pull request',
        "        if: github.event_name == 'pull_request'",
        '        uses: actions/github-script@v7',
        '        with:',
        '          script: |',
        '            const fs = require("fs");',
        '            const plan = fs.readFileSync(process.env.GITHUB_WORKSPACE + "/plan.txt", "utf8").slice(0, 60000);',
        '            await github.rest.issues.createComment({',
        '              issue_number: context.issue.number,',
        '              owner: context.repo.owner,',
        '              repo: context.repo.repo,',
        '              body: "```\\n" + plan + "\\n```",',
        '            });',
        '        continue-on-error: true',
        '      - uses: actions/upload-artifact@v4',
        '        with:',
        '          name: tfplan',
        `          path: ${dir}tfplan`,
        '',
        '  apply:',
        "    if: github.ref == 'refs/heads/main' && github.event_name == 'push'",
        '    needs: plan',
        '    runs-on: ubuntu-latest',
        ...(approval ? ['    # The environment carries the approval. That is where a human reads', '    # the plan before anything reaches the estate.', '    environment: production'] : []),
        '    defaults:',
        '      run:',
        `        working-directory: ${dir}`,
        '    steps:',
        '      - uses: actions/checkout@v4',
        '      - uses: actions/download-artifact@v4',
        '        with:',
        '          name: tfplan',
        `          path: ${dir}`,
        '      - uses: hashicorp/setup-terraform@v3',
        '      - run: terraform init',
        '      - name: Apply the plan that was reviewed',
        '        run: terraform apply -auto-approve -lock-timeout=5m tfplan',
        '',
      ].join('\n');

      const azdoYaml = [
        '# Generated by ArchToolKit.',
        '#',
        '# Plan on a pull request, apply from main behind an environment approval.',
        'trigger:',
        '  branches: { include: [main] }',
        `  paths: { include: ['${dir}'] }`,
        'pr:',
        '  branches: { include: ["*"] }',
        `  paths: { include: ['${dir}'] }`,
        '',
        'pool:',
        '  vmImage: ubuntu-latest',
        '',
        'variables:',
        `  workingDirectory: ${dir}`,
        '',
        'stages:',
        '  - stage: plan',
        '    jobs:',
        '      - job: plan',
        '        steps:',
        '          - task: TerraformInstaller@1',
        '          - script: terraform init',
        '            workingDirectory: $(workingDirectory)',
        '          - script: terraform validate',
        '            workingDirectory: $(workingDirectory)',
        '          - script: terraform plan -no-color -lock-timeout=5m -out=tfplan',
        '            workingDirectory: $(workingDirectory)',
        '          - publish: $(workingDirectory)/tfplan',
        '            artifact: tfplan',
        '',
        '  - stage: apply',
        "    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))",
        '    jobs:',
        '      - deployment: apply',
        '        # The environment is where the approval lives.',
        `        environment: ${approval ? 'production' : 'production-unattended'}`,
        '        strategy:',
        '          runOnce:',
        '            deploy:',
        '              steps:',
        '                - download: current',
        '                  artifact: tfplan',
        '                - task: TerraformInstaller@1',
        '                - script: terraform init',
        '                  workingDirectory: $(workingDirectory)',
        '                - script: terraform apply -auto-approve -lock-timeout=5m $(Pipeline.Workspace)/tfplan/tfplan',
        '                  workingDirectory: $(workingDirectory)',
        '',
      ].join('\n');

      return {
        platform: PLATFORM,
        title: `Terraform on ${ci === 'github' ? 'GitHub Actions' : 'Azure Pipelines'} — plan on a pull request, apply from main`,
        effect: 'reversible',
        trigger: { kind: 'commit', detail: `A pull request touching ${dir} plans; a merge to main applies${approval ? ' after an approval' : ''}`, worstCase: 'as often as people merge' },
        scope: {
          what: `Whatever the Terraform in ${dir} manages, against ${cloud}.`,
          decidedBy: ['The state file the backend points at.', 'The identity the pipeline assumes and what it is allowed to touch.', 'The contents of the plan, which is the only place this is visible before it happens.'],
          ifWrong: 'Terraform destroys and recreates without being asked twice. The plan is where that is visible, which is why it is posted on the pull request rather than buried in a log.',
        },
        guardrails: [
          { rule: 'Apply runs the plan that was reviewed, not a fresh one', because: 'A re-planned apply can do something the reviewer never saw, because the world changed in between.' },
          ...(approval ? [{ rule: 'An environment approval gates the apply', because: 'The plan is only worth producing if somebody reads it.' }] : []),
          { rule: 'One run at a time against the same state', because: 'Terraform locks, but a queued run holding a lock is a confusing way to discover that.' },
          { rule: 'A lock timeout of five minutes', because: 'The default waits forever, and a job that hangs forever is a job nobody notices has hung.' },
          ...(cloud !== 'vsphere' ? [{ rule: 'OIDC rather than a stored credential', because: 'Nothing to rotate, nothing to leak, and it expires on its own.' }] : []),
        ],
        dryRun: ['The plan job is the dry run, and it runs on every pull request. Read it — particularly the destroy lines.'],
        undo: ['Revert the commit and let the pipeline apply the revert. That is the only undo that leaves state and code agreeing.'],
        told: ['The plan is posted on the pull request. The apply is in the run log. Add a notification on apply failure — a half-applied change is the one to know about.'],
        requires: [
          'A remote backend with locking. Local state in CI is a corrupted state file waiting for a concurrent run.',
          cloud === 'vsphere' ? 'A vSphere service account in the secret store.' : 'A federated identity credential trusting this repository, and the roles it needs.',
        ],
        files: {
          ...(ci === 'github' ? { '.github/workflows/terraform.yml': githubYaml } : { 'azure-pipelines.yml': azdoYaml }),
          'IMPORT.md': [
            `# Putting this pipeline into ${ci === 'github' ? 'GitHub Actions' : 'Azure Pipelines'}`,
            '',
            'The pipeline file is not uploaded anywhere: it is committed to the repository that holds the Terraform, at exactly the path it has here.',
            '',
            ...(ci === 'github'
              ? [
                  '1. Commit `.github/workflows/terraform.yml` to the default branch (main). GitHub picks up every workflow in `.github/workflows/` on its own; there is nothing to import.',
                  `2. ${cloud === 'azure' ? 'Add repository variables AZURE_CLIENT_ID, AZURE_TENANT_ID and AZURE_SUBSCRIPTION_ID (Settings → Secrets and variables → Actions → Variables), and a federated credential on the app registration for this repository.' : cloud === 'aws' ? 'Add repository variables AWS_ROLE_ARN and AWS_REGION, and an IAM role that trusts token.actions.githubusercontent.com for this repository.' : 'Add repository secrets VSPHERE_USER and VSPHERE_PASSWORD (Settings → Secrets and variables → Actions).'}`,
                  ...(approval ? ['3. Create the environment **production** (Settings → Environments) with required reviewers — that is the approval the apply job waits on.'] : []),
                  `${approval ? '4' : '3'}. Open a pull request that touches \`${dir}\` and check that the plan is posted on it.`,
                ]
              : [
                  '1. Commit `azure-pipelines.yml` to the root of the repository.',
                  '2. Azure DevOps → Pipelines → **New pipeline** → your repository → **Existing Azure Pipelines YAML file** → branch main, path `/azure-pipelines.yml` → **Save**. Or: `az pipelines create --name terraform --repository <repo> --branch main --yml-path azure-pipelines.yml --skip-first-run true`.',
                  `3. Create the environment **${approval ? 'production' : 'production-unattended'}** (Pipelines → Environments)${approval ? ' and add an Approvals check to it — that is the approval the apply stage waits on' : ''}.`,
                  '4. Install the "Terraform" extension (TerraformInstaller@1) from the Visual Studio Marketplace in the organization if it is not there, and give the pipeline its cloud credential through a service connection.',
                ]),
            '',
            'Sources: GitHub Docs, "Workflow syntax for GitHub Actions" (workflows live in .github/workflows); Microsoft Learn, "Create your first pipeline" and az pipelines create (--yml-path).',
            '',
          ].join('\n'),
        },
        notes: [
          'Apply the saved plan rather than re-planning. It is the difference between applying what was reviewed and applying what is true now.',
          'terraform fmt -check in the plan job keeps the diff about the change rather than about whitespace.',
        ],
        findings,
      };
    },
  }),
];
