/**
 * Pipelines and runners: the glue that runs everything else.
 *
 * The toolkit already writes Terraform, Ansible, PowerShell and Python. What it
 * did not write is the thing that runs them on a schedule, with credentials
 * that are not in the file, and a record afterwards. That is this.
 *
 * Every runner here is generated with the same four properties, because they
 * are the four that are missing when an automation goes wrong at 3am: the
 * schedule is created disabled, the credential comes from the runner's own
 * store, there is a dry run, and the run says where it went afterwards.
 */

import { bool, num, str,                      } from '../../kit/blueprint.js';
import { error, warning,              } from '../../core/findings.js';
import { automationBlueprint,                          } from '../from-automation.js';
import { slugOf,                 } from '../automation.js';
import { stableId } from '../vcfa-import.js';
import { packageNameOf, toPackage,                        } from '../vro/to-package.js';
                                                   
import { ciRepoPackage, packageImportMd } from './pipeline-vcf.js';

const PLATFORM = 'pipeline'         ;

export const PIPELINE_AUTOMATIONS                                 = [
  automationBlueprint({
    id: 'pipe_azure_runbook',
    platform: PLATFORM,
    label: 'Azure Automation runbook on a schedule',
    group: 'Azure',
    description:
      'A PowerShell runbook with a managed identity rather than a stored credential, a dry run that is on by default, and a schedule created disabled. The runbook that does the work is yours; everything around it is the part people skip.',
    inputs: [
      { id: 'runbook_name', label: 'Runbook name', control: 'text', default: 'Nightly tag compliance' },
      { id: 'what_it_does', label: 'What it does', control: 'text', default: 'Reports resources missing a cost-centre tag' },
      { id: 'schedule', label: 'Runs', control: 'text', default: 'Daily 02:00' },
      {
        id: 'identity',
        label: 'Authenticates with',
        control: 'select',
        options: [
          { value: 'system', label: 'System-assigned managed identity' },
          { value: 'user', label: 'User-assigned managed identity' },
          { value: 'runas', label: 'A Run As account — retired, see the finding' },
        ],
        default: 'system',
      },
      { id: 'scope', label: 'Over', control: 'text', default: 'the subscription the account is in' },
      { id: 'changes_things', label: 'It changes things', control: 'toggle', default: false },
    ],
    automation: (values                 , name        )             => {
      const runbookName = str(values, 'runbook_name', 'Runbook');
      const whatItDoes = str(values, 'what_it_does', 'Reports something');
      const schedule = str(values, 'schedule', 'Daily 02:00');
      const identity = str(values, 'identity', 'system');
      const scope = str(values, 'scope', 'the subscription');
      const changes = bool(values, 'changes_things', false);

      const findings            = [];
      if (identity === 'runas') {
        findings.push(
          error('pipe.azure.runas', 'Run As accounts are retired and their certificates expire silently.', {
            remediation: 'Use a managed identity. There is no credential to rotate and nothing to expire at the worst moment.',
            source: 'ArchToolKit',
          }),
        );
      }

      const ps = [
        '<#',
        `.SYNOPSIS`,
        `    ${runbookName} — ${whatItDoes}`,
        '',
        '.DESCRIPTION',
        '    Generated by ArchToolKit. Runs in Azure Automation.',
        '',
        '    The dry run is on by default. Pass -Execute to make it act, and read',
        `    what the dry run listed before you do.${changes ? '' : ' This runbook only reads.'}`,
        '',
        '.NOTES',
        `    Authenticates with a ${identity === 'system' ? 'system-assigned' : identity === 'user' ? 'user-assigned' : 'Run As'} identity.`,
        '    No credential is stored in this file.',
        '#>',
        '[CmdletBinding(SupportsShouldProcess)]',
        'param(',
        '    [Parameter()][switch]$Execute,',
        '    [Parameter()][string]$UserAssignedClientId',
        ')',
        '',
        'Set-StrictMode -Version Latest',
        "$ErrorActionPreference = 'Stop'",
        '',
        'function Write-Log {',
        "    param([string]$Message, [ValidateSet('INFO','WARN','ERROR')][string]$Level = 'INFO')",
        "    Write-Output ('{0} [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message)",
        '}',
        '',
        '# The identity is the whole point: nothing to rotate, nothing to expire.',
        'try {',
        identity === 'user'
          ? '    Connect-AzAccount -Identity -AccountId $UserAssignedClientId | Out-Null'
          : '    Connect-AzAccount -Identity | Out-Null',
        "    Write-Log \"Connected as $((Get-AzContext).Account.Id)\"",
        '} catch {',
        "    Write-Log \"Could not authenticate: $($_.Exception.Message)\" -Level ERROR",
        '    throw',
        '}',
        '',
        '# Assert the subscription before doing anything. The context is per-session',
        '# and a runbook that assumes it is a subscription it is not will act on the',
        '# wrong estate without saying so.',
        "Write-Log \"Subscription: $((Get-AzContext).Subscription.Name)\"",
        '',
        `if (-not $Execute) { $WhatIfPreference = $true; Write-Log 'DRY RUN — nothing will be changed. Re-run with -Execute.' -Level WARN }`,
        '',
        'try {',
        `    # --- the work: ${whatItDoes} ---`,
        '    # Replace this block. Everything above and below it is the scaffolding',
        '    # that makes the run safe and the result findable afterwards.',
        '    $found = @()',
        '',
        '    Write-Log "$($found.Count) item(s) matched"',
        '    foreach ($item in $found) {',
        changes
          ? "        if ($PSCmdlet.ShouldProcess($item.Name, '" + runbookName + "')) {\n            # act on $item\n        }"
          : '        Write-Log "would report: $($item.Name)"',
        '    }',
        '} catch {',
        "    Write-Log $_.Exception.Message -Level ERROR",
        '    throw',
        '} finally {',
        "    Write-Log 'finished'",
        '}',
        '',
      ].join('\n');

      // Azure Automation names an imported runbook after its file: letters,
      // digits, - and _, starting with a letter, at most 63 characters.
      const rbSlug = slugOf(runbookName, 'runbook');
      const rb = (/^[a-z]/.test(rbSlug) ? rbSlug : `rb-${rbSlug}`).slice(0, 63);
      const time = /(\d{1,2}):(\d{2})/.exec(schedule);
      const hh = String(Math.min(23, Number(time?.[1] ?? 2))).padStart(2, '0');
      const mm = String(Math.min(59, Number(time?.[2] ?? 0))).padStart(2, '0');
      const frequency = /hour/i.test(schedule) ? 'Hour' : /week|monday|tuesday|wednesday|thursday|friday|saturday|sunday/i.test(schedule) ? 'Week' : /month/i.test(schedule) ? 'Month' : 'Day';
      const scheduleName = `${rb}-schedule`;
      const scheduleDescription = `${schedule} — ${whatItDoes}`;
      const bicepString = (text        )         => `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$\{/g, '\\${')}'`;

      const bicep = [
        '// Schedule for the runbook, and the job schedule that links the two.',
        '//',
        '// Azure has no create-time switch for a schedule — isEnabled: false can',
        '// only be set by an update — so "created disabled" is done the documented',
        '// way: the job schedule that makes the runbook run is only deployed when',
        '// linkRunbook is true. Deploy with the default, start the runbook by hand',
        '// and read its output, then deploy again with linkRunbook=true.',
        '//',
        `//   az deployment group create -g <resource group> -f ${rb}-schedule.bicep -p automationAccountName=<account>`,
        '',
        "@description('The Automation account the runbook was imported into.')",
        'param automationAccountName string',
        '',
        "@description('The runbook, exactly as imported.')",
        `param runbookName string = ${bicepString(rb)}`,
        '',
        `@description('First run. Defaults to tomorrow ${hh}:${mm} UTC; must be at least 5 minutes after the deployment.')`,
        `param startTime string = dateTimeAdd('\${utcNow('yyyy-MM-dd')}T${hh}:${mm}:00Z', 'P1D')`,
        '',
        "@description('Time zone for startTime, e.g. UTC or Europe/London.')",
        "param timeZone string = 'UTC'",
        '',
        "@description('False: the schedule exists and nothing runs. True: the runbook runs on it.')",
        'param linkRunbook bool = false',
        ...(identity === 'user' ? ['', "@description('Client id of the user-assigned identity the runbook connects as.')", 'param userAssignedClientId string'] : []),
        '',
        "resource account 'Microsoft.Automation/automationAccounts@2023-11-01' existing = {",
        '  name: automationAccountName',
        '}',
        '',
        "resource schedule 'Microsoft.Automation/automationAccounts/schedules@2023-11-01' = {",
        '  parent: account',
        `  name: ${bicepString(scheduleName)}`,
        '  properties: {',
        `    description: ${bicepString(scheduleDescription)}`,
        `    frequency: '${frequency}'`,
        '    interval: 1',
        '    startTime: startTime',
        '    timeZone: timeZone',
        '  }',
        '}',
        '',
        "resource jobSchedule 'Microsoft.Automation/automationAccounts/jobSchedules@2023-11-01' = if (linkRunbook) {",
        '  parent: account',
        '  name: guid(account.id, runbookName, schedule.name)',
        '  properties: {',
        '    runbook: { name: runbookName }',
        '    schedule: { name: schedule.name }',
        identity === 'user' ? '    parameters: { UserAssignedClientId: userAssignedClientId }' : '    parameters: {}',
        '  }',
        '}',
        '',
        'output scheduleName string = schedule.name',
        'output linked bool = linkRunbook',
        '',
      ].join('\n');

      // The same deployment as ARM JSON, for the portal's "Deploy a custom
      // template" (which takes JSON only) and for anyone without Bicep.
      const arm = {
        $schema: 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#',
        contentVersion: '1.0.0.0',
        parameters: {
          automationAccountName: { type: 'string', metadata: { description: 'The Automation account the runbook was imported into.' } },
          runbookName: { type: 'string', defaultValue: rb, metadata: { description: 'The runbook, exactly as imported.' } },
          startTime: { type: 'string', defaultValue: `[dateTimeAdd(concat(utcNow('yyyy-MM-dd'), 'T${hh}:${mm}:00Z'), 'P1D')]`, metadata: { description: 'First run; at least 5 minutes after the deployment.' } },
          timeZone: { type: 'string', defaultValue: 'UTC' },
          linkRunbook: { type: 'bool', defaultValue: false, metadata: { description: 'False: the schedule exists and nothing runs. True: the runbook runs on it.' } },
          ...(identity === 'user' ? { userAssignedClientId: { type: 'string' } } : {}),
        },
        resources: [
          {
            type: 'Microsoft.Automation/automationAccounts/schedules',
            apiVersion: '2023-11-01',
            name: `[format('{0}/{1}', parameters('automationAccountName'), '${scheduleName}')]`,
            properties: {
              description: scheduleDescription.replace(/^\[/, '[['),
              frequency,
              interval: 1,
              startTime: "[parameters('startTime')]",
              timeZone: "[parameters('timeZone')]",
            },
          },
          {
            condition: "[parameters('linkRunbook')]",
            type: 'Microsoft.Automation/automationAccounts/jobSchedules',
            apiVersion: '2023-11-01',
            name: `[format('{0}/{1}', parameters('automationAccountName'), guid(resourceId('Microsoft.Automation/automationAccounts', parameters('automationAccountName')), parameters('runbookName'), '${scheduleName}'))]`,
            properties: {
              runbook: { name: "[parameters('runbookName')]" },
              schedule: { name: scheduleName },
              parameters: identity === 'user' ? { UserAssignedClientId: "[parameters('userAssignedClientId')]" } : {},
            },
            dependsOn: [`[resourceId('Microsoft.Automation/automationAccounts/schedules', parameters('automationAccountName'), '${scheduleName}')]`],
          },
        ],
        outputs: { scheduleName: { type: 'string', value: scheduleName } },
      };

      // The Orchestrator package does steps 1 and 3 (and 4, once linkRunbook is
      // set) through Azure Resource Manager, as a service principal: runbook
      // created if missing, its draft replaced and published only when the
      // published content differs, the schedule created if missing, and the
      // job schedule — the link that makes it run — only when asked for.
      const jobScheduleId = stableId(`azure-job-schedule:${rb}:${scheduleName}`);
      const pkg = toPackage({
        packageName: packageNameOf('pipeline', 'azure', rb),
        description: `Imports the Azure Automation runbook ${rb} and its schedule through Azure Resource Manager. Generated by ArchToolKit.`,
        categoryPath: `ArchToolKit/Pipelines/${rb}`,
        workflow: {
          name: `Import runbook ${rb}`,
          description: `Creates or updates the runbook ${rb} in an Azure Automation account (published only when its content differs), creates the schedule ${scheduleName}, and links the two only when linkRunbook is true. A dry run until dryRun is set to false in the configuration element.`,
          inputs: [{ name: 'dryRun', type: 'boolean', description: 'true: report what would be changed and change nothing' }],
          outputs: [
            { name: 'runbookState', type: 'string', description: 'created, updated or unchanged' },
            { name: 'summary', type: 'string', description: 'The audit record, JSON' },
          ],
          script: azureWorkflow({ rb, scheduleName, scheduleDescription, frequency, hh: Number(hh), mm: Number(mm), jobScheduleId, userIdentity: identity === 'user', description: `${runbookName} — ${whatItDoes}` }),
        },
        actions: [AZURE_LOGIN],
        config: {
          name: 'Settings',
          description: `Settings of Import runbook ${rb}. Fill azureClientSecret after import; set dryRun to false only after a dry run.`,
          attributes: [
            { name: 'azureTenantId', type: 'string', value: '', description: 'Microsoft Entra tenant id' },
            { name: 'azureClientId', type: 'string', value: '', description: 'Application (client) id of a service principal with Automation Contributor on the account' },
            { name: 'azureClientSecret', type: 'SecureString', description: 'Its client secret' },
            { name: 'subscriptionId', type: 'string', value: '', description: 'The subscription of the Automation account' },
            { name: 'resourceGroup', type: 'string', value: '', description: 'The resource group of the Automation account' },
            { name: 'automationAccount', type: 'string', value: '', description: 'The Automation account' },
            { name: 'timeZone', type: 'string', value: 'UTC', description: 'Time zone of the schedule' },
            { name: 'linkRunbook', type: 'boolean', value: false, description: 'False: the schedule exists and nothing runs. True: the job schedule links the runbook to it' },
            ...(identity === 'user' ? [{ name: 'userAssignedClientId', type: 'string'         , value: '', description: 'Client id of the user-assigned identity the runbook connects as' }] : []),
            { name: 'azureLoginHost', type: 'string', value: 'login.microsoftonline.com', description: 'Entra ID login host (another cloud: login.microsoftonline.us, …)' },
            { name: 'armHost', type: 'string', value: 'management.azure.com', description: 'Resource Manager host (another cloud: management.usgovcloudapi.net, …)' },
            { name: 'dryRun', type: 'boolean', value: true, description: 'The arming switch: nothing is changed while this is true' },
            { name: 'cap', type: 'number', value: 5, description: 'The most changes one run may make' },
            { name: 'webhook', type: 'string', value: '', description: 'Optional: where the audit record is posted' },
          ],
        },
        resources: [{ name: `${rb}.ps1`, content: ps, mimeType: 'text/plain' }],
      });

      const importMd = [
        '# Importing this into Azure Automation',
        '',
        ...packageImportMd(pkg, [
          '## Route 1 — the Orchestrator package imports it through Azure Resource Manager',
          '',
          `The package \`${pkg.packageDir}\` holds the workflow **${pkg.workflowName}**, the central component: as a service principal (client credentials at https://login.microsoftonline.com/<tenant>/oauth2/v2.0/token, scope https://management.azure.com/.default) it creates the runbook if missing (PUT …/runbooks/${rb}), replaces its draft (PUT …/draft/content, text/powershell) and publishes it (POST …/publish) only when the published content (GET …/content) differs, creates the schedule ${scheduleName} if missing (PUT …/schedules/…), and creates the job schedule (PUT …/jobSchedules/${jobScheduleId}) only when linkRunbook is true — so it is created disabled here too. api-version 2023-11-01 throughout. Orchestrator runs anywhere VCF 9.1 runs it (Orchestrate tab or VCF Operations orchestrator); it needs HTTPS out to login.microsoftonline.com and management.azure.com.`,
        ]),
        '## Route 2 — by hand',
        '',
        'Do the steps in order. `RG` is the resource group and `ACCT` the Automation account.',
        '',
        `## 1. The runbook — \`import/azure/${rb}.ps1\``,
        '',
        `Portal: Automation account → Process Automation → **Runbooks** → **Import a runbook** → browse for \`${rb}.ps1\`, Runbook type **PowerShell**, Runtime version 7.2 (5.1 also works) → **Import**, then **Publish**. The runbook is named after the file.`,
        '',
        'Azure CLI (the `automation` extension: `az extension add --name automation`):',
        '',
        '```bash',
        `az automation runbook create -g RG --automation-account-name ACCT --name ${rb} --type PowerShell`,
        `az automation runbook replace-content -g RG --automation-account-name ACCT --name ${rb} --content @import/azure/${rb}.ps1`,
        `az automation runbook publish -g RG --automation-account-name ACCT --name ${rb}`,
        '```',
        '',
        'Or Az PowerShell:',
        '',
        '```powershell',
        `Import-AzAutomationRunbook -Path ./import/azure/${rb}.ps1 -Type PowerShell -ResourceGroupName RG -AutomationAccountName ACCT -Published`,
        '```',
        '',
        '## 2. Run it once by hand',
        '',
        `Portal: the runbook → **Start** with Execute left empty, or \`az automation runbook start -g RG --automation-account-name ACCT --name ${rb}\`. Read the output stream: it is a dry run.`,
        '',
        `## 3. The schedule — \`import/azure/${rb}-schedule.bicep\` (or \`${rb}-schedule.json\`)`,
        '',
        '```bash',
        `az deployment group create -g RG --template-file import/azure/${rb}-schedule.bicep --parameters automationAccountName=ACCT${identity === 'user' ? ' userAssignedClientId=<client id>' : ''}`,
        '```',
        '',
        `Portal alternative: **Deploy a custom template** → **Build your own template in the editor** → **Load file** → \`${rb}-schedule.json\`.`,
        '',
        'This creates the schedule and does not link the runbook to it, so nothing runs yet.',
        '',
        '## 4. Turn it on',
        '',
        '```bash',
        `az deployment group create -g RG --template-file import/azure/${rb}-schedule.bicep --parameters automationAccountName=ACCT linkRunbook=true${identity === 'user' ? ' userAssignedClientId=<client id>' : ''}`,
        '```',
        '',
        'The scheduled run is still a dry run: the job schedule passes no `Execute`. When the reports read right, add `Execute: \'true\'` to the job schedule parameters (a job schedule cannot be changed in place — delete it and deploy again).',
        '',
        '## Confirmed, and what to verify',
        '',
        '- `az automation runbook create / replace-content --content @file / publish` and the `--type` values: Microsoft Learn, az automation runbook (extension).',
        '- The schedules and jobSchedules resource shapes (a job schedule name is a GUID; `isEnabled` is not a create property): Microsoft Learn, Microsoft.Automation template reference.',
        '- startTime defaults to tomorrow ${hh}:${mm} UTC (the time in the schedule text, read as UTC). To run in local time, pass startTime without the Z and timeZone as an IANA name such as `Europe/London` — VERIFY the result in the schedule blade before linking.',
        '- The workflow\'s calls: Microsoft Learn, Azure Automation REST 2023-11-01 — "Runbook - Create Or Update" (location and properties.runbookType required), "Runbook Draft - Replace Content" (PUT, Content-Type text/powershell, 202), "Runbook - Publish" (POST, 202), "Runbook - Get Content", "Schedule - Create Or Update", "Job Schedule - Create"; and the Microsoft identity platform client-credentials grant.',
        '- VERIFY: that the draft replacement (202, asynchronous) has finished before the publish on a large runbook; if a publish fails with a conflict, run the workflow again.',
        '',
      ].join('\n');

      return {
        platform: PLATFORM,
        title: `${runbookName} — ${whatItDoes}`,
        effect: changes ? 'reversible' : 'read',
        trigger: { kind: 'schedule', detail: schedule, worstCase: 'once a day, plus whenever somebody starts it by hand' },
        scope: {
          what: `Whatever the identity can see in ${scope}.`,
          decidedBy: [
            `The ${identity === 'runas' ? 'Run As account' : 'managed identity'} and the roles assigned to it.`,
            'The subscription the automation account is in — assert it, do not assume it.',
            'Whatever filter the work block applies.',
          ],
          ifWrong: 'An over-privileged identity is the real blast radius here, not the script. Give it exactly the role it needs and the scope is bounded by Azure rather than by the code.',
        },
        guardrails: [
          { rule: 'Dry run by default; -Execute takes it off', because: 'Nobody reads a runbook before the first scheduled run. This way the first run reports.' },
          { rule: 'The schedule is created disabled', because: 'Deploying a template should not start something running.' },
          { rule: 'No credential in the file', because: 'A runbook is exported, versioned and read by more people than the person who wrote it.' },
          { rule: 'The subscription is logged before any work', because: 'The context is per-session. A runbook that acts on the wrong subscription does so silently.' },
        ],
        dryRun: [`The Orchestrator workflow ${pkg.workflowName} is a dry run until dryRun is set to false in its configuration element: it reads, and logs every "DRY RUN: would …" with an AUDIT summary.`, 'Start it by hand with -Execute absent and read the output stream in full.', 'Only then enable the schedule.'],
        undo: changes ? ['Whatever the work block changed has to be put back by the same means. Record the previous values in the run output — that log is the only undo.'] : ['Nothing to undo. It reads.'],
        told: ['The job output in Azure Automation, kept for the account’s retention period. Forward it to a log workspace if the record needs to outlive that.'],
        requires: [
          'An Automation account with the Az modules imported — the built-in versions lag, and a runbook that works locally can fail there on a missing cmdlet.',
          `${identity === 'user' ? 'A user-assigned identity and its client id' : identity === 'system' ? 'A system-assigned identity on the account' : 'A Run As account, which is retired'}, with exactly the roles this needs.`,
        ],
        files: {
          ...pkg.files,
          [`import/azure/${rb}.ps1`]: ps,
          [`import/azure/${rb}-schedule.bicep`]: bicep,
          [`import/azure/${rb}-schedule.json`]: `${JSON.stringify(arm, null, 2)}\n`,
          'IMPORT.md': importMd,
        },
        notes: [
          'Module versions in Azure Automation are not the versions on your laptop. Pin them in the account and test there, not locally.',
          'The output stream is the record. Write what you did to it, not just that you finished.',
        ],
        findings,
      };
    },
  }),

  automationBlueprint({
    id: 'pipe_ssm_document',
    platform: PLATFORM,
    label: 'AWS Systems Manager document',
    group: 'AWS',
    description:
      'An SSM document with the two things that separate a safe run from a bad afternoon: a targeted resource group rather than every instance, and a rate control that stops it doing all of them at once when the first one fails.',
    inputs: [
      { id: 'doc_name', label: 'Document name', control: 'text', default: 'PatchAndReport' },
      { id: 'what_it_does', label: 'What it does', control: 'text', default: 'Applies the patch baseline and reports what changed' },
      { id: 'target_tag', label: 'Targets instances tagged', control: 'text', default: 'PatchGroup=standard' },
      { id: 'concurrency', label: 'At most (instances at once)', control: 'text', default: '10%', hint: 'A count or a percentage' },
      { id: 'error_threshold', label: 'Stop after (failures)', control: 'text', default: '1', hint: 'A count or a percentage. 1 is the safe first answer' },
      { id: 'reboot', label: 'May reboot', control: 'toggle', default: false },
    ],
    automation: (values                 , name        )             => {
      const docName = str(values, 'doc_name', 'Document');
      const whatItDoes = str(values, 'what_it_does', 'Does something');
      const targetTag = str(values, 'target_tag', '');
      const concurrency = str(values, 'concurrency', '10%');
      const errorThreshold = str(values, 'error_threshold', '1');
      const reboot = bool(values, 'reboot', false);
      const base = slugOf(name || docName, 'ssm-document');
      // SSM document names: letters, digits, _ - and ., 3 to 128 characters, and
      // not starting with aws or amazon (those prefixes are reserved).
      const cleanName = docName.replace(/[^A-Za-z0-9_.-]+/g, '-').replace(/^-+|-+$/g, '');
      const ssmName = (/^(aws|amazon)/i.test(cleanName) || cleanName.length < 3 ? `ATK-${cleanName || 'Document'}` : cleanName).slice(0, 128);

      const findings            = [];
      if (!targetTag) {
        findings.push(
          error('pipe.ssm.no-target', 'No target tag, so this can be run against every managed instance in the account.', {
            remediation: 'Target by tag. An SSM document with no target is one console click away from the whole estate.',
            source: 'ArchToolKit',
          }),
        );
      }
      if (/^100%$|^0$/.test(errorThreshold)) {
        findings.push(
          warning('pipe.ssm.no-stop', 'Nothing stops this if instances start failing.', {
            remediation: 'Set the error threshold to 1 for the first few runs. If the first instance fails, the other four hundred should not be attempted.',
            source: 'ArchToolKit',
          }),
        );
      }

      const doc = [
        `# ${docName} — ${whatItDoes}`,
        '#',
        '# Generated by ArchToolKit. Run it with --dry-run first; the document',
        '# honours it and reports rather than acting.',
        "schemaVersion: '2.2'",
        `description: ${JSON.stringify(whatItDoes)}`,
        'parameters:',
        '  DryRun:',
        '    type: String',
        "    default: 'true'",
        "    allowedValues: ['true', 'false']",
        '    description: Report what would be done without doing it',
        ...(reboot
          ? [
              '  RebootOption:',
              '    type: String',
              "    default: 'NoReboot'",
              "    allowedValues: ['NoReboot', 'RebootIfNeeded']",
              '    description: Rebooting is a separate decision from patching',
            ]
          : []),
        'mainSteps:',
        '  - action: aws:runShellScript',
        '    name: run',
        '    precondition:',
        '      StringEquals: [platformType, Linux]',
        '    inputs:',
        '      timeoutSeconds: 3600',
        '      runCommand:',
        '        # runShellScript runs the lines with sh, which may be dash: no pipefail.',
        '        - set -eu',
        '        - |',
        '          if [ "{{ DryRun }}" = "true" ]; then',
        `            echo "DRY RUN: would ${whatItDoes.toLowerCase()} on $(hostname)"`,
        '            exit 0',
        '          fi',
        `        - '# --- the work: ${whatItDoes.replace(/'/g, "''")} ---'`,
        '        - echo "replace this step"',
        ...(reboot
          ? [
              '        # Exit code 194 asks the agent to reboot and run the document again;',
              '        # the second pass finds no reboot pending and ends.',
              '        - |',
              '          if [ "{{ RebootOption }}" = "RebootIfNeeded" ] && [ -f /var/run/reboot-required ]; then',
              '            exit 194',
              '          fi',
            ]
          : []),
        '',
      ].join('\n');

      // The CreateAssociation request, as aws ssm create-association --cli-input-json takes it.
      const association = {
        Name: ssmName,
        DocumentVersion: '$DEFAULT',
        AssociationName: `${base}-association`,
        Targets: targetTag
          ? [{ Key: `tag:${targetTag.split('=')[0]}`, Values: [targetTag.split('=')[1] ?? '<REQUIRED>'] }]
          : [{ Key: 'tag:<REQUIRED>', Values: ['<REQUIRED>'] }],
        Parameters: { DryRun: ['true'] },
        ScheduleExpression: 'cron(0 3 ? * SUN *)',
        MaxConcurrency: concurrency,
        MaxErrors: errorThreshold,
        ComplianceSeverity: 'MEDIUM',
        ApplyOnlyAtCronInterval: true,
      };

      // The Orchestrator package does both steps of the import through the SSM
      // API (JSON 1.1 protocol, Signature Version 4, signed in the workflow's
      // own action because Orchestrator has no AWS signer): the document
      // created, or a new version made default when its content differs; the
      // association created only if none has its name.
      const pkg = toPackage({
        packageName: packageNameOf('pipeline', 'ssm', ssmName),
        description: `Creates the SSM document ${ssmName} and its State Manager association through the Systems Manager API. Generated by ArchToolKit.`,
        categoryPath: `ArchToolKit/Pipelines/${ssmName}`,
        workflow: {
          name: `Import SSM document ${ssmName}`,
          description: `Creates the Command document ${ssmName} (or a new default version when its content differs) and the association ${association.AssociationName} (only if none has that name). The association is created with DryRun=true. A dry run until dryRun is set to false in the configuration element.`,
          inputs: [{ name: 'dryRun', type: 'boolean', description: 'true: report what would be changed and change nothing' }],
          outputs: [
            { name: 'documentState', type: 'string', description: 'created, updated or unchanged' },
            { name: 'associationId', type: 'string', description: 'The association id; empty when a dry run would create it' },
            { name: 'summary', type: 'string', description: 'The audit record, JSON' },
          ],
          script: ssmWorkflow(ssmName, association.AssociationName),
        },
        actions: [AWS_SSM],
        config: {
          name: 'Settings',
          description: `Settings of Import SSM document ${ssmName}. Fill awsSecretAccessKey after import; set dryRun to false only after a dry run.`,
          attributes: [
            { name: 'awsRegion', type: 'string', value: '', description: 'The region, e.g. eu-west-1' },
            { name: 'awsAccessKeyId', type: 'string', value: '', description: 'Access key id of an IAM user or role allowed ssm:DescribeDocument, GetDocument, CreateDocument, UpdateDocument, UpdateDocumentDefaultVersion, ListAssociations and CreateAssociation — nothing else' },
            { name: 'awsSecretAccessKey', type: 'SecureString', description: 'Its secret access key' },
            { name: 'awsSessionToken', type: 'SecureString', description: 'Optional: the session token of temporary credentials' },
            { name: 'ssmEndpoint', type: 'string', value: '', description: 'Optional: another endpoint host, e.g. a VPC endpoint; empty for ssm.<region>.amazonaws.com' },
            { name: 'dryRun', type: 'boolean', value: true, description: 'The arming switch: nothing is changed while this is true' },
            { name: 'cap', type: 'number', value: 3, description: 'The most changes one run may make' },
            { name: 'webhook', type: 'string', value: '', description: 'Optional: where the audit record is posted' },
          ],
        },
        resources: [
          { name: 'document.yaml', content: doc, mimeType: 'text/plain' },
          { name: 'association.json', content: `${JSON.stringify(association, null, 2)}\n` },
        ],
      });

      return {
        platform: PLATFORM,
        title: `${docName} — ${whatItDoes}`,
        effect: reboot ? 'irreversible' : 'reversible',
        trigger: { kind: 'schedule', detail: 'Weekly, Sunday 03:00 UTC, through a State Manager association', worstCase: `once a week across every instance tagged ${targetTag || '(nothing — see the finding)'}` },
        scope: {
          what: targetTag ? `Managed instances tagged ${targetTag}.` : 'Every managed instance — no target is set.',
          decidedBy: ['The target tag on the association.', 'Which instances have the SSM agent and an instance profile.', `The concurrency: ${concurrency} at a time.`],
          ifWrong: `It runs on instances you did not mean, ${concurrency} at a time, stopping after ${errorThreshold} failures. Those last two numbers are what turn a mistake into a contained one.`,
        },
        guardrails: [
          { rule: `Targets by tag: ${targetTag || 'NOT SET'}`, because: 'The alternative is every managed instance in the account, and that is a single click in the console.' },
          { rule: `At most ${concurrency} at a time`, because: 'If it is going to break them, it should break a few before anybody notices, not all of them.' },
          { rule: `Stops after ${errorThreshold} failures`, because: 'The first failure is information. The four hundredth is an incident review.' },
          { rule: 'DryRun defaults to true', because: 'The association is created reporting. Flip the parameter when the report reads correctly.' },
          ...(reboot ? [{ rule: 'Rebooting is a separate parameter', because: 'Patching and rebooting are two decisions and two maintenance windows.' }] : []),
        ],
        dryRun: [`The Orchestrator workflow ${pkg.workflowName} is a dry run until dryRun is set to false in its configuration element: it reads, and logs every "DRY RUN: would …" with an AUDIT summary.`, 'The association is created with DryRun=true. Let it run once on the schedule and read the command output for a sample of instances.'],
        undo: reboot
          ? ['A reboot cannot be undone. Whatever was in memory on those instances is gone, which is why the reboot option is separate and off.']
          : ['Depends on the work. Record enough in the output to put it back, and treat that output as the undo.'],
        told: ['Command history in Systems Manager, and compliance status on the association. Neither pages anybody — wire a CloudWatch Events rule to the failure if somebody needs to know.'],
        requires: ['The SSM agent and an instance profile with the managed policy on every target.', 'The tag actually applied to the instances you mean — check with a Resource Groups query first.'],
        files: {
          ...pkg.files,
          [`import/ssm/${ssmName}.yaml`]: doc,
          [`import/ssm/${base}-association.json`]: `${JSON.stringify(association, null, 2)}\n`,
          'IMPORT.md': [
            '# Importing this into AWS Systems Manager',
            '',
            ...packageImportMd(pkg, [
              '## Route 1 — the Orchestrator package creates both through the SSM API',
              '',
              `The package \`${pkg.packageDir}\` holds the workflow **${pkg.workflowName}**, the central component. It signs each call with Signature Version 4 (the signer is an action in the package: Orchestrator has none) and calls the SSM JSON API: DescribeDocument; CreateDocument when the document is missing, or GetDocument, UpdateDocument and UpdateDocumentDefaultVersion when its content differs; ListAssociations filtered by AssociationName, and CreateAssociation with \`import/ssm/${base}-association.json\` when none exists — an existing association is left alone (change DryRun on it with update-association). Orchestrator needs HTTPS out to ssm.<region>.amazonaws.com or a VPC endpoint.`,
            ]),
            '## Route 2 — the AWS CLI',
            '',
            'Run from the folder this file is in, with credentials for the target account and region.',
            '',
            `## 1. The document — \`import/ssm/${ssmName}.yaml\``,
            '',
            '```bash',
            `aws ssm create-document --name ${ssmName} --document-type Command --document-format YAML --content file://import/ssm/${ssmName}.yaml`,
            '```',
            '',
            `Console alternative: Systems Manager → Documents → **Create document** → **Command or Session**, name \`${ssmName}\`, Document type Command, Content **YAML**, paste the file.`,
            '',
            `To change it later: \`aws ssm update-document --name ${ssmName} --document-format YAML --content file://import/ssm/${ssmName}.yaml --document-version '$LATEST'\`, then \`aws ssm update-document-default-version --name ${ssmName} --document-version <n>\`.`,
            '',
            '## 2. Try it on one instance',
            '',
            '```bash',
            `aws ssm send-command --document-name ${ssmName} --targets Key=InstanceIds,Values=<one instance id> --parameters DryRun=true`,
            '```',
            '',
            `## 3. The association — \`import/ssm/${base}-association.json\``,
            '',
            '```bash',
            `aws ssm create-association --cli-input-json file://import/ssm/${base}-association.json`,
            '```',
            '',
            'It is created with DryRun=true and ApplyOnlyAtCronInterval, so it runs first at the next scheduled time and only reports. When the reports read right: `aws ssm update-association --association-id <id> --parameters DryRun=false` (update-association replaces the parameters you pass).',
            '',
            '## Confirmed',
            '',
            '- create-document with `--document-format YAML --content file://…` and schema 2.2 `mainSteps` / `aws:runShellScript`: AWS CLI reference and the SSM document syntax reference.',
            '- The association file uses only CreateAssociation request members (Name, DocumentVersion, AssociationName, Targets, Parameters, ScheduleExpression, MaxConcurrency, MaxErrors, ComplianceSeverity, ApplyOnlyAtCronInterval), which is what `--cli-input-json` takes.',
            '- The workflow: POST / with X-Amz-Target AmazonSSM.<Operation> and Content-Type application/x-amz-json-1.1 (the SSM API\'s JSON protocol), signed with AWS4-HMAC-SHA256 over content-type, host, x-amz-date and x-amz-target (AWS General Reference, "Signature Version 4 signing process"). A missing document answers 400 InvalidDocument; UpdateDocument with the same content answers DuplicateDocumentContent, which the workflow treats as unchanged.',
            '',
          ].join('\n'),
        },
        notes: [
          'Targeting by tag means the estate can add itself to the automation by tagging. That is the feature and the risk in the same sentence.',
          'ApplyOnlyAtCronInterval stops the association running the moment it is created, which is otherwise the default and a surprise.',
        ],
        findings,
      };
    },
  }),

  automationBlueprint({
    id: 'pipe_awx_template',
    platform: PLATFORM,
    label: 'AWX or Tower job template',
    group: 'Ansible',
    description:
      'A job template for the playbooks this toolkit already writes: credentials from AWX rather than from the repository, a check-mode run first, limits so a wrong inventory does not become a wrong estate, and a survey when a human has to choose.',
    inputs: [
      { id: 'template_name', label: 'Template name', control: 'text', default: 'Patch Linux — standard group' },
      { id: 'playbook', label: 'Playbook', control: 'text', default: 'playbooks/patch.yml' },
      { id: 'organization', label: 'Organization', control: 'text', default: 'Default' },
      { id: 'project', label: 'Project (where the playbook lives)', control: 'text', default: 'Infrastructure playbooks' },
      { id: 'inventory', label: 'Inventory', control: 'text', default: 'Production Linux' },
      { id: 'machine_credential', label: 'Machine credential', control: 'text', default: 'Linux — patching service account', hint: 'The name of a credential already in AWX. Nothing secret goes in the file' },
      { id: 'limit', label: 'Limit to', control: 'text', default: 'linux_standard', hint: 'A group. An empty limit is the whole inventory' },
      { id: 'forks', label: 'Hosts at a time', control: 'number', default: 10, min: 1, max: 200 },
      { id: 'check_first', label: 'Run in check mode first', control: 'toggle', default: true },
      { id: 'ask_for_approval', label: 'Needs approval in the workflow', control: 'toggle', default: false },
    ],
    automation: (values                 , name        )             => {
      const templateName = str(values, 'template_name', 'Job template');
      const playbook = str(values, 'playbook', 'site.yml');
      const inventory = str(values, 'inventory', 'Production');
      const organization = str(values, 'organization', 'Default');
      const project = str(values, 'project', 'Playbooks');
      const machineCredential = str(values, 'machine_credential', 'Machine credential');
      const limit = str(values, 'limit', '');
      const forks = num(values, 'forks', 10);
      const checkFirst = bool(values, 'check_first', true);
      const approval = bool(values, 'ask_for_approval', false);
      const base = slugOf(name || templateName, 'job-template');

      const findings            = [];
      if (!limit) {
        findings.push(
          warning('pipe.awx.no-limit', `No limit is set, so this runs against every host in "${inventory}".`, {
            remediation: 'Set a limit to a group. An inventory grows; a limit is a deliberate statement about what this template is for.',
            source: 'ArchToolKit',
          }),
        );
      }

      // The awxkit export format — what `awx export` writes and `awx import`
      // reads: one key per resource type, every reference a natural key (names,
      // qualified by organization) rather than an id, so it imports into any
      // instance that has objects with those names.
      const org = { name: organization, type: 'organization' };
      const jtKey = { organization: org, name: templateName, type: 'job_template' };
      const workflowName = `${templateName} — workflow`;
      const wfKey = { organization: org, name: workflowName, type: 'workflow_job_template' };
      const nodeKey = (identifier        ) => ({ workflow_job_template: wfKey, identifier, type: 'workflow_job_template_node' });

      const template = {
        name: templateName,
        description: 'ArchToolKit. Credentials are attached in AWX, never in the repository.',
        job_type: 'run',
        inventory: { organization: org, name: inventory, type: 'inventory' },
        project: { organization: org, name: project, type: 'project' },
        playbook,
        scm_branch: '',
        forks,
        limit,
        verbosity: 1,
        extra_vars: '---',
        job_tags: '',
        skip_tags: '',
        timeout: 0,
        become_enabled: true,
        diff_mode: true,
        allow_simultaneous: false,
        ask_limit_on_launch: true,
        ask_variables_on_launch: true,
        // A workflow node can only run the template in check mode if the
        // template prompts for the job type.
        ask_job_type_on_launch: checkFirst,
        survey_enabled: true,
        related: {
          credentials: [{ organization: org, name: machineCredential, credential_type: { name: 'Machine', kind: 'ssh', type: 'credential_type' }, type: 'credential' }],
          labels: [],
          survey_spec: {
            name: '',
            description: '',
            spec: [
              {
                question_name: 'Change reference',
                question_description: 'The change or ticket this run belongs to. It is written into the job so the record says why.',
                required: true,
                type: 'text',
                variable: 'change_reference',
                min: 1,
                max: 128,
                default: '',
                choices: '',
                new_question: true,
              },
            ],
          },
        },
        natural_key: jtKey,
      };

      const order = [...(checkFirst ? ['check'] : []), ...(approval ? ['approve'] : []), 'run'];
      const node = (identifier        ) => {
        const next = order[order.indexOf(identifier) + 1];
        const base = {
          identifier,
          all_parents_must_converge: false,
          extra_data: {},
          job_type: identifier === 'check' ? 'check' : null,
          limit: null,
          inventory: null,
          scm_branch: null,
          job_tags: null,
          skip_tags: null,
          diff_mode: null,
          verbosity: null,
          workflow_job_template: wfKey,
          natural_key: nodeKey(identifier),
        };
        const related = { success_nodes: next ? [nodeKey(next)] : [], failure_nodes: [], always_nodes: [], credentials: [] };
        // An approval node has no job template: awxkit exports it with the
        // approval template's own fields under create_approval_template.
        return identifier === 'approve'
          ? { ...base, related: { ...related, create_approval_template: { name: `${templateName} — read the check-mode output before approving`, description: 'The check-mode job is the node before this one. Open it and read what would change.', timeout: 86400 } } }
          : { ...base, unified_job_template: jtKey, related };
      };

      const workflow = {
        name: workflowName,
        description: 'ArchToolKit: check mode, then approval, then the real run.',
        organization: org,
        extra_vars: '---',
        inventory: null,
        limit: null,
        scm_branch: null,
        allow_simultaneous: false,
        ask_variables_on_launch: false,
        ask_inventory_on_launch: false,
        ask_limit_on_launch: false,
        survey_enabled: false,
        related: { workflow_nodes: order.map(node), labels: [] },
        natural_key: wfKey,
      };

      const exportJson = { job_templates: [template], workflow_job_templates: [workflow] };

      // What the Orchestrator workflow creates through the AWX REST API: the
      // same job template and workflow, with names resolved to ids at run time.
      const { related: _jtRelated, natural_key: _jtKey, inventory: _inv, project: _proj, ...jobTemplateBody } = template;
      const awxObjects = {
        organization,
        inventory,
        project,
        credential: machineCredential,
        jobTemplate: jobTemplateBody,
        survey: template.related.survey_spec,
        workflow: {
          name: workflow.name,
          description: workflow.description,
          extra_vars: workflow.extra_vars,
          allow_simultaneous: workflow.allow_simultaneous,
          ask_variables_on_launch: workflow.ask_variables_on_launch,
          ask_inventory_on_launch: workflow.ask_inventory_on_launch,
          ask_limit_on_launch: workflow.ask_limit_on_launch,
          survey_enabled: workflow.survey_enabled,
        },
        nodes: order.map((identifier) =>
          identifier === 'approve'
            ? { identifier, kind: 'approval', approval: { name: `${templateName} — read the check-mode output before approving`, description: 'The check-mode job is the node before this one. Open it and read what would change.', timeout: 86400 } }
            : { identifier, kind: 'job', ...(identifier === 'check' ? { job_type: 'check' } : {}) },
        ),
      };
      const pkg = toPackage({
        packageName: packageNameOf('pipeline', 'awx', base),
        description: `Creates the AWX job template "${templateName}" and its workflow through the AWX REST API. Generated by ArchToolKit.`,
        categoryPath: `ArchToolKit/Pipelines/${base}`,
        workflow: {
          name: `Import AWX template ${base}`,
          description: `Creates in AWX / Automation Controller the job template "${templateName}" (credential and survey attached) and the workflow "${workflowName}" (${order.join(' → ')}), resolving the organization, inventory, project and credential by name. Either one that already exists is left alone. A dry run until dryRun is set to false in the configuration element.`,
          inputs: [{ name: 'dryRun', type: 'boolean', description: 'true: report what would be created and change nothing' }],
          outputs: [
            { name: 'jobTemplateId', type: 'string', description: 'The job template id; empty when a dry run would create it' },
            { name: 'workflowTemplateId', type: 'string', description: 'The workflow job template id; empty when a dry run would create it' },
            { name: 'summary', type: 'string', description: 'The audit record, JSON' },
          ],
          script: AWX_WORKFLOW,
        },
        config: {
          name: 'Settings',
          description: `Settings of Import AWX template ${base}. Fill awxToken after import; set dryRun to false only after a dry run.`,
          attributes: [
            { name: 'awxHost', type: 'string', value: '', description: 'AWX or Automation Controller host (Automation Platform 2.5 and later: the gateway)' },
            { name: 'awxApiPath', type: 'string', value: '/api/v2/', description: '/api/v2/ for AWX and controller up to AAP 2.4; /api/controller/v2/ through the AAP 2.5 gateway' },
            { name: 'awxToken', type: 'SecureString', description: 'An OAuth2 token of an account that may create templates in the organization' },
            { name: 'dryRun', type: 'boolean', value: true, description: 'The arming switch: nothing is created while this is true' },
            { name: 'cap', type: 'number', value: 4 + order.length * 2 + (approval ? 1 : 0), description: 'The most objects one run may create or link' },
            { name: 'webhook', type: 'string', value: '', description: 'Optional: where the audit record is posted' },
          ],
        },
        resources: [{ name: 'awx-objects.json', content: `${JSON.stringify(awxObjects, null, 2)}\n` }],
      });

      const importMd = [
        '# Importing this into AWX or Automation Platform',
        '',
        ...packageImportMd(pkg, [
          '## Route 1 — the Orchestrator package creates them through the AWX API',
          '',
          `The package \`${pkg.packageDir}\` holds the workflow **${pkg.workflowName}**, the central component. With an OAuth2 token it resolves the organization, inventory, project and machine credential by name (GET organizations/, inventories/, projects/, credentials/ — each must exist, and exactly once), then, unless a job template of that name exists: POST job_templates/, POST job_templates/{id}/credentials/ and POST job_templates/{id}/survey_spec/; unless the workflow exists: POST workflow_job_templates/, one POST workflow_job_templates/{id}/workflow_nodes/ per node${approval ? ', POST workflow_job_template_nodes/{id}/create_approval_template/ for the approval' : ''} and POST workflow_job_template_nodes/{id}/success_nodes/ for each link. What exists is left alone. Orchestrator needs HTTPS to the controller.`,
        ]),
        '## Route 2 — awx import',
        '',
        `\`import/awx/${base}.json\` is in the format \`awx export\` writes and \`awx import\` reads (awxkit): a job template and a workflow, every reference by name.`,
        '',
        '## 1. What must exist first, with exactly these names',
        '',
        `- Organization **${organization}**`,
        `- Project **${project}**, containing \`${playbook}\``,
        `- Inventory **${inventory}**${limit ? ` with a group **${limit}**` : ''}`,
        `- Machine credential **${machineCredential}** (and a vault credential, attached by hand afterwards, if the playbook uses one)`,
        '',
        'The import resolves each of these by name and stops if one is missing.',
        '',
        '## 2. Import',
        '',
        '```bash',
        'pip install awxkit            # the version that matches your AWX / controller',
        'export CONTROLLER_HOST=https://awx.example.com',
        'export CONTROLLER_USERNAME=<an account that can create templates in the organization>',
        'read -rs CONTROLLER_PASSWORD && export CONTROLLER_PASSWORD',
        '# Automation Platform 2.5 and later, through the gateway:',
        '# export AWXKIT_API_BASE_PATH=/api/controller/',
        `awx import < import/awx/${base}.json`,
        '```',
        '',
        '## 3. Before the first real run',
        '',
        `Launch **${workflowName}**${checkFirst ? ' and read the check-mode job' : ''}${approval ? ', then approve or deny the approval node' : ''}. Attach a failure notification in the template’s Notifications tab.`,
        '',
        '## Confirmed, and what to verify',
        '',
        '- The top-level keys (`job_templates`, `workflow_job_templates`), natural keys, `related.credentials`, `related.survey_spec` and `related.workflow_nodes` with `success_nodes` as node natural keys: awxkit (awxkit/api/pages/api.py) and exports shown in ansible/awx issues #7946 and #14292.',
        ...(approval ? ['- VERIFY: the approval node. awxkit exports approval nodes through `create_approval_template` (name, description, timeout) rather than a natural key; if your awxkit version rejects it, delete that node from the file and add the approval in the workflow visualizer.'] : []),
        '- awxkit 22.4.0 to 23.x had a bug that dropped success_nodes on export (issue #14292). Import with a current awxkit.',
        '- The workflow\'s endpoints are the AWX API v2 ones (the browsable API at /api/v2/ lists them: job_templates/{id}/credentials/, job_templates/{id}/survey_spec/, workflow_job_templates/{id}/workflow_nodes/, workflow_job_template_nodes/{id}/success_nodes/ and create_approval_template/). Through the Automation Platform 2.5 gateway the same API is under /api/controller/v2/ — set awxApiPath.',
        '',
      ].join('\n');

      return {
        platform: PLATFORM,
        title: `${templateName} — ${playbook} against ${limit || inventory}`,
        effect: 'reversible',
        trigger: { kind: 'schedule', detail: 'Whatever schedule you attach in AWX, or launched by hand', worstCase: `every host in ${limit || inventory}, ${forks} at a time` },
        scope: {
          what: limit ? `Hosts in the group "${limit}" of inventory "${inventory}".` : `Every host in inventory "${inventory}".`,
          decidedBy: ['The inventory and how it is populated — a dynamic inventory changes under you.', limit ? `The limit: ${limit}.` : 'No limit.', 'Any limit typed at launch, which overrides the one above.'],
          ifWrong: 'The playbook runs somewhere it should not. Ansible is idempotent, which helps, and not harmless, which people forget.',
        },
        guardrails: [
          ...(checkFirst ? [{ rule: 'Check mode runs first in the workflow', because: 'Check mode is Ansible’s dry run and it is free. The output is the list of what would change.' }] : []),
          ...(approval ? [{ rule: 'A human approves between check and run', because: 'The approval is only worth having if the check-mode output is in front of the approver. Link it in the approval description.' }] : []),
          { rule: `${forks} hosts at a time`, because: 'A playbook that breaks things should break a few first.' },
          { rule: 'Credentials come from AWX', because: 'A vault password in the repository is a vault password in everyone’s clone.' },
        ],
        dryRun: [`The Orchestrator workflow ${pkg.workflowName} is a dry run until dryRun is set to false in its configuration element: it reads, and logs every "DRY RUN: would …" with an AUDIT summary.`, 'Launch the check-mode node on its own and read the changed list.', 'Not every module supports check mode — the ones that do not are the ones to read twice.'],
        undo: ['Ansible does not roll back. The undo is another playbook, and if the change is significant it should be written before the change is run.'],
        told: ['The job output in AWX, kept per its retention. Set a notification on failure — a silent failed job is worse than a loud one.'],
        requires: [`The organization "${organization}", project "${project}", inventory "${inventory}" and the group "${limit || '(none)'}".`, `The machine credential "${machineCredential}" in AWX, and a vault credential if the playbook uses one.`],
        files: { ...pkg.files, [`import/awx/${base}.json`]: `${JSON.stringify(exportJson, null, 2)}\n`, 'IMPORT.md': importMd },
        notes: [
          'ask_limit_on_launch is on, which lets somebody narrow the run at launch. It also lets them widen it — the limit on the template is a default, not a ceiling.',
          'A dynamic inventory means the scope is decided at launch by something else entirely. Check what populates it before trusting the limit.',
        ],
        findings,
      };
    },
  }),

  automationBlueprint({
    id: 'pipe_ci_terraform',
    platform: PLATFORM,
    label: 'Plan on a pull request, apply on merge',
    group: 'CI',
    description:
      'The pipeline for the Terraform this toolkit writes: plan on every pull request with the output posted back, apply only from the default branch, state locked, and credentials from the platform’s identity rather than a secret in the repository.',
    inputs: [
      {
        id: 'ci',
        label: 'Runs on',
        control: 'select',
        options: [
          { value: 'github', label: 'GitHub Actions' },
          { value: 'azdo', label: 'Azure Pipelines' },
        ],
        default: 'github',
      },
      { id: 'working_dir', label: 'Terraform lives in', control: 'text', default: 'infra/' },
      {
        id: 'cloud',
        label: 'Against',
        control: 'select',
        options: [
          { value: 'azure', label: 'Azure' },
          { value: 'aws', label: 'AWS' },
          { value: 'vsphere', label: 'vSphere' },
        ],
        default: 'azure',
      },
      { id: 'require_approval', label: 'Apply needs an environment approval', control: 'toggle', default: true },
      { id: 'auto_apply', label: 'Apply automatically on merge', control: 'toggle', default: false },
    ],
    automation: (values                 , name        )             => {
      const ci = str(values, 'ci', 'github');
      const dir = str(values, 'working_dir', 'infra/');
      const cloud = str(values, 'cloud', 'azure');
      const approval = bool(values, 'require_approval', true);
      const autoApply = bool(values, 'auto_apply', false);
      const base = slugOf(name || `terraform-${ci}`, 'terraform-pipeline');

      const findings            = [];
      if (autoApply && !approval) {
        findings.push(
          error('pipe.ci.unattended-apply', 'A merge applies to the estate with no human in the loop.', {
            remediation: 'For a well-tested module set that is a deliberate choice. For anything else, put an environment approval on the apply — the plan is only useful if somebody reads it.',
            source: 'ArchToolKit',
          }),
        );
      }
      if (cloud === 'vsphere') {
        findings.push(
          warning('pipe.ci.vsphere-credentials', 'vSphere has no workload identity, so this needs a real credential in the CI secret store.', {
            remediation: 'Use a service account scoped to exactly what the Terraform manages, rotate it on a schedule, and never put it in the repository.',
            source: 'ArchToolKit',
          }),
        );
      }

      const githubYaml = [
        'name: Terraform',
        '',
        '# Generated by ArchToolKit.',
        '#',
        '# Plan on every pull request; apply only from the default branch. The',
        '# credential comes from OIDC rather than a stored secret, so there is',
        '# nothing to rotate and nothing to leak.',
        'on:',
        '  pull_request:',
        `    paths: ['${dir}**']`,
        '  push:',
        '    branches: [main]',
        `    paths: ['${dir}**']`,
        '',
        'permissions:',
        '  contents: read',
        '  id-token: write        # OIDC. This is what replaces a stored credential.',
        '  pull-requests: write   # so the plan can be posted back',
        '',
        'concurrency:',
        '  # One run at a time against the same state. Terraform locks, but a',
        '  # queued second run holding a lock is a confusing way to find that out.',
        '  group: terraform-${{ github.ref }}',
        '  cancel-in-progress: false',
        '',
        'jobs:',
        '  plan:',
        '    runs-on: ubuntu-latest',
        '    defaults:',
        '      run:',
        `        working-directory: ${dir}`,
        '    steps:',
        '      - uses: actions/checkout@v4',
        ...(cloud === 'azure'
          ? [
              '      - uses: azure/login@v2',
              '        with:',
              '          client-id: ${{ vars.AZURE_CLIENT_ID }}',
              '          tenant-id: ${{ vars.AZURE_TENANT_ID }}',
              '          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}',
            ]
          : cloud === 'aws'
            ? [
                '      - uses: aws-actions/configure-aws-credentials@v4',
                '        with:',
                '          role-to-assume: ${{ vars.AWS_ROLE_ARN }}',
                '          aws-region: ${{ vars.AWS_REGION }}',
              ]
            : [
                '      # vSphere has no workload identity. These come from the secret',
                '      # store, scoped to exactly what this Terraform manages.',
                '      - name: vSphere credentials',
                '        run: |',
                '          echo "TF_VAR_vsphere_user=${{ secrets.VSPHERE_USER }}" >> $GITHUB_ENV',
                '          echo "TF_VAR_vsphere_password=${{ secrets.VSPHERE_PASSWORD }}" >> $GITHUB_ENV',
              ]),
        '      - uses: hashicorp/setup-terraform@v3',
        '      - run: terraform fmt -check -recursive',
        '      - run: terraform init',
        '      - run: terraform validate',
        '      - name: Plan',
        '        id: plan',
        '        run: |',
        '          terraform plan -no-color -lock-timeout=5m -out=tfplan',
        '          terraform show -no-color tfplan > "$GITHUB_WORKSPACE/plan.txt"',
        '      - name: Post the plan on the pull request',
        "        if: github.event_name == 'pull_request'",
        '        uses: actions/github-script@v7',
        '        with:',
        '          script: |',
        '            const fs = require("fs");',
        '            const plan = fs.readFileSync(process.env.GITHUB_WORKSPACE + "/plan.txt", "utf8").slice(0, 60000);',
        '            await github.rest.issues.createComment({',
        '              issue_number: context.issue.number,',
        '              owner: context.repo.owner,',
        '              repo: context.repo.repo,',
        '              body: "```\\n" + plan + "\\n```",',
        '            });',
        '        continue-on-error: true',
        '      - uses: actions/upload-artifact@v4',
        '        with:',
        '          name: tfplan',
        `          path: ${dir}tfplan`,
        '',
        '  apply:',
        "    if: github.ref == 'refs/heads/main' && github.event_name == 'push'",
        '    needs: plan',
        '    runs-on: ubuntu-latest',
        ...(approval ? ['    # The environment carries the approval. That is where a human reads', '    # the plan before anything reaches the estate.', '    environment: production'] : []),
        '    defaults:',
        '      run:',
        `        working-directory: ${dir}`,
        '    steps:',
        '      - uses: actions/checkout@v4',
        '      - uses: actions/download-artifact@v4',
        '        with:',
        '          name: tfplan',
        `          path: ${dir}`,
        '      - uses: hashicorp/setup-terraform@v3',
        '      - run: terraform init',
        '      - name: Apply the plan that was reviewed',
        '        run: terraform apply -auto-approve -lock-timeout=5m tfplan',
        '',
      ].join('\n');

      const azdoYaml = [
        '# Generated by ArchToolKit.',
        '#',
        '# Plan on a pull request, apply from main behind an environment approval.',
        'trigger:',
        '  branches: { include: [main] }',
        `  paths: { include: ['${dir}'] }`,
        'pr:',
        '  branches: { include: ["*"] }',
        `  paths: { include: ['${dir}'] }`,
        '',
        'pool:',
        '  vmImage: ubuntu-latest',
        '',
        'variables:',
        `  workingDirectory: ${dir}`,
        '',
        'stages:',
        '  - stage: plan',
        '    jobs:',
        '      - job: plan',
        '        steps:',
        '          - task: TerraformInstaller@1',
        '          - script: terraform init',
        '            workingDirectory: $(workingDirectory)',
        '          - script: terraform validate',
        '            workingDirectory: $(workingDirectory)',
        '          - script: terraform plan -no-color -lock-timeout=5m -out=tfplan',
        '            workingDirectory: $(workingDirectory)',
        '          - publish: $(workingDirectory)/tfplan',
        '            artifact: tfplan',
        '',
        '  - stage: apply',
        "    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))",
        '    jobs:',
        '      - deployment: apply',
        '        # The environment is where the approval lives.',
        `        environment: ${approval ? 'production' : 'production-unattended'}`,
        '        strategy:',
        '          runOnce:',
        '            deploy:',
        '              steps:',
        '                - download: current',
        '                  artifact: tfplan',
        '                - task: TerraformInstaller@1',
        '                - script: terraform init',
        '                  workingDirectory: $(workingDirectory)',
        '                - script: terraform apply -auto-approve -lock-timeout=5m $(Pipeline.Workspace)/tfplan/tfplan',
        '                  workingDirectory: $(workingDirectory)',
        '',
      ].join('\n');

      // The pipeline file is imported by committing it to the repository. The
      // Orchestrator package does that through the git host's API, as a pull
      // request, and on Azure DevOps creates the pipeline definition once the
      // file is on main.
      const ciPath = ci === 'github' ? '.github/workflows/terraform.yml' : 'azure-pipelines.yml';
      const pkg = ciRepoPackage({
        packageName: packageNameOf('pipeline', 'terraform', base),
        categoryPath: `ArchToolKit/Pipelines/${base}`,
        what: 'the Terraform pipeline (plan on a pull request, apply from main)',
        ci: ci === 'github' ? 'github' : 'azdo',
        ciPath,
        files: { [ciPath]: ci === 'github' ? githubYaml : azdoYaml },
        branch: `archtoolkit/${base}`,
        ...(ci === 'azdo' ? { pipelineName: base } : {}),
      });

      return {
        platform: PLATFORM,
        title: `Terraform on ${ci === 'github' ? 'GitHub Actions' : 'Azure Pipelines'} — plan on a pull request, apply from main`,
        effect: 'reversible',
        trigger: { kind: 'commit', detail: `A pull request touching ${dir} plans; a merge to main applies${approval ? ' after an approval' : ''}`, worstCase: 'as often as people merge' },
        scope: {
          what: `Whatever the Terraform in ${dir} manages, against ${cloud}.`,
          decidedBy: ['The state file the backend points at.', 'The identity the pipeline assumes and what it is allowed to touch.', 'The contents of the plan, which is the only place this is visible before it happens.'],
          ifWrong: 'Terraform destroys and recreates without being asked twice. The plan is where that is visible, which is why it is posted on the pull request rather than buried in a log.',
        },
        guardrails: [
          { rule: 'Apply runs the plan that was reviewed, not a fresh one', because: 'A re-planned apply can do something the reviewer never saw, because the world changed in between.' },
          ...(approval ? [{ rule: 'An environment approval gates the apply', because: 'The plan is only worth producing if somebody reads it.' }] : []),
          { rule: 'One run at a time against the same state', because: 'Terraform locks, but a queued run holding a lock is a confusing way to discover that.' },
          { rule: 'A lock timeout of five minutes', because: 'The default waits forever, and a job that hangs forever is a job nobody notices has hung.' },
          ...(cloud !== 'vsphere' ? [{ rule: 'OIDC rather than a stored credential', because: 'Nothing to rotate, nothing to leak, and it expires on its own.' }] : []),
        ],
        dryRun: ['The Orchestrator workflow Propose the pipeline to the repository is a dry run until dryRun is set to false in its configuration element: it compares the files and logs what it would write and open.', 'The plan job is the dry run, and it runs on every pull request. Read it — particularly the destroy lines.'],
        undo: ['Revert the commit and let the pipeline apply the revert. That is the only undo that leaves state and code agreeing.'],
        told: ['The plan is posted on the pull request. The apply is in the run log. Add a notification on apply failure — a half-applied change is the one to know about.'],
        requires: [
          'A remote backend with locking. Local state in CI is a corrupted state file waiting for a concurrent run.',
          cloud === 'vsphere' ? 'A vSphere service account in the secret store.' : 'A federated identity credential trusting this repository, and the roles it needs.',
        ],
        files: {
          ...pkg.files,
          ...(ci === 'github' ? { '.github/workflows/terraform.yml': githubYaml } : { 'azure-pipelines.yml': azdoYaml }),
          'IMPORT.md': [
            `# Putting this pipeline into ${ci === 'github' ? 'GitHub Actions' : 'Azure Pipelines'}`,
            '',
            ...packageImportMd(pkg, [
              '## Route 1 — the Orchestrator package proposes it to the repository',
              '',
              `The package \`${pkg.packageDir}\` holds the workflow **${pkg.workflowName}**, the central component: it compares \`${ciPath}\` with the base branch of the repository in its settings, writes it to the working branch when it differs, and opens a pull request (or reuses the open one) through the ${ci === 'github' ? 'GitHub' : 'Azure DevOps'} API. The merge is what switches the pipeline on.${ci === 'azdo' ? ` Run the workflow once more after the merge: it creates the pipeline definition **${base}** pointing at /${ciPath} (POST _apis/pipelines, api-version 7.1).` : ''} Orchestrator needs HTTPS out to the git host.`,
            ]),
            '## Route 2 — commit it yourself',
            '',
            'The pipeline file is not uploaded anywhere: it is committed to the repository that holds the Terraform, at exactly the path it has here.',
            '',
            ...(ci === 'github'
              ? [
                  '1. Commit `.github/workflows/terraform.yml` to the default branch (main). GitHub picks up every workflow in `.github/workflows/` on its own; there is nothing to import.',
                  `2. ${cloud === 'azure' ? 'Add repository variables AZURE_CLIENT_ID, AZURE_TENANT_ID and AZURE_SUBSCRIPTION_ID (Settings → Secrets and variables → Actions → Variables), and a federated credential on the app registration for this repository.' : cloud === 'aws' ? 'Add repository variables AWS_ROLE_ARN and AWS_REGION, and an IAM role that trusts token.actions.githubusercontent.com for this repository.' : 'Add repository secrets VSPHERE_USER and VSPHERE_PASSWORD (Settings → Secrets and variables → Actions).'}`,
                  ...(approval ? ['3. Create the environment **production** (Settings → Environments) with required reviewers — that is the approval the apply job waits on.'] : []),
                  `${approval ? '4' : '3'}. Open a pull request that touches \`${dir}\` and check that the plan is posted on it.`,
                ]
              : [
                  '1. Commit `azure-pipelines.yml` to the root of the repository.',
                  '2. Azure DevOps → Pipelines → **New pipeline** → your repository → **Existing Azure Pipelines YAML file** → branch main, path `/azure-pipelines.yml` → **Save**. Or: `az pipelines create --name terraform --repository <repo> --branch main --yml-path azure-pipelines.yml --skip-first-run true`.',
                  `3. Create the environment **${approval ? 'production' : 'production-unattended'}** (Pipelines → Environments)${approval ? ' and add an Approvals check to it — that is the approval the apply stage waits on' : ''}.`,
                  '4. Install the "Terraform" extension (TerraformInstaller@1) from the Visual Studio Marketplace in the organization if it is not there, and give the pipeline its cloud credential through a service connection.',
                ]),
            '',
            'Sources: GitHub Docs, "Workflow syntax for GitHub Actions" (workflows live in .github/workflows); Microsoft Learn, "Create your first pipeline" and az pipelines create (--yml-path).',
            '',
          ].join('\n'),
        },
        notes: [
          'Apply the saved plan rather than re-planning. It is the difference between applying what was reviewed and applying what is true now.',
          'terraform fmt -check in the plan job keeps the diff about the change rather than about whitespace.',
        ],
        findings,
      };
    },
  }),
];

// ---------------------------------------------------------------------------
// The Orchestrator side of the non-VCF runners: each workflow puts the native
// artifact into its platform through that platform's API, idempotently, with
// the core library's dry run, cap and audit.

/** Microsoft Entra ID, client credentials: a bearer token for Azure Resource Manager. */
const AZURE_LOGIN               = {
  name: 'loginAzure',
  description:
    'Microsoft identity platform, client credentials grant: POST https://<loginHost>/<tenant>/oauth2/v2.0/token with client_id, the client secret and scope https://<armHost>/.default. Returns { Authorization: "Bearer <access token>" }.',
  resultType: 'Any',
  params: [
    { name: 'loginHost', type: 'string', description: 'login.microsoftonline.com, or another cloud\'s' },
    { name: 'tenantId', type: 'string', description: 'Entra tenant id' },
    { name: 'clientId', type: 'string', description: 'Application (client) id' },
    { name: 'clientSecret', type: 'string', description: 'From a SecureString attribute' },
    { name: 'armHost', type: 'string', description: 'management.azure.com, or another cloud\'s' },
  ],
  script: String.raw`var core = System.getModule("com.archtoolkit.core");
var form = [
  "grant_type=client_credentials",
  "client_id=" + encodeURIComponent(String(clientId)),
  "client_secret" + "=" + encodeURIComponent(String(clientSecret)),
  "scope=" + encodeURIComponent("https://" + String(armHost || "management.azure.com") + "/.default")
].join("&");
var r = core.http("POST", "https://" + (loginHost || "login.microsoftonline.com") + "/" + encodeURIComponent(String(tenantId)) + "/oauth2/v2.0/token", null, form, { contentType: "application/x-www-form-urlencoded", redact: [clientSecret] });
if (!r.body || !r.body.access_token) throw new Error("Entra ID returned no access token for client " + clientId + ".");
return { "Authorization": "Bearer " + r.body.access_token };`,
};

function azureWorkflow(spec   
                      
                                
                                       
                             
                      
                      
                                 
                                 
                               
 )         {
  const q = JSON.stringify;
  return String.raw`var RUNBOOK = ${q(spec.rb)};
var SCHEDULE = ${q(spec.scheduleName)};
var SCHEDULE_DESCRIPTION = ${q(spec.scheduleDescription)};
var FREQUENCY = ${q(spec.frequency)};
var AT_HOUR = ${spec.hh};
var AT_MINUTE = ${spec.mm};
var JOB_SCHEDULE_ID = ${q(spec.jobScheduleId)};
var USER_IDENTITY = ${spec.userIdentity ? 'true' : 'false'};
var DESCRIPTION = ${q(spec.description)};
var API_VERSION = "2023-11-01";
var ctx = core.begin(settings, dryRun);
var need = ["azureTenantId", "azureClientId", "azureClientSecret", "subscriptionId", "resourceGroup", "automationAccount"];
for (var n = 0; n < need.length; n++) if (!settings[need[n]]) throw new Error("Set " + need[n] + " in the configuration element " + SETTINGS_NAME + ".");
var armHost = settings.armHost || "management.azure.com";
var auth = mod.loginAzure(settings.azureLoginHost || "login.microsoftonline.com", settings.azureTenantId, settings.azureClientId, settings.azureClientSecret, armHost);
var ACCOUNT = "https://" + armHost + "/subscriptions/" + encodeURIComponent(settings.subscriptionId) + "/resourceGroups/" + encodeURIComponent(settings.resourceGroup) +
  "/providers/Microsoft.Automation/automationAccounts/" + encodeURIComponent(settings.automationAccount);
function url(path) { return ACCOUNT + path + "?api-version=" + API_VERSION; }
function o(extra) {
  var r = { redact: settings._secrets };
  if (extra) for (var k in extra) if (extra.hasOwnProperty(k)) r[k] = extra[k];
  return r;
}
function get(path) { return core.http("GET", url(path), auth, null, o({ allow: [404] })); }

var account = core.http("GET", url(""), auth, null, o()).body || {};
if (!account.location) throw new Error("The Automation account " + settings.automationAccount + " answered without a location.");
var script = core.resource(RESOURCE_PATH, RUNBOOK + ".ps1");

// 1. The runbook: created if missing; its draft replaced and published only
//    when what is published differs from the generated script.
var runbook = get("/runbooks/" + encodeURIComponent(RUNBOOK));
var published = null;
if (runbook.statusCode === 404) {
  core.act(ctx, "create runbook " + RUNBOOK, function () {
    return core.http("PUT", url("/runbooks/" + encodeURIComponent(RUNBOOK)), auth,
      { name: RUNBOOK, location: account.location, properties: { runbookType: "PowerShell", logProgress: false, logVerbose: false, description: DESCRIPTION } }, o());
  });
} else {
  var content = core.http("GET", url("/runbooks/" + encodeURIComponent(RUNBOOK) + "/content"), auth, null, o({ allow: [404], accept: "text/powershell, text/plain, */*" }));
  published = content.statusCode === 404 ? null : content.text;
}
if (published === script) {
  runbookState = "unchanged";
  System.log("The published runbook " + RUNBOOK + " is the generated one; left as it is.");
} else {
  runbookState = runbook.statusCode === 404 ? "created" : "updated";
  core.act(ctx, "replace the draft of " + RUNBOOK + " with the generated script", function () {
    return core.http("PUT", url("/runbooks/" + encodeURIComponent(RUNBOOK) + "/draft/content"), auth, script, o({ contentType: "text/powershell" }));
  });
  core.act(ctx, "publish " + RUNBOOK, function () {
    return core.http("POST", url("/runbooks/" + encodeURIComponent(RUNBOOK) + "/publish"), auth, null, o());
  });
}

// 2. The schedule, if missing. First run tomorrow at the time asked for.
if (get("/schedules/" + encodeURIComponent(SCHEDULE)).statusCode === 404) {
  var start = new Date();
  start.setUTCDate(start.getUTCDate() + 1);
  start.setUTCHours(AT_HOUR, AT_MINUTE, 0, 0);
  core.act(ctx, "create schedule " + SCHEDULE + " (" + FREQUENCY + ", from " + start.toISOString() + ")", function () {
    return core.http("PUT", url("/schedules/" + encodeURIComponent(SCHEDULE)), auth,
      { name: SCHEDULE, properties: { description: SCHEDULE_DESCRIPTION, startTime: start.toISOString(), interval: 1, frequency: FREQUENCY, timeZone: settings.timeZone || "UTC" } }, o());
  });
} else {
  System.log("Schedule " + SCHEDULE + " exists; left as it is.");
}

// 3. The link, only when asked for: until then the schedule runs nothing.
var linked = settings.linkRunbook === true || String(settings.linkRunbook) === "true";
if (!linked) {
  System.log("Not linked: nothing runs on " + SCHEDULE + " until linkRunbook is set to true in " + SETTINGS_NAME + ". Start the runbook by hand first and read its output.");
} else if (get("/jobSchedules/" + JOB_SCHEDULE_ID).statusCode === 404) {
  var parameters = {};
  if (USER_IDENTITY) parameters.UserAssignedClientId = String(settings.userAssignedClientId || "");
  core.act(ctx, "link " + RUNBOOK + " to " + SCHEDULE, function () {
    return core.http("PUT", url("/jobSchedules/" + JOB_SCHEDULE_ID), auth, { properties: { schedule: { name: SCHEDULE }, runbook: { name: RUNBOOK }, parameters: parameters } }, o());
  });
} else {
  System.log("Job schedule " + JOB_SCHEDULE_ID + " exists; left as it is (a job schedule cannot be changed in place).");
}
summary = core.audit(ctx, { runbook: RUNBOOK, runbookState: runbookState, schedule: SCHEDULE, linked: linked });
core.notify(settings.webhook, summary);`;
}

/**
 * One SSM API call, signed with Signature Version 4. SHA-256 and HMAC are
 * written out here in ES5 because Orchestrator's scripting API has no HMAC-SHA256
 * a script can rely on; the tests check the signature against Node's crypto.
 */
const AWS_SSM               = {
  name: 'awsSsm',
  description:
    'POST one Systems Manager API operation (JSON 1.1 protocol: X-Amz-Target AmazonSSM.<operation>) to https://ssm.<region>.amazonaws.com/ or the endpoint given, signed with AWS4-HMAC-SHA256. Returns what core.http returns; allow lists the statuses to return rather than throw (AWS answers errors with 400 and a __type).',
  resultType: 'Any',
  params: [
    { name: 'region', type: 'string', description: 'e.g. eu-west-1' },
    { name: 'endpoint', type: 'string', description: 'Host[:port] of another endpoint, or empty' },
    { name: 'operation', type: 'string', description: 'e.g. DescribeDocument' },
    { name: 'body', type: 'Any', description: 'The request object' },
    { name: 'accessKeyId', type: 'string', description: 'Access key id' },
    { name: 'secretAccessKey', type: 'string', description: 'From a SecureString attribute' },
    { name: 'sessionToken', type: 'string', description: 'From a SecureString attribute, or empty' },
    { name: 'allow', type: 'Any', description: 'Array of statuses to return rather than throw' },
  ],
  script: String.raw`var K = [
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
];
function utf8(text) {
  var u = unescape(encodeURIComponent(String(text)));
  var out = [];
  for (var i = 0; i < u.length; i++) out.push(u.charCodeAt(i));
  return out;
}
function rotr(x, n) { return (x >>> n) | (x << (32 - n)); }
function sha256(bytes) {
  var H = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];
  var m = bytes.slice(0);
  var bits = bytes.length * 8;
  m.push(0x80);
  while (m.length % 64 !== 56) m.push(0);
  var hi = Math.floor(bits / 0x100000000);
  var lo = bits >>> 0;
  m.push((hi >>> 24) & 255, (hi >>> 16) & 255, (hi >>> 8) & 255, hi & 255, (lo >>> 24) & 255, (lo >>> 16) & 255, (lo >>> 8) & 255, lo & 255);
  var W = [];
  for (var i = 0; i < m.length; i += 64) {
    var t;
    for (t = 0; t < 16; t++) W[t] = (m[i + 4 * t] << 24) | (m[i + 4 * t + 1] << 16) | (m[i + 4 * t + 2] << 8) | m[i + 4 * t + 3];
    for (t = 16; t < 64; t++) {
      var s0 = rotr(W[t - 15], 7) ^ rotr(W[t - 15], 18) ^ (W[t - 15] >>> 3);
      var s1 = rotr(W[t - 2], 17) ^ rotr(W[t - 2], 19) ^ (W[t - 2] >>> 10);
      W[t] = (W[t - 16] + s0 + W[t - 7] + s1) | 0;
    }
    var a = H[0], b = H[1], c = H[2], d = H[3], e = H[4], f = H[5], g = H[6], h = H[7];
    for (t = 0; t < 64; t++) {
      var t1 = (h + (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) + ((e & f) ^ (~e & g)) + K[t] + W[t]) | 0;
      var t2 = ((rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) | 0;
      h = g; g = f; f = e; e = (d + t1) | 0; d = c; c = b; b = a; a = (t1 + t2) | 0;
    }
    H[0] = (H[0] + a) | 0; H[1] = (H[1] + b) | 0; H[2] = (H[2] + c) | 0; H[3] = (H[3] + d) | 0;
    H[4] = (H[4] + e) | 0; H[5] = (H[5] + f) | 0; H[6] = (H[6] + g) | 0; H[7] = (H[7] + h) | 0;
  }
  var out = [];
  for (var j = 0; j < 8; j++) out.push((H[j] >>> 24) & 255, (H[j] >>> 16) & 255, (H[j] >>> 8) & 255, H[j] & 255);
  return out;
}
function hmac(key, message) {
  var k = key.length > 64 ? sha256(key) : key.slice(0);
  while (k.length < 64) k.push(0);
  var inner = [];
  var outer = [];
  for (var i = 0; i < 64; i++) { inner.push(k[i] ^ 0x36); outer.push(k[i] ^ 0x5c); }
  return sha256(outer.concat(sha256(inner.concat(message))));
}
function hex(bytes) {
  var out = "";
  for (var i = 0; i < bytes.length; i++) out += (bytes[i] < 16 ? "0" : "") + bytes[i].toString(16);
  return out;
}

var host = endpoint ? String(endpoint) : "ssm." + region + ".amazonaws.com";
var payload = JSON.stringify(body || {});
var amzDate = new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d+/, "");
var day = amzDate.substring(0, 8);
var target = "AmazonSSM." + operation;
var signedHeaders = { "content-type": "application/x-amz-json-1.1", "host": host, "x-amz-date": amzDate, "x-amz-target": target };
if (sessionToken) signedHeaders["x-amz-security-token"] = String(sessionToken);
var names = [];
for (var n in signedHeaders) if (signedHeaders.hasOwnProperty(n)) names.push(n);
names.sort();
var canonicalHeaders = "";
for (var i = 0; i < names.length; i++) canonicalHeaders += names[i] + ":" + signedHeaders[names[i]] + "\n";
var canonical = ["POST", "/", "", canonicalHeaders, names.join(";"), hex(sha256(utf8(payload)))].join("\n");
var scope = day + "/" + region + "/ssm/aws4_request";
var toSign = ["AWS4-HMAC-SHA256", amzDate, scope, hex(sha256(utf8(canonical)))].join("\n");
var key = hmac(hmac(hmac(hmac(utf8("AWS4" + secretAccessKey), utf8(day)), utf8(region)), utf8("ssm")), utf8("aws4_request"));
var headers = {
  "X-Amz-Date": amzDate,
  "X-Amz-Target": target,
  "Authorization": "AWS4-HMAC-SHA256 " + "Credential" + "=" + accessKeyId + "/" + scope + ", SignedHeaders=" + names.join(";") + ", Signature=" + hex(hmac(key, utf8(toSign)))
};
if (sessionToken) headers["X-Amz-Security-Token"] = String(sessionToken);
return System.getModule("com.archtoolkit.core").http("POST", "https://" + host + "/", headers, payload,
  { contentType: "application/x-amz-json-1.1", accept: "application/json", allow: allow || [], redact: [secretAccessKey, sessionToken] });`,
};

function ssmWorkflow(documentName        , associationName        )         {
  const q = JSON.stringify;
  return String.raw`var DOCUMENT = ${q(documentName)};
var ASSOCIATION = ${q(associationName)};
var ctx = core.begin(settings, dryRun);
if (!settings.awsRegion || !settings.awsAccessKeyId || !settings.awsSecretAccessKey) throw new Error("Set awsRegion, awsAccessKeyId and awsSecretAccessKey in the configuration element " + SETTINGS_NAME + ".");
function ssm(operation, body, allow) {
  return mod.awsSsm(settings.awsRegion, settings.ssmEndpoint || "", operation, body, settings.awsAccessKeyId, settings.awsSecretAccessKey, settings.awsSessionToken || "", allow || []);
}
function awsError(r) { return r.body && r.body.__type ? String(r.body.__type).split("#").pop() : ""; }
var content = core.resource(RESOURCE_PATH, "document.yaml");

// 1. The document.
var described = ssm("DescribeDocument", { Name: DOCUMENT }, [400]);
if (described.statusCode !== 200 && awsError(described) !== "InvalidDocument") {
  throw new Error("DescribeDocument " + DOCUMENT + " failed: " + awsError(described) + " " + ((described.body && described.body.message) || ""));
}
if (described.statusCode !== 200) {
  documentState = "created";
  core.act(ctx, "create document " + DOCUMENT, function () {
    return ssm("CreateDocument", { Name: DOCUMENT, Content: content, DocumentType: "Command", DocumentFormat: "YAML" });
  });
} else {
  var current = ssm("GetDocument", { Name: DOCUMENT, DocumentVersion: "$LATEST", DocumentFormat: "YAML" }).body || {};
  if (String(current.Content) === content) {
    documentState = "unchanged";
    System.log("Document " + DOCUMENT + " already has the generated content; left as it is.");
  } else {
    documentState = "updated";
    var version = core.act(ctx, "update document " + DOCUMENT + " (a new version)", function () {
      var r = ssm("UpdateDocument", { Name: DOCUMENT, Content: content, DocumentVersion: "$LATEST", DocumentFormat: "YAML" }, [400]);
      if (r.statusCode === 400 && awsError(r) === "DuplicateDocumentContent") { System.log("SSM says the content is the same as a version it has."); return "same"; }
      if (r.statusCode !== 200) throw new Error("UpdateDocument answered " + awsError(r) + ": " + ((r.body && r.body.message) || ""));
      return String(r.body.DocumentDescription.DocumentVersion);
    });
    if (version !== "same") {
      core.act(ctx, "make the new version the default of " + DOCUMENT, function () {
        return ssm("UpdateDocumentDefaultVersion", { Name: DOCUMENT, DocumentVersion: version });
      });
    }
  }
}

// 2. The association, only if none has its name. It is created with
//    DryRun=true; changing an existing one is a decision for a person.
var request = JSON.parse(core.resource(RESOURCE_PATH, "association.json"));
var found = ssm("ListAssociations", { AssociationFilterList: [{ key: "AssociationName", value: ASSOCIATION }] }).body || {};
var existing = found.Associations || [];
if (existing.length > 0) {
  associationId = String(existing[0].AssociationId);
  System.log("Association " + ASSOCIATION + " exists (" + associationId + "); left as it is.");
} else {
  associationId = core.act(ctx, "create association " + ASSOCIATION + " (DryRun=true)", function () {
    return String(ssm("CreateAssociation", request).body.AssociationDescription.AssociationId);
  }) || "";
}
summary = core.audit(ctx, { document: DOCUMENT, documentState: documentState, association: ASSOCIATION, associationId: associationId });
core.notify(settings.webhook, summary);`;
}

/** The AWX workflow: resolve by name, create what is missing, leave the rest. */
const AWX_WORKFLOW = String.raw`var ctx = core.begin(settings, dryRun);
if (!settings.awxHost || !settings.awxToken) throw new Error("Set awxHost and awxToken in the configuration element " + SETTINGS_NAME + ".");
var API = "https://" + settings.awxHost + ("/" + (settings.awxApiPath || "/api/v2/") + "/").replace(/\/+/g, "/");
var auth = { "Authorization": "Bearer " + settings.awxToken };
var SAFE = { redact: settings._secrets };
var O = JSON.parse(core.resource(RESOURCE_PATH, "awx-objects.json"));
function get(path) { return core.http("GET", API + path, auth, null, SAFE).body || {}; }
function post(path, body) { return core.http("POST", API + path, auth, body, SAFE).body || {}; }
// The id of the one object that matches, null when none does; two is an error,
// because acting on the wrong one of two is worse than stopping.
function one(path, query, what, required) {
  var list = get(path + "?" + query).results || [];
  if (list.length > 1) throw new Error(what + " matches " + list.length + " objects; refusing to guess.");
  if (list.length === 0) {
    if (required) throw new Error(what + " does not exist in AWX. Create it first, with exactly that name (IMPORT.md).");
    return null;
  }
  return list[0].id;
}
function enc(v) { return encodeURIComponent(String(v)); }
function copy(o) { return JSON.parse(JSON.stringify(o)); }

var org = one("organizations/", "name=" + enc(O.organization), "Organization \"" + O.organization + "\"", true);
var inventory = one("inventories/", "name=" + enc(O.inventory) + "&organization=" + org, "Inventory \"" + O.inventory + "\"", true);
var project = one("projects/", "name=" + enc(O.project) + "&organization=" + org, "Project \"" + O.project + "\"", true);
var credential = one("credentials/", "name=" + enc(O.credential) + "&credential_type__kind=ssh", "Machine credential \"" + O.credential + "\"", true);

var jt = one("job_templates/", "name=" + enc(O.jobTemplate.name) + "&organization=" + org, "Job template", false);
if (jt) {
  System.log("Job template \"" + O.jobTemplate.name + "\" exists (" + jt + "); left as it is.");
} else {
  var body = copy(O.jobTemplate);
  body.inventory = inventory;
  body.project = project;
  jt = core.act(ctx, "create job template \"" + O.jobTemplate.name + "\"", function () { return post("job_templates/", body).id; });
  core.act(ctx, "attach credential \"" + O.credential + "\" to the job template", function () { return post("job_templates/" + jt + "/credentials/", { id: credential }); });
  if (O.survey && O.survey.spec && O.survey.spec.length) {
    core.act(ctx, "set the survey of the job template", function () { return post("job_templates/" + jt + "/survey_spec/", O.survey); });
  }
}

var wf = one("workflow_job_templates/", "name=" + enc(O.workflow.name) + "&organization=" + org, "Workflow", false);
if (wf) {
  System.log("Workflow \"" + O.workflow.name + "\" exists (" + wf + "); left as it is.");
} else {
  var wbody = copy(O.workflow);
  wbody.organization = org;
  wf = core.act(ctx, "create workflow \"" + O.workflow.name + "\"", function () { return post("workflow_job_templates/", wbody).id; });
  var ids = [];
  for (var i = 0; i < O.nodes.length; i++) {
    (function (node) {
      var nb = { identifier: node.identifier };
      if (node.kind === "job") {
        nb.unified_job_template = jt;
        if (node.job_type) nb.job_type = node.job_type;
      }
      var id = core.act(ctx, "add workflow node " + node.identifier, function () { return post("workflow_job_templates/" + wf + "/workflow_nodes/", nb).id; });
      if (node.kind === "approval") {
        core.act(ctx, "make node " + node.identifier + " an approval", function () { return post("workflow_job_template_nodes/" + id + "/create_approval_template/", node.approval); });
      }
      ids.push(id);
    })(O.nodes[i]);
  }
  for (var j = 1; j < ids.length; j++) {
    (function (from, to, label) {
      core.act(ctx, label, function () { return post("workflow_job_template_nodes/" + from + "/success_nodes/", { id: to }); });
    })(ids[j - 1], ids[j], "run " + O.nodes[j].identifier + " after " + O.nodes[j - 1].identifier + " succeeds");
  }
}
jobTemplateId = jt ? String(jt) : "";
workflowTemplateId = wf ? String(wf) : "";
summary = core.audit(ctx, { jobTemplateId: jobTemplateId, workflowTemplateId: workflowTemplateId });
core.notify(settings.webhook, summary);`;
