/**
 * The Multi-Cloud Planner's data model: one serialisable `Plan`, the decision
 * made from it, the target design and the waves.
 *
 * Every other planner module codes against these types, so they change only by
 * a deliberate, reviewed edit. Every closed set here has an option table in
 * `options.ts`, which is the single source for the dropdowns and the CSV, and
 * a test proves the two agree in both directions.
 *
 * Nothing here is behaviour: this file is types, plus the one constant that
 * names the plan's file kind.
 */

                                                
                                                      
                                                            

                                                
                                                      
                                                            

/** The four hyperscalers, as a type: everything except VCF on owned hardware. */
                                                      

// ---------- identities -------------------------------------------------------

/** Stable: `'w:<slug(name)>'` | `'d:<slug(name)>'` | `'a:<slug(app)>'`. See `itemId` in options.ts. */
                            
                                                       
/** Every yes/no dropdown. Stored as a boolean in the model. */
                                 

// ---------- operating systems ------------------------------------------------

                  
                                                                                                
                                                         
                                                                                 
                                                                        
                                               
                                                 
                                                                                      
                                                                      
                                                           
/** Package-manager family. */
                                                                        
                                                   
                         
                    
                         
                            
                        
                                                     
                                
                  
                                         
                                                              
                                         
                                              
                            
             
                          
                                      
 

// ---------- intake -----------------------------------------------------------

                                                             
                                                                                                  
                                                                                     
                                                                
                                                    
                                                      
                                                                                                 
                                                                                                          
                                                          
                                                                                                                 
                    
                                                                                              
                                                               
                                                                    
                                                                                           
                     // retire / retain / repurchase

                                                                              
                                                               
                                                                   

                           
                      
                        
                       
                    
                      
                    
                        
                          
                    
                                       
                                    
                    
                    
                              
                                                      
                                 
                                          
                                     
                                                       
                                        
                          
                                     
                              
                                                    
                              
                                        
                                 
                                                
 
                                
                                   
                           
                      
                                 
                                 
                                    
                                     
                                           
                                                                                                
                              
                               
                                                                      
                                   
 

                                                                                                                              
                                                                                                                
                                                                 
/** The Version column's values. `other` for anything not listed. */
                         
                                                                                                              
                                                                                            
                                                                                 
                                           
                                                     
            
                                                                                                                
                                                                                  
                                                                                                       
                                                            
                                                                                                                      
                                                                                                       
                                                              
                                                                                                              
                                     

                           
                      
                        
                            
                              
                                                                 
                                
                        
                                    
                        
                          
                           
                    
                    
                                          
                              
                       
                                    
                              
                                               
                                                
 

                                                                                                            
/** From decide.ts `Latency`. */
                                                            
/** The Migration page's spelling of the clouds (Google is 'gcp' there). */
                                                             
                                                      
                      
                      
                        
                          
                                    
                                
                                    
                                   
                            
                                                                              
                     
                     
                                         
                               
                         
                         
                          
                        
                               
                                 
                                    
                                           
    
                                                              
                                           
 
                                        
                                                                                                       

// ---------- requirements -----------------------------------------------------

                                                                                                         
                                                                                                             
                                                                                                                             
                                                                                                                                     
                                                                                               
                       
                        
                      
                            
                           
                       
                                    
                                
                            
                                    
 
                                                                       
                                                        
                                                          
                             
                              
                                      
                                 
                             
                              
 
                                                                                            
                                                                                                                  
                                                                         
                                                                            
                                                              
                                             
                                                                                                                                          
                                                                                             
                                                                                   
                                                        
                                                                  
                                               
                                                                           
                                                   
                                                                    
                                                                               
                                             

                             
                              
                                
                           
                 
                         
 

                               
                                        
                                      
                                                   
                                                                                                  
                                  
                                            
                                    
                                       
                                              
                               
                                  
                                  
                      
                                    
                             
                                 
                                  
                                      
                              
    
                                              
                                                               
                                
                                              
                       
                                      
                                             
                                    
                                           
                                  
                                         
                                 
    
                                                    
                              
                          
                                  
                      
 

/** A change to the requirements, for the estate what-if. Top-level keys replace whole. */
                                                                                         

// ---------- decision ---------------------------------------------------------

                         
                                                                                               
                                                                                                     
                                         
                                                                                                                       
                                                                                            
                
                          
                                    
                        
                                                                                              
                                       
                         
                          
                                                 
                                      
             
                           
 
                                                                                                                            
                                                                                                         
                              
                             
                         
                               
                        
                                                                                                     
                               
                                                                               
                                     
 
/** One platform (+ service, for a DB) considered for one item. */
                         
                              
                                 
                         
                                    
                               
                                    
                                 
 
                               
                      
                                         
                                    
                          
                                                             
                                      
                                                                            
                           
                           
                                                                                                     
                                                             
                          
                                        
 
                               
                                  
                                 
                           
                                          
                                                                                                        
                                                         
                                        
 
/** Licence counts per platform, as the BOM and the what-if diff sum them. */
                                                                                                                

// ---------- target design ----------------------------------------------------

                                                        
                                                          
/** Screen 7 landing-zone card controls, kept in `Plan.designOverrides` as strings. */
                                                                 
                                  
                                                                 
                                
                        
                                
                        
                         
                             
                                         
                                                                                                                                   
 
                                
                            
                        
                        
                          
                          
                                                                                              
                              
                           
                                                                             
                           
                             
                        
                                         
                                   
                                    
                                   
                                                                                      
                                            
 
                      
                                                            
                                                                                             
                                                                                                                                             
                                                                                      
                                                                                                 
                                                                    
                                              
                                                          
                             
                                                                                  
                                         
                           
                            
                                
                                
                              
                      
                                
                                    
                                                                                                     
                                 
                                                   
                                     
 
                                 
                              
                          
                          
                             
                          
                                              
                            
                                    
                                             
                                          
                                                                                                                      
                                                                                            
                                                             
                                                                           
                                                                                                
                                       
                                          
                                                       
 
                                                                                                                      

// ---------- waves ------------------------------------------------------------

                                                        
                                     
                                      
                                                                                                     
                               
                          
                              
                                  
                            
                                                       
                          
                                            
 
                                                                                                                                                           
                           
                                  
                                                                                                                                        
                                        
                                        
 

// ---------- screen settings that are not requirements ---------------------------

/** Screen 1 (Sources): how the estate becomes rows. Kept so a reload repeats the same import. */
                                            
/** Pseudo-attributes offered beside the estate's custom attribute keys. */
                                                        
                                                
                                 
                                                                       
                         
                                      
                                                              
                                
                                                      
                                
                                     
                                  
                                
 

/** Screen 9 (Generate). */
                                                                                
                                                                                   
                                             
                                   
                                          
                                                                                                
                                 
                                  
 

// ---------- the plan and its output ------------------------------------------

export const PLAN_KIND = 'archtoolkit.multicloud-plan';
                                        

                       
                          
                      
                                                 
                      
                        
                           
                                          
                                          
                                
                                            
                                      
                                      
                                   
                                                             
                                      
                                   
                                       
 
                                   
                                                  
                                                   
                                        
                      
                                                                             
                                               
    
 
                                    
                      
                               
                         
                                          
 
/** What generator-page.ts `load` already accepts (settings-file envelope). */
                                            
                                                   
                      
                           
                                                                  
                             
                                          
                             
                                               
 
                                          
                                                 
                      
                           
                           
                             
                                          
                             
                                               
 
