// scripts/catalog/build-ccsm.mjs
//
// Builds CCSM cross-cloud index from classified inventories.
//
// Outputs:
//   data/ccsm/ccsm.index.json
//   web/cloud-decision-logic-kit/data/ccsm-index.js (browser global)

import fs from "fs";
import path from "path";
import { readJson, writeJson, ts } from "./common.mjs";

const ROOT = path.resolve(process.cwd());
const TAXONOMY_FP = path.join(ROOT, "data/taxonomy/ccsm-enterprise-taxonomy.json");
const IN_DIR = path.join(ROOT, "data/imports/provider-inventory");
const OUT_DIR = path.join(ROOT, "data/ccsm");
const WEB_OUT = path.join(ROOT, "web/cloud-decision-logic-kit/data/ccsm-index.js");

const PROVIDERS = ["aws","azure","gcp","oci"];

function ensureDir(p){ fs.mkdirSync(p, { recursive: true }); }

function loadClassified(provider){
  const fp = path.join(IN_DIR, `${provider}.classified.json`);
  if(!fs.existsSync(fp)) return null;
  const d = readJson(fp);
  if(d && d.skipped) return { provider, skipped:true, services:[] };
  const services = Array.isArray(d.services) ? d.services : [];
  return { provider, services };
}

function main(){
  ensureDir(OUT_DIR);
  const tax = readJson(TAXONOMY_FP);
  const cats = Array.isArray(tax.categories) ? tax.categories : [];

  const index = {};
  for(const c of cats){
    index[c.id] = {
      categoryId: c.id,
      categoryName: c.name,
      providers: { aws:[], azure:[], gcp:[], oci:[] }
    };
  }

  for(const p of PROVIDERS){
    const d = loadClassified(p);
    if(!d) continue;
    for(const s of d.services){
      const cat = s.classification?.categoryId || "unknown";
      if(!index[cat]){
        index[cat] = { categoryId: cat, categoryName: cat, providers:{ aws:[], azure:[], gcp:[], oci:[] } };
      }
      index[cat].providers[p].push({
        name: s.name,
        serviceId: s.serviceId,
        aliases: s.aliases || [],
        confidence: s.classification?.confidence ?? null
      });
    }
  }

  for(const k of Object.keys(index)){
    for(const p of PROVIDERS){
      index[k].providers[p].sort((a,b)=>String(a.name).localeCompare(String(b.name)));
    }
  }

  const outJson = {
    generatedAt: ts(),
    taxonomy: tax.meta || {},
    providers: PROVIDERS,
    index
  };

  const outFp = path.join(OUT_DIR, "ccsm.index.json");
  writeJson(outFp, outJson);

  ensureDir(path.dirname(WEB_OUT));
  // Browser-friendly output (non-module): attaches index onto window.CDK.ccsmIndex
  const js =
    `// Auto-generated by scripts/catalog/build-ccsm.mjs\n` +
    `// NOTE: This is intentionally NOT an ES module.\n` +
    `// It attaches to window.CDK.ccsmIndex for use by ATK web pages.\n\n` +
    `(function(){\n` +
    `  window.CDK = window.CDK || {};\n` +
    `  window.CDK.ccsmIndex = ${JSON.stringify(outJson, null, 2)};\n` +
    `})();\n`;
  fs.writeFileSync(WEB_OUT, js, "utf-8");

  console.log(`[ccsm] wrote: ${outFp}`);
  console.log(`[ccsm] wrote: ${WEB_OUT}`);
}

main();
