/**
 * The config shape of every widget type in a customer content export (306
 * dashboards, 2,903 widgets): for each type, how many widgets, and each config
 * key with the JSON types its value took (and, for an object, its keys and
 * theirs). Keys and types only: no names, ids or values from the export.
 * Regenerate from an export with the catalogue test (see
 * vcf-ops-widget-catalogue.test.ts).
 */

export interface KeyShape {
  readonly types: readonly string[];
  readonly sub?: Readonly<Record<string, readonly string[]>>;
}

export const EXPORT_SHAPES: Readonly<Record<string, { readonly count: number; readonly keys: Readonly<Record<string, KeyShape>> }>> = {
  AlertList: {
    count: 64,
    keys: {
      "alertAction": { types: ["array"] },
      "alertImpact": { types: ["array"] },
      "criticalityLevel": { types: ["array"] },
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "depth": { types: ["number"] },
      "filterMode": { types: ["string"] },
      "hierarchyMode": { types: ["number"] },
      "mode": { types: ["string"] },
      "periodLength": { types: ["null"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "relationshipMode": { types: ["object"], sub: { "relationshipMode": ["array","number"] } },
      "resource": { types: ["array","object"], sub: { "resourceId": ["string"], "resourceName": ["string"] } },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "state": { types: ["array"] },
      "status": { types: ["array"] },
      "tagFilter": { types: ["null","object"], sub: { "path": ["array"], "value": ["object"] } },
      "title": { types: ["string"] },
      "type": { types: ["array"] },
    },
  },
  Geo: {
    count: 1,
    keys: {
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "filterMode": { types: ["string"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "tagFilter": { types: ["object"], sub: { "path": ["array"], "value": ["object"] } },
      "title": { types: ["string"] },
    },
  },
  HealthChart: {
    count: 125,
    keys: {
      "chartHeight": { types: ["number"] },
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "depth": { types: ["number"] },
      "filterMode": { types: ["string"] },
      "metricFullName": { types: ["string"] },
      "metricKey": { types: ["string"] },
      "metricLabel": { types: ["string"] },
      "metricName": { types: ["string"] },
      "metricType": { types: ["object"], sub: { "metricType": ["string"] } },
      "metricUnit": { types: ["object"], sub: { "metricUnitId": ["null","number","string"], "metricUnitName": ["string"] } },
      "mode": { types: ["object","string"], sub: { "mode": ["string"] } },
      "orangeBound": { types: ["number"] },
      "paginationNumber": { types: ["number"] },
      "periodLength": { types: ["string"] },
      "redBound": { types: ["number"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "relationshipMode": { types: ["object"], sub: { "relationshipMode": ["number"] } },
      "resource": { types: ["array"] },
      "resourceKindId": { types: ["string"] },
      "selectFirstRow": { types: ["object"], sub: { "selectFirstRow": ["boolean"] } },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "showMetricLabel": { types: ["object"], sub: { "showMetricLabel": ["boolean"] } },
      "showResourceName": { types: ["object"], sub: { "showResourceName": ["boolean"] } },
      "sortBy": { types: ["string"] },
      "sortByDir": { types: ["object"], sub: { "orderByDir": ["string"] } },
      "tagFilter": { types: ["null","object"], sub: { "path": ["array"], "value": ["object"] } },
      "title": { types: ["string"] },
      "undefined": { types: ["string"] },
      "yellowBound": { types: ["number"] },
    },
  },
  Heatmap: {
    count: 90,
    keys: {
      "configs": { types: ["array"] },
      "depth": { types: ["number"] },
      "mode": { types: ["string"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "relationshipMode": { types: ["object"], sub: { "relationshipMode": ["array","number"] } },
      "resource": { types: ["array"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
      "value": { types: ["number"] },
    },
  },
  IntSummaryAlertVolume: {
    count: 9,
    keys: {
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resource": { types: ["null","object"], sub: { "resourceId": ["string"], "resourceName": ["string"] } },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  IntSummaryCapacity: {
    count: 5,
    keys: {
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resource": { types: ["null"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  IntSummaryFaults: {
    count: 1,
    keys: {
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  IntSummaryStress: {
    count: 99,
    keys: {
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resource": { types: ["null"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  IntSummaryTimeRemaining: {
    count: 2,
    keys: {
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resource": { types: ["null"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  MashupChart: {
    count: 2,
    keys: {
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resourceName": { types: ["string"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  MetricChart: {
    count: 360,
    keys: {
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "depth": { types: ["number"] },
      "metric": { types: ["object"], sub: { "mode": ["string"], "resourceKindMetrics": ["array"], "resourceMetrics": ["array"], "subMode": ["string"] } },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "relationshipMode": { types: ["number","object"], sub: { "relationshipMode": ["number"] } },
      "resInteractionMode": { types: ["null","string"] },
      "resource": { types: ["array"] },
      "resourceMetrics": { types: ["array"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  MetricPicker: {
    count: 3,
    keys: {
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "title": { types: ["string"] },
    },
  },
  ParetoAnalysis: {
    count: 142,
    keys: {
      "additionalColumns": { types: ["array"] },
      "additionalColumns_resource": { types: ["array"] },
      "barsCount": { types: ["number"] },
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "depth": { types: ["number"] },
      "filterMode": { types: ["string"] },
      "filterOldMetrics": { types: ["boolean","object"], sub: { "filterOldMetrics": ["boolean"] } },
      "maxValue": { types: ["null"] },
      "metric": { types: ["object"], sub: { "metricKey": ["string"], "name": ["string"] } },
      "metricName": { types: ["string"] },
      "metricOption": { types: ["object"], sub: { "metricInfo": ["object"], "resourceKindId": ["array"], "tagFilter": ["null","object"], "value": ["object"] } },
      "metricUnit": { types: ["object"], sub: { "metricUnitId": ["number","string"], "metricUnitName": ["string"] } },
      "mode": { types: ["string"] },
      "orangeBound": { types: ["number"] },
      "percentileValue": { types: ["null","number"] },
      "periodLength": { types: ["object"], sub: { "dateRange": ["string"], "dateRangeText": ["string"] } },
      "redBound": { types: ["number"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "regenerationTime": { types: ["number"] },
      "relationshipMode": { types: ["object"], sub: { "relationshipMode": ["array","number"] } },
      "resource": { types: ["array"] },
      "resourceKind": { types: ["array"] },
      "roundDecimals": { types: ["number"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "tagFilter": { types: ["null","object"], sub: { "path": ["array"], "value": ["object"] } },
      "tagOption": { types: ["object"], sub: { "tagFilter": ["null"], "value": ["object"] } },
      "title": { types: ["string"] },
      "topOption": { types: ["string"] },
      "yellowBound": { types: ["number"] },
    },
  },
  ParetoChart: {
    count: 2,
    keys: {
      "barsCount": { types: ["number"] },
      "mode": { types: ["object"], sub: { "mode": ["string"] } },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resource": { types: ["null"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "tagFilter": { types: ["null"] },
      "title": { types: ["string"] },
    },
  },
  ProblemAlertsList: {
    count: 108,
    keys: {
      "impactedBadge": { types: ["string"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "relationshipMode": { types: ["object"], sub: { "relationshipMode": ["array","number"] } },
      "resource": { types: ["null","object"], sub: { "resourceId": ["string"], "resourceName": ["string"] } },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
      "topIssuesDisplayLimit": { types: ["number"] },
      "triggeredObject": { types: ["object"], sub: { "triggeredObject": ["string"] } },
    },
  },
  PropertyList: {
    count: 8,
    keys: {
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "depth": { types: ["number"] },
      "metric": { types: ["object"], sub: { "mode": ["string"], "resourceKindMetrics": ["array"], "resourceMetrics": ["array"], "subMode": ["string"] } },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "relationshipMode": { types: ["object"], sub: { "relationshipMode": ["number"] } },
      "resInteractionMode": { types: ["null","string"] },
      "resource": { types: ["array"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "showMetricFullName": { types: ["object"], sub: { "metricFullName": ["boolean"] } },
      "title": { types: ["string"] },
      "visualTheme": { types: ["number"] },
    },
  },
  ResourceList: {
    count: 414,
    keys: {
      "additionalColumns": { types: ["array"] },
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "depth": { types: ["number"] },
      "filterMode": { types: ["string"] },
      "mode": { types: ["number","object","string"], sub: { "mode": ["number"] } },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "relationshipMode": { types: ["object"], sub: { "relationshipMode": ["array","number"] } },
      "resource": { types: ["array"] },
      "selectFirstRow": { types: ["object"], sub: { "selectFirstRow": ["boolean"] } },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "tagFilter": { types: ["null","object"], sub: { "path": ["array"], "value": ["object"] } },
      "title": { types: ["string"] },
    },
  },
  ResourceRelationship: {
    count: 105,
    keys: {
      "autoZoom": { types: ["object"], sub: { "autoSize": ["boolean"] } },
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "filterMode": { types: ["string"] },
      "nodeSize": { types: ["null"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resourceId": { types: ["null"] },
      "resourceName": { types: ["null","string"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "tagFilter": { types: ["null","object"], sub: { "path": ["array"], "value": ["object"] } },
      "title": { types: ["string"] },
    },
  },
  ResourceRelationshipAdvanced: {
    count: 16,
    keys: {
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "depth": { types: ["string"] },
      "filterMode": { types: ["string"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resourceId": { types: ["null","string"] },
      "resourceName": { types: ["null","string"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "tagFilter": { types: ["null","object"], sub: { "path": ["array"], "value": ["object"] } },
      "title": { types: ["string"] },
      "traversalSpecId": { types: ["string"] },
    },
  },
  RollingViewChart: {
    count: 5,
    keys: {
      "autoTransitionInterval": { types: ["null","number"] },
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "depth": { types: ["number"] },
      "metric": { types: ["object"], sub: { "mode": ["string"], "resourceKindMetrics": ["array"], "resourceMetrics": ["array"], "subMode": ["string"] } },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "relationshipMode": { types: ["object"], sub: { "relationshipMode": ["number"] } },
      "resInteractionMode": { types: ["null"] },
      "resource": { types: ["array"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  Scoreboard: {
    count: 156,
    keys: {
      "boxColumns": { types: ["number"] },
      "boxHeight": { types: ["null","number"] },
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "depth": { types: ["number"] },
      "labelSize": { types: ["number"] },
      "maxCellCount": { types: ["number"] },
      "metric": { types: ["object"], sub: { "mode": ["string"], "resourceKindMetrics": ["array"], "resourceMetrics": ["array"], "subMode": ["string"] } },
      "mode": { types: ["object"], sub: { "layoutMode": ["string"] } },
      "oldMetricValues": { types: ["boolean"] },
      "periodLength": { types: ["null","string"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "relationshipMode": { types: ["number","object"], sub: { "relationshipMode": ["number"] } },
      "resInteractionMode": { types: ["null","string"] },
      "resource": { types: ["array"] },
      "roundDecimals": { types: ["null","number"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "showDT": { types: ["object"], sub: { "showDT": ["boolean"] } },
      "showMetricName": { types: ["object"], sub: { "showMetricName": ["boolean"] } },
      "showMetricUnit": { types: ["object"], sub: { "showMetricUnit": ["boolean"] } },
      "showResourceName": { types: ["object"], sub: { "showResourceName": ["boolean"] } },
      "showSparkline": { types: ["object"], sub: { "showSparkline": ["boolean"] } },
      "title": { types: ["string"] },
      "undefined": { types: ["object"], sub: { "showMetricUnit": ["boolean"] } },
      "valueSize": { types: ["number"] },
      "visualTheme": { types: ["number","object"], sub: { "visualTheme": ["boolean"] } },
    },
  },
  ScoreboardHealth: {
    count: 2,
    keys: {
      "imageType": { types: ["string"] },
      "metricType": { types: ["object"], sub: { "metricType": ["string"] } },
      "metricValue": { types: ["string"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resources": { types: ["array"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  Skittles: {
    count: 4,
    keys: {
      "badge": { types: ["array"] },
      "custom": { types: ["array"] },
      "mode": { types: ["string"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  SparklineChart: {
    count: 11,
    keys: {
      "columnSequence": { types: ["object"], sub: { "columnSequence": ["string"] } },
      "customFilter": { types: ["object"], sub: { "excludedResources": ["null"], "filter": ["array"], "includedResources": ["null"] } },
      "depth": { types: ["number"] },
      "metric": { types: ["object"], sub: { "mode": ["string"], "resourceKindMetrics": ["array"], "resourceMetrics": ["array"], "subMode": ["string"] } },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "relationshipMode": { types: ["object"], sub: { "relationshipMode": ["number"] } },
      "resInteractionMode": { types: ["null","string"] },
      "resource": { types: ["array"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "showDT": { types: ["object"], sub: { "showDT": ["boolean"] } },
      "showResourceName": { types: ["object"], sub: { "showObjectName": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
  TagPicker: {
    count: 91,
    keys: {
    },
  },
  TextDisplay: {
    count: 39,
    keys: {
      "editorData": { types: ["string"] },
      "locationFile": { types: ["string"] },
      "locationUrl": { types: ["string"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "title": { types: ["string"] },
      "titleLocalized": { types: ["string"] },
      "viewModeHTML": { types: ["boolean"] },
      "xtype": { types: ["string"] },
    },
  },
  TopologyGraph: {
    count: 2,
    keys: {
      "custom": { types: ["array"] },
      "depth": { types: ["number"] },
      "filterMode": { types: ["object"], sub: { "leafExpand": ["boolean"] } },
      "mode": { types: ["string"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resInteractionMode": { types: ["null"] },
      "resource": { types: ["object"], sub: { "resourceId": ["string"], "resourceName": ["string"] } },
      "resources": { types: ["array"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
      "treeType": { types: ["object"], sub: { "treeType": ["boolean"] } },
    },
  },
  View: {
    count: 1000,
    keys: {
      "chartViewItems": { types: ["array"] },
      "custom": { types: ["array"] },
      "isUpdatedView": { types: ["boolean"] },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resource": { types: ["null","object"], sub: { "adapterKindId": ["null","string"], "allowDrag": ["boolean"], "allowDrop": ["boolean"], "checked": ["null"], "children": ["null"], "cls": ["string"], "depth": ["number"], "expandable": ["boolean"], "expanded": ["boolean"], "href": ["string"], "hrefTarget": ["string"], "icon": ["string"], "iconCls": ["string"], "iconSrc": ["string"], "id": ["string"], "index": ["number"], "isFirst": ["boolean"], "isLast": ["boolean"], "leaf": ["boolean"], "loaded": ["boolean"], "loading": ["boolean"], "nodeType": ["string"], "parentId": ["string"], "qshowDelay": ["number"], "qtip": ["string"], "qtitle": ["string"], "resourceId": ["string"], "resourceKindId": ["string"], "resourceKindKey": ["string"], "resourceKindName": ["string"], "resourceKindType": ["number","string"], "resourceName": ["string"], "root": ["boolean"], "rootResourceId": ["string"], "text": ["string"], "traversalSpecId": ["string"], "uniqueId": ["string"], "visible": ["boolean"] } },
      "selectFirstRow": { types: ["object"], sub: { "selectFirstRow": ["boolean"] } },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
      "traversalSpecId": { types: ["null","string"] },
      "viewDefinitionId": { types: ["string"] },
      "viewType": { types: ["string"] },
    },
  },
  WorkloadBalance: {
    count: 1,
    keys: {
      "badge": { types: ["object"], sub: { "utilizationSource": ["string"] } },
      "refreshContent": { types: ["object"], sub: { "refreshContent": ["boolean"] } },
      "refreshInterval": { types: ["number"] },
      "resource": { types: ["object"], sub: { "adapterKindId": ["string"], "allowDrag": ["boolean"], "allowDrop": ["boolean"], "checked": ["null"], "children": ["null"], "cls": ["string"], "depth": ["number"], "expandable": ["boolean"], "expanded": ["boolean"], "href": ["string"], "hrefTarget": ["string"], "icon": ["string"], "iconCls": ["string"], "iconSrc": ["string"], "id": ["string"], "index": ["number"], "isFirst": ["boolean"], "isLast": ["boolean"], "leaf": ["boolean"], "loaded": ["boolean"], "loading": ["boolean"], "nodeType": ["string"], "parentId": ["string"], "qshowDelay": ["number"], "qtip": ["string"], "qtitle": ["string"], "resourceId": ["string"], "resourceKindId": ["string"], "resourceKindKey": ["string"], "resourceKindType": ["number"], "resourceName": ["string"], "root": ["boolean"], "rootResourceId": ["string"], "text": ["string"], "traversalSpecId": ["string"], "uniqueId": ["string"], "visible": ["boolean"] } },
      "resourceKindId": { types: ["array"] },
      "selfProvider": { types: ["object"], sub: { "selfProvider": ["boolean"] } },
      "title": { types: ["string"] },
    },
  },
};

/** Dashboard-level keys the same export holds (303 distinct dashboards). */
export const EXPORT_DASHBOARD_KEYS: readonly string[] = [
  'adapterName', 'autoswitchEnabled', 'columnCount', 'columnProportion', 'creationTime', 'dashboardNavigations', 'description', 'disabled', 'docCenterKey', 'entryKeys',
  'gridsterMaxColumns', 'hidden', 'homeTab', 'id', 'importAttempts', 'importComplete', 'lastUpdateTime', 'lastUpdateUserId', 'locked', 'name', 'namePath', 'rank', 'shared',
  'states', 'temporary', 'userId', 'videoKey', 'videoPlaylistKey', 'widgetInteractions', 'widgets',
];
