/**
 * One blueprint per resource, for every resource in the six VMware providers
 * and in the providers the Linux and Windows platforms build with (Active
 * Directory, DNS, TLS, cloud-init, Ansible, local files, random, null).
 *
 * The VMware platforms had two blueprints between them, Linux and Windows one
 * each. The providers have ~650 resources and ~15,000 arguments, and writing a
 * form for each by hand would be both a year's work and wrong within a
 * release. So the forms are made from the providers' own schemas
 * (vmware-schema-data.ts and os-schema-data.ts, generated by
 * tools/fetch-provider-schemas.mjs from `terraform providers schema -json`):
 *
 *  - every argument the resource takes is a field — required ones up top,
 *    optional ones in a collapsible section, each nested block in its own;
 *  - an optional nested block is a tick box, and its fields appear when ticked;
 *  - an argument the documentation gives a closed set for is a dropdown of it,
 *    one you can still type into, so a set the docs under-state blocks nothing;
 *  - a sensitive argument is never a text box: it is a `var.` reference, and
 *    the variable is declared `sensitive`;
 *  - a required argument left empty becomes a variable rather than a guess, so
 *    the file plans once terraform.tfvars supplies it.
 *
 * Deprecated arguments are left out — the provider accepts them only while it
 * warns — and so are computed-only ones, which nothing can set.
 *
 * Any field accepts a reference instead of a literal: `data.vsphere_datacenter.dc.id`,
 * `var.x`, `vsphere_folder.apps.path` or a function call is written unquoted.
 */

import type { Blueprint, BlueprintInput, BlueprintValues, SelectOption } from '../kit/blueprint.ts';
import { warning, type Finding } from '../core/findings.ts';
import { quote } from './hcl.ts';
import { VMWARE_SCHEMA_DATA } from './vmware-schema-data.ts';
import { OS_SCHEMA_DATA } from './os-schema-data.ts';

// ------------------------------------------------------------------ data ---

type TypeCode = 's' | 'n' | 'b' | 'ls' | 'ss' | 'ln' | 'sn' | 'm' | 'x';
/** [name, type, flags, description, allowedValues?] */
type AttrRow = [string, TypeCode, string, string, string[]?];
/** [name, mode, minItems, maxItems, block] */
type BlockRow = [string, 1 | 'l' | 's', number, number, SchemaBlock];
interface SchemaBlock {
  readonly a: readonly AttrRow[];
  readonly b?: readonly BlockRow[];
}
interface ResourceSchema extends SchemaBlock {
  /** The registry documentation's section, where it has one. */
  readonly g?: string;
}
interface ProviderSchema {
  readonly source: string;
  readonly version: string;
  readonly provider: SchemaBlock;
  readonly resources: Readonly<Record<string, ResourceSchema>>;
}

export type VmwareProvider = 'vsphere' | 'vcf' | 'nsxt' | 'avi' | 'vra' | 'vcd';
/** The providers the Linux and Windows platforms build with. */
export type OsProvider = 'ad' | 'dns' | 'tls' | 'cloudinit' | 'ansible' | 'local' | 'random' | 'null';
export type SchemaProvider = VmwareProvider | OsProvider;

const DATA = { ...VMWARE_SCHEMA_DATA, ...OS_SCHEMA_DATA } as Readonly<Record<SchemaProvider, ProviderSchema>>;

export function providerSchema(provider: SchemaProvider): ProviderSchema {
  return DATA[provider];
}

export function resourceSchema(type: string): ResourceSchema | undefined {
  const provider = type.slice(0, type.indexOf('_')) as SchemaProvider;
  return DATA[provider]?.resources[type];
}

/** `~> 2.17` for 2.17.1: the minor line, which is what the providers keep compatible. */
export function versionConstraint(provider: SchemaProvider): string {
  const [major, minor] = DATA[provider].version.split('.');
  return `~> ${major}.${minor ?? '0'}`;
}

// -------------------------------------------------------------- provider ---

interface ProviderMeta {
  /** The product, as the picker's headings name it. */
  readonly product: string;
  /**
   * The provider settings every file writes, with what they start as. The
   * rest of the provider's arguments are offered in the same section, empty.
   */
  readonly defaults: Readonly<Record<string, string | boolean>>;
  /**
   * Credentials, written as references to sensitive variables — never fields.
   * `when` names the setting that has to be filled for the credential to apply,
   * for a provider that talks to one of two endpoints.
   */
  readonly credentials: readonly { readonly attr: string; readonly variable: string; readonly when?: string; readonly sensitive: boolean; readonly description: string }[];
  /** Headings for a provider whose documentation files no sections. */
  readonly sections?: readonly (readonly [RegExp, string])[];
  /**
   * A provider whose configuration is a nested block rather than arguments
   * (DNS's `update { gssapi { } }`) writes it itself, with its own fields.
   */
  readonly custom?: {
    readonly inputs: readonly BlueprintInput[];
    readonly render: (values: BlueprintValues, out: Emitted) => string;
  };
}

const DNS_MODES = [
  { value: 'gssapi', label: 'Kerberos (GSS-TSIG) — Windows DNS / AD-integrated' },
  { value: 'tsig', label: 'TSIG key — BIND and most others' },
  { value: 'none', label: 'Unauthenticated (lab only)' },
];

export const PROVIDER_META: Readonly<Record<SchemaProvider, ProviderMeta>> = {
  vsphere: {
    product: 'vSphere',
    defaults: { vsphere_server: 'vcenter.example.com', user: 'administrator@vsphere.local', allow_unverified_ssl: false },
    credentials: [{ attr: 'password', variable: 'vsphere_password', sensitive: true, description: 'Password for the vSphere user' }],
  },
  vcf: {
    product: 'VCF',
    defaults: { sddc_manager_host: 'sddc-manager.example.com', sddc_manager_username: 'administrator@vsphere.local', allow_unverified_tls: false },
    credentials: [
      { attr: 'sddc_manager_password', variable: 'sddc_manager_password', when: 'sddc_manager_host', sensitive: true, description: 'Password for the SDDC Manager user' },
      { attr: 'installer_password', variable: 'installer_password', when: 'installer_host', sensitive: true, description: 'Password for the VCF Installer admin user' },
    ],
    sections: [
      [/^vcf_instance$/, 'Bring-up'],
      [/^vcf_(domain|cluster|cluster_personality|host|network_pool)$/, 'Workload domains, clusters & hosts'],
      [/^vcf_edge_cluster$/, 'NSX edge clusters'],
      [/^vcf_(certificate|certificate_authority|csr|external_certificate)$/, 'Certificates'],
      [/^vcf_(credentials_.*|user)$/, 'Credentials & users'],
      [/./, 'Settings'],
    ],
  },
  nsxt: {
    product: 'NSX',
    defaults: { host: 'nsx-manager.example.com', username: 'admin', allow_unverified_ssl: false },
    credentials: [{ attr: 'password', variable: 'nsx_password', sensitive: true, description: 'Password for the NSX Manager user' }],
  },
  avi: {
    product: 'Avi Load Balancer',
    defaults: { avi_controller: 'avi-controller.example.com', avi_username: 'admin', avi_tenant: 'admin', avi_version: '31.1.1' },
    credentials: [{ attr: 'avi_password', variable: 'avi_password', sensitive: true, description: 'Password for the Avi Controller user' }],
    sections: [
      [/^avi_(virtualservice|vsvip|vsdatascriptset|vsgs|httppolicyset|l4policyset|dnspolicy|natpolicy|networksecuritypolicy|trafficcloneprofile|ipaddrgroup|stringgroup|microservicegroup)$/, 'Virtual services & policies'],
      [/^avi_(pool|poolgroup|poolgroupdeploymentpolicy|server|healthmonitor|serverautoscalepolicy|autoscalelaunchconfig|prioritylabels)$/, 'Pools, servers & health monitors'],
      [/^avi_(gslb|geodb)/, 'GSLB'],
      [/^avi_(waf|bot|csrf|positivesecuritypolicy|securitypolicy|ratelimitconfiguration|apiratelimitprofile|ipreputationdb|icapprofile|protocolparser)/, 'WAF & application security'],
      [/^avi_(ssl|pki|cert|hardwaresecuritymodulegroup|jwtserverprofile|trustedhostprofile)/, 'Certificates & PKI'],
      [/^avi_(cloud|cloudproperties|serviceengine|serviceenginegroup|seproperties|availabilityzone|network|networkservice|vrfcontext|vcenterserver|ipamdnsproviderprofile|customipamdnsprofile|dynamicdnsrecord|nsxtsegmentruntime|image|labelgroup)$/, 'Clouds, service engines & networks'],
      [/^avi_(tenant|tenantbinding|tenantsystemconfiguration|role|user|useraccount|useraccountprofile|authprofile|authmappingprofile|ssopolicy|serviceauthprofile|cloudconnectoruser)$/, 'Tenants, users & authentication'],
      [/^avi_(alert|actiongroupconfig|snmptrapprofile|webhook|analyticsprofile|report|inventoryfaultconfig|applicationinsightspolicy)/, 'Alerts, analytics & reports'],
      [/profile$/, 'Application & network profiles'],
      [/./, 'Controller & system'],
    ],
  },
  vra: {
    product: 'VCF Automation',
    defaults: { url: 'https://vcf-automation.example.com', insecure: false },
    credentials: [{ attr: 'refresh_token', variable: 'vra_refresh_token', sensitive: true, description: 'API refresh token for VCF Automation' }],
    sections: [
      [/^vra_(cloud_account_.*|integration)$/, 'Cloud accounts & integrations'],
      [/^vra_(zone|fabric_.*|flavor_profile|image_profile|storage_profile.*|network_profile|network_ip_range)$/, 'Cloud zones & profiles'],
      [/^vra_(project|content_.*|policy_.*)$/, 'Projects, content & policies'],
      [/^vra_(blueprint.*|catalog_.*)$/, 'Templates & catalog'],
      [/./, 'Deployments & resources'],
    ],
  },
  vcd: {
    product: 'Cloud Director',
    defaults: { url: 'https://vcd.example.com/api', org: 'System', user: 'administrator', auth_type: 'integrated', allow_unverified_ssl: false },
    credentials: [{ attr: 'password', variable: 'vcd_password', sensitive: true, description: 'Password for the Cloud Director user' }],
    sections: [
      [/^vcd_nsxt_alb_/, 'Load balancing (Avi)'],
      [/^vcd_(vapp.*|vm|vm_internal_disk|vm_affinity_rule|independent_disk|inserted_media|cloned_vapp)$/, 'vApps & VMs'],
      [/^vcd_(catalog.*|subscribed_catalog|library_certificate)$/, 'Catalogs'],
      [/^vcd_(org.*|rights_bundle|role|global_role|api_token|api_filter|service_account|multisite_.*)$/, 'Organizations & access'],
      [/^vcd_(provider_vdc|vdc_group|network_pool|vm_placement_policy|vm_sizing_policy|vm_vgpu_policy)$/, 'Provider VDCs & policies'],
      [/^vcd_(cse_.*|dse_.*|solution_.*|rde.*|ui_plugin|external_endpoint)$/, 'Extensions, Kubernetes & solutions'],
      [/./, 'Networking & security'],
    ],
  },
  ad: {
    product: 'Active Directory',
    defaults: { winrm_hostname: 'dc01.example.com', winrm_username: 'EXAMPLE\\svc-terraform', winrm_proto: 'https', winrm_port: '5986', winrm_use_ntlm: true, winrm_insecure: false },
    credentials: [{ attr: 'winrm_password', variable: 'ad_password', sensitive: true, description: 'Password for the account the AD provider signs in to WinRM with' }],
  },
  dns: {
    product: 'DNS records',
    defaults: {},
    credentials: [],
    custom: {
      inputs: [
        { id: 'p.dns_server', label: 'DNS server', control: 'text', default: 'dc01.example.com', section: 'Provider connection', hint: 'where dynamic updates are sent' },
        { id: 'p.dns_auth', label: 'Authentication', control: 'select', options: DNS_MODES, default: 'gssapi', section: 'Provider connection' },
        { id: 'p.dns_realm', label: 'Kerberos realm', control: 'text', default: 'EXAMPLE.COM', section: 'Provider connection', showWhen: { input: 'p.dns_auth', equals: ['gssapi'] } },
        { id: 'p.dns_username', label: 'Kerberos user', control: 'text', default: 'svc-terraform', section: 'Provider connection', showWhen: { input: 'p.dns_auth', equals: ['gssapi'] }, hint: 'blank = the current Kerberos ticket' },
        { id: 'p.dns_key_name', label: 'TSIG key name', control: 'text', default: 'terraform.', section: 'Provider connection', showWhen: { input: 'p.dns_auth', equals: ['tsig'] }, hint: 'fully qualified, trailing dot' },
        { id: 'p.dns_key_algorithm', label: 'TSIG algorithm', control: 'select', options: ['hmac-sha256', 'hmac-sha512', 'hmac-sha1', 'hmac-md5'].map((v) => ({ value: v, label: v })), default: 'hmac-sha256', section: 'Provider connection', showWhen: { input: 'p.dns_auth', equals: ['tsig'] } },
      ],
      render: (values, out) => {
        const mode = String(values['p.dns_auth'] ?? 'gssapi');
        const lines = [`    server = ${quote(String(values['p.dns_server'] ?? 'dc01.example.com'))}`];
        if (mode === 'tsig') {
          lines.push(`    key_name      = ${quote(String(values['p.dns_key_name'] ?? 'terraform.'))}`);
          lines.push(`    key_algorithm = ${quote(String(values['p.dns_key_algorithm'] ?? 'hmac-sha256'))}`);
          lines.push('    key_secret    = var.dns_tsig_secret');
          out.variables.set('dns_tsig_secret', { type: 'string', sensitive: true, description: 'Base64 TSIG key secret' });
        } else if (mode === 'gssapi') {
          const user = String(values['p.dns_username'] ?? '').trim();
          lines.push('', '    gssapi {', `      realm    = ${quote(String(values['p.dns_realm'] ?? 'EXAMPLE.COM'))}`);
          if (user) {
            lines.push(`      username = ${quote(user)}`, '      password = var.dns_password');
            out.variables.set('dns_password', { type: 'string', sensitive: true, description: 'Password for the Kerberos user that signs DNS updates' });
          }
          lines.push('    }');
        }
        return `provider "dns" {\n  update {\n${lines.join('\n')}\n  }\n}`;
      },
    },
  },
  tls: { product: 'Keys & certificates (TLS)', defaults: {}, credentials: [], custom: { inputs: [], render: () => '' } },
  cloudinit: { product: 'cloud-init', defaults: {}, credentials: [] },
  ansible: { product: 'Ansible', defaults: {}, credentials: [] },
  local: { product: 'Files on the Terraform runner', defaults: {}, credentials: [] },
  random: { product: 'Random values (passwords, IDs)', defaults: {}, credentials: [] },
  null: { product: 'Remote execution (null_resource)', defaults: {}, credentials: [] },
};

/** The heading a resource sits under in the picker. */
export function sectionOf(provider: SchemaProvider, type: string): string {
  const meta = PROVIDER_META[provider];
  const documented = DATA[provider].resources[type]?.g;
  if (!documented && !meta.sections) return meta.product;
  let section = documented ?? meta.sections?.find(([re]) => re.test(type))?.[1] ?? 'Other';
  if (section === 'Beta') section = 'Beta (subject to change)';
  if (section === 'Deprecated') section = 'Deprecated (Manager API)';
  return `${meta.product} · ${section}`;
}

// ---------------------------------------------------------------- labels ---

const WORDS: Readonly<Record<string, string>> = {
  vm: 'VM', vms: 'VMs', vapp: 'vApp', vdc: 'VDC', vds: 'VDS', vnic: 'VMkernel adapter', ha: 'HA', drs: 'DRS', dpm: 'DPM',
  sso: 'SSO', vmfs: 'VMFS', nas: 'NAS', ovf: 'OVF', ip: 'IP', ips: 'IPs', ipv6: 'IPv6', dhcp: 'DHCP', dhcpv6: 'DHCPv6', dns: 'DNS',
  nat: 'NAT', bgp: 'BGP', ospf: 'OSPF', vpc: 'VPC', vpn: 'VPN', ipsec: 'IPsec', l2: 'L2', l4: 'L4', l7: 'L7', lb: 'LB',
  id: 'ID', api: 'API', ssl: 'SSL', tls: 'TLS', pki: 'PKI', waf: 'WAF', gslb: 'GSLB', csr: 'CSR', ceip: 'CEIP', nsxt: 'NSX',
  nsxv: 'NSX-V', alb: 'ALB', rde: 'RDE', cse: 'CSE', dse: 'DSE', ui: 'UI', oidc: 'OIDC', saml: 'SAML', ldap: 'LDAP',
  vgpu: 'vGPU', evpn: 'EVPN', vrf: 'VRF', vtep: 'VTEP', gre: 'GRE', idps: 'IDPS', idp: 'IdP', lacp: 'LACP', mac: 'MAC',
  pci: 'PCI', gpu: 'GPU', dfw: 'DFW', tep: 'TEP', vni: 'VNI', ntp: 'NTP', snmp: 'SNMP', aws: 'AWS', gcp: 'GCP', vmc: 'VMC',
  vsphere: 'vSphere', vcenter: 'vCenter', esxi: 'ESXi', vsan: 'vSAN', nsx: 'NSX', tier0: 'Tier-0', tier1: 'Tier-1',
  pbr: 'PBR', mtu: 'MTU', url: 'URL', uri: 'URI', vro: 'vRO', ad: 'AD', ldp: 'LDP', ca: 'CA', vip: 'VIP', qos: 'QoS',
  vsvip: 'VS VIP', vs: 'VS', se: 'SE', gs: 'GS', crs: 'CRS', jwt: 'JWT', icap: 'ICAP', csrf: 'CSRF', crm: 'CRM', hsm: 'HSM',
  sm: 'SM', fds: 'FDS', psm: 'PSM', ut: 'UT', rm: 'RM', addr: 'address', albservices: 'ALB services', geodb: 'GeoDB',
  datascript: 'DataScript', serviceengine: 'service engine', webapp: 'web app', l3: 'L3', ssp: 'SSP', ipam: 'IPAM',
  http: 'HTTP', https: 'HTTPS', db: 'DB',
};

/**
 * The words Avi runs together in its resource names, longest first, so
 * `applicationpersistenceprofile` reads as "application persistence profile".
 */
const AVI_WORDS = [
  'datascript', 'serviceengine', 'microservice', 'autoscale', 'albservices', 'geodb', 'application', 'persistence',
  'availability', 'configuration', 'consolidator', 'registration', 'certificate', 'management', 'reputation', 'inventory',
  'controller', 'properties', 'connector', 'detection', 'deployment', 'analytics', 'insights', 'download', 'protocol',
  'scheduler', 'retention', 'snapshot', 'operation', 'hardware', 'security', 'balancer', 'priority', 'positive', 'datastore',
  'instance', 'webhook', 'upgrade', 'summary', 'support', 'message', 'journal', 'network', 'service', 'virtual', 'vcenter',
  'context', 'runtime', 'account', 'binding', 'cluster', 'details', 'profile', 'mapping', 'request', 'version', 'trusted',
  'signature', 'provider', 'traffic', 'manager', 'monitor', 'segment', 'syslog', 'script', 'report', 'policy', 'config',
  'launch', 'module', 'server', 'string', 'system', 'limits', 'status', 'ledger', 'license', 'memory', 'parser', 'portal',
  'object', 'record', 'backup', 'action', 'dynamic', 'custom', 'labels', 'tenant', 'worker', 'webapp', 'upload', 'health',
  'clone', 'cloud', 'group', 'alert', 'email', 'label', 'image', 'error', 'fault', 'store', 'local', 'state', 'level1',
  'level2', 'level3', 'limit', 'rules', 'entity', 'vsvip', 'proto', 'task', 'tech', 'test', 'user', 'role', 'site', 'type',
  'body', 'page', 'file', 'rate', 'auth', 'host', 'pool', 'zone', 'addr', 'diff', 'gslb', 'ipam', 'icap', 'csrf', 'snmp',
  'trap', 'nsxt', 'http', 'cert', 'data', 'crs', 'waf', 'bot', 'api', 'dns', 'nat', 'vip', 'pki', 'ssl', 'jwt', 'sso', 'ssp',
  'crm', 'hsm', 'fds', 'vrf', 'set', 'job', 'key', 'and', 'ops', 'psm', 'se', 'sm', 'vs', 'gs', 'ip', 'db', 'l4', 'ut', 'rm',
];
const AVI_SORTED = [...new Set(AVI_WORDS)].sort((a, b) => b.length - a.length);

/** Split one of Avi's run-together names, longest known word first. */
function aviWords(name: string): string {
  const words: string[] = [];
  let rest = name;
  while (rest.length > 0) {
    const word = AVI_SORTED.find((w) => rest.startsWith(w));
    if (!word) {
      // Nothing known starts here: keep the remainder whole rather than guess.
      words.push(rest);
      break;
    }
    words.push(word);
    rest = rest.slice(word.length);
  }
  return words.join('_');
}

/** `compute_cluster_vm_host_rule` → `Compute cluster VM host rule`. */
export function humanize(name: string): string {
  const words = name.split('_').map((w) => WORDS[w] ?? w);
  const first = words[0] ?? '';
  return [first === first.toLowerCase() ? first.charAt(0).toUpperCase() + first.slice(1) : first, ...words.slice(1)].join(' ');
}

// ---------------------------------------------------------------- inputs ---

const PROVIDER_SECTION = 'Provider connection';
const OPTIONAL_SECTION = 'Optional arguments';

const TYPE_HINT: Readonly<Record<TypeCode, string>> = {
  s: '',
  n: 'number',
  b: '',
  ls: 'comma-separated list',
  ss: 'comma-separated set',
  ln: 'comma-separated numbers',
  sn: 'comma-separated numbers',
  m: 'one key=value per line',
  x: 'HCL expression',
};

const VAR_TYPE: Readonly<Record<TypeCode, string>> = {
  s: 'string',
  n: 'number',
  b: 'bool',
  ls: 'list(string)',
  ss: 'set(string)',
  ln: 'list(number)',
  sn: 'set(number)',
  m: 'map(string)',
  x: 'any',
};

const TRUE_FALSE: readonly SelectOption[] = [
  { value: 'true', label: 'true' },
  { value: 'false', label: 'false' },
];

/** The variable a sensitive or empty required argument becomes. */
function variableName(path: readonly string[]): string {
  const name = path.join('_').replace(/[^A-Za-z0-9_]/g, '_');
  // Terraform reserves these for module blocks; `variable "source"` is an error.
  return RESERVED_VARIABLES.has(name) ? `${name}_value` : name;
}

const RESERVED_VARIABLES = new Set(['source', 'version', 'providers', 'count', 'for_each', 'lifecycle', 'depends_on', 'locals']);

function attrInput(
  row: AttrRow,
  path: readonly string[],
  section: string | undefined,
  showWhen: BlueprintInput['showWhen'],
): BlueprintInput {
  const [name, type, flags, description, values] = row;
  const required = flags.startsWith('r');
  const sensitive = flags.includes('s');
  const id = `r.${[...path, name].join('.')}`;
  const hintParts = [TYPE_HINT[type], required ? 'required' : flags.startsWith('c') ? 'optional — provider picks a default' : 'optional']
    .filter(Boolean);
  const base = {
    id,
    label: name,
    hint: hintParts.join(' · '),
    ...(description ? { help: description } : {}),
    ...(section ? { section } : {}),
    ...(showWhen ? { showWhen } : {}),
  };
  if (sensitive) {
    // Never a secret typed into a box that ends up in a file.
    const variable = variableName([...path, name]);
    return { ...base, control: 'text', default: required ? `var.${variable}` : '', placeholder: `var.${variable}`, hint: `${base.hint} · sensitive: use a var. reference` };
  }
  if (type === 'b') {
    return required
      ? { ...base, control: 'select', options: TRUE_FALSE, default: 'false' }
      : { ...base, control: 'select', options: TRUE_FALSE, blankLabel: '(provider default)' };
  }
  if (type === 'n') return { ...base, control: 'number', default: '' };
  if (type === 'm' || type === 'x') {
    return { ...base, control: 'textarea', default: '', placeholder: type === 'm' ? 'key = value' : '[{ ... }]' };
  }
  if (values && values.length > 0) {
    return {
      ...base,
      control: 'combo',
      options: values.map((v) => ({ value: v, label: v })),
      ...(required ? { default: '' } : { blankLabel: '(provider default)' }),
    };
  }
  return { ...base, control: 'text', default: '' };
}

function sectionName(path: readonly string[]): string {
  return `Block: ${path.join(' › ')}`;
}

/**
 * Walk a block, producing its inputs in form order: this block's own
 * arguments, then each nested block's toggle and arguments.
 */
function blockInputs(
  block: SchemaBlock,
  path: readonly string[],
  section: string | undefined,
  gate: BlueprintInput['showWhen'],
  out: BlueprintInput[],
): void {
  for (const row of block.a) {
    // Top level: required up top, optional in its section.
    const where = path.length === 0 ? (row[2].startsWith('r') ? undefined : OPTIONAL_SECTION) : section;
    out.push(attrInput(row, path, where, gate));
  }
  for (const [name, mode, min, max, child] of block.b ?? []) {
    const childPath = [...path, name];
    const childSection = sectionName(childPath);
    let childGate = gate;
    if (min < 1) {
      const toggle = `b.${childPath.join('.')}`;
      const many = mode !== 1 && max !== 1;
      out.push({
        id: toggle,
        label: `Include ${name}`,
        control: 'toggle',
        default: false,
        hint: many ? `nested block · repeatable${max > 1 ? `, up to ${max}` : ''} — repeat it in main.tf for more` : 'nested block',
        section: childSection,
        ...(gate ? { showWhen: gate } : {}),
      });
      childGate = { input: toggle, equals: ['true'] };
    }
    blockInputs(child, childPath, childSection, childGate, out);
  }
}

export function providerInputs(provider: SchemaProvider): BlueprintInput[] {
  const meta = PROVIDER_META[provider];
  if (meta.custom) return [...meta.custom.inputs];
  const credentialAttrs = new Set(meta.credentials.map((c) => c.attr));
  const inputs: BlueprintInput[] = [];
  const rows = [...DATA[provider].provider.a].sort((x, y) => {
    const dx = x[0] in meta.defaults ? 0 : 1;
    const dy = y[0] in meta.defaults ? 0 : 1;
    return dx - dy;
  });
  for (const row of rows) {
    const [name, , flags] = row;
    // Credentials and anything else sensitive stay out of the form entirely.
    if (credentialAttrs.has(name) || flags.includes('s') || /password|token|secret|_key$|client_auth_key/.test(name)) continue;
    const { blankLabel, ...input } = attrInput(row, [], PROVIDER_SECTION, undefined);
    const preset = meta.defaults[name];
    inputs.push(
      preset === undefined
        ? { ...input, id: `p.${name}`, ...(blankLabel !== undefined ? { blankLabel } : {}) }
        : { ...input, id: `p.${name}`, default: String(preset) },
    );
  }
  return inputs;
}

// ------------------------------------------------------------------- HCL ---

/** A value that is an expression, not text: written without quotes. */
export function isExpression(value: string): boolean {
  const v = value.trim();
  return (
    /^(var|local|data|module|each|count|path|terraform)\.[\w.\-[\]"*]+$/.test(v) ||
    /^[a-z][a-z0-9]*_[a-z0-9_]+\.[A-Za-z_][\w-]*(\[[^\]]+\])?\.[\w.[\]"*]+$/.test(v) ||
    /^[a-z][a-z0-9_]*\([\s\S]*\)$/.test(v) ||
    /^<<-?[A-Z]+\n[\s\S]*\n\s*[A-Z]+$/.test(v) ||
    /^(null|true|false)$/.test(v)
  );
}

function hclKey(key: string): string {
  return /^[A-Za-z_][\w-]*$/.test(key) ? key : quote(key);
}

function indentRaw(text: string, indent: string): string {
  return text
    .trim()
    .split('\n')
    .map((line, i) => (i === 0 ? line : `${indent}${line}`))
    .join('\n');
}

export interface Emitted {
  readonly variables: Map<string, { type: string; sensitive: boolean; description: string }>;
  readonly findings: Finding[];
}

export function newEmitted(): Emitted {
  return { variables: new Map(), findings: [] };
}

function renderAttr(row: AttrRow, raw: unknown, path: readonly string[], indent: string, out: Emitted): string | null {
  const [name, type, flags, description] = row;
  const required = flags.startsWith('r');
  let value = raw === undefined || raw === null ? '' : String(raw).trim();
  if (value === '') {
    if (!required) return null;
    // Required and not given: a variable, so the file plans once tfvars has it.
    value = `var.${variableName([...path, name])}`;
  }
  const varRef = /^var\.([A-Za-z_][\w-]*)$/.exec(value);
  if (varRef) {
    const variable = varRef[1] as string;
    if (!out.variables.has(variable)) {
      out.variables.set(variable, { type: VAR_TYPE[type], sensitive: flags.includes('s'), description: description || `${[...path, name].join('.')}` });
    }
  }
  const lhs = `${indent}${name} = `;
  const list = type === 'ls' || type === 'ss' || type === 'ln' || type === 'sn';
  // In a list field, `data.x.y.path` is one element; `var.x` or a function
  // call may well be the whole list, so those are left as they are.
  if (isExpression(value) && !(list && !/^(var|local)\.|^[a-z][a-z0-9_]*\(/.test(value))) return lhs + value;
  switch (type) {
    case 's':
      return lhs + quote(value);
    case 'n': {
      const n = Number(value);
      if (!Number.isFinite(n)) {
        out.findings.push(warning('terraform.vmware.not-a-number', `${[...path, name].join('.')} is a number; "${value}" was left out.`, { path: [...path, name].join('.') }));
        return null;
      }
      return lhs + String(n);
    }
    case 'b':
      return lhs + (value === 'true' || value === 'yes' ? 'true' : 'false');
    case 'ls':
    case 'ss':
    case 'ln':
    case 'sn': {
      if (value.startsWith('[')) return lhs + indentRaw(value, indent);
      const items = value.split(/[,\n]/).map((s) => s.trim()).filter(Boolean);
      const numeric = type === 'ln' || type === 'sn';
      const rendered = items.map((s) => (isExpression(s) ? s : numeric && Number.isFinite(Number(s)) ? String(Number(s)) : quote(s)));
      return `${lhs}[${rendered.join(', ')}]`;
    }
    case 'm': {
      if (value.startsWith('{')) return lhs + indentRaw(value, indent);
      const pairs = value
        .split('\n')
        .map((line) => /^\s*("?)([^="]+)\1\s*[=:]\s*(.*?)\s*$/.exec(line))
        .filter((m): m is RegExpExecArray => m !== null);
      if (pairs.length === 0) return null;
      const body = pairs.map((m) => {
        const v = (m[3] ?? '').replace(/^"(.*)"$/, '$1');
        return `${indent}  ${hclKey((m[2] ?? '').trim())} = ${isExpression(v) ? v : quote(v)}`;
      });
      return `${lhs}{\n${body.join('\n')}\n${indent}}`;
    }
    default:
      return lhs + indentRaw(value, indent);
  }
}

function renderBlockBody(
  block: SchemaBlock,
  values: BlueprintValues,
  path: readonly string[],
  indent: string,
  out: Emitted,
  rules: ResourceRules = {},
  varPath: readonly string[] = path,
): string[] {
  const lines: string[] = [];
  const attrs: string[] = [];
  for (const row of block.a) {
    const line = renderAttr(row, values[`r.${[...path, row[0]].join('.')}`], varPath, indent, out);
    if (line !== null) attrs.push(line);
  }
  // Align the `=` of single-line attributes, as terraform fmt does.
  const width = attrs.reduce((w, l) => (l.includes('\n') ? w : Math.max(w, l.indexOf(' = '))), 0);
  for (const l of attrs) {
    const at = l.indexOf(' = ');
    lines.push(!l.includes('\n') && at > 0 ? l.slice(0, at).padEnd(width) + l.slice(at) : l);
  }
  for (const [name, mode, min, max, child] of block.b ?? []) {
    const childPath = [...path, name];
    const toggle = values[`b.${childPath.join('.')}`];
    const included = min >= 1 || rules.minBlocks?.[childPath.join('.')] !== undefined || toggle === true || toggle === 'true';
    if (!included) continue;
    const repeatable = mode !== 1 && max !== 1;
    // The provider checks some minimums in code rather than in its schema.
    const copies = Math.max(1, rules.minBlocks?.[childPath.join('.')] ?? 1);
    for (let k = 0; k < copies; k++) {
      if (lines.length > 0) lines.push('');
      if (k === 0 && repeatable) {
        lines.push(
          copies > 1
            ? `${indent}# ${name}: at least ${copies} are required. Each copy below needs its own values.`
            : `${indent}# ${name}: repeat this block for each one you need.`,
        );
      }
      const childVarPath = k === 0 ? [...varPath, name] : [...varPath, `${name}${k + 1}`];
      lines.push(`${indent}${name} {`);
      lines.push(...renderBlockBody(child, values, childPath, `${indent}  `, out, rules, childVarPath));
      lines.push(`${indent}}`);
    }
  }
  return lines;
}

function providerBlock(provider: SchemaProvider, values: BlueprintValues, out: Emitted): string {
  const meta = PROVIDER_META[provider];
  if (meta.custom) return meta.custom.render(values, out);
  const lines: string[] = [];
  const credentialAttrs = new Set(meta.credentials.map((c) => c.attr));
  for (const row of DATA[provider].provider.a) {
    const [name, , flags] = row;
    if (credentialAttrs.has(name) || flags.includes('s') || /password|token|secret|_key$|client_auth_key/.test(name)) continue;
    const line = renderAttr(row, values[`p.${name}`], [], '  ', out);
    if (line !== null) lines.push(line);
  }
  for (const c of meta.credentials) {
    if (c.when && String(values[`p.${c.when}`] ?? '').trim() === '') continue;
    lines.push(`  ${c.attr} = var.${c.variable}`);
    out.variables.set(c.variable, { type: 'string', sensitive: c.sensitive, description: c.description });
  }
  const width = lines.reduce((w, l) => Math.max(w, l.indexOf(' = ')), 0);
  const aligned = lines.map((l) => {
    const at = l.indexOf(' = ');
    return l.includes('\n') || at < 0 ? l : l.slice(0, at).padEnd(width) + l.slice(at);
  });
  // A provider with nothing to configure (random, local, null) needs no block.
  if (aligned.length === 0) return '';
  return `provider "${provider}" {\n${aligned.join('\n')}\n}`;
}

function variablesHcl(variables: Emitted['variables']): string[] {
  return [...variables].map(([name, v]) => {
    const body = [`  type        = ${v.type}`, `  description = ${quote(v.description.split('. ')[0]?.replace(/\.$/, '') ?? name)}`];
    if (v.sensitive) body.push('  sensitive   = true');
    return `variable "${name}" {\n${body.join('\n')}\n}`;
  });
}

/**
 * The Terraform block, provider blocks and variables, around the given
 * resource blocks. A scenario that uses several providers — a key from `tls`,
 * a file from `local`, a run over SSH from `null` — names them all.
 */
export function wrapConfiguration(
  providers: SchemaProvider | readonly SchemaProvider[],
  values: BlueprintValues,
  resources: readonly string[],
  out: Emitted = newEmitted(),
): string {
  const list = [...new Set(typeof providers === 'string' ? [providers] : providers)];
  const required = list
    .map(
      (p) => `    ${p} = {
      source  = "${DATA[p].source}"
      version = "${versionConstraint(p)}"
    }`,
    )
    .join('\n');
  const parts = [
    `terraform {
  required_version = ">= 1.5.0"
  required_providers {
${required}
  }
}`,
    ...list.map((p) => providerBlock(p, values, out)),
    ...resources,
    ...variablesHcl(out.variables),
  ].filter((part) => part.trim() !== '');
  return `${parts.join('\n\n')}\n`;
}

/** A Terraform identifier from whatever name the page was given. */
function localName(name: string): string {
  const id = name.trim().toLowerCase().replace(/[^a-z0-9_]+/g, '_').replace(/^_+|_+$/g, '');
  if (id === '') return 'this';
  return /^[a-z_]/.test(id) ? id : `r_${id}`;
}

// ----------------------------------------------------------------- rules ---

/**
 * What the providers check in code rather than in their schemas, so
 * `terraform providers schema` cannot say it and `terraform validate` can.
 * Found by running tools/validate-terraform-blueprints.mjs over every resource
 * with nothing filled in; a new entry is a new failure there.
 */
interface ResourceRules {
  /** Groups of arguments of which exactly (or at least) one has to be set; the first stands in when none is. */
  readonly oneOf?: readonly (readonly string[])[];
  /** Nested blocks that need more copies than the schema's min_items says. */
  readonly minBlocks?: Readonly<Record<string, number>>;
  /** Fields that start other than empty, keyed by input id. */
  readonly defaults?: Readonly<Record<string, string | boolean>>;
}

const RESOURCE_RULES: Readonly<Record<string, ResourceRules>> = {
  vsphere_network_protocol_profile: { oneOf: [['ipv4', 'ipv6']] },
  vcf_cluster: { minBlocks: { host: 2 } },
  vcf_domain: { minBlocks: { 'cluster.host': 2 } },
  vcf_network_pool: { minBlocks: { network: 1 } },
  nsxt_policy_ipsec_vpn_service: { oneOf: [['gateway_path', 'locale_service_path']] },
  nsxt_policy_cluster_security_config: { oneOf: [['dfw_enabled']] },
  nsxt_policy_gateway_security_config: { oneOf: [['tier1_id', 'tier0_id']] },
  nsxt_compute_manager: { defaults: { 'b.credential.username_password_login': true } },
  vra_cloud_account_vsphere: { oneOf: [['enabled_regions', 'regions']] },
  vra_content_sharing_policy: { oneOf: [['project_id', 'entitlement_type'], ['catalog_source_ids', 'catalog_item_ids']] },
  vcd_api_token: { defaults: { 'r.allow_token_file': 'true' } },
  vcd_catalog_media: { oneOf: [['catalog_id', 'catalog']] },
  vcd_edgegateway_settings: { oneOf: [['edge_gateway_id', 'edge_gateway_name']] },
  vcd_external_network_v2: { defaults: { 'b.nsxt_network': true } },
  vcd_multisite_org_association: { oneOf: [['association_data_file', 'association_data']] },
  vcd_multisite_site_association: { oneOf: [['association_data_file', 'association_data']] },
  vcd_nsxt_network_imported: { oneOf: [['nsxt_logical_switch_name', 'dvpg_name']] },
  vcd_org_oidc: { oneOf: [['wellknown_endpoint', 'access_token_endpoint'], ['wellknown_endpoint', 'user_authorization_endpoint'], ['wellknown_endpoint', 'userinfo_endpoint'], ['wellknown_endpoint', 'issuer_id']] },
  vcd_org_saml: { oneOf: [['identity_provider_metadata_file', 'identity_provider_metadata_text']] },
  vcd_rde: { oneOf: [['input_entity', 'input_entity_url']] },
  vcd_rde_interface_behavior: { oneOf: [['execution', 'execution_json']] },
  vcd_rde_type: { oneOf: [['schema_url', 'schema']] },
  vcd_rde_type_behavior: { oneOf: [['execution', 'execution_json']] },
  vcd_vapp_network: { oneOf: [['prefix_length', 'netmask']] },
  vcd_vm_placement_policy: { oneOf: [['vm_group_ids', 'logical_vm_group_ids']] },
  tls_cert_request: { oneOf: [['private_key_pem']] },
  tls_self_signed_cert: { oneOf: [['private_key_pem']] },
  tls_locally_signed_cert: { oneOf: [['ca_private_key_pem']] },
  local_file: { oneOf: [['content', 'sensitive_content', 'content_base64', 'source']] },
  local_sensitive_file: { oneOf: [['content', 'content_base64', 'source']] },
  cloudinit_config: { minBlocks: { part: 1 } },
};

// ------------------------------------------------------------- blueprint ---

/**
 * The blueprint for one resource: every argument it takes, as a field.
 * `prefix` keeps ids unique where two platforms offer the same resource —
 * tls_private_key is on Linux (lnx_) and Windows (win_) alike.
 */
export function resourceBlueprint(type: string, prefix = 'vmw'): Blueprint {
  const provider = type.slice(0, type.indexOf('_')) as SchemaProvider;
  const schema = DATA[provider].resources[type];
  if (!schema) throw new Error(`${type}: not in the provider schema data`);
  const rules = RESOURCE_RULES[type] ?? {};
  const collected: BlueprintInput[] = [];
  blockInputs(schema, [], undefined, undefined, collected);
  const inputs: BlueprintInput[] = collected.map((input) => {
    const path = input.id.slice(2);
    const group = rules.oneOf?.find((g) => g.includes(path));
    // A block the provider always needs starts ticked, so its fields show.
    const forced = input.id.startsWith('b.') && (rules.minBlocks?.[path] !== undefined || rules.oneOf?.some((g) => g[0] === path));
    const preset = rules.defaults?.[input.id] ?? (forced ? true : undefined);
    return {
      ...input,
      ...(preset !== undefined ? { default: preset } : {}),
      ...(group && group.length > 1 ? { hint: `${input.hint ?? ''} · set this or ${group.filter((g) => g !== path).join(' / ')}` } : {}),
    };
  });
  inputs.push(...providerInputs(provider));
  const bare = type.slice(provider.length + 1);
  // NSX's policy API is the current one; "Policy" on 170 labels says nothing.
  const human = humanize(provider === 'avi' ? aviWords(bare) : provider === 'nsxt' ? bare.replace(/^policy_/, '') : bare);
  const required = schema.a.filter((a) => a[2].startsWith('r')).length;
  const optional = schema.a.length - required;
  const blocks = (schema.b ?? []).length;
  return {
    id: `${prefix}_${type}`,
    label: `${human} (${type})`,
    group: sectionOf(provider, type),
    description:
      `One ${type} resource, with every argument the ${DATA[provider].source} ${DATA[provider].version} provider takes: ` +
      `${required} required up top, ${optional} optional${blocks > 0 ? `, and ${blocks} nested block${blocks === 1 ? '' : 's'}` : ''} in the sections below. ` +
      'Any field takes a reference — data.x.y.id, var.x — as well as a value.',
    inputs,
    emits: [type],
    build: (values: BlueprintValues, name: string) => {
      const out: Emitted = { variables: new Map(), findings: [] };
      const filled: Record<string, BlueprintValues[string]> = { ...values };
      // A "one of these" group with none set: the first becomes a variable, so
      // the file validates and the variable's name says what to supply.
      for (const group of rules.oneOf ?? []) {
        const isBlock = (path: string): boolean => (schema.b ?? []).some((b) => b[0] === path);
        const set = (path: string): boolean =>
          isBlock(path) ? values[`b.${path}`] === true || values[`b.${path}`] === 'true' : String(values[`r.${path}`] ?? '').trim() !== '';
        if (group.some(set)) continue;
        const first = group[0] as string;
        if (isBlock(first)) filled[`b.${first}`] = true;
        else filled[`r.${first}`] = `var.${variableName(first.split('.'))}`;
      }
      const body = renderBlockBody(schema, filled, [], '  ', out, rules);
      const resource = `resource "${type}" "${localName(name)}" {\n${body.join('\n')}\n}`;
      return { files: { 'main.tf': wrapConfiguration(provider, values, [resource], out) }, findings: out.findings };
    },
  };
}

/** Every resource of a provider, as blueprints, in section then name order. */
export function providerBlueprints(provider: SchemaProvider, prefix = 'vmw'): Blueprint[] {
  const types = Object.keys(DATA[provider].resources);
  const rank = (type: string): number => {
    const section = sectionOf(provider, type);
    // Beta and deprecated resources last, so the supported ones are found first.
    return /Deprecated/.test(section) ? 2 : /Beta/.test(section) ? 1 : 0;
  };
  return types
    .map((type) => ({ type, section: sectionOf(provider, type) }))
    .sort((a, b) => rank(a.type) - rank(b.type) || a.section.localeCompare(b.section) || a.type.localeCompare(b.type))
    .map(({ type }) => resourceBlueprint(type, prefix));
}

export const VMWARE_PROVIDERS: readonly VmwareProvider[] = ['vsphere', 'vcf', 'nsxt', 'avi', 'vra', 'vcd'];
