/**
 * VCF 9.1 `SddcSpec` — the VCF Installer bring-up document.
 *
 * Field names here are transcribed from the VCF Installer API reference
 * (`POST /v1/sddcs`, 9.1.1) and cross-checked against a real working 9.1.0.0
 * spec. They are deliberately exact, including the inconsistencies:
 *
 *  - `IpAddressPoolRangeSpec` uses `start` / `end`, while `IpRange` (used in
 *    `networkSpecs[].includeIpAddressRanges` and `IPv4Pool.ipRange`) uses
 *    `startIpAddress` / `endIpAddress`. Two different range shapes in one
 *    document.
 *  - `TeamingSpec.standByUplinks` has a capital B, unlike
 *    `SddcNetworkSpec.standbyUplinks`.
 *
 * Getting either wrong produces a spec the installer rejects, so they are not
 * "tidied up" here.
 *
 * VCF 9 replaced Cloud Builder with the VCF Installer appliance, but the
 * request body type name did not change — it is still `SddcSpec`.
 */

// ---------------------------------------------------------------------------
// Shared primitives
// ---------------------------------------------------------------------------

export interface SddcCredentials {
  username: string;
  password: string;
}

/** Range shape used by networkSpecs and IPv4Pool. */
export interface IpRange {
  startIpAddress: string;
  endIpAddress: string;
}

/** IPv6 range. Same field names as IpRange but wider length bounds (2-39). */
export interface IpRangeV6 {
  startIpAddress: string;
  endIpAddress: string;
}

/** Range shape used by the NSX host TEP pool. Note: start/end, not *IpAddress. */
export interface IpAddressPoolRangeSpec {
  start: string;
  end: string;
}

export interface IpAddressPoolSubnetSpec {
  cidr: string;
  gateway: string;
  ipAddressPoolRanges: IpAddressPoolRangeSpec[];
}

export interface IpAddressPoolSpec {
  /** Pattern: ^[a-zA-Z0-9-_]+$ */
  name: string;
  description?: string;
  ignoreUnavailableNsxtCluster?: boolean;
  subnets?: IpAddressPoolSubnetSpec[];
}

/** One of cidr / ipRange / addresses is required. */
export interface IPv4Pool {
  cidr?: string;
  ipRange?: IpRange;
  /** Non-contiguous allocation — new in 9.1 (UI from 9.1.0.400+). */
  addresses?: string[];
  /** Applies to range and CIDR forms only. */
  excludedAddresses?: string[];
}

export interface IPv6Pool {
  cidr?: string;
  /** Uses the wider IPv6 range bounds, not the IPv4 IpRange. */
  ipRange?: IpRangeV6;
  addresses?: string[];
  excludedAddresses?: string[];
}

// ---------------------------------------------------------------------------
// Core specs
// ---------------------------------------------------------------------------

export interface DnsSpec {
  /** Tenant subdomain, including the full domain suffix. */
  subdomain: string;
  /** First entry is primary. Maximum 2 entries. */
  nameservers?: string[];
}

export type NetworkType =
  | 'MANAGEMENT'
  | 'VM_MANAGEMENT'
  | 'VMOTION'
  | 'VSAN'
  | 'NFS'
  | 'FLEET_MANAGEMENT'
  | (string & {});

export type TeamingPolicy =
  | 'loadbalance_ip'
  | 'loadbalance_srcmac'
  | 'loadbalance_srcid'
  | 'failover_explicit'
  | 'loadbalance_loadbased';

export type IpAddressVersion = 'IPv4' | 'IPv6';
export type IpAddressAssignmentMode = 'STATIC' | 'DHCP' | 'SLAAC';

export interface SddcNetworkSpec {
  networkType: NetworkType;
  /**
   * Documented as int32. A real working 9.1.0.0 spec emits these as strings
   * ("30") and the installer coerces. This model accepts both; the builder
   * emits numbers.
   */
  vlanId: number | string;
  subnet?: string;
  gateway?: string;
  subnetMask?: string;
  mtu?: number;
  includeIpAddress?: string[];
  includeIpAddressRanges?: IpRange[];
  teamingPolicy?: TeamingPolicy;
  activeUplinks?: string[];
  /** Lowercase b here — unlike TeamingSpec.standByUplinks. */
  standbyUplinks?: string[];
  /** Autogenerated when null. Max 80 chars. */
  portGroupKey?: string;
  ipAddressVersion?: IpAddressVersion;
  ipAddressAssignmentMode?: IpAddressAssignmentMode;
}

export type VcenterVmSize = 'tiny' | 'small' | 'medium' | 'large' | 'xlarge';
export type VcenterStorageSize = 'lstorage' | 'xlstorage';

export interface SddcVcenterSpec {
  /** Max 63 chars. */
  vcenterHostname: string;
  /** New deployment: 15-20 chars. Brownfield conversion: 8-20. */
  rootVcenterPassword: string;
  vmSize?: VcenterVmSize;
  storageSize?: VcenterStorageSize;
  ssoDomain?: string;
  /** Defaults to "administrator". */
  adminUserSsoUsername?: string;
  adminUserSsoPassword?: string;
  version?: string;
  useExistingDeployment?: boolean;
  /** SHA256. Required when useExistingDeployment is true. */
  sslThumbprint?: string;
}

export interface SddcHostSpec {
  /** Short name only — it is prefixed to dnsSpec.subdomain. RFC1123, max 63. */
  hostname: string;
  credentials?: SddcCredentials;
  /** RSA SHA256 for a new deployment; SSH key RSA|ECDSA when reusing. */
  sshThumbprint?: string;
  sslThumbprint?: string;
}

/**
 * EVC baselines.
 *
 * Two spellings below are Broadcom's own and are reproduced verbatim:
 * `INTEL_NEALEM` (not NEHALEM) and `AMD_STREAMROLLER` (not STEAMROLLER).
 * Correcting them would produce a value the installer rejects.
 */
export type EvcMode =
  | 'INTEL_MEROM'
  | 'INTEL_PENRYN'
  | 'INTEL_NEALEM'
  | 'INTEL_WESTMERE'
  | 'INTEL_SANDYBRIDGE'
  | 'INTEL_IVYBRIDGE'
  | 'INTEL_HASWELL'
  | 'INTEL_BROADWELL'
  | 'INTEL_SKYLAKE'
  | 'INTEL_CASCADELAKE'
  | 'INTEL_ICELAKE'
  | 'INTEL_SAPPHIRERAPIDS'
  | 'AMD_REV_E'
  | 'AMD_REV_F'
  | 'AMD_GREYHOUND_NO3DNOW'
  | 'AMD_GREYHOUND'
  | 'AMD_BULLDOZER'
  | 'AMD_PILEDRIVER'
  | 'AMD_STREAMROLLER'
  | 'AMD_ZEN'
  | 'AMD_ZEN2'
  | 'AMD_ZEN3'
  | 'AMD_ZEN4'
  | (string & {});

/**
 * The EVC baselines as a runtime list, for offering them in a UI.
 *
 * Order and spelling match the published enum exactly, including Broadcom's own
 * `INTEL_NEALEM` and `AMD_STREAMROLLER`.
 */
export const EVC_MODES: readonly EvcMode[] = [
  'INTEL_MEROM',
  'INTEL_PENRYN',
  'INTEL_NEALEM',
  'INTEL_WESTMERE',
  'INTEL_SANDYBRIDGE',
  'INTEL_IVYBRIDGE',
  'INTEL_HASWELL',
  'INTEL_BROADWELL',
  'INTEL_SKYLAKE',
  'INTEL_CASCADELAKE',
  'INTEL_ICELAKE',
  'INTEL_SAPPHIRERAPIDS',
  'AMD_REV_E',
  'AMD_REV_F',
  'AMD_GREYHOUND_NO3DNOW',
  'AMD_GREYHOUND',
  'AMD_BULLDOZER',
  'AMD_PILEDRIVER',
  'AMD_STREAMROLLER',
  'AMD_ZEN',
  'AMD_ZEN2',
  'AMD_ZEN3',
  'AMD_ZEN4',
];

export interface ResourcePoolSpec {
  /** Max 80 chars. */
  name?: string;
  type?: 'management' | 'compute' | 'network';
  cpuSharesLevel?: string;
  cpuSharesValue?: number;
  cpuLimit?: number;
  cpuReservationExpandable?: boolean;
  cpuReservationMhz?: number;
  cpuReservationPercentage?: number;
  memorySharesLevel?: string;
  memorySharesValue?: number;
  memoryLimit?: number;
  memoryReservationExpandable?: boolean;
  memoryReservationMb?: number;
  memoryReservationPercentage?: number;
}

export interface SddcClusterSpec {
  /** Auto-generated when blank. */
  datacenterName?: string;
  /** Auto-generated when blank. */
  clusterName?: string;
  clusterEvcMode?: EvcMode;
  resourcePoolSpecs?: ResourcePoolSpec[];
}

export interface TransportZone {
  /** Optional; max 255 chars. */
  name?: string;
  transportType: 'OVERLAY' | 'VLAN';
}

export interface NsxtSwitchConfig {
  transportZones?: TransportZone[];
  /** Documented as VI workload domain only. */
  hostSwitchOperationalMode?: 'STANDARD' | 'ENS' | 'ENS_INTERRUPT';
  ipAssignmentType?: string;
}

export interface TeamingSpec {
  policy: 'FAILOVER_ORDER' | 'LOADBALANCE_SRCID' | 'LOADBALANCE_SRC_MAC';
  /** Minimum 1 entry. */
  activeUplinks: string[];
  /** Capital B — unlike SddcNetworkSpec.standbyUplinks. */
  standByUplinks?: string[] | null;
}

export type LagLoadBalancingMode =
  | 'SOURCE_MAC'
  | 'DESTINATION_MAC'
  | 'SOURCE_AND_DESTINATION_MAC'
  | 'DESTINATION_IP_AND_VLAN'
  | 'SOURCE_IP_AND_VLAN'
  | 'SOURCE_AND_DESTINATION_IP_AND_VLAN'
  | 'DESTINATION_TCP_UDP_PORT'
  | 'SOURCE_TCP_UDP_PORT'
  | 'SOURCE_AND_DESTINATION_TCP_UDP_PORT'
  | 'DESTINATION_IP_AND_TCP_UDP_PORT'
  | 'SOURCE_IP_AND_TCP_UDP_PORT'
  | 'SOURCE_AND_DESTINATION_IP_AND_TCP_UDP_PORT'
  | 'DESTINATION_IP_AND_TCP_UDP_PORT_AND_VLAN'
  | 'SOURCE_IP_AND_TCP_UDP_PORT_AND_VLAN'
  | 'SOURCE_AND_DESTINATION_IP_AND_TCP_UDP_PORT_AND_VLAN'
  | 'DESTINATION_IP'
  | 'SOURCE_IP'
  | 'SOURCE_AND_DESTINATION_IP'
  | 'VLAN'
  | 'SOURCE_PORT_ID';

/** LACP. Exposed in the UI for the first time in 9.1; previously API-only. */
export interface LagSpec {
  /** Max 16 chars. */
  name: string;
  uplinksCount: number;
  lacpMode: 'ACTIVE' | 'PASSIVE';
  lacpTimeoutMode: 'SLOW' | 'FAST';
  loadBalancingMode: LagLoadBalancingMode;
}

export interface VmnicToUplink {
  /** e.g. "vmnic0" */
  id: string;
  /** e.g. "uplink1" */
  uplink: string;
}

export interface DvsSpec {
  /** Max 80 chars. Auto-generated when blank. */
  dvsName?: string;
  networks?: NetworkType[];
  /** Default 9000. */
  mtu?: number;
  nsxtSwitchConfig?: NsxtSwitchConfig;
  vmnicsToUplinks: VmnicToUplink[];
  /** 0 or 1 items. */
  nsxTeamings?: TeamingSpec[] | null;
  lagSpecs?: LagSpec[] | null;
}

export interface DtgwSpec {
  vlan: number | string;
  gatewayCidr: string;
  externalIpBlockCidr: string;
  /** Optional, unlike the two CIDRs above it. */
  privateTgwIpBlockCidr?: string;
}

export interface VpcSpec {
  vpcNetworkConfigurationType?:
    | 'VLAN_BACKED_VPC'
    | 'FULL_STACK_VPC'
    | 'VPC_UNSUPPORTED'
    | 'INVALID_TYPE';
  dtgwSpec?: DtgwSpec;
}

export interface NsxtManagerSpec {
  /** Optional in the API. The builder always supplies one. */
  hostname?: string;
}

/** Only medium | large | xlarge are accepted for VCF bring-up. */
export type NsxtManagerSize = 'medium' | 'large' | 'xlarge';

/**
 * Overlay VTEP configuration.
 *
 * `NO_IP` disables VTEP creation entirely — the TEP-less deployment mode added
 * in 9.1.1.
 */
export interface OverlayVtepSpec {
  vtepType?: 'NO_IP';
}

export interface SddcNsxtSpec {
  nsxtManagers: NsxtManagerSpec[];
  vipFqdn: string;
  /** Default medium. xsmall/small are NOT selectable for bring-up. */
  nsxtManagerSize?: NsxtManagerSize;
  /** Minimum 12 chars. */
  rootNsxtManagerPassword?: string;
  nsxtAdminPassword?: string;
  nsxtAuditPassword?: string;
  /** Default 0. */
  transportVlanId?: number | string;
  /** Host TEP pool. */
  ipAddressPoolSpec?: IpAddressPoolSpec;
  vpcSpec?: VpcSpec;
  skipNsxOverlayOverManagementNetwork?: boolean;
  /** Only when importing existing NSX. */
  enableEdgeClusterSync?: boolean;
  /** TEP-less deployment (9.1.1+). */
  overlayVtepSpec?: OverlayVtepSpec;
  version?: string;
  useExistingDeployment?: boolean;
  sslThumbprint?: string;
}

export interface VsanEsaConfig {
  enabled: boolean;
  skipHclAutoDiskClaim?: boolean;
}

export interface EncryptionConfig {
  dataInTransitConfig?: {
    enable: boolean;
    rekeyInterval?: number;
  };
}

export interface VsanSpec {
  /** Max 80 chars. Auto-generated when blank. */
  datastoreName?: string;
  /** Dedup + compression. OSA only. */
  vsanDedup?: boolean;
  /**
   * Min 0, max 3. One API rendering claims a default of 3, which would be
   * surprising (FTT=3 needs 7+ hosts). Always emit explicitly.
   */
  failuresToTolerate?: number;
  esaConfig?: VsanEsaConfig;
  encryptionConfig?: EncryptionConfig;
}

/** The API calls this `NasVolumeSpec`; `nasVolume` is the property that holds it. */
export interface NasVolumeSpec {
  serverName: string[];
  path: string;
  /**
   * Required, despite reading like a flag that could be left to a default.
   * Omitting it is rejected.
   */
  readOnly: boolean;
  userTag?: string;
  enableBindToVmknic?: boolean;
}

export interface NfsDatastoreSpec {
  datastoreName: string;
  nasVolume: NasVolumeSpec;
}

export interface VmfsDatastoreSpec {
  /** Optional in the API, even though a VMFS datastore spec without it is inert. */
  fcSpec?: { datastoreName: string }[];
}

export interface SddcDatastoreSpec {
  vsanSpec?: VsanSpec;
  nfsDatastoreSpec?: NfsDatastoreSpec;
  vmfsDatastoreSpec?: VmfsDatastoreSpec;
  /** For converting legacy environments. */
  existingDatastoreName?: string;
}

export interface SddcManagerSpec {
  /** Max 63 chars. */
  hostname: string;
  /** Min 15 chars; needs upper/lower/digit/special from [!%@$^#?*]. */
  rootPassword?: string;
  /** Min 15 chars — the 'vcf' user. */
  sshPassword?: string;
  /** Min 12 chars — the built-in admin account. */
  localUserPassword?: string;
  version?: string;
  useExistingDeployment?: boolean;
  sslThumbprint?: string;
}

export interface RootCaCerts {
  alias: string;
  certChain: string[];
}

export interface SecuritySpec {
  esxiCertsMode?: 'Custom' | 'VMCA';
  rootCaCerts?: RootCaCerts[];
}

// ---------------------------------------------------------------------------
// VCF 9.x components
// ---------------------------------------------------------------------------

export interface VcfOperationsNode {
  hostname: string;
  /** Min 15 chars. */
  rootUserPassword?: string;
  type?: 'master' | 'replica' | 'data';
  sslThumbprint?: string;
}

export interface VcfOperationsSpec {
  /** 1-3 nodes. */
  nodes: VcfOperationsNode[];
  /** Min 8 chars. */
  adminUserPassword?: string;
  /** Simple: xsmall..xlarge. HA: small..xlarge. Default medium. */
  applianceSize?: 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge';
  loadBalancerFqdn?: string;
  /** Set true for a secondary VCF instance joining an existing fleet. */
  useExistingDeployment?: boolean;
  version?: string;
}

export interface VcfOperationsCollectorSpec {
  hostname: string;
  /** Min 15 chars. */
  rootUserPassword?: string;
  /** Default small. */
  applianceSize?: 'small' | 'standard';
  version?: string;
  useExistingDeployment?: boolean;
  sslThumbprint?: string;
}

export interface VcfAutomationSpec {
  hostname: string;
  /** Must be globally unique. */
  internalClusterCidr: string;
  /** Required unless useExistingDeployment. */
  platformFqdn?: string;
  /** Min 15 chars. */
  adminUserPassword?: string;
  ipPool?: string[];
  /** Max 57 chars, lowercase alnum + hyphens, must start/end alphanumeric. */
  nodePrefix?: string;
  size?: string;
  version?: string;
  useExistingDeployment?: boolean;
  sslThumbprint?: string;
}

/** vSphere Supervisor / VCF Management Services runtime. */
export interface SddcVspClusterSpec {
  /** Short name, max 63. */
  platformFqdn: string;
  instanceFqdn: string;
  /** Provide for VVF and the PRIMARY instance; omit for a secondary. */
  fleetFqdn?: string;
  ipv4Pool: IPv4Pool;
  ipv6Pool?: IPv6Pool;
  /** Min 15 chars — vmware-system-user and admin@vsp.local. */
  systemUserPassword?: string;
  /** small_ha is management-VSP only, not for a consumption cluster. */
  size?: 'small' | 'small_ha' | 'medium' | 'large';
  /** Restricted to 198.18.0.0/15, 240.0.0.0/15 or 250.0.0.0/15. */
  internalClusterCidrIpv4?: string;
  internalClusterCidrIpv6?: string;
  /**
   * Present in a real working 9.1.0.0 spec but NOT in the published
   * SddcVspClusterSpec data structure. Undocumented but accepted.
   */
  name?: string;
  version?: string;
  useExistingDeployment?: boolean;
  sslThumbprint?: string;
}

/**
 * Fleet and lifecycle service specs.
 *
 * The API documents these as `{ version, size }` only, but a real working spec
 * also carries `hostname` on fleetLcmSpec and sddcLcmSpec. The published schema
 * appears incomplete, so hostname is modelled as optional.
 */
export interface FleetLcmServiceSpec {
  hostname?: string;
  version?: string;
  size?: string;
}

export interface SddcLcmServiceSpec {
  hostname?: string;
  version?: string;
  size?: string;
}

/** Passed as an empty object to deploy with defaults. */
export interface FleetDepotServiceSpec {
  hostname?: string;
  version?: string;
  size?: string;
}

export interface TelemetryAcceptorSpec {
  hostname?: string;
  version?: string;
  size?: string;
}

export interface SaltSpec {
  hostname?: string;
  version?: string;
  size?: string;
}

export interface SaltRaasSpec {
  hostname?: string;
  version?: string;
  size?: string;
}

/** VCF Identity Broker. */
export interface VidbSpec {
  hostname: string;
  version?: string;
  /** Enum values are not published. */
  size?: string;
}

/** Centralized License Server — mandatory in 9.1 for VCF and VVF. */
export interface LicenseServerSpec {
  hostname: string;
  version?: string;
  useExistingDeployment?: boolean;
  sslThumbprint?: string;
}

export interface VcfManagementComponentsNetworkSpec {
  /** Required. */
  networkName: string;
  /** Required. */
  subnetMask: string;
  /** Required. */
  gateway: string;
  ipv6Gateway?: string;
  /** int32 in the API, not a string. */
  ipv6Prefix?: number;
}

export interface VcfManagementComponentsInfrastructureSpec {
  localRegionNetwork?: VcfManagementComponentsNetworkSpec;
  xRegionNetwork?: VcfManagementComponentsNetworkSpec;
}

// ---------------------------------------------------------------------------
// Top-level document
// ---------------------------------------------------------------------------

export type WorkflowType = 'VCF' | 'VCF_COMPLETE' | 'VCF_EXTEND' | 'VVF' | 'VCF_BOOTSTRAP';

/**
 * The VCF Installer bring-up document.
 *
 * Required: sddcId, vcenterSpec, networkSpecs, dnsSpec.
 */
/**
 * Declared as a type alias rather than an interface on purpose.
 *
 * TypeScript gives a type alias of an object type an implicit index signature
 * but never gives one to an interface, so an interface here cannot be passed to
 * anything typed `Record<string, unknown>` — which is exactly what the validator
 * takes, because it also checks for keys the schema does not define. Declaring
 * it as an interface made every validator call site a type error.
 */
export type SddcSpec = {
  /** 3-20 chars, alphanumeric and hyphens. */
  sddcId: string;
  vcenterSpec: SddcVcenterSpec;
  networkSpecs: SddcNetworkSpec[];
  dnsSpec: DnsSpec;

  workflowType?: WorkflowType;
  /** 1-300 chars. */
  vcfInstanceName?: string;
  /** e.g. "9.1.0.0" */
  version?: string;
  hostSpecs?: SddcHostSpec[];
  clusterSpec?: SddcClusterSpec;
  dvsSpecs?: DvsSpec[];
  nsxtSpec?: SddcNsxtSpec;
  ntpServers?: string[];
  sddcManagerSpec?: SddcManagerSpec;
  managementPoolName?: string;
  ceipEnabled?: boolean;
  skipEsxThumbprintValidation?: boolean;
  skipGatewayPingValidation?: boolean;
  securitySpec?: SecuritySpec;
  datastoreSpec?: SddcDatastoreSpec;
  vspClusterSpec?: SddcVspClusterSpec;
  fleetLcmSpec?: FleetLcmServiceSpec;
  sddcLcmSpec?: SddcLcmServiceSpec;
  fleetDepotSpec?: FleetDepotServiceSpec;
  telemetryAcceptorSpec?: TelemetryAcceptorSpec;
  vidbSpec?: VidbSpec;
  saltSpec?: SaltSpec;
  saltRaasSpec?: SaltRaasSpec;
  vcfOperationsSpec?: VcfOperationsSpec;
  vcfOperationsCollectorSpec?: VcfOperationsCollectorSpec;
  vcfAutomationSpec?: VcfAutomationSpec;
  vcfManagementComponentsInfrastructureSpec?: VcfManagementComponentsInfrastructureSpec;
  licenseServerSpec?: LicenseServerSpec;
};

/**
 * Every top-level key the 9.1 schema defines, for completeness checking.
 */
export const SDDC_SPEC_TOP_LEVEL_KEYS = [
  'sddcId',
  'vcenterSpec',
  'networkSpecs',
  'dnsSpec',
  'workflowType',
  'vcfInstanceName',
  'version',
  'hostSpecs',
  'clusterSpec',
  'dvsSpecs',
  'nsxtSpec',
  'ntpServers',
  'sddcManagerSpec',
  'managementPoolName',
  'ceipEnabled',
  'skipEsxThumbprintValidation',
  'skipGatewayPingValidation',
  'securitySpec',
  'datastoreSpec',
  'vspClusterSpec',
  'fleetLcmSpec',
  'sddcLcmSpec',
  'fleetDepotSpec',
  'telemetryAcceptorSpec',
  'vidbSpec',
  'saltSpec',
  'saltRaasSpec',
  'vcfOperationsSpec',
  'vcfOperationsCollectorSpec',
  'vcfAutomationSpec',
  'vcfManagementComponentsInfrastructureSpec',
  'licenseServerSpec',
] as const;

export const SDDC_SPEC_REQUIRED_KEYS = ['sddcId', 'vcenterSpec', 'networkSpecs', 'dnsSpec'] as const;

/**
 * Emitted by the builder wherever a plan supplies no secret.
 *
 * A spec carrying placeholders is deliberately incomplete rather than wrong, so
 * validation reports these as "not yet supplied" instead of failing them
 * against password complexity rules — which would be both misleading and noisy.
 */
export const PLACEHOLDER_SECRET = '<REQUIRED>';

export function isPlaceholderSecret(value: unknown): boolean {
  return value === PLACEHOLDER_SECRET;
}

/**
 * Keys that existed in VCF 9.0 and were REMOVED in 9.1.
 *
 * `vcfOperationsFleetManagementSpec` corresponded to the VCF Fleet Management
 * Appliance, which KB 440630 confirms is no longer available in 9.1. A spec
 * carrying it is a 9.0 document and will not deploy on 9.1.
 */
export const REMOVED_IN_91_KEYS = ['vcfOperationsFleetManagementSpec'] as const;
