/**
 * Figures from Broadcom's VCF Planning and Preparation Workbook — GENERATED by
 * tools/fetch-vcf-workbook.mjs (npm run vcf:workbook), do not edit by hand.
 *
 * Per release: the "Lookup Tables" of the "Static Reference Tables" sheet, keyed exactly as
 * the workbook keys them (e.g. tables["SDDC Manager"].CPU). sizing-data.ts
 * reads these and cites them as published.
 */

export interface WorkbookRelease {
  readonly source: string;
  readonly tables: Readonly<Record<string, Readonly<Record<string, number | string>>>>;
}

export interface WorkbookData {
  readonly fetchedAt: string;
  readonly page: string;
  readonly releases: Readonly<Record<string, WorkbookRelease>>;
}

export const WORKBOOK: WorkbookData = {
 "fetchedAt": "2026-09-26",
 "page": "https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/planning-and-preparation.html",
 "releases": {
  "9.1": {
   "source": "https://techdocs.broadcom.com/content/dam/broadcom/techdocs/us/en/assets/vmware-cis/vcf/vcf-9.1-planning-and-preparation-workbook.xlsx",
   "tables": {
    "SDDC Manager": {
     "CPU": 4,
     "RAM": 16,
     "Disk": 914
    },
    "vCenter Appliance CPU": {
     "Tiny": 2,
     "Small": 4,
     "Medium": 8,
     "Large": 16,
     "XLarge": 24
    },
    "vCenter Appliance RAM": {
     "Tiny": 14,
     "Small": 21,
     "Medium": 30,
     "Large": 39,
     "XLarge": 58
    },
    "vCenter Disk": {
     "TinyDefault": 619,
     "TinyLarge": 2059,
     "TinyXLarge": 4319,
     "SmallDefault": 734,
     "SmallLarge": 2084,
     "SmallXLarge": 4344,
     "MediumDefault": 933,
     "MediumLarge": 2233,
     "MediumXLarge": 4493,
     "LargeDefault": 1383,
     "LargeLarge": 2283,
     "LargeXLarge": 4543,
     "XLargeDefault": 2308,
     "XLargeLarge": 2408,
     "XLargeXLarge": 4668
    },
    "NSX-T Manager CPU": {
     "Extra_Small": 2,
     "Small": 4,
     "Medium": 6,
     "Large": 12,
     "XLarge": 24
    },
    "NSX-T Manager RAM": {
     "Extra_Small": 8,
     "Small": 16,
     "Medium": 24,
     "Large": 48,
     "XLarge": 96
    },
    "NSX-T Manager Disk": {
     "Extra_Small": 300,
     "Small": 300,
     "Medium": 300,
     "Large": 300,
     "XLarge": 400
    },
    "NSX-T Edge CPU": {
     "NSX Edge Small": 2,
     "NSX Edge Medium": 4,
     "NSX Edge Large": 8,
     "NSX Edge XLarge": 16,
     "VNA Small": 2,
     "VNA Medium": 4,
     "VNA Large": 8,
     "VNA XLarge": 16
    },
    "NSX-T Edge RAM": {
     "NSX Edge Small": 4,
     "NSX Edge Medium": 8,
     "NSX Edge Large": 32,
     "NSX Edge XLarge": 64,
     "VNA Small": 4,
     "VNA Medium": 8,
     "VNA Large": 32,
     "VNA XLarge": 64
    },
    "NSX-T Edge Disk": {
     "NSX Edge Small": 200,
     "NSX Edge Medium": 200,
     "NSX Edge Large": 200,
     "NSX Edge XLarge": 200,
     "VNA Small": 200,
     "VNA Medium": 200,
     "VNA Large": 200,
     "VNA XLarge": 200
    },
    "Identity Broker CPU": {
     "Small": 2,
     "Medium": 2,
     "Large": 4,
     "XLarge": 4
    },
    "Identity Broker RAM": {
     "Small": 4,
     "Medium": 4,
     "Large": 8,
     "XLarge": 8
    },
    "Identity Broker Disk": {
     "Small": 10,
     "Medium": 10,
     "Large": 20,
     "XLarge": 20
    },
    "VCF Automation CPU": {
     "Small": 24,
     "Medium": 24,
     "Large": 32
    },
    "VCF Automation RAM": {
     "Small": 96,
     "Medium": 96,
     "Large": 128
    },
    "VCF Automation Disk": {
     "Small": 600,
     "Medium": 900,
     "Large": 1200
    },
    "vRLI CPU": {
     "Small": 8,
     "Medium": 12,
     "Large": 16
    },
    "vRLI RAM": {
     "Small": 16,
     "Medium": 24,
     "Large": 32
    },
    "vRLI Disk": {
     "Small": 575,
     "Medium": 575,
     "Large": 575
    },
    "VCF Operations CPU": {
     "Extra Small": 2,
     "Small": 4,
     "Medium": 8,
     "Large": 16,
     "Extra Large": 24
    },
    "VCF Operations RAM": {
     "Extra Small": 8,
     "Small": 16,
     "Medium": 32,
     "Large": 48,
     "Extra Large": 128
    },
    "VCF Operations Disk": {
     "Extra Small": 274,
     "Small": 274,
     "Medium": 274,
     "Large": 274,
     "Extra Large": 274
    },
    "VCF Operations Proxy CPU": {
     "Small": 4,
     "Medium": 8,
     "Large": 8
    },
    "VCF Operations Proxy RAM": {
     "Small": 16,
     "Medium": 48,
     "Large": 48
    },
    "VCF Operations Proxy Disk": {
     "Small": 264,
     "Medium": 264,
     "Large": 264
    },
    "VRMS CPU": {
     "Light": 2,
     "Standard": 4
    },
    "VRMS RAM": {
     "Light": 8,
     "Standard": 8
    },
    "VRMS Disk": {
     "Light": 33,
     "Standard": 33
    },
    "SRM CPU": {
     "Light": 2,
     "Standard": 8
    },
    "SRM RAM": {
     "Light": 8,
     "Standard": 24
    },
    "SRM Disk": {
     "Light": 20,
     "Standard": 800
    },
    "Health Reporting and Monitoring - HVM": {
     "CPU": 2,
     "RAM": 8,
     "Disk": 20
    },
    "VCF Operations for networks CPU": {
     "Small": 4,
     "Medium": 8,
     "Large": 12
    },
    "VCF Operations for networks RAM": {
     "Small": 16,
     "Medium": 32,
     "Large": 48
    },
    "VCF Operations for networks DISK": {
     "Small": 1024,
     "Medium": 1024,
     "Large": 1024
    },
    "VCF Operations for networks - Collector CPU": {
     "Small": 2,
     "Medium": 4,
     "Large": 8,
     "Extra Large": 8,
     "Extra Extra Large": 16
    },
    "VCF Operations for networks - Collector RAM": {
     "Small": 4,
     "Medium": 12,
     "Large": 16,
     "Extra Large": 24,
     "Extra Extra Large": 48
    },
    "VCF Operations for networks - Collecter DISK": {
     "Small": 250,
     "Medium": 250,
     "Large": 250,
     "Extra Large": 250,
     "Extra Extra Large": 300
    },
    "Cloud-Based Ransomware": {
     "CPU": 8,
     "RAM": 12,
     "Disk": 100
    },
    "Cross-Cloud Mobility - HCX Conn": {
     "CPU": 4,
     "RAM": 12,
     "Disk": 65
    },
    "AVI Load Balancer CPU": {
     "Small": 6,
     "Large": 16,
     "X-Large": 16
    },
    "AVI Load Balancer Ram": {
     "Small": 32,
     "Large": 48,
     "X-Large": 64
    },
    "AVI Load Balancer Disk": {
     "Small": 512,
     "Large": 1400,
     "X-Large": 1750
    },
    "SSP CPU": {
     "Excluded": 96
    },
    "Deployed in WLD": {
     "Include": 96
    },
    "SSP RAM": {
     "Include": 350
    },
    "SSP Disk": {
     "Include": 3867
    },
    "SSP License": {
     "CPU": 10,
     "RAM": 30,
     "Storage": 725
    },
    "Deployment Size Control Node": {
     "Simple": 1,
     "High Availability": 3
    },
    "VCFMS Control Node CPU": {
     "Small": 4,
     "Small HA": 4,
     "Medium": 4,
     "Large": 8
    },
    "VCFMS Control Node RAM": {
     "Small": 10,
     "Small HA": 10,
     "Medium": 10,
     "Large": 14
    },
    "VCFMS Control Node Disk": {
     "Small": 100,
     "Small HA": 100,
     "Medium": 100,
     "Large": 100
    },
    "VCFMS Worker Node": {
     "Small": 3,
     "Medium": 3,
     "Large": 4
    },
    "VCFMS Worker Node CPU": {
     "Small": 12,
     "Medium": 24,
     "Large": 24
    },
    "VCFMS Worker Node RAM": {
     "Small": 24,
     "Medium": 48,
     "Large": 48
    },
    "VCFMS Worker Node Disk": {
     "Small": 100,
     "Medium": 100,
     "Large": 100
    },
    "WLD Domain 5.x Storage Option": {
     "vSAN-ESA": "vSAN-ESA",
     "vSAN-OSA": "vSAN-OSA",
     "vSAN Storage Cluster": "vSAN Compute Cluster",
     "NFSv3": "vSAN Storage Cluster",
     "VMFS on Fibre Channel (FC)": "NFSv3"
    },
    "vLAN source port ID": {
     "vCenter Size": "Supported Limits",
     "Tiny": "10 Hosts 100 VMs",
     "Small": "POC only",
     "Medium": "128 Hosts - 5 vSphere Clusters",
     "Large": "1024 Hosts - 256 vSphere Clusters",
     "XLarge": "2048 Hosts - 512 vSphere Clusters",
     "NSX Size": "Supported Limits",
     "Extra_Small": "Cloud Service Manager Only"
    }
   }
  },
  "9.1.1": {
   "source": "https://techdocs.broadcom.com/content/dam/broadcom/techdocs/us/en/assets/vmware-cis/vcf/vcf-9.1.1-planning-and-preparation-workbook.xlsx",
   "tables": {
    "SDDC Manager": {
     "CPU": 4,
     "RAM": 16,
     "Disk": 914
    },
    "vCenter Appliance CPU": {
     "Tiny": 2,
     "Small": 4,
     "Medium": 8,
     "Large": 16,
     "XLarge": 24
    },
    "vCenter Appliance RAM": {
     "Tiny": 14,
     "Small": 21,
     "Medium": 30,
     "Large": 39,
     "XLarge": 58
    },
    "vCenter Disk": {
     "TinyDefault": 619,
     "TinyLarge": 2059,
     "TinyXLarge": 4319,
     "Tinylstorage": 2059,
     "Tinyxlstorage": 4319,
     "SmallDefault": 734,
     "SmallLarge": 2084,
     "SmallXLarge": 4344,
     "Smalllstorage": 2084,
     "Smallxlstorage": 4344,
     "MediumDefault": 933,
     "MediumLarge": 2233,
     "MediumXLarge": 4493,
     "Mediumlstorage": 2233,
     "Mediumxlstorage": 4493,
     "LargeDefault": 1383,
     "LargeLarge": 2283,
     "Largelstorage": 2283,
     "Largexlstorage": 4553,
     "LargeXLarge": 4543,
     "XLargeDefault": 2308,
     "XLargeLarge": 2408,
     "XLargeXLarge": 4668,
     "XLargelstorage": 2408,
     "Xlargexlstorage": 4668
    },
    "NSX-T Manager CPU": {
     "Extra_Small": 2,
     "Small": 4,
     "Medium": 6,
     "Large": 12,
     "XLarge": 24
    },
    "NSX-T Manager RAM": {
     "Extra_Small": 8,
     "Small": 16,
     "Medium": 24,
     "Large": 48,
     "XLarge": 96
    },
    "NSX-T Manager Disk": {
     "Extra_Small": 300,
     "Small": 300,
     "Medium": 300,
     "Large": 300,
     "XLarge": 400
    },
    "NSX-T Edge CPU": {
     "NSX Edge Small": 2,
     "NSX Edge Medium": 4,
     "NSX Edge Large": 8,
     "NSX Edge XLarge": 16,
     "VNA Small": 2,
     "VNA Medium": 4,
     "VNA Large": 8,
     "VNA XLarge": 16
    },
    "NSX-T Edge RAM": {
     "NSX Edge Small": 4,
     "NSX Edge Medium": 8,
     "NSX Edge Large": 32,
     "NSX Edge XLarge": 64,
     "VNA Small": 4,
     "VNA Medium": 8,
     "VNA Large": 32,
     "VNA XLarge": 64
    },
    "NSX-T Edge Disk": {
     "NSX Edge Small": 200,
     "NSX Edge Medium": 200,
     "NSX Edge Large": 200,
     "NSX Edge XLarge": 200,
     "VNA Small": 200,
     "VNA Medium": 200,
     "VNA Large": 200,
     "VNA XLarge": 200
    },
    "Identity Broker CPU": {
     "Small": 2,
     "Medium": 2,
     "Large": 4,
     "XLarge": 4
    },
    "Identity Broker RAM": {
     "Small": 4,
     "Medium": 4,
     "Large": 8,
     "XLarge": 8
    },
    "Identity Broker Disk": {
     "Small": 10,
     "Medium": 10,
     "Large": 20,
     "XLarge": 20
    },
    "VCF Automation CPU": {
     "Small": 24,
     "Medium": 24,
     "Large": 32
    },
    "VCF Automation RAM": {
     "Small": 96,
     "Medium": 96,
     "Large": 128
    },
    "VCF Automation Disk": {
     "Small": 600,
     "Medium": 900,
     "Large": 1200
    },
    "vRLI CPU": {
     "Small": 8,
     "Medium": 12,
     "Large": 16
    },
    "vRLI RAM": {
     "Small": 16,
     "Medium": 24,
     "Large": 32
    },
    "vRLI Disk": {
     "Small": 575,
     "Medium": 575,
     "Large": 575
    },
    "VCF Operations CPU": {
     "Extra Small": 2,
     "Small": 4,
     "Medium": 8,
     "Large": 16,
     "Extra Large": 24
    },
    "VCF Operations RAM": {
     "Extra Small": 8,
     "Small": 16,
     "Medium": 32,
     "Large": 48,
     "Extra Large": 128
    },
    "VCF Operations Disk": {
     "Extra Small": 274,
     "Small": 274,
     "Medium": 274,
     "Large": 274,
     "Extra Large": 274
    },
    "VCF Operations Proxy CPU": {
     "Small": 4,
     "Standard": 8
    },
    "VCF Operations Proxy RAM": {
     "Small": 16,
     "Standard": 48
    },
    "VCF Operations Proxy Disk": {
     "Small": 264,
     "Standard": 264
    },
    "VRMS CPU": {
     "Light": 2,
     "Standard": 4
    },
    "VRMS RAM": {
     "Light": 8,
     "Standard": 8
    },
    "VRMS Disk": {
     "Light": 33,
     "Standard": 33
    },
    "SRM CPU": {
     "Light": 2,
     "Standard": 8
    },
    "SRM RAM": {
     "Light": 8,
     "Standard": 24
    },
    "SRM Disk": {
     "Light": 20,
     "Standard": 800
    },
    "Health Reporting and Monitoring - HVM": {
     "CPU": 2,
     "RAM": 8,
     "Disk": 20
    },
    "VCF Operations for networks CPU": {
     "Small": 4,
     "Medium": 8,
     "Large": 12,
     "XL": 16,
     "XXL": 24
    },
    "VCF Operations for networks RAM": {
     "Small": 16,
     "Medium": 32,
     "Large": 48,
     "XL": 64,
     "XXL": 128
    },
    "VCF Operations for networks DISK": {
     "Small": 1024,
     "Medium": 1024,
     "Large": 2048,
     "XL": 2048,
     "XXL": 2048
    },
    "VCF Operations for networks - Collector CPU": {
     "Small": 2,
     "Medium": 4,
     "Large": 8,
     "XL": 8,
     "XXL": 16
    },
    "VCF Operations for networks - Collector RAM": {
     "Small": 4,
     "Medium": 12,
     "Large": 16,
     "XL": 24,
     "XXL": 48
    },
    "VCF Operations for networks - Collecter DISK": {
     "Small": 250,
     "Medium": 250,
     "Large": 250,
     "XL": 250,
     "XXL": 300
    },
    "Cloud-Based Ransomware": {
     "CPU": 8,
     "RAM": 12,
     "Disk": 100
    },
    "Cross-Cloud Mobility - HCX Conn": {
     "CPU": 4,
     "RAM": 12,
     "Disk": 65
    },
    "AVI Load Balancer CPU": {
     "Small": 6,
     "Large": 16,
     "X-Large": 16
    },
    "AVI Load Balancer Ram": {
     "Small": 32,
     "Large": 48,
     "X-Large": 64
    },
    "AVI Load Balancer Disk": {
     "Small": 512,
     "Large": 1400,
     "X-Large": 1750
    },
    "SSP CPU": {
     "Excluded": 96
    },
    "Deployed in WLD": {
     "Medium": 64,
     "Large": 96,
     "XLarge": 160
    },
    "SSP RAM": {
     "Medium": 222,
     "Large": 350,
     "XLarge": 606
    },
    "SSP Disk": {
     "Medium": 3260,
     "Large": 3600,
     "XLarge": 6120
    },
    "SSP Workers": {
     "Medium": 2,
     "Large": 4,
     "XLarge": 8
    },
    "SSP Controller": {
     "Medium": 3,
     "Large": 3,
     "XLarge": 3
    },
    "SSPI": {
     "Medium": 1,
     "Large": 1,
     "XLarge": 1
    },
    "SSPI CPU": {
     "Medium": 4,
     "Large": 4,
     "XLarge": 4
    },
    "RAM": {
     "Medium": 6,
     "Large": 6,
     "XLarge": 6
    },
    "SSPI Table": {
     "Medium": 400,
     "Large": 400,
     "XLarge": 400
    },
    "SSP License": {
     "CPU": 6,
     "RAM": 12,
     "Storage": 256
    },
    "Deployment Size Control Node": {
     "Simple": 1,
     "High Availability": 3
    },
    "VCFMS Control Node CPU": {
     "Small": 4,
     "Small HA": 4,
     "Medium": 4,
     "Large": 8
    },
    "VCFMS Control Node RAM": {
     "Small": 10,
     "Small HA": 10,
     "Medium": 10,
     "Large": 14
    },
    "VCFMS Control Node Disk": {
     "Small": 100,
     "Small HA": 100,
     "Medium": 100,
     "Large": 100
    },
    "VCFMS Worker Node": {
     "First InstanceSimpleSmall": 2,
     "First InstanceHigh AvailabilitySmall": 3,
     "First InstanceHigh AvailabilityMedium": 3,
     "First InstanceHigh AvailabilityLarge": 3,
     "Additional InstanceSimpleSmall": 1,
     "Additional InstanceHigh AvailabilitySmall": 3,
     "Additional InstanceHigh AvailabilityMedium": 3,
     "Additional InstanceHigh AvailabilityLarge": 3
    },
    "VCFMS Worker Node CPU": {
     "First InstanceSimpleSmall": 12,
     "First InstanceHigh AvailabilitySmall": 10,
     "First InstanceHigh AvailabilityMedium": 12,
     "First InstanceHigh AvailabilityLarge": 16,
     "Additional InstanceSimpleSmall": 12,
     "Additional InstanceHigh AvailabilitySmall": 10,
     "Additional InstanceHigh AvailabilityMedium": 12,
     "Additional InstanceHigh AvailabilityLarge": 16
    },
    "VCFMS Worker Node RAM": {
     "First InstanceSimpleSmall": 24,
     "First InstanceHigh AvailabilitySmall": 16,
     "First InstanceHigh AvailabilityMedium": 24,
     "First InstanceHigh AvailabilityLarge": 32,
     "Additional InstanceSimpleSmall": 24,
     "Additional InstanceHigh AvailabilitySmall": 16,
     "Additional InstanceHigh AvailabilityMedium": 24,
     "Additional InstanceHigh AvailabilityLarge": 32
    },
    "VCFMS Worker Node Disk": {
     "First InstanceSimpleSmall": 2900,
     "First InstanceHigh AvailabilitySmall": 2800,
     "First InstanceHigh AvailabilityMedium": 3300,
     "First InstanceHigh AvailabilityLarge": 4002,
     "Additional InstanceSimpleSmall": 1000,
     "Additional InstanceHigh AvailabilitySmall": 1000,
     "Additional InstanceHigh AvailabilityMedium": 1202,
     "Additional InstanceHigh AvailabilityLarge": 1500
    },
    "VODAP CPU Per Replica": {
     "SimpleSmall": 16,
     "High AvailabilitySmall": 16,
     "High AvailabilityMedium": 31,
     "High AvailabilityLarge": 47
    },
    "VODAP RAM Per Replica": {
     "SimpleSmall": 20,
     "High AvailabilitySmall": 20,
     "High AvailabilityMedium": 41,
     "High AvailabilityLarge": 62
    },
    "Log Managment CPU Per Replica": {
     "Small": 8,
     "Medium": 16,
     "Large": 32
    },
    "Log Managment RAM Per Replica": {
     "Small": 16,
     "Medium": 32,
     "Large": 64
    },
    "Supervisor CPU": {
     "Tiny": 2,
     "Small": 4,
     "Medium": 8,
     "Large": 16,
     "Xlarge": 32
    },
    "Supervisor RAM": {
     "Tiny": 8,
     "Small": 16,
     "Medium": 24,
     "Large": 32,
     "Xlarge": 64
    },
    "Supervisor Disk": {
     "Tiny": 48,
     "Small": 48,
     "Medium": 48,
     "Large": 48,
     "Xlarge": 48
    },
    "Identity Broker CPU (VCFMS)": {
     "SimpleSmall": 1.5,
     "High AvailabilitySmall": 3,
     "High AvailabilityMedium": 5,
     "High AvailabilityLarge": 10
    },
    "Identity Broker RAM (VCFMS)": {
     "SimpleSmall": 2,
     "High AvailabilitySmall": 5,
     "High AvailabilityMedium": 5,
     "High AvailabilityLarge": 20
    },
    "Identity Broker Disk (VCFMS)": {
     "SimpleSmall": 20,
     "High AvailabilitySmall": 60,
     "High AvailabilityMedium": 60,
     "High AvailabilityLarge": 120
    },
    "Software Depot CPU": {
     "SimpleSmall": 2,
     "High AvailabilitySmall": 2,
     "High AvailabilityMedium": 3,
     "High AvailabilityLarge": 4
    },
    "Software Depot RAM": {
     "SimpleSmall": 2,
     "High AvailabilitySmall": 2,
     "High AvailabilityMedium": 3,
     "High AvailabilityLarge": 6
    },
    "Software Depot Disk": {
     "SimpleSmall": 1500,
     "High AvailabilitySmall": 1500,
     "High AvailabilityMedium": 1500,
     "High AvailabilityLarge": 1500
    },
    "Salt CPU": {
     "SimpleSmall": 0.7,
     "High AvailabilitySmall": 0.7,
     "High AvailabilityMedium": 1.5,
     "High AvailabilityLarge": 2.5
    },
    "Salt RAM": {
     "SimpleSmall": 1.5,
     "High AvailabilitySmall": 1.5,
     "High AvailabilityMedium": 2.5,
     "High AvailabilityLarge": 4.5
    },
    "Salt Raas CPU": {
     "SimpleSmall": 1.15,
     "High AvailabilitySmall": 1.15,
     "High AvailabilityMedium": 4.5,
     "High AvailabilityLarge": 7
    },
    "Salt Raas RAM": {
     "SimpleSmall": 2.6,
     "High AvailabilitySmall": 2.6,
     "High AvailabilityMedium": 6,
     "High AvailabilityLarge": 9
    },
    "Telemetry Acceptor CPU": {
     "SimpleSmall": 0.5,
     "High AvailabilitySmall": 0.5,
     "High AvailabilityMedium": 1,
     "High AvailabilityLarge": 1
    },
    "Telemetry Acceptor RAM": {
     "SimpleSmall": 2,
     "High AvailabilitySmall": 2,
     "High AvailabilityMedium": 3,
     "High AvailabilityLarge": 6
    },
    "Fleet LCM CPU": {
     "SimpleSmall": 2,
     "High AvailabilitySmall": 2.5,
     "High AvailabilityMedium": 2.5,
     "High AvailabilityLarge": 2.5
    },
    "Fleet LCM RAM": {
     "SimpleSmall": 3,
     "High AvailabilitySmall": 3.5,
     "High AvailabilityMedium": 3.5,
     "High AvailabilityLarge": 3.5
    },
    "SDDC LCM CPU": {
     "SimpleSmall": 2,
     "High AvailabilitySmall": 2.5,
     "High AvailabilityMedium": 2.5,
     "High AvailabilityLarge": 2.5
    },
    "SDDC LCM RAM": {
     "SimpleSmall": 3,
     "High AvailabilitySmall": 3.5,
     "High AvailabilityMedium": 3.5,
     "High AvailabilityLarge": 3.5
    },
    "WLD Domain 5.x Storage Option": {
     "vSAN-ESA": "vSAN-ESA",
     "vSAN-OSA": "vSAN-OSA",
     "vSAN Storage Cluster": "vSAN Compute Cluster",
     "NFSv3": "vSAN Storage Cluster",
     "VMFS on Fibre Channel (FC)": "NFSv3"
    },
    "vLAN source port ID": {
     "vCenter Size": "Supported Limits",
     "Tiny": "10 Hosts 100 VMs",
     "Small": "POC only",
     "Medium": "128 Hosts - 5 vSphere Clusters",
     "Large": "1024 Hosts - 256 vSphere Clusters",
     "XLarge": "2048 Hosts - 512 vSphere Clusters",
     "NSX Size": "Supported Limits",
     "Extra_Small": "Cloud Service Manager Only"
    }
   }
  }
 }
};
