/**
 * The Splunk Cloud ACS blueprints for archiving, maintenance and limits.
 *
 * What is checked is what would go wrong silently on a real stack: an archive
 * ACS would reject, an index left to be deleted, a restart with no guard, a
 * limits change with nothing written down to back it out, and a token or a
 * FedRAMP host that ends up somewhere it should not.
 */

import { describe, it } from 'node:test';
import { expect } from '../testing/expect.ts';
import { defaultValues, type BlueprintValues } from '../kit/blueprint.ts';
import { CLOUD_ACS_BLUEPRINTS } from './blueprints/cloud-acs.ts';

function blueprint(id: string) {
  const found = CLOUD_ACS_BLUEPRINTS.find((b) => b.id === id);
  if (!found) throw new Error(`missing ${id}`);
  return found;
}

function build(id: string, overrides: BlueprintValues = {}) {
  const b = blueprint(id);
  return b.build({ ...defaultValues(b), ...overrides }, id);
}

const codes = (result: ReturnType<typeof build>, severity?: string) =>
  (result.findings ?? []).filter((f) => !severity || f.severity === severity).map((f) => f.code);

const file = (result: ReturnType<typeof build>, suffix: string) => Object.entries(result.files).find(([path]) => path.endsWith(suffix))?.[1] ?? '';

describe('cloud ACS blueprints', () => {
  it('are all Cloud tier and build from their defaults without an error', () => {
    expect(CLOUD_ACS_BLUEPRINTS.map((b) => b.id)).toEqual(['splunk_acs_archive', 'splunk_acs_maintenance', 'splunk_acs_limits']);
    for (const b of CLOUD_ACS_BLUEPRINTS) {
      expect(b.tier).toBe('cloud');
      expect([b.id, codes(build(b.id), 'error')]).toEqual([b.id, []]);
    }
  });

  it('never writes a token, a footprint or an --execute flag, and applies unless --dry-run', () => {
    for (const b of CLOUD_ACS_BLUEPRINTS) {
      const result = build(b.id);
      for (const [path, body] of Object.entries(result.files)) {
        expect([path, /ArchToolKit|Generated by|--execute/i.test(body)]).toEqual([path, false]);
        expect([path, /Bearer [A-Za-z0-9]/.test(body)]).toEqual([path, false]);
      }
      const sh = Object.entries(result.files).find(([p]) => p.endsWith('.sh'))?.[1] ?? '';
      expect(sh.startsWith('#!/usr/bin/env bash')).toBe(true);
      expect(sh.includes('EXECUTE=1')).toBe(true);
      expect(sh.includes('--dry-run) EXECUTE=0')).toBe(true);
    }
  });

  it('uses the FedRAMP ACS host when it is chosen', () => {
    const fed = build('splunk_acs_limits', { acs_host: 'https://admin.splunkcloudfed.com' });
    expect(file(fed, 'acs-limits.sh').includes('ACS_SERVER="${ACS_SERVER:-https://admin.splunkcloudfed.com}"')).toBe(true);
    expect(file(fed, 'acs-rest.txt').includes('https://admin.splunkcloudfed.com/example-stack/adminconfig/v2/limits')).toBe(true);
    const commercial = build('splunk_acs_limits');
    expect(file(commercial, 'acs-limits.sh').includes('https://admin.splunk.com}')).toBe(true);
  });
});

describe('archive', () => {
  it('writes the desired state and a location for each DDSS path', () => {
    const result = build('splunk_acs_archive');
    const desired = JSON.parse(file(result, 'ops/archive.json'));
    expect(desired).toEqual([
      { name: 'app_web', searchableDays: 90, splunkArchivalRetentionDays: 365 },
      { name: 'netfw', searchableDays: 90, splunkArchivalRetentionDays: 1095 },
      { name: 'audit', searchableDays: 90, selfStorageBucketPath: 's3://org-splunk-ddss/audit' },
    ]);
    const locations = JSON.parse(file(result, 'ops/ddss-locations.json'));
    expect(locations[0].bucketName).toBe('org-splunk-ddss');
    expect(locations[0].folder).toBe('audit');
    const sh = file(result, 'acs-archive.sh');
    expect(sh.includes('/cloud-resources/self-storage-locations')).toBe(true);
    expect(sh.includes('/policy')).toBe(true);
    expect(sh.includes('PATCH "/indexes/$(enc "$name")"')).toBe(true);
  });

  it('refuses archive days not above searchable days, and both DDAA and DDSS on one index', () => {
    expect(codes(build('splunk_acs_archive', { archive: 'app_web | 90 | 60 |' }), 'error')).toContain('splunk.acs-ddaa-days');
    expect(codes(build('splunk_acs_archive', { archive: 'app_web | 90 | 365 | s3://b-ucket/x' }), 'error')).toContain('splunk.acs-archive-both');
    expect(codes(build('splunk_acs_archive', { archive: 'app_web | 90 |  | ftp://nope' }), 'error')).toContain('splunk.acs-ddss-path');
  });

  it('warns when an index has no archive, or is searchable beyond the contract', () => {
    const result = build('splunk_acs_archive', { archive: 'app_web | 180 |  | ', contract_days: 90 });
    expect(codes(result, 'warning')).toContain('splunk.acs-index-no-archive');
    expect(codes(result, 'warning')).toContain('splunk.acs-searchable-over-contract');
    expect(codes(result, 'error')).toEqual([]);
  });

  it('says that S3 federated search is now a Data Management connection, not an aws_s3 provider', () => {
    const note = build('splunk_acs_archive').files['DEPLOY.md'] ?? '';
    expect(note.includes('Data Management connection')).toBe(true);
    expect(/type = aws_s3/.test(Object.values(build('splunk_acs_archive').files).join('\n'))).toBe(false);
  });
});

describe('maintenance', () => {
  it('guards the restart with the stack name and a deployment check, then polls restart/status', () => {
    const sh = file(build('splunk_acs_maintenance'), 'acs-maintenance.sh');
    expect(sh.includes('[ "$CONFIRM" = "$STACK" ]')).toBe(true);
    expect(sh.includes('IGNORE_DEPLOYMENTS=0')).toBe(true);
    expect(sh.includes('acs POST /restart-now')).toBe(true);
    expect(sh.includes('/restart/status')).toBe(true);
    expect(sh.includes('/deployment/status')).toBe(true);
    expect(sh.includes('/maintenance-windows/schedules')).toBe(true);
    expect(sh.includes('PREFS_METHOD=POST')).toBe(true);
  });

  it('marks the unverified preferences method, and warns when the deployment check is off', () => {
    const note = build('splunk_acs_maintenance').files['DEPLOY.md'] ?? '';
    expect(note.includes('VERIFY: whether maintenance-windows/preferences takes POST or PUT')).toBe(true);
    expect(codes(build('splunk_acs_maintenance', { block_deploying: false }), 'warning')).toContain('splunk.acs-restart-during-deploy');
    expect(file(build('splunk_acs_maintenance', { prefs_method: 'PUT' }), 'acs-maintenance.sh').includes('PREFS_METHOD=PUT')).toBe(true);
  });
});

describe('limits', () => {
  it('writes the rows as stanza | setting | value and reads the current value before changing it', () => {
    const result = build('splunk_acs_limits');
    expect(file(result, 'ops/limits.txt').includes('kv | limit | 200')).toBe(true);
    const sh = file(result, 'acs-limits.sh');
    expect(sh.indexOf('current_value "$st" "$se"') < sh.indexOf('acs_json PATCH')).toBe(true);
    expect(sh.includes('limits-before-')).toBe(true);
    expect(sh.includes('/private-connectivity/eligibility')).toBe(true);
    expect(sh.includes('/private-connectivity/endpoints')).toBe(true);
  });

  it('refuses malformed and duplicate rows, and a package with nothing to do', () => {
    expect(codes(build('splunk_acs_limits', { limits: 'kv | limit' }), 'error')).toContain('splunk.acs-limits-row');
    expect(codes(build('splunk_acs_limits', { limits: 'kv | limit | 1\nkv | limit | 2' }), 'error')).toContain('splunk.acs-limits-duplicate');
    expect(codes(build('splunk_acs_limits', { limits: '', connectivity: false }), 'error')).toContain('splunk.acs-limits-nothing');
  });

  it('refuses a stack that is not a stack name', () => {
    expect(codes(build('splunk_acs_limits', { stack: 'acme prod' }), 'error')).toContain('splunk.acs-bad-stack');
  });
});
