/**
 * The 10.x forwarder inputs: Windows Event Forwarding, scripted inputs and
 * the modular input skeleton.
 *
 * What is checked is what fails quietly in Splunk: an input written disabled,
 * a Python input on a tier that has no Python, a filter the forwarder
 * rejects, and a modular input whose first input cannot pass its own
 * validation.
 */

import { describe, it } from 'node:test';
import { expect } from '../testing/expect.ts';
import { defaultValues, type BlueprintValues } from '../kit/blueprint.ts';
import { hasErrors } from '../core/findings.ts';
import { FORWARDER_10X_BLUEPRINTS } from './blueprints/forwarder-10x.ts';
import type { SplunkBlueprint } from './from-app.ts';

function blueprint(id: string): SplunkBlueprint {
  const found = FORWARDER_10X_BLUEPRINTS.find((b) => b.id === id);
  if (!found) throw new Error(`missing ${id}`);
  return found;
}

function build(id: string, changes: BlueprintValues = {}) {
  const b = blueprint(id);
  const values = { ...defaultValues(b), ...changes };
  return { app: b.app(values, id), result: b.build(values, id) };
}

const codes = (findings: readonly { code: string }[] | undefined): string[] => (findings ?? []).map((f) => f.code);

describe('forwarder 10.x: every blueprint', () => {
  it('builds from its defaults with no error, an app.conf and a deployment note', () => {
    for (const b of FORWARDER_10X_BLUEPRINTS) {
      const result = b.build(defaultValues(b), b.id);
      expect([b.id, hasErrors(result.findings ?? [])]).toEqual([b.id, false]);
      expect([b.id, Object.keys(result.files).some((n) => n.endsWith('/default/app.conf'))]).toEqual([b.id, true]);
      expect([b.id, (result.files['DEPLOY.md'] ?? '').includes('## Back out')]).toEqual([b.id, true]);
    }
  });

  it('creates everything enabled, applies when run and leaves no footprint', () => {
    for (const b of FORWARDER_10X_BLUEPRINTS) {
      for (const language of ['bash', 'powershell', 'python']) {
        const { files } = b.build({ ...defaultValues(b), language }, b.id);
        for (const [path, body] of Object.entries(files)) {
          expect([b.id, path, /^\s*disabled\s*=\s*(1|true)\s*$/m.test(body)]).toEqual([b.id, path, false]);
          expect([b.id, path, /--execute|-Execute\b/.test(body)]).toEqual([b.id, path, false]);
          expect([b.id, path, /ArchToolKit|Generated by/i.test(body)]).toEqual([b.id, path, false]);
          if (/\.(sh|py)$/.test(path) && body.includes('#!/')) expect([path, body.startsWith('#!')]).toEqual([path, true]);
        }
      }
    }
  });
});

describe('Windows Event Forwarding collector', () => {
  it('reads ForwardedEvents as XML with the allow and deny lists', () => {
    const { app, result } = build('splunk_wef_collector', { allow_codes: '4624, 4625, 4720-4767' });
    expect(app.tier).toBe('forwarder');
    const inputs = result.files['org_wef_collector/default/inputs.conf'] ?? '';
    expect(inputs).toContain('[WinEventLog://ForwardedEvents]');
    expect(inputs).toContain('renderXml = true');
    expect(inputs).toContain('whitelist = 4624,4625,4720-4767');
    expect(inputs).toContain('blacklist = 5156,5158');
    expect(inputs).toContain('blacklist1 = EventCode="^4658$"');
  });

  it('writes a source-initiated subscription with each channel in the query', () => {
    const { result } = build('splunk_wef_collector', { sources: 'both' });
    const xml = result.files['org_wef_collector/ops/subscription.xml'] ?? '';
    expect(xml.startsWith('<?xml')).toBe(true);
    expect(xml).toContain('<SubscriptionType>SourceInitiated</SubscriptionType>');
    expect(xml).toContain('<Select Path="Security">*</Select>');
    expect(xml).toContain('O:NSG:BAD:P(A;;GA;;;DC)(A;;GA;;;DD)S:');
    const gpo = result.files['org_wef_collector/ops/gpo-settings.txt'] ?? '';
    expect(gpo).toContain('Server=http://wec01.example.com:5985/wsman/SubscriptionManager/WEC,Refresh=60');
  });

  it('refuses event codes, filter fields and SIDs the forwarder or wecutil reject', () => {
    expect(codes(build('splunk_wef_collector', { deny_codes: '5156, fivefiftyeight' }).result.findings)).toContain('splunk.wef-bad-code');
    expect(codes(build('splunk_wef_collector', { deny_rows: 'Colour | red' }).result.findings)).toContain('splunk.wef-bad-field');
    const ten = Array.from({ length: 10 }, (_, i) => `EventCode | ^46${i}0$`).join('\n');
    expect(codes(build('splunk_wef_collector', { deny_rows: ten }).result.findings)).toContain('splunk.wef-too-many-rules');
    expect(codes(build('splunk_wef_collector', { sources: 'sid', source_sid: 'Domain Admins' }).result.findings)).toContain('splunk.wef-source-sid');
    expect(codes(build('splunk_wef_collector', { collector: '' }).result.findings)).toContain('splunk.wef-collector');
  });

  it('warns when the sourcetype does not match the rendering', () => {
    const { result } = build('splunk_wef_collector', { sourcetype: 'WinEventLog' });
    expect(codes(result.findings)).toContain('splunk.wef-sourcetype');
    expect(hasErrors(result.findings ?? [])).toBe(false);
  });
});

describe('scripted input', () => {
  it('runs a bash script on the universal forwarder', () => {
    const { app, result } = build('splunk_scripted_input');
    expect(app.tier).toBe('forwarder');
    expect(result.files['org_scripted_input/default/inputs.conf'] ?? '').toContain('[script://./bin/disk_free.sh]');
    expect((result.files['org_scripted_input/bin/disk_free.sh'] ?? '').startsWith('#!/usr/bin/env bash')).toBe(true);
  });

  it('puts a Python script on a heavy forwarder with python.required', () => {
    const { app, result } = build('splunk_scripted_input', { language: 'python' });
    expect(app.tier).toBe('heavy_forwarder');
    const inputs = result.files['org_scripted_input/default/inputs.conf'] ?? '';
    expect(inputs).toContain('[script://./bin/disk_free.py]');
    expect(inputs).toContain('python.required = 3.9, 3.13');
    expect(inputs.includes('python.version')).toBe(false);
    expect(build('splunk_scripted_input', { language: 'python', also_9x: true }).result.files['org_scripted_input/default/inputs.conf'] ?? '').toContain('python.version = python3');
  });

  it('uses the PowerShell input on Windows', () => {
    const { app, result } = build('splunk_scripted_input', { language: 'powershell', interval: '0 * * * *' });
    expect(app.tier).toBe('forwarder');
    const inputs = result.files['org_scripted_input/default/inputs.conf'] ?? '';
    expect(inputs).toContain('[powershell://disk_free]');
    expect(inputs).toContain('bin\\disk_free.ps1');
    expect(inputs).toContain('schedule = 0 * * * *');
  });

  it('refuses an interval that is neither seconds nor cron, and warns about sudo and compiled modules', () => {
    expect(codes(build('splunk_scripted_input', { interval: 'every five minutes' }).result.findings)).toContain('splunk.script-interval');
    expect(codes(build('splunk_scripted_input', { script_body: '#!/usr/bin/env bash\nsudo cat /var/log/secure' }).result.findings)).toContain('splunk.script-sudo');
    expect(codes(build('splunk_scripted_input', { language: 'python', script_body: '#!/usr/bin/env python3\nimport numpy as np' }).result.findings)).toContain('splunk.script-binary-module');
  });
});

describe('modular input skeleton', () => {
  it('ships the spec, the scheme, python.required and one enabled input on a heavy forwarder', () => {
    const { app, result } = build('splunk_modular_input');
    expect(app.tier).toBe('heavy_forwarder');
    const spec = result.files['ta_org_api/README/inputs.conf.spec'] ?? '';
    expect(spec).toContain('[org_api_poll://<name>]');
    expect(spec).toContain('endpoint = <string>');
    const inputs = result.files['ta_org_api/default/inputs.conf'] ?? '';
    expect(inputs).toContain('[org_api_poll]\n# The Python versions');
    expect(inputs).toContain('python.required = 3.9, 3.13');
    expect(inputs).toContain('[org_api_poll://primary]\ndisabled = 0');
    expect(inputs).toContain('endpoint = https://api.example.com/v1/records');
    const script = result.files['ta_org_api/bin/org_api_poll.py'] ?? '';
    expect(script).toContain('from splunklib.modularinput import');
    expect(script).toContain('("endpoint", "string", True, "Base URL of the API"),');
    expect(script).toContain('scheme.use_external_validation = True');
    expect(Object.keys(result.files)).toContain('ta_org_api/ops/validate_modinput.py');
    expect(Object.keys(result.files)).toContain('ta_org_api/ops/vendor-sdk.sh');
  });

  it('refuses parameters that cannot work', () => {
    expect(codes(build('splunk_modular_input', { params: 'index | string | false | x | clashes' }).result.findings)).toContain('splunk.modinput-param-reserved');
    expect(codes(build('splunk_modular_input', { params: 'endpoint | string | true |  | no value' }).result.findings)).toContain('splunk.modinput-required-empty');
    expect(codes(build('splunk_modular_input', { params: 'size | integer | false | 5 | wrong type' }).result.findings)).toContain('splunk.modinput-param-type');
    expect(codes(build('splunk_modular_input', { params: 'size | number | false | lots | not a number' }).result.findings)).toContain('splunk.modinput-param-value');
    expect(codes(build('splunk_modular_input', { params: 'Bad-Name | string | false | x | bad' }).result.findings)).toContain('splunk.modinput-param-name');
  });

  it('warns when a credential would sit in inputs.conf', () => {
    const { result } = build('splunk_modular_input', { params: 'api_key | string | true | abc123 | key' });
    expect(codes(result.findings)).toContain('splunk.modinput-secret-param');
  });
});
