/**
 * The indexer storage and 10.x management blueprints.
 *
 * What these have to get right is what fails quietly: a remote store whose
 * certificate nobody checks, a secret in the cluster bundle, two indexes in one
 * prefix, a search peer on the wrong port, a KV store upgrade started without a
 * backup or on a CPU that cannot run it, and a health report threshold that
 * never warns.
 */

import { describe, it } from 'node:test';
import { expect } from '../testing/expect.ts';
import { defaultValues, type BlueprintValues } from '../kit/blueprint.ts';
import { hasErrors } from '../core/findings.ts';
import type { SplunkBlueprint } from './from-app.ts';
import { INDEXER_STORAGE_BLUEPRINTS } from './blueprints/indexer-storage.ts';
import { MANAGEMENT_10X_BLUEPRINTS } from './blueprints/management-10x.ts';

const ALL: readonly SplunkBlueprint[] = [...INDEXER_STORAGE_BLUEPRINTS, ...MANAGEMENT_10X_BLUEPRINTS];

function blueprint(id: string): SplunkBlueprint {
  const found = ALL.find((b) => b.id === id);
  if (!found) throw new Error(`missing ${id}`);
  return found;
}

function build(id: string, overrides: BlueprintValues = {}) {
  const b = blueprint(id);
  return b.build({ ...defaultValues(b), ...overrides }, id);
}

function file(id: string, suffix: string, overrides: BlueprintValues = {}): string {
  const files = build(id, overrides).files;
  const key = Object.keys(files).find((k) => k.endsWith(suffix));
  return key ? (files[key] ?? '') : '';
}

const codes = (id: string, overrides: BlueprintValues = {}) => (build(id, overrides).findings ?? []).map((f) => `${f.severity}:${f.code}`);

describe('indexer storage and 10.x management: every blueprint', () => {
  it('is on the tier it says, with unique ids', () => {
    for (const b of INDEXER_STORAGE_BLUEPRINTS) expect([b.id, b.tier]).toEqual([b.id, 'indexer']);
    for (const b of MANAGEMENT_10X_BLUEPRINTS) expect([b.id, b.tier]).toEqual([b.id, 'management']);
    const ids = ALL.map((b) => b.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('builds from its own defaults without an error finding', () => {
    for (const b of ALL) {
      const result = b.build(defaultValues(b), b.id);
      expect([b.id, hasErrors(result.findings ?? [])]).toEqual([b.id, false]);
      expect([b.id, Object.keys(result.files).includes('DEPLOY.md')]).toEqual([b.id, true]);
    }
  });

  it('leaves no footprint, no disabled flag on what was asked for, and no --execute', () => {
    for (const b of ALL) {
      for (const [path, body] of Object.entries(b.build(defaultValues(b), b.id).files)) {
        expect([b.id, path, /ArchToolKit|Generated by/i.test(body)]).toEqual([b.id, path, false]);
        expect([b.id, path, body.includes('--execute')]).toEqual([b.id, path, false]);
        expect([b.id, path, /^\s*disabled\s*=\s*(1|true)\s*$/m.test(body)]).toEqual([b.id, path, false]);
      }
    }
  });

  it('gives every script a --dry-run and a refusal to run as root, with the shebang on line one', () => {
    for (const b of ALL) {
      for (const [path, body] of Object.entries(b.build(defaultValues(b), b.id).files)) {
        if (!path.endsWith('.sh')) continue;
        expect([path, body.startsWith('#!/usr/bin/env bash')]).toEqual([path, true]);
        expect([path, body.includes('--dry-run) EXECUTE=0')]).toEqual([path, true]);
        expect([path, body.includes('$EUID -eq 0')]).toEqual([path, true]);
      }
    }
  });
});

describe('SmartStore on Azure Blob', () => {
  it('verifies the endpoint and keeps the secret out of the app', () => {
    const conf = file('splunk_smartstore_azure', 'default/indexes.conf');
    expect(conf).toContain('path = azure://splunk-smartstore/prod-cluster');
    expect(conf).toContain('remote.azure.sslVerifyServerCert = true');
    expect(conf).toContain('remote.azure.sslVerifyServerName = true');
    expect(conf).toContain('remote.azure.encryption = azure-sse-ms');
    expect(conf).toContain('remote.azure.client_secret = <set in local/');
    expect(conf).toContain('remotePath = volume:remote_store/$_index_name');
    expect(file('splunk_smartstore_azure', 'default/server.conf')).toContain('[cachemanager]');
  });

  it('uses the account key only as a placeholder, and warns about it', () => {
    const conf = file('splunk_smartstore_azure', 'default/indexes.conf', { auth: 'key' });
    expect(conf).toContain('remote.azure.secret_key = <set in local/');
    expect(conf.includes('remote.azure.client_id')).toBe(false);
    expect(codes('splunk_smartstore_azure', { auth: 'key' })).toContain('warning:splunk.smartstore-azure-account-key');
  });

  it('refuses a path that is not azure://, and an endpoint that is not https', () => {
    expect(codes('splunk_smartstore_azure', { remote_path: 's3://bucket/x' })).toContain('error:splunk.smartstore-azure-path');
    expect(codes('splunk_smartstore_azure', { endpoint: 'http://acct.blob.core.windows.net' })).toContain('error:splunk.smartstore-azure-endpoint');
  });

  it('refuses two indexes in one remote prefix', () => {
    const indexes = 'app_prod | shared | 100 | 90\nnetfw | shared | 100 | 90';
    expect(codes('splunk_smartstore_azure', { indexes })).toContain('error:splunk.smartstore-shared-prefix');
  });

  it('refuses a cache far too small for the search window', () => {
    expect(codes('splunk_smartstore_azure', { cache_gb: 50 })).toContain('error:splunk.smartstore-cache-too-small');
  });
});

describe('SmartStore on Google Cloud Storage', () => {
  it('writes the Cloud KMS key and TLS verification', () => {
    const conf = file('splunk_smartstore_gcs', 'default/indexes.conf');
    expect(conf).toContain('path = gs://acme-splunk-smartstore-prod/indexes');
    expect(conf).toContain('remote.gs.encryption = gcp-sse-kms');
    expect(conf).toContain('remote.gs.gcp_kms.key_ring = splunk');
    expect(conf).toContain('remote.gs.sslVerifyServerCert = true');
    expect(conf).toContain('remote.gs.sslVerifyServerName = true');
    expect(conf.includes('credential_file')).toBe(false);
  });

  it('names the service account or the key file only when chosen', () => {
    expect(file('splunk_smartstore_gcs', 'default/indexes.conf', { auth: 'email' })).toContain('remote.gs.service_account_email = splunk-smartstore@');
    expect(file('splunk_smartstore_gcs', 'default/indexes.conf', { auth: 'file' })).toContain('remote.gs.credential_file = gcs-smartstore.json');
    expect(codes('splunk_smartstore_gcs', { auth: 'file', credential_file: '/etc/key.json' })).toContain('error:splunk.smartstore-gcs-key-path');
  });

  it('refuses Cloud KMS without a key, and a path that is not gs://', () => {
    expect(codes('splunk_smartstore_gcs', { kms_key: '' })).toContain('error:splunk.smartstore-gcs-kms');
    expect(codes('splunk_smartstore_gcs', { remote_path: 'azure://x/y' })).toContain('error:splunk.smartstore-gcs-path');
  });
});

describe('data integrity control', () => {
  it('turns it on per listed index and checks with check-integrity', () => {
    const conf = file('splunk_data_integrity', 'default/indexes.conf');
    expect(conf).toContain('[netfw]\nenableDataIntegrityControl = true');
    expect(file('splunk_data_integrity', 'bin/check-integrity.sh')).toContain('check-integrity -index "$index"');
  });

  it('refuses an empty list', () => {
    expect(codes('splunk_data_integrity', { indexes: '' })).toContain('error:splunk.integrity-no-indexes');
  });
});

describe('distributed search peers', () => {
  it('adds each peer with add search-server and never prints the password', () => {
    const script = file('splunk_distsearch_peers', 'bin/add-search-peers.sh');
    expect(script).toContain('add search-server "$uri" -remoteUsername "$user"');
    expect(script).toContain('-remotePassword ****');
  });

  it('writes distsearch.conf and the trusted.pem copy for the conf method', () => {
    const result = build('splunk_distsearch_peers', { method: 'conf' });
    const conf = Object.entries(result.files).find(([k]) => k.endsWith('distsearch.conf'))?.[1] ?? '';
    expect(conf).toContain('servers = https://idx01.example.com:8089,https://idx02.example.com:8089');
    expect(Object.keys(result.files).some((k) => k.endsWith('bin/copy-trusted-pem.sh'))).toBe(true);
  });

  it('refuses the receiving port as a management port', () => {
    expect(codes('splunk_distsearch_peers', { peers: 'idx01.example.com | 9997 | admin' })).toContain('error:splunk.distsearch-not-management-port');
  });
});

describe('KV store server upgrade', () => {
  it('maps --dry-run to the CLI’s own dry run, for each topology', () => {
    expect(file('splunk_kvstore_upgrade', 'bin/20-kvstore-upgrade.sh')).toContain('start-shcluster-upgrade kvstore -isDryRun true');
    expect(file('splunk_kvstore_upgrade', 'bin/20-kvstore-upgrade.sh', { topology: 'standalone' })).toContain('start-standalone-upgrade kvstore -dryRun true');
    expect(file('splunk_kvstore_upgrade', 'bin/20-kvstore-upgrade.sh', { topology: 'standalone' })).toContain('show standalone-kvupgrade-status');
  });

  it('checks CPU flags and glibc before, and backs up first', () => {
    const pre = file('splunk_kvstore_upgrade', 'bin/00-kvstore-precheck.sh');
    for (const flag of ['avx', 'sse4_2', 'aes', '2.27', 'kvstore-status']) expect([flag, pre.includes(flag)]).toEqual([flag, true]);
    expect(file('splunk_kvstore_upgrade', 'bin/10-kvstore-backup.sh')).toContain('backup kvstore -archiveName');
  });

  it('refuses 4.2 on 10.4 and warns without a backup', () => {
    expect(codes('splunk_kvstore_upgrade', { splunk_version: '10.4', current_server: '4.2' })).toContain('error:splunk.kvstore-42-on-104');
    expect(codes('splunk_kvstore_upgrade', { backup: false })).toContain('warning:splunk.kvstore-no-backup');
  });
});

describe('health report', () => {
  it('writes thresholds, alerting and the email action', () => {
    const conf = file('splunk_health_report', 'default/health.conf');
    expect(conf).toContain('[feature:disk_space]\nindicator:disk_space_remaining_multiple_minfreespace:yellow = 2');
    expect(conf).toContain('alert.disabled = 0');
    expect(conf).toContain('[alert_action:email]\ndisabled = 0');
  });

  it('allow-lists the webhook and snoozes until the date given', () => {
    const values = { webhook: true, snooze: true, snoozed: 'buckets | 2030-01-01' };
    expect(file('splunk_health_report', 'default/alert_actions.conf', values)).toContain('allowlist.health_report = ^https://hooks\\.example\\.com/');
    expect(file('splunk_health_report', 'default/health.conf', values)).toContain(`snooze_end_time = ${Date.UTC(2030, 0, 1) / 1000}`);
  });

  it('refuses a threshold that is not a number, and warns when yellow equals red', () => {
    expect(codes('splunk_health_report', { thresholds: 'disk_space | disk_space_remaining_multiple_minfreespace | two | 1' })).toContain('error:splunk.health-threshold');
    expect(codes('splunk_health_report', { thresholds: 'buckets | percent_small_buckets_created_last_24h | 40 | 40' })).toContain('warning:splunk.health-same-threshold');
  });
});
