/**
 * The second set of onboarding blueprints: NSX, the VCF management
 * components, Ansible, HCP Terraform and Juniper.
 *
 * What is checked is what would otherwise fail quietly: a script that only
 * previews when someone expected it to apply, a sourcetype routed to the wrong
 * index, a HEC URL the controller will post to and get a 404 from, a listener
 * a non-root Splunk cannot bind.
 */

import { describe, it } from 'node:test';
import { expect } from '../testing/expect.ts';
import { defaultValues, type BlueprintValues } from '../kit/blueprint.ts';
import { ONBOARDING_MORE_BLUEPRINTS } from './blueprints/onboarding-more.ts';
import { splunkApp } from './blueprints/index.ts';

function blueprint(id: string) {
  const b = ONBOARDING_MORE_BLUEPRINTS.find((x) => x.id === id);
  if (!b) throw new Error(`missing ${id}`);
  return b;
}

function build(id: string, overrides: BlueprintValues = {}) {
  const b = blueprint(id);
  return b.build({ ...defaultValues(b), ...overrides }, id);
}

function codes(id: string, overrides: BlueprintValues = {}): string[] {
  return (build(id, overrides).findings ?? []).map((f) => `${f.severity}:${f.code}`);
}

describe('onboarding-more: every blueprint', () => {
  it('is registered with the add-ons, in the onboarding group', () => {
    for (const b of ONBOARDING_MORE_BLUEPRINTS) {
      expect([b.id, splunkApp(b.id)?.id]).toEqual([b.id, b.id]);
      expect([b.id, b.tier, b.group]).toEqual([b.id, 'addon', 'Onboard what you built']);
    }
  });

  it('builds from its defaults without an error', () => {
    for (const b of ONBOARDING_MORE_BLUEPRINTS) {
      const errors = (build(b.id).findings ?? []).filter((f) => f.severity === 'error').map((f) => f.code);
      expect([b.id, errors]).toEqual([b.id, []]);
    }
  });

  it('leaves no footprint and nothing disabled', () => {
    for (const b of ONBOARDING_MORE_BLUEPRINTS) {
      for (const [path, body] of Object.entries(build(b.id).files)) {
        expect([b.id, path, /ArchToolKit|Generated by/i.test(body)]).toEqual([b.id, path, false]);
        expect([b.id, path, /^\s*disabled\s*=\s*(1|true)\s*$/m.test(body)]).toEqual([b.id, path, false]);
      }
    }
  });

  it('writes scripts that apply when run, with --dry-run to preview', () => {
    for (const b of ONBOARDING_MORE_BLUEPRINTS) {
      for (const [path, body] of Object.entries(build(b.id).files)) {
        if (!path.endsWith('.sh')) continue;
        expect([path, body.includes('--execute')]).toEqual([path, false]);
        expect([path, body.startsWith('#!/usr/bin/env bash')]).toEqual([path, true]);
        // The read-only token check has nothing to preview.
        if (!path.endsWith('check-audit-trail.sh')) expect([path, /EXECUTE=1/.test(body) && body.includes('--dry-run) EXECUTE=0')]).toEqual([path, true]);
      }
    }
  });
});

describe('onboarding-more: NSX', () => {
  it('routes the packet logs to the firewall index and the rest to the infrastructure index', () => {
    const files = build('splunk_onboard_nsx').files;
    const csv = Object.entries(files).find(([p]) => p.endsWith('ops/sc4s/splunk_metadata.csv'))![1];
    expect(csv).toContain('vmware_vsphere_nsxfw,index,netfw');
    expect(csv).toContain('vmware_vsphere_nsx,index,infraops');
    const searches = Object.entries(files).find(([p]) => p.endsWith('savedsearches.conf'))![1];
    expect(searches).toContain('sourcetype="vmware:nsxlog:dfwpktlogs"');
    expect(searches).toContain('where drops > 200');
  });

  it('turns rule logging on through the Policy API and can undo exactly that', () => {
    const script = Object.entries(build('splunk_onboard_nsx').files).find(([p]) => p.endsWith('nsx-syslog.sh'))![1];
    expect(script).toContain('/policy/api/v1/infra/domains/default/security-policies');
    expect(script).toContain('.logged = $v');
    expect(script).toContain('--undo');
    expect(script).toContain("POLICIES=('app-tier' 'dmz-inbound')");
  });

  it('warns about logging every rule, and refuses an empty collector', () => {
    expect(codes('splunk_onboard_nsx', { dfw_policies: '*' })).toContain('warning:splunk.nsx-log-every-rule');
    expect(codes('splunk_onboard_nsx', { sc4s_host: '' })).toContain('error:splunk.nsx-no-collector');
  });
});

describe('onboarding-more: VCF management components', () => {
  it('refuses a port below 1024 on a heavy forwarder, which runs as non-root', () => {
    expect(codes('splunk_onboard_vcf_management', { collector: 'hf', listener: 'tcp514' })).toContain('error:splunk.vcf-hf-low-port');
    expect(codes('splunk_onboard_vcf_management', { collector: 'hf', listener: 'tcp1514' }).some((c) => c.startsWith('error:'))).toBe(false);
  });

  it('defaults to infraops, and says there is no add-on', () => {
    const result = build('splunk_onboard_vcf_management');
    const note = result.files['DEPLOY.md'] ?? '';
    expect(note).toContain('VERIFY: there is no Splunk add-on');
    const lookup = Object.entries(result.files).find(([p]) => p.endsWith('expected_vcf_components.csv'))![1];
    expect(lookup.startsWith('host,component')).toBe(true);
    expect(lookup).toContain('sddc01,sddc_manager');
    const hf = build('splunk_onboard_vcf_management', { collector: 'hf', listener: 'tls6514' }).files;
    const inputs = Object.entries(hf).find(([p]) => p.endsWith('heavy_forwarder/inputs.conf'))![1];
    expect(inputs).toContain('[tcp-ssl:6514]');
    expect(inputs).toContain('index = infraops');
  });
});

describe('onboarding-more: Ansible', () => {
  it('refuses a HEC URL without the event path', () => {
    expect(codes('splunk_onboard_ansible', { hec_url: 'https://hec.example.com:8088' })).toContain('error:splunk.ansible-hec-url');
  });

  it('PATCHes the logging settings with the splunk aggregator and never prints the token', () => {
    const script = Object.entries(build('splunk_onboard_ansible').files).find(([p]) => p.endsWith('awx-logging.sh'))![1];
    expect(script).toContain('-X PATCH');
    expect(script).toContain('$API/settings/logging/');
    expect(script).toContain('LOG_AGGREGATOR_TYPE: "splunk"');
    expect(script).toContain('.LOG_AGGREGATOR_PASSWORD = "<hidden>"');
    expect(script).toContain('API="$CONTROLLER/api/v2"');
    const gateway = Object.entries(build('splunk_onboard_ansible', { product: 'aap25' }).files).find(([p]) => p.endsWith('awx-logging.sh'))![1];
    expect(gateway).toContain('API="$CONTROLLER/api/controller/v2"');
  });

  it('warns when job events are not sent, since the failed-job alert reads them', () => {
    expect(codes('splunk_onboard_ansible', { loggers: 'awx,activity_stream' })).toContain('warning:splunk.ansible-no-job-events');
    expect(codes('splunk_onboard_ansible', { loggers: '' })).toContain('error:splunk.ansible-no-loggers');
  });
});

describe('onboarding-more: HCP Terraform', () => {
  it('warns that the app is not supported on clustered Enterprise', () => {
    expect(codes('splunk_onboard_hcp_terraform', { deployment: 'clustered' })).toContain('warning:splunk.tfc-clustered');
    expect(codes('splunk_onboard_hcp_terraform')).toEqual([]);
  });

  it('names the app and keeps the token out of every file', () => {
    const result = build('splunk_onboard_hcp_terraform');
    expect(result.files['DEPLOY.md'] ?? '').toContain('Splunkbase 5141');
    const check = Object.entries(result.files).find(([p]) => p.endsWith('check-audit-trail.sh'))![1];
    expect(check).toContain('/api/v2/organization/audit-trail');
    expect(check).toContain('-H @"$WORK/auth.h"');
  });
});

describe('onboarding-more: Juniper', () => {
  it('writes set commands per device, with a security log stream only on SRX', () => {
    const files = build('splunk_onboard_juniper').files;
    const srx = Object.entries(files).find(([p]) => p.endsWith('device-config/srx_edge01.txt'))![1];
    const ex = Object.entries(files).find(([p]) => p.endsWith('device-config/ex_access01.txt'))![1];
    expect(srx).toContain('set security log stream SPLUNK host 10.0.5.10 port 514');
    expect(ex.includes('security log')).toBe(false);
    expect(ex).toContain('set system syslog host 10.0.5.10 structured-data');
    // A note after a command is part of the command to the CLI.
    for (const line of srx.split('\n')) expect([line, line.startsWith('set ') && line.includes('#')]).toEqual([line, false]);
  });

  it('warns about an unknown role, a host name for an SRX stream, and non-default indexes', () => {
    expect(codes('splunk_onboard_juniper', { devices: 'fw1 | 10.0.0.1 | srx\nodd1 | 10.0.0.2 | ptx' })).toContain('warning:splunk.junos-unknown-role');
    expect(codes('splunk_onboard_juniper', { sc4s_host: 'sc4s01.example.com' })).toContain('warning:splunk.junos-stream-host');
    expect(codes('splunk_onboard_juniper', { netfw_index: 'firewall' })).toContain('warning:splunk.junos-index-override');
  });
});
