/**
 * The search head knowledge blueprints: event types and tags, field
 * enrichment, workflow actions, the webhook alert, the custom alert action,
 * the emailed report and Federated Search.
 *
 * Each builds clean from its defaults, writes the stanzas it exists for, is
 * created enabled, and carries nothing of the tool that made it.
 */

import { describe, it } from 'node:test';
import { expect } from '../testing/expect.ts';
import { defaultValues, type BlueprintValues } from '../kit/blueprint.ts';
import { hasErrors } from '../core/findings.ts';
import { SEARCH_HEAD_KNOWLEDGE_BLUEPRINTS } from './blueprints/search-head-knowledge.ts';

function blueprint(id: string) {
  const found = SEARCH_HEAD_KNOWLEDGE_BLUEPRINTS.find((b) => b.id === id);
  if (!found) throw new Error(`no blueprint ${id}`);
  return found;
}

function build(id: string, overrides: BlueprintValues = {}) {
  const b = blueprint(id);
  return b.build({ ...defaultValues(b), ...overrides }, b.id);
}

/** The one generated file whose path ends with this. */
function file(files: Readonly<Record<string, string>>, suffix: string): string {
  const path = Object.keys(files).find((p) => p.endsWith(suffix));
  if (!path) throw new Error(`no file ending ${suffix} in ${Object.keys(files).join(', ')}`);
  return files[path] ?? '';
}

describe('search head knowledge: every blueprint', () => {
  it('builds from its defaults with no errors and no warnings', () => {
    for (const b of SEARCH_HEAD_KNOWLEDGE_BLUEPRINTS) {
      const result = b.build(defaultValues(b), b.id);
      const found = (result.findings ?? []).filter((f) => f.severity !== 'info').map((f) => f.code);
      expect([b.id, found]).toEqual([b.id, []]);
      expect([b.id, b.tier]).toEqual([b.id, 'search_head']);
    }
  });

  it('creates everything enabled, applies when run and leaves no footprint', () => {
    for (const b of SEARCH_HEAD_KNOWLEDGE_BLUEPRINTS) {
      const { files } = b.build(defaultValues(b), b.id);
      for (const [path, text] of Object.entries(files)) {
        expect([b.id, path, /^\s*disabled\s*=\s*(1|true)\s*$/m.test(text)]).toEqual([b.id, path, false]);
        expect([b.id, path, /^\s*enableSched\s*=\s*0/m.test(text)]).toEqual([b.id, path, false]);
        expect([b.id, path, /ArchToolKit|Generated by/i.test(text)]).toEqual([b.id, path, false]);
        expect([b.id, path, text.includes('--execute')]).toEqual([b.id, path, false]);
      }
    }
  });

  it('gives every app its sharing metadata', () => {
    for (const b of SEARCH_HEAD_KNOWLEDGE_BLUEPRINTS) {
      const { files } = b.build(defaultValues(b), b.id);
      expect([b.id, Object.keys(files).some((p) => p.endsWith('metadata/default.meta'))]).toEqual([b.id, true]);
    }
  });

  it('uses unique blueprint ids', () => {
    const ids = SEARCH_HEAD_KNOWLEDGE_BLUEPRINTS.map((b) => b.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});

describe('event types and tags', () => {
  it('writes each event type and its tags', () => {
    const { files } = build('splunk_eventtypes_tags');
    const eventtypes = file(files, 'default/eventtypes.conf');
    const tags = file(files, 'default/tags.conf');
    expect(eventtypes).toContain('[acme_auth_privileged]');
    expect(eventtypes).toContain('search = sourcetype="acme:auth" user IN (root, admin, administrator)');
    expect(tags).toContain('[eventtype=acme_auth_privileged]');
    expect(tags).toContain('privileged = enabled');
  });

  it('adds the ticked CIM tags to every event type', () => {
    const tags = file(build('splunk_eventtypes_tags', { extra_tags: 'default' }).files, 'default/tags.conf');
    expect(tags.match(/^default = enabled$/gm)?.length).toBe(3);
  });

  it('rejects an event type with a pipe', () => {
    const result = build('splunk_eventtypes_tags', { eventtypes: 'bad | sourcetype=x | stats count | web' });
    expect(hasErrors(result.findings ?? [])).toBe(true);
  });
});

describe('field enrichment', () => {
  it('writes aliases, calculated fields and lookups in one sourcetype stanza', () => {
    const { files } = build('splunk_field_enrichment');
    const props = file(files, 'default/props.conf');
    expect(props).toContain('[acme:orders:log]');
    expect(props).toContain('FIELDALIAS-src = src_ip AS src');
    expect(props).toContain('EVAL-duration = round(duration_ms / 1000, 3)');
    expect(props).toContain('LOOKUP-acme_asset_owner = acme_asset_owner host AS dest OUTPUTNEW owner business_unit');
    expect(file(files, 'default/transforms.conf')).toContain('filename = acme_asset_owner.csv');
    expect(file(files, 'lookups/acme_asset_owner.csv').trim()).toBe('host,owner,business_unit');
  });

  it('warns about a calculated field that uses another', () => {
    const result = build('splunk_field_enrichment', { evals: 'a | 1\nb | a + 1' });
    expect((result.findings ?? []).map((f) => f.code)).toContain('splunk.eval-chain');
  });
});

describe('workflow action', () => {
  it('writes a link action', () => {
    const conf = file(build('splunk_workflow_action').files, 'default/workflow_actions.conf');
    expect(conf).toContain('[ipam_lookup_src_ip]');
    expect(conf).toContain('type = link');
    expect(conf).toContain('link.uri = https://ipam.example.com/search?q=$src_ip$');
    expect(conf).toContain('display_location = both');
  });

  it('writes a search action', () => {
    const conf = file(build('splunk_workflow_action', { action_type: 'search' }).files, 'default/workflow_actions.conf');
    expect(conf).toContain('type = search');
    expect(conf).toContain('search.search_string = index=netfw src_ip=$src_ip$');
  });

  it('warns when a token names a field the action does not require', () => {
    const result = build('splunk_workflow_action', { link_uri: 'https://ipam.example.com/?q=$dest_ip$' });
    expect((result.findings ?? []).map((f) => f.code)).toContain('splunk.workflow-token-unlisted');
  });
});

describe('webhook alert', () => {
  it('writes the allow list and a scheduled alert with the webhook action', () => {
    const { files } = build('splunk_webhook_alert');
    expect(file(files, 'default/alert_actions.conf')).toContain('allowlist.acme_hooks = https://hooks\\.example\\.com/services/acme/.*');
    const saved = file(files, 'default/savedsearches.conf');
    expect(saved).toContain('enableSched = 1');
    expect(saved).toContain('action.webhook = 1');
    expect(saved).toContain('action.webhook.param.url = https://hooks.example.com/services/acme/alerts');
  });

  it('refuses a URL the allow list blocks', () => {
    const result = build('splunk_webhook_alert', { webhook_url: 'https://other.example.net/hook' });
    expect((result.findings ?? []).map((f) => f.code)).toContain('splunk.webhook-not-allowed');
  });
});

describe('custom alert action', () => {
  it('ships the conf, spec, form, Python 3 script and a dry-run test', () => {
    const { files } = build('splunk_custom_alert_action');
    const conf = file(files, 'default/alert_actions.conf');
    expect(conf).toContain('[acme_ticket]');
    expect(conf).toContain('is_custom = 1');
    expect(conf).toContain('payload_format = json');
    expect(conf).toContain('python.required = 3.9, 3.13');
    expect(file(files, 'README/alert_actions.conf.spec')).toContain('param.endpoint = <string>');
    expect(file(files, 'default/data/ui/alerts/acme_ticket.html')).toContain('name="action.acme_ticket.param.severity"');
    const py = file(files, 'bin/acme_ticket.py');
    expect(py.startsWith('#!/usr/bin/env python3')).toBe(true);
    expect(py).toContain('ssl.create_default_context()');
    expect(file(files, 'ops/test_alert_action.sh')).toContain('--dry-run');
  });

  it('refuses the name of a built-in action', () => {
    expect(hasErrors(build('splunk_custom_alert_action', { action_name: 'email' }).findings ?? [])).toBe(true);
  });
});

describe('scheduled report by email', () => {
  it('writes a scheduled report with the chosen deliveries', () => {
    const saved = file(build('splunk_report_email', { delivery: 'inline, pdf' }).files, 'default/savedsearches.conf');
    expect(saved).toContain('enableSched = 1');
    expect(saved).toContain('cron_schedule = 0 7 * * 1-5');
    expect(saved).toContain('action.email.to = ops-team@example.com, service-owner@example.com');
    expect(saved).toContain('action.email.sendpdf = 1');
    expect(saved).toContain('action.email.inline = 1');
    expect(saved).toContain('action.email.sendcsv = 0');
  });

  it('rejects a schedule that is not cron', () => {
    expect(hasErrors(build('splunk_report_email', { cron: 'every day' }).findings ?? [])).toBe(true);
  });
});

describe('federated search', () => {
  it('writes the provider, the federated indexes, the remote role and a dry-run REST script', () => {
    const { files } = build('splunk_federated_search');
    const fed = file(files, 'default/federated.conf');
    expect(fed).toContain('[provider://acme_dc2]');
    expect(fed).toContain('type = splunk');
    expect(fed).toContain('mode = standard');
    expect(/^\s*password\s*=/m.test(fed)).toBe(false);
    expect(file(files, 'default/indexes.conf')).toContain('[federated:fed_dc2_web]');
    expect(file(files, 'ops/remote-provider/authorize.conf')).toContain('srchIndexesAllowed = web;os');
    const rest = file(files, 'ops/federated-rest.sh');
    expect(rest).toContain('/data/federated/provider');
    expect(rest).toContain('/data/federated/index');
    expect(rest).toContain('--dry-run) EXECUTE=0');
  });

  it('writes no federated indexes in transparent mode', () => {
    const { files } = build('splunk_federated_search', { mode: 'transparent' });
    expect(Object.keys(files).some((p) => p.endsWith('default/indexes.conf'))).toBe(false);
    expect(file(files, 'default/federated.conf')).toContain('mode = transparent');
  });

  it('refuses the forwarding port as the provider port', () => {
    expect(hasErrors(build('splunk_federated_search', { host_port: 'sh1.dc2.example.com:9997' }).findings ?? [])).toBe(true);
  });
});
