/**
 * The same change, as a playbook that applies it.
 *
 * A config file is what a change record needs and what someone pastes at 2am.
 * A playbook is what applies the same change to forty switches without anyone
 * pasting anything. Both come from one `DeviceChange`, so the file and the
 * playbook cannot say different things.
 *
 * Every play is generated in check mode first — `--check --diff` shows what
 * would change without changing it, which is the closest a network device has
 * to a Terraform plan — and nothing saves the configuration unless the change
 * actually applied.
 *
 * Credentials are never written here. The play reads them from the inventory
 * or a vault, and the README says which variables each platform expects.
 */

import { renderYaml,                } from '../ansible/yaml.js';
import { PLATFORMS,                                  } from './device.js';

/** The inventory group a platform's devices are expected to be in. */
export function defaultHosts(platform          )         {
  switch (platform) {
    case 'cisco_ios':
      return 'ios';
    case 'cisco_nxos':
      return 'nxos';
    case 'cisco_wlc':
      return 'wlc';
    case 'cisco_asa':
      return 'asa';
    case 'arista_eos':
      return 'eos';
    case 'panos':
      return 'panos';
    case 'fortios':
      return 'fortigates';
    case 'f5':
      return 'bigips';
    default:
      return 'network';
  }
}

/**
 * The push task for a change that has no vendor-specific module of its own.
 *
 * `*_config` with `lines` is the generic way to apply IOS, NX-OS and EOS
 * configuration, and it is idempotent in the way those platforms are: the
 * module compares against the running configuration and sends only what
 * differs.
 */
export function configPush(change              )                                                           {
  const module =
    change.platform === 'cisco_ios' || change.platform === 'cisco_wlc'
      ? 'cisco.ios.ios_config'
      : change.platform === 'cisco_nxos'
        ? 'cisco.nxos.nxos_config'
        : change.platform === 'cisco_asa'
          ? 'cisco.asa.asa_config'
          : change.platform === 'arista_eos'
            ? 'arista.eos.eos_config'
            : null;
  if (!module) return null;
  return {
    module,
    args: {
      lines: change.config.filter((line) => line.trim() !== '' && !line.trim().startsWith('!')),
      save_when: 'changed',
    },
  };
}

/** The play for one change, as the YAML structure the writer renders. */
export function playFor(change              , name        )                   {
  const push = change.push ?? configPush(change);
  if (!push) return null;

  const platform = PLATFORMS[change.platform];
  const hosts = ('hosts' in push && typeof push.hosts === 'string' ? push.hosts : undefined) ?? defaultHosts(change.platform);

  const tasks                              = [
    {
      name: change.title,
      [push.module]: push.args             ,
      register: 'change_result',
    },
  ];

  for (const extra of 'after' in push && Array.isArray(push.after) ? push.after : []) {
    tasks.push({
      name: extra.name,
      [extra.module]: extra.args             ,
      when: 'change_result is changed',
    });
  }

  tasks.push({
    name: 'Show what changed',
    'ansible.builtin.debug': { var: 'change_result' },
    when: 'change_result is changed',
  });

  return [
    {
      name: `${name || change.title} (${platform.label})`,
      hosts,
      gather_facts: false,
      tasks,
    },
  ];
}

/**
 * The playbook file for one change.
 *
 * Returns null for a change with nothing to push — which is honest rather than
 * emitting a playbook that does nothing.
 */
export function pushPlaybook(change              , name        )                {
  const play = playFor(change, name);
  if (!play) return null;
  const platform = PLATFORMS[change.platform];
  return renderYaml(play, {
    header: [
      `${change.title} — generated by ArchToolKit.`,
      '',
      `Dry run first:  ansible-playbook -i inventory ${name || 'change'}.yml --check --diff`,
      `Then apply:     ansible-playbook -i inventory ${name || 'change'}.yml --diff --limit <device>`,
      '',
      `Connection variables belong in the inventory, and credentials in a vault:`,
      ...inventoryHint(platform.id).map((line) => `  ${line}`),
      '',
      'Nothing here writes a password, an enable secret or an API key.',
    ].join('\n'),
  });
}

/** What the inventory has to say for this platform's connection to work. */
export function inventoryHint(platform          )           {
  const info = PLATFORMS[platform];
  switch (platform) {
    case 'cisco_ios':
    case 'cisco_nxos':
    case 'cisco_wlc':
    case 'cisco_asa':
    case 'arista_eos':
      return [
        'ansible_connection: ansible.netcommon.network_cli',
        `ansible_network_os: ${info.networkOs ?? ''}`,
        'ansible_user: "{{ vault_network_user }}"',
        'ansible_password: "{{ vault_network_password }}"',
        'ansible_become: true',
        'ansible_become_method: enable',
        'ansible_become_password: "{{ vault_enable_secret }}"',
      ];
    case 'panos':
      return [
        'provider:',
        '  ip_address: "{{ inventory_hostname }}"',
        '  username: "{{ vault_panos_user }}"',
        '  password: "{{ vault_panos_password }}"',
        '# or api_key: "{{ vault_panos_api_key }}" instead of username and password',
      ];
    case 'fortios':
      return [
        'ansible_connection: httpapi',
        'ansible_httpapi_use_ssl: true',
        'ansible_httpapi_validate_certs: true',
        'ansible_httpapi_port: 443',
        'ansible_network_os: fortinet.fortios.fortios',
        'ansible_httpapi_key: "{{ vault_fortios_token }}"',
      ];
    case 'f5':
      return [
        'provider:',
        '  server: "{{ inventory_hostname }}"',
        '  user: "{{ vault_bigip_user }}"',
        '  password: "{{ vault_bigip_password }}"',
        '  validate_certs: true',
      ];
    default:
      return [];
  }
}
